### ISSUE TITLE
"style.css" is not in the SourceMap

### ISSUE THREAD

**Issue by moretti** [webpack-contrib/css-loader#100]
I've just updated to 1.5.3 (from 1.4.5) and I now get the following error when I start the dev server:

```
Module build failed: Error: "webpack-bug/style.css" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (webpack-bug/node_modules/css-loader/node_modules/postcss/node_modules/source-map/lib/source-map/source-map-consumer.js:677:15)
    at Input.origin (webpack-bug/node_modules/css-loader/node_modules/postcss/lib/input.js:91:31)
    at Input.error (webpack-bug/node_modules/css-loader/node_modules/postcss/lib/input.js:61:27)
    at Rule.error (webpack-bug/node_modules/css-loader/node_modules/postcss/lib/node.js:68:38)
    at webpack-bug/node_modules/css-loader/node_modules/postcss-modules-local-by-default/index.js:240:20
    at webpack-bug/node_modules/css-loader/node_modules/postcss/lib/container.js:141:30
    at webpack-bug/node_modules/css-loader/node_modules/postcss/lib/container.js:102:26
    at Root.each (webpack-bug/node_modules/css-loader/node_modules/postcss/lib/container.js:89:22)
    at Root.eachInside (webpack-bug/node_modules/css-loader/node_modules/postcss/lib/container.js:101:21)
    at Root.eachRule (webpack-bug/node_modules/css-loader/node_modules/postcss/lib/container.js:139:21)
```

**Update:**
I created a small [example](https://github.com/moretti/css-loader-bug-100) on github which can be used for replicating the error:

```
git clone git@github.com:moretti/css-loader-bug-100.git; cd css-loader-bug-100; npm i; npm start
```

**Comment by markdalgleish** [comment]
Could I see a repro somewhere?

**Comment by moretti** [comment]
Yeah, sorry about that, I'm about to push to github a small project which can be used for replicating the error :smile:

**Comment by markdalgleish** [comment]
Perfect, thank you :smile:

**Comment by moretti** [comment]
@markdalgleish 
```
git clone git@github.com:moretti/css-loader-bug-100.git; cd css-loader-bug-100; npm i; npm start
```
:smile:

**Comment by markdalgleish** [comment]
I've found that the issue goes away if I change this line: https://github.com/moretti/css-loader-bug-100/blob/f8ba2343deb07ffc31ea7f1ed3b4f11cbc901fe3/src/style.css#L15

From this:
```css
:global a:hover, a:focus, a:active
```

to this:
```css
:global a:hover, :global a:focus, :global a:active
```

Still trying to figure out why this is significant, though.

**Comment by moretti** [comment]
Oh I see, that's my bad. Perhaps we should just display a more relevant error.

This is unrelated, but I'm wondering if there's a way to define a global section of rules.

I tried something like:
```
:global {
  body {
    color: black;
  }
  * {
      box-sizing: border-box;
  }
}
```

But it was translated to:

```
{
  body {
    color: black;
  }
  * {
      box-sizing: border-box;
  }
}
```

**Comment by markdalgleish** [comment]
Looks errors thrown inside the `css-loader` PostCSS pipeline don't propagate to the CLI.

If I comment out the following lines inside `postcss-modules-local-by-default`: https://github.com/css-modules/postcss-modules-local-by-default/blob/343c4d08ca1f2870caf2c7c19ad9ee979fbc9f02/index.js#L45-L46 — then the error goes away. You should ideally be seeing the error message causing your build to fail. This will require a bit more investigation.

**Comment by michael-ciniawsky** [comment]
If `postcss-loader`'s  `options: { sourceMap: true }` isn't set explicitly `css-loader` won't recieve [anything](https://github.com/postcss/postcss-loader/blob/master/index.js#L140)
