### ISSUE TITLE
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js)

### ISSUE THREAD

**Issue by aZolo77** [webpack-contrib/css-loader#1030]
- Linux 3.10.0-957.21.3.el7.x86_64
- v6.17.1
- 3.10.10
-"webpack": "^4.41.2"
- "css-loader": "^3.4.0"

### Actual Behavior

ERROR in ./src/css/main.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
/home/newpanel/node_modules/css-loader/dist/plugins/postcss-icss-parser.js:34
      accumulator[normalizedUrl] = { ...accumulator[normalizedUrl],
                               

### Code

```js
// indexs.js
import "./css/main.css";

// webpack.config.js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  ...
  module: {
    rules: [
      ...,
      {
        test: /\.css$/i,
        use: [MiniCssExtractPlugin.loader, "css-loader"]
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: "[name].css"
    })
  ]
};

**Comment by aZolo77** [comment]
I installed "css-loader": "^2.1.0" - everything works fine

**Comment by aleksandergorecki80** [comment]
Thanks aZolo77

**Comment by catLotto** [comment]
Same in css-loader 4.2.1.
I solved it thanks to you.
