### ISSUE TITLE
Add getLocalIdent to export

### ISSUE THREAD

**Issue by oceandrama** [webpack-contrib/css-loader#1032]
In previous versions of this package, it has `getLocalIdent` function exported from `utils` folder. We use it as a first step of our own `getLocalIdent` implementation

In version 3.3.0 it was removed

Please, add this function to export again

**Comment by evilebottnawi** [comment]
What is use case?

**Comment by oceandrama** [comment]
We use our own `getLocalIdent` function to create special locators in `storybook` for e2e testing. But we don't need to do this for every classname, so as the first step of our function we use default implementation and then replace some patterns

**Comment by evilebottnawi** [comment]
We never exported `getLocalIdent`, it is part of private API and can be changed in any time so we don't want to export that, you can copy paste code from our code base

**Comment by pillowfication** [comment]
I also would like `getLocalIdent` to be exported again. I had my class names created based off of what the `getLocalIdent` function returned.

```js
const { getLocalIdent } = require('css-loader/dist/utils')

...

  modules: {
    localIdentName: '[path][name]__[local]--[hash:base64:5]',
    getLocalIdent: (...args) => 'prefix-' + getLocalIdent(...args)
  },
```

**Comment by evilebottnawi** [comment]
What is problem with copy/paste the code?

**Comment by pillowfication** [comment]
I currently am copy/pasting the code, but it's an ugly solution that can potentially cause troubles with dependency versions or updating `css-loader`, for something that this module used to export.

**Comment by dmgauthier** [comment]
I also want `getLocalIdent` to be exported from the package plz.

**Comment by haggen** [comment]
+1 for this, specially so since [you used to export it back in version 2.1.1](https://github.com/webpack-contrib/css-loader/blob/bc16c3db953dbf4d711753fbb0cc60253def6916/src/utils.js#L111).

The function is not trivial and depends on other stuff such as `normalizePath` and `cssesc`. Copying into our own codebase is recipe to disaster. If it's something you change that often we can think of a stabilized API, wrap with it and export it.
