### ISSUE TITLE
"Composes" duplicating css (again)

### ISSUE THREAD

**Issue by vlazh** [webpack-contrib/css-loader#1037]
- webpack Version: 4.19.1
- css-loader Version: 3.4.1

It's copy of #772 but with latest css-loader.

### Expected Behavior
It shouldn't duplicate css class.

### Actual Behavior
When a class name within a css file is shared using "composes" in a 2 degree level, it gets duplicated (when each class has its own file).

For example (each class has its own css file):

Case 1 (composes in 1 degree level)
"primary-button" which composes "button" and;
"secondary-button" which composes "button".
This case is ok, and nothing gets duplicated.

Case 2 (composes in 2 degree level)
"next-button" which composes "primary-button" which composes "button" and;
"back-button" which composes "secondary-button" which composes "button".
On this case, the "button" class gets duplicated.

The second case was tested with the following plugins:
style-loader (see print): https://raw.githubusercontent.com/ivensgoncalves/Webpack_StylesDuplication/master/prints/style-loader.png
mini-css-extract-plugin (see print): https://raw.githubusercontent.com/ivensgoncalves/Webpack_StylesDuplication/master/prints/mini-css-extract-plugin.png

On both plugins the "button" class got duplicated.

### Code
With latest css-loader:
https://github.com/vlazh/Webpack_StylesDuplication

### How Do We Reproduce?
A minimal reproducible project with this issue:
https://github.com/vlazh/Webpack_StylesDuplication

To test with style-loader, execute "npm run start1"
To test with mini-css-extract-plugin, execute "npm run start2"

**Comment by jquense** [comment]
working for me 👍

**Comment by vlazh** [comment]
Example project work fine, but in my real project still has dublicating in some cases. Unfortunately I can't reproduce it in example project. I use typescript, react and a lot of components. I continue to research, but still have no success.

**Comment by jquense** [comment]
@vlazh make sure you also have style-loader installed that is less than 1.1.0

**Comment by vlazh** [comment]
@jquense, Yes, I have latest version of style-loader installed.

**Comment by vlazh** [comment]
I just have managed to demonstrate the problem.
Demo project: https://github.com/vlazh/css-dublication
Run `start:client` script.

![image](https://user-images.githubusercontent.com/374240/72209562-00410f00-34da-11ea-81e7-7884a6acc021.png)

Class `.CompB__children--10ad6` is duplicating.

**Comment by evilebottnawi** [comment]
@vlazh please use style-loader less than 1.1.0, we have some problems with latest version, i will fix it in near future

**Comment by vlazh** [comment]
@evilebottnawi with style-loader@1.0.2 works great!
Thank you!
Worth it to create a new issue for the problem with style-loader or it already exists?

**Comment by evilebottnawi** [comment]
@vlazh already exists

**Comment by vlazh** [comment]
@evilebottnawi, seems like fixed in style-loader@1.1.3. Thank you!
