### ISSUE TITLE
Enabled modules break  fonts,  Mixed Content?

### ISSUE THREAD

**Issue by BonBonSlick** [webpack-contrib/css-loader#1041]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [StackOverflow](https://stackoverflow.com/questions/tagged/webpack)
or [the Webpack Gitter](https://gitter.im/webpack/webpack) instead.

This might be a bug for enabled css modules. I am not sure.
```
    "@fortawesome/fontawesome-free": "^5.5.0",

 "webpack": "^4.20.2",
    "webpack-bundle-analyzer": "^3.4.1",
    "copy-webpack-plugin": "^5.0.4",
    "webpack-cli": "^3.3.6",
    "script-ext-html-webpack-plugin": "^2.1.4",
    "uglifyjs-webpack-plugin": "^2.1.3",
    "webpack-merge": "^4.1.4",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^4.0.0-beta.11",
    "webpack-dev-server": "^3.8.0"
```
```

 {
        test: /\.css$/,
        use:  [
          'vue-style-loader',
          'style-loader',
          {
            loader:  'css-loader',
            options: {
              modules:        true,
              localIdentName: '[path][name]__[local]',
              sourceMap:      true,
            },
          },
        ],
      },
      {
        test: /\.scss$/,
        use:  [
          {
            loader: 'style-loader',
          },
          {
            loader:  'css-loader',
            options: {
              modules:        true,
              // localIdentName: '[path][name]__[local]--[hash:base64:12]',
              localIdentName: '[path][name]__[local]',
              sourceMap:      true,
            },
          },
          {
            loader: 'sass-loader',
          },
        ],
      },
```

If modules are enabled, fonts throw errors, not loaded

ERROR
`Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure font ''. This request has been blocked; the content must be served over HTTPS`

for CSS   like
```

font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  font-display: auto;
  src: url("../webfonts/fa-solid-900.eot");
  src: url("../webfonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../webfonts/fa-solid-900.woff2") format("woff2"),...
```
If modules disabled, everything works fine.

I tried different CSP settings, does not help. 
`'font-src \'unsafe-inline\' \'unsafe-eval\' \'unsafe-hashes\'  https: data: blob: mediastream: filesystem:;',
`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/font-src

Request headers
```

General
Request URL: :
Referrer Policy: no-referrer-when-downgrade
```

Probably, something wrong with 
`src: url("../webfonts/fa-regular-400.eot?#iefix") 
`
url parsing.

Tell me please why so? 
Maybe anyone knows how to fix it?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use issue template, CSP is out of scope css-loader, use stackoverflow or gitter for questions
