### ISSUE TITLE
Adding hot reload?

### ISSUE THREAD

**Issue by weilinzung** [webpack-contrib/css-loader#1043]
Ignored an update to unaccepted module ../node_modules/css-loader/dist/cjs.js?{"url":false,"sourceMap":true,"importLoaders":2}!..

process-update.js:102 [HMR] The following modules couldn't be hot updated: (Full reload needed)

This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.

**Comment by evilebottnawi** [comment]
Out of scope css-loader, please use style-loader too

**Comment by weilinzung** [comment]
@evilebottnawi i use style-loader too, which show me that errors with their latest version.

**Comment by evilebottnawi** [comment]
What is error? Please provide reproducible test repo
