### ISSUE TITLE
key containing "@" as first character in resolve.alias breaks url("~@my-alias/foo.jpg") in css

### ISSUE THREAD

**Issue by rikers** [webpack-contrib/css-loader#1045]
- Operating System: Windows 10
- Node Version: 12.9.0
- NPM Version: 6.10.2
- webpack Version: 4.41.5
- css-loader Version: 3.4.2

Hi,
I get the same issue as mentioned in [issues/49](https://github.com/webpack-contrib/css-loader/issues/49) but the tilde in front of the alias inside url() in my css file doesn't get the job done.
However, if I go from this resolve.alias configuration:
```js
// webpack.config.js
//...
resolve: {
    extensions: ['.js', '.json', '.css', '.scss'],
    alias: {
        //...
        '@styles': path.resolve(__dirname, 'src/assets/styles'),
        '@images': path.resolve(__dirname, 'src/assets/images')
    },
    modules: [path.resolve(__dirname, 'src'), path.resolve(__dirname, 'node_modules')]
}
//...
```

```scss
background-image: url("~@images_/landscape.jpg");
```
to

```js
//...
alias: {
    //...
    '@styles': path.resolve(__dirname, 'src/assets/styles'),
    '_images': path.resolve(__dirname, 'src/assets/images')
}
//...
```
```scss
background-image: url("~_images_/landscape.jpg");
```
then it works as expected. The @ character seems to be problematic here.

**Comment by evilebottnawi** [comment]
Please fill issue template and provide example how we can reproduce problem, otherwise issue will be closed, thanks

**Comment by evilebottnawi** [comment]
Do not forget what `@` is special character for npm/yarn, for example you can have a package `@images/landscape.jpg`, it is valid package name, so it can potential will be problem in future, anyway it should work, so i wait minimum reproducible test repo

**Comment by rikers** [comment]
Thank you for the answer. I'll set up a repo as soon as I can and edit this msg.

**Comment by evilebottnawi** [comment]
Problem in `precss` postcss plugin (just comment that plugin and build is fine), sorry I don't know how to fix it (i think you need disable `url` handling) or maybe it is bug, and `precss` should ignore `url` value, please open issue in `precss` we can't fix it on our side.

**Comment by rikers** [comment]
Thank you for investigating. I'll head over to precss.
