### ISSUE TITLE
ModuleConcatenation bailout: Module uses module.id

### ISSUE THREAD

**Issue by Linksku** [webpack-contrib/css-loader#1051]
- css-loader Version: 3.4.2

### Expected Behavior / Situation
`ModuleConcatenation bailout: Module uses module.id` doesn't appear.

### Actual Behavior / Situation
`ModuleConcatenation bailout: Module uses module.id` appears.

### Modification Proposal
I think this is caused by https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L247 or https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L399

I don't understand what these lines do, but perhaps you guys can see if it's possible to get ModuleConcatenationPlugin to work with CSS modules?

**Comment by evilebottnawi** [comment]
`ModuleConcatenation bailout` just message from webpack, change `stats` option

**Comment by leo-lime** [comment]
It's a warning saying it can't optimize further because of CSS loader. If CSS loader doesn't use module.id, every user's file sizes can be smaller

**Comment by Linksku** [comment]
It's a warning about a legitimate issue. If CSS loader didn't use module.id, every user's file size could be smaller

**Comment by evilebottnawi** [comment]
We can't remove `module.id`, it is required for `@import` and other stuff

**Comment by Linksku** [comment]
I see, thanks for letting me know
