### ISSUE TITLE
Upgrade to loader-utils 2.0.0

### ISSUE THREAD

**Issue by stellamargonar** [webpack-contrib/css-loader#1060]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version: 
- css-loader Version: 3.4.2

### Expected Behavior / Situation
npm audit is notifying [a low priority issue on minimist](https://www.npmjs.com/advisories/1179), which is included through `css-loader > loader-utils > json5 > minimist`

### Actual Behavior / Situation
No audit error

### Modification Proposal
since [loader-utils v2.0.0](https://github.com/webpack/loader-utils/releases/tag/v2.0.0) (released 10 days ago) they started using [json5 v2.12](https://github.com/json5/json5/releases/tag/v2.1.2) which uses a version of minimist not affect from the issue above.
Could you upgrade to loader-utils 2.0.0?

Note: the same thing happens in [style-loader](https://github.com/webpack-contrib/style-loader), should i create a separated issue there?

**Comment by evilebottnawi** [comment]
It will be done in next major release, anyway you can open an issue in `json5` repo for backporting

**Comment by evilebottnawi** [comment]
We will update that for next major release, because it is breaking change, anyway right now now problems with `minimist`, so I closed issue, anyway thanks for issue
