### ISSUE TITLE
modules.mode callback function

### ISSUE THREAD

**Issue by mnpenner** [webpack-contrib/css-loader#1063]
- Operating System: Ubuntu 18.04
- Node Version: v13.11.0
- NPM Version: 6.13.7
- webpack Version: 4.42.1
- css-loader Version: 3.4.2

### Feature Proposal

[`modules.mode`](https://github.com/webpack-contrib/css-loader#mode) can be set to `global` or `local` (AFAICT) -- I propose allowing it to take a callback function as well. Callback will be given the full filepath/name which can then return a string, "global" or "local". 

### Feature Use Case

Projects that were started with existing CSS files will likely need to use "global" mode to avoid having to refactor everything/wrap every file. However, new files/components will probably want to use "local" mode. Being able to turn global/local on for specific directories will make this much easier.

**Edit:** I suppose if [this](https://github.com/webpack/webpack/issues/8952) gets fixed, that'd work too.

**Comment by evilebottnawi** [comment]
Yep, let's do it, PR welcome

**Comment by mnpenner** [comment]
Awesome! Thank you very much @cap-Bernardito and @evilebottnawi !
