### ISSUE TITLE
loader loses paths to source files in source map

### ISSUE THREAD

**Issue by alexhisen** [webpack-contrib/css-loader#1064]
When css-loader calls postcss with an existing source map previously generated by postcss-loader, the resulting source map ends up with just the file name for sources without any paths. If there are then collisions of this file name with other same-named files in other directories, only one of these source maps ends up being retained.

This is particularly noticeable for the react-toolbox project which has about a dozen files all named theme.modules.css in different directories.

See https://github.com/alexhisen/mobx-forms-demo project for example config, etc. Note it's currently set up to use a fork with a workaround in https://github.com/webpack-contrib/css-loader/pull/1053, so it doesn't exhibit the problem any more.

**Comment by evilebottnawi** [comment]
Thanks, I will look at that in near future

**Comment by evilebottnawi** [comment]
@alexhisen I will try your repo, but looks it doesn't work, I have white screen with a lot of errors in console, can you provide steps to reproduce?

**Comment by evilebottnawi** [comment]
Can you provide places where source maps broken (maybe screenshots), yes, right now it use absolute paths (it is bad for production, we are working on it)

**Comment by evilebottnawi** [comment]
Yep, looks duplicate, here the original issue https://github.com/webpack-contrib/css-loader/issues/622, solution https://github.com/webpack-contrib/css-loader/issues/622#issuecomment-609818169, feel free to leave feedback, we will try to fix it ASAP
