### ISSUE TITLE
Sourcemaps pointing to wrong file

### ISSUE THREAD

**Issue by JParkinson1991** [webpack-contrib/css-loader#1078]
* Operating System: macOS 10.14.5
* Node Version: 8.16.0
* NPM Version: 6.4.1
* webpack Version: 4.35.0
* sass-loader Version: 7.1.0

It seems that there (somewhere in the chain) are some alterations to node-sass generated sourcemaps which results in them pointing to the wrong scss source declarations.

The sourcemaps do not point to completely the wrong file, the point to a file/line in which styling exists for the element, just not the file/line where the shown styles have been defined.

### Assumptions

- When style definitions exist in multiple files, sourcemaps point to one of (but in some cases) the wrong file in which they are defined.
- This only seems to be the case when multiple style definitions exist for an element

### Screenshots

Webpack generated sourcemap - broken - chrome browser
![webpack sourcemap - broken](https://user-images.githubusercontent.com/6921398/60188490-49c05a00-9827-11e9-8f2a-07211622a939.png)

node-sass generated sourcemap - working - chrome browser
![Screenshot 2019-06-26 at 15 29 37](https://user-images.githubusercontent.com/6921398/60188573-71172700-9827-11e9-800c-0fb9f8e2daf9.png)

### How Do We Reproduce?

Reproducable repository here: 
https://github.com/JParkinson1991/webpack-sourcemaps-debug

The `./public/index.html` page in the above repository will show the expected locations of sourcemap references.

These expected locations are correct when the sourcemaps are generated/styles compiled with node-sass directly. This can be achieved by running the following in the above repository `npm run script build:node-sass`

However, when compiled using webpack and usings its generated sourcemaps the locations do not match up, they are not compeltely wrong in that they reference somewhere in source where this file has been generated, but not the correct point in the code. 
Can be checked by running the following in the above repository `npm run script build:webpack`

### Testing

In chrome, when source compiled with node-sass the sourcemaps are correct, they are incorrect when compiled with webpack.

In firefox, sourcemaps are incorrect when source compiled with both **webpack and node-sass**

-----

If you need anymore information on this one, let me know.
Thanks in advance for any help/input provided on this one!

**Comment by JParkinson1991** [comment]
@evilebottnawi given the bug has now been narrowed down to css-loader, i assume we can rule out dart sass being a fix (ie node-sass being the issue)?

**Comment by evilebottnawi** [comment]
@JParkinson1991 not sure, using `sass` (`dart-sass`) solve issue, maybe something wrong in `mapping` for `node-sass`, it is a real hard bug, I don’t even know where we will need to start

**Comment by JParkinson1991** [comment]
Yeah it does seem like a tricky bug to track down! Atleast there is some sort of work around in place with using dart sass.

Just for clarity, using dart sass with `npm install --save-dev sass` is all thats needed? Removing node-sass of course.

I will dig around this soon and verify dart sass can be used as a work around.

**Comment by evilebottnawi** [comment]
> Just for clarity, using dart sass with npm install --save-dev sass is all thats needed? Removing node-sass of course.

Yes

> I will dig around this soon and verify dart sass can be used as a work around.

I already checked this and everything works fine, I'm not sure that I can find the time to track down this error in the near future

**Comment by JParkinson1991** [comment]
Just updated the reproducible repository to include dart sass test cases. Everything working as expected.

https://github.com/JParkinson1991/webpack-sourcemaps-debug

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack-contrib/css-loader/issues/622, I will add tests to ensure what we fix it after source map improvements
