### ISSUE TITLE
Escape encoding content

### ISSUE THREAD

**Issue by sabuz** [webpack-contrib/css-loader#1079]
css-loader encoding fontawesome content. eg. content: '\f10e' turns into content: "". How to solve this?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

We don't touch your css
