### ISSUE TITLE
Error: Validation error

### ISSUE THREAD

**Issue by WayneJr** [webpack-contrib/css-loader#1085]
- Operating System: Kali linux
- Node Version: 13.1.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- css-loader Version: 3.5.3

### Expected Behavior

It should build the webapp

### Actual Behavior
[Error: Validation Error

Extract Text Plugin (Loader) Invalid Options

options['loader'] should NOT have additional properties
] {
  err: [
    {
      keyword: 'additionalProperties',
      dataPath: "['loader']",
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties'
    }
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tictactoe@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tictactoe@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-24T09_48_20_808Z-debug.log

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```
https://gist.github.com/WayneJr/63fba9e5d296d676d2384181a63bb076

**Comment by evilebottnawi** [comment]
Extract Text Plugin is deprecated, please migrate on mini-css-extract-plugin

**Comment by WayneJr** [comment]
Alright thanks
