### ISSUE TITLE
Skip generation of Javascript files

### ISSUE THREAD

**Issue by AmitJoki** [webpack-contrib/css-loader#1088]
- Operating System: Elementary OS, Linux.
- Node Version: v12.17.0
- NPM Version: 6.14.4
- webpack Version: ^4.43
- css-loader Version: ^3.53

### Expected Behavior / Situation

We don't use inline CSS in our organization. Everything is in a stylesheet. We just want the CSS to be compiled and then extracted out into separate files using `mini-css-extract-plugin`.

`css-loader` however insists on generating deadcode in the form of CommonJS modules. Currently, we have been removing those dead assets using the 
```
new ExcludeAssetsPlugin({
  path: ['^.*\\.js$']
});
```
This is two unnecessary steps - 
1. Generation of unnecessary files.
2. Removal of those files using an extra dependency (plugin).

The expected situation is not to have the above two steps at all.

### Actual Behavior / Situation
Unnecessary Javascript code is emitted which is of no use and I am sure will have some overhead.

### Modification Proposal
There should be an option which altogether skips the generation of JS files.

**Comment by evilebottnawi** [comment]
@AmitJoki It should be fixed in `mini-css-extract-plugin`, it is a bug
