### ISSUE TITLE
Webpack 5.beta.17  DEP_WEBPACK_MODULE_ID  warning

### ISSUE THREAD

**Issue by scrajesh** [webpack-contrib/css-loader#1090]
- Operating System:
- Node Version: v10.16.0
- NPM Version: 6.14.3
- webpack Version: 5.0.0-beta.17
- css-loader Version: 3.5.3

### Expected Behavior

Get a valid Webpack build without errors/warnings

### Actual Behavior

```bash
(node:50162) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
```

### How Do We Reproduce?

Use:
webpack@5.0.0-beta.17

**Comment by evilebottnawi** [comment]
No related to css-loader
