### ISSUE TITLE
I face an error. here it is , please help me.

### ISSUE THREAD

**Issue by SahithiSunkara** [webpack-contrib/css-loader#1091]
I face an error. here it is , please help me.

ERROR in Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(1:1) Unknown word

> 1 | .
      | ^
  2  |

_Originally posted by @kazinoman in https://github.com/webpack-contrib/css-loader/issues/617#issuecomment-607281233_

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
