### ISSUE TITLE
How css modules affect performance?

### ISSUE THREAD

**Issue by nguyenxndaidev** [webpack-contrib/css-loader#1097]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### I'm not sure which kind of performance is mentioned in the documentation below? The performance in transpiling phase or at the end users' browsers?

https://www.npmjs.com/package/css-loader#modules
> Using false value increase performance because we avoid parsing CSS Modules features, it will be useful for developers who use vanilla css or use other technologies.

**Comment by evilebottnawi** [comment]
> we avoid parsing CSS Modules features

parsing require time

**Comment by nguyenxndaidev** [comment]
Sorry because I'm quite new to frontend technologies, does *parsing* happens when *transpiling css when run webpack* or at the end users' browsers?

**Comment by evilebottnawi** [comment]
> parsing happens when transpiling css when run webpack

Yes, it is happens only on bundle step

**Comment by nguyenxndaidev** [comment]
Thanks for your answer!
