### ISSUE TITLE
___CSS_LOADER_GET_URL_IMPORT___ is not a function

### ISSUE THREAD

**Issue by cgb1021** [webpack-contrib/css-loader#1098]
- Operating System: windows 10
- Node Version: 12.17.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- css-loader Version: 3.6.0

### Expected Behavior

It can delete background image or add background image freely with HMR.
### Actual Behavior

When I set a background image,then delete it.After that,I set the background image again,it report a error.
### Code

```js
{
          test: /\.s[ac]ss$/,
          use: [
            'vue-style-loader',
            {
              loader: 'css-loader',
              options: {
                sourceMap: true
              }
            },
            {
              loader: 'postcss-loader',
              options: {}
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: true
              }
            }
          ]
        }
```

### How Do We Reproduce?

1.Set a background image.
```js
background-image:url(../../../../common/img/mobile/pop/inline/btn_sure.png);
```
2.Delete it.
```js
// background-image:url(../../../../common/img/mobile/pop/inline/btn_sure.png);
```
3.Set it again.
```js
background-image:url(../../../../common/img/mobile/pop/inline/btn_sure.png);
```
4.It report error
```js
bootstrap:457 [HMR] unexpected require(../common/img/mobile/pop/inline/btn_sure.png) to disposed module
TypeError: ___CSS_LOADER_GET_URL_IMPORT___ is not a function
```
![企业微信截图_15929924228073](https://user-images.githubusercontent.com/3213767/85534338-da509680-b643-11ea-9bdd-40f37715a71d.png)

**Comment by cgb1021** [comment]
When,only one image it run normally.But more than one image will report error.

**Comment by cgb1021** [comment]
![1](https://user-images.githubusercontent.com/3213767/85980716-8237dc80-ba15-11ea-8e4b-99d675afcebe.gif)
![2](https://user-images.githubusercontent.com/3213767/85980726-86fc9080-ba15-11ea-9b62-352e3139b984.gif)
![3](https://user-images.githubusercontent.com/3213767/85980733-8a901780-ba15-11ea-81db-c0af3089a46f.gif)

**Comment by evilebottnawi** [comment]
Please open an issue in `vue-style-loader`, not related to `css-loader`

**Comment by cgb1021** [comment]
When use `style-loader`,it report the same error.

**Comment by evilebottnawi** [comment]
@cgb1021 Please create reproducible test repo, I can't reproduce
