### ISSUE TITLE
Missing npm install style-loader in README

### ISSUE THREAD

**Issue by nischayv** [webpack-contrib/css-loader#1100]
Documentation Is:

- [x] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

The webpack config example in the README uses the style loader but the npm install statement does not include it. This is done for the style loader example as well, where the css-loader is missing. Is this intentional?

### Your Proposal for Changes

Updating the install statement to `npm install --save-dev css-loader style-loader` would be helpful.

**Comment by evilebottnawi** [comment]
You don't need `style-loader` for all cases, you can use `file-loader` or MiniCssExtractPlugin, even other loaders, you can find most popular examples in the `Examples` section
