### ISSUE TITLE
Disable build ':export{}'

### ISSUE THREAD

**Issue by xmsz** [webpack-contrib/css-loader#1138]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- css-loader Version:

### Feature Proposal

In v3.6.0，It doesn't build ':export{}' in output result，but v4.0.0 do

```
// xxx.input.css
.a {}
:export {
  name: 'scss';
}

```

```
// xxx.output.css
.a {}
:export {
  name: 'scss';
}

```

I need an option to disabled this feature

### Feature Use Case
```
{
  loader: 'css-loader',
  options: {
     removeExport: true
  }
}
```

then, output file
```
// xxx.output.css
.a {}
```

**Comment by evilebottnawi** [comment]
You can use postcss plugin for this, it is out of scope `css-loader`
