### ISSUE TITLE
v4 compiles file name with '_' ?

### ISSUE THREAD

**Issue by xmsz** [webpack-contrib/css-loader#1139]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- css-loader Version:

### Expected Behavior

No complies file name with '_'。
v3.6.6 was Expected

```
// _a.css

.a {}

```

```
@import './_a';

.b {}

```
Expected result

```
// b.css
{
  .b {}
}
```

### Actual Behavior

Does complies file name with '_'。

```
// b.css
{
  .a {}
  .b {}
}
```

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
{
    test: /\.scss$/,
    use: [
      {
        loader: 'css-loader',
      },
      PostcssLoader(),
      SassLoader(),
    ],
    exclude: /node_modules/,
    include: Path.resolve('src'),
  }
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by evilebottnawi** [comment]
`@import './_a';` try to open it in browser, please read how `@import` in CSS works. It was bug and it is fixed, you need to write `@import './_a.css';`

**Comment by xmsz** [comment]
> `@import './_a';` try to open it in browser, please read how `@import` in CSS works. It was bug and it is fixed, you need to write `@import './_a.css';`

 It works on v3.6.0, I will do more test for it .

**Comment by evilebottnawi** [comment]
@xmsz It is breaking change, and will not work, rewrite your code, using `@import './a'` is misleading, do you want to loader
- `_a`
- `_a.css`
- `_a.js`
- `a.[ext]`

This was done on purpose
