### ISSUE TITLE
Forgotten timeEnd causes noise

### ISSUE THREAD

**Issue by zoeesilcock** [webpack-contrib/css-loader#1147]
- Operating System: Mac OS X 10.15.6
- Node Version: 14.5
- NPM Version: 6.14.6
- webpack Version: 4.44.0
- css-loader Version: 4.1.0

### Expected Behavior

Don't print out warning messages.

### Actual Behavior

The following output is shown:
```
Warning: No such label 'URL' for console.timeEnd()
```

### Code

The issue is just a forgotten timeEnd here: https://github.com/webpack-contrib/css-loader/blob/35dee96ee359b20d8a5b89f6ec57d53fcd55e6b0/src/plugins/postcss-url-parser.js#L234

### How Do We Reproduce?

Simply use the latest version.

**Comment by joebnb** [comment]
and css loader will resove absolute path
![image](https://user-images.githubusercontent.com/1646883/88902477-d76d4500-d284-11ea-89b6-2644698924ad.png)

```css
.delete-condition{
      background: url("/img/delete-btn.svg") no-repeat;
    }
```
it should be not resolve

**Comment by evilebottnawi** [comment]
@joebnb do not spam in not related issue, it is expected and written in changelog, `/images/img.png` is resolved as:
-  Server relative URL
- Absolute path
