### ISSUE TITLE
.toString() returns [object Module] in v4.0.0

### ISSUE THREAD

**Issue by Luxiyalu** [webpack-contrib/css-loader#1151]
- Operating System: OSX
- Node Version: 12.16.3
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- css-loader Version: 4.0.0

This error only happens >= v4.0.0, v3.6.0 was fine.

### Expected Behavior

While used with to-string-loader, result should be resolved styles.

### Actual Behavior

While used with to-string-loader, result is `[object Module]`, implying that `.toString()` no longer returns string. See docs for to-string-loader here: https://developer.aliyun.com/mirror/npm/package/to-string-loader

### Code

```js
        config.module.rules.push({
            test: /\.(css|less)$/,
            use: ['to-string-loader', 'css-loader', 'less-loader'],
        })
```

### How Do We Reproduce?

String the 3 above loaders together and try to get a pure string css output out of it.

Thanks!

**Comment by evilebottnawi** [comment]
Open an issue in `to-string-loader`, not related to `css-loader`

**Comment by evilebottnawi** [comment]
Workaround - `{ esModule: false }` for `css-loader` options

**Comment by evilebottnawi** [comment]
Also you can remove this loader from your configuration and just use `import styles from './styles.css'; console.log(styles.toString())`

**Comment by JonWallsten** [comment]
@evilebottnawi Do you have an alternative in mind for to-string-loader? I use it for my Webpack/Angular setup.

**Comment by evilebottnawi** [comment]
@JonWallsten Just run `toString` in source code, or you can create own loader, look at source code, it is easy

**Comment by JonWallsten** [comment]
> @JonWallsten Just run `toString` in source code, or you can create own loader, look at source code, it is easy

Yeah, that was not a lot of code. I'll look into it. I added esModule: false for now. Thanks!
