### ISSUE TITLE
style is not affective on vue demo

### ISSUE THREAD

**Issue by eminoda** [webpack-contrib/css-loader#1152]
- Operating System: window10
- Node Version: v10.15.3
- NPM Version: 6.4.1
- webpack Version:  4.44.1
- css-loader Version: 4.2.0

### Expected Behavior

I use wepback make a simple vue demo, try to use scss-loader parse scss style, expect below picture

![搜狗截图20年08月01日1631_2](https://user-images.githubusercontent.com/15711478/89097771-7ffddf00-d414-11ea-9dee-2f689b4795e4.png)

### Actual Behavior

but，now is this picture. You can css style is not become effective, because <style> attribute is not appear to html.
![搜狗截图20年08月01日1630_1](https://user-images.githubusercontent.com/15711478/89097778-90ae5500-d414-11ea-8795-ba4fba1d12da.png)

### Code

```js
{
        test: /\.scss$/,
        use: [
          {
            loader: 'vue-style-loader',
            options: {
              // sourceMap: false,
              // shadowMode: false,
            },
          },
          {
            loader: 'css-loader',
            options: {
              // sourceMap: false,
              // importLoaders: 2,
              // modules: {
              //   localIdentName: '[name]_[local]_[hash:base64:5]',
              // },
            },
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: false,
            },
          },
        ],
      }
```

```js
// additional code, HEY YO remove this block if you don't need it
```

### Solution
I try to downgrade css-loader to 3.5.3，webpack builded ok，I dont know why is it.

**Comment by birdofpreyru** [comment]
I believe, I know why it happens: in their update from v3.6.0 to v4.0.0 they bumped `loader-utils` dependency from v1.2.3 to v2.0.0. That altered generated hashes in class names, and right away breaks any web app setups with server-side rendering, as hashes generated at server-side (usually with alternative tools) mismatch hashes generated by webpack-bundled JS. Very bad, `css-loader` guys did not noticed this change, and have not mentioned it explicitly as a huge breaking change in the release notes.

Also, I am still struggling to figure out how to achieve old hash values with the latest `css-loader`. I figured out, the `loader-utils` changed the default hashing algo from `md5` to `md4`, but so far it seems that just specifying `md5` explicitly still does not result in the old values. Should be some extra changes affecting hashes (or might be I am doing something stupid).

**Comment by evilebottnawi** [comment]
It is expected, because we have some rare cases where generated classes can be potential same for difference classes, so we fix it, you can use `getlocalIdent()` if you want to own return previous behavior

**Comment by evilebottnawi** [comment]
> Also, I am still struggling to figure out how to achieve old hash values with the latest css-loader. I figured out, the loader-utils changed the default hashing algo from md5 to md4, but so far it seems that just specifying md5 explicitly still does not result in the old values. Should be some extra changes affecting hashes (or might be I am doing something stupid).

You should not use old algorithm, because it has collisions as I described above

**Comment by evilebottnawi** [comment]
> changed the default hashing algo from md5 to md4

Because md4 is faster for hashing, it is the perf improvement

**Comment by evilebottnawi** [comment]
Why you need old classes? We have `exportOnlyLocals` for SSR, you should never use hardcoded classnames

**Comment by birdofpreyru** [comment]
@evilebottnawi well, I wouldn't care much about the algo you prefer, but...

There is https://www.npmjs.com/package/babel-plugin-react-css-modules (125k weekly downloads)
and there is https://www.npmjs.com/package/babel-plugin-css-modules-transform (51k weekly downloads),
both relying on matching classnames with `css-loader` ¯\_(ツ)_/¯

**Comment by evilebottnawi** [comment]
`babel-plugin-react-css-modules` need to update and has incompatibility with current implementation :disappointed: Why do you use this? There are a lot of alternative solutions

**Comment by birdofpreyru** [comment]
I use it in my React setup since 2018. It looked like a great choice back then, and it did not caused me any issue since then. If something is not broken I don't fix it :)

I'll appreciate if you suggest a better alternative, or warn me about any incompatibility issues beside the classname difference discussed above. With what I know currently, the option to just fork / update / package my own version of babel-plugin-react-css-modules seems like the easiest and fastest to me :)

**Comment by evilebottnawi** [comment]
You can use `exportOnlyLocals` to implement SSR, it is what you search?

**Comment by birdofpreyru** [comment]
I guess, it would work if I pass server-side code through Webpack, but that's not how I do stuff. I only use Webpack to bundle the client-side code, and the server-side code I just compile with Babel only.

**Comment by evilebottnawi** [comment]
hm, make sense, in your case I recommend to migrate on the `getLocalIdent` option, it is allow to control it, also will be great to implement it on `babel-plugin-react-css-modules` side

**Comment by ThiefMaster** [comment]
Could you provide an example on what to specify as `getLocalIdent` to restore compatibility with `babel-plugin-react-css-modules`?

**Comment by evilebottnawi** [comment]
You can fix example in README, if you need help with implementation, please provide repo with example and I will help

**Comment by birdofpreyru** [comment]
Here is my fork of `babel-plugin-react-css-modules` with fixed compatibility to `css-loader`:
https://www.npmjs.com/package/@dr.pogodin/babel-plugin-react-css-modules

@evilebottnawi it would be very handy if you export `defaultGetLocalIdent(..)` function as a named export of `css-loader`. I found a way to get it anyway, but it is kind of goofy :)

**Comment by evilebottnawi** [comment]
@birdofpreyru Sorry we can't export `defaultGetLocalIdent`, because we change it very often, so we have to do constantly breaking change when we change something, it is not good, why do not copy/paste code?

**Comment by birdofpreyru** [comment]
@evilebottnawi

> why do not copy/paste code?

For the reason you told: to not have to update dependent code each time you change something inside `defaultGetLocalIdent` (assuming the dependent code just wants to generate matching classnames). I don't get your point about breaking changes: if you change the default classname generation it might be a breaking change for users no matter whether you export the default classname generator function directly, or just use it behind the scene. Also, if you export it, you can just put a disclaimer in the docs that the exact generated classname may change between releases and won't be anounced as a breaking change.

**Comment by evilebottnawi** [comment]
Changes are not critical in all cases, but it can be breaking change for developers who rely on this, it was discussed already, for example we can change first characters if class starts number on other `._1234` to `.x1234`, it was breaking change who uses this function, but it is not breaking change for us

**Comment by ThiefMaster** [comment]
But by exporting it, tools like `babel-plugin-react-css-modules` can (peer-)depend on an exact version of this package (or `~` version if you promise to not change the logic in patch releases) and use the same logic you have, to avoid breakage due to different hashing logic.

**Comment by evilebottnawi** [comment]
It will violate semver, I don't want to do it without no real good reason, because many developer starts to use it, we will get a lot of issue after new release, what is a problem with copy/paste, code is very small

**Comment by ThiefMaster** [comment]
It uses code from other libraries (`normalize-path`, `cssesc`, `loader-utils`). So by copying the code, those libraries now have to be dependencies of my own code/library, because *I* am the one using them (and thus need to care about updating them).

**Comment by ThiefMaster** [comment]
Anyway, would it really be a problem to use semver-major releases for changes to that logic? I guess you don't change it *that* often...

**Comment by evilebottnawi** [comment]
> Anyway, would it really be a problem to use semver-major releases for changes to that logic? I guess you don't change it that often...

It used to happen often, now less often, ok, i am ready to consider exporting this, but it will still be internal and can't change in any version, so if want to rely on this, use pinned version of css-loader in your app, but my recommendation is avoid it
