### ISSUE TITLE
Compile is broken after upgrade to v4

### ISSUE THREAD

**Issue by geryit** [webpack-contrib/css-loader#1154]
I am using `sass loader` in nextjs and `v3` was working with config below. After upgrade, I am getting `[object]`  when I print css (`import css from "./testpage.scss"`)
```js
      {
        test: /\.scss$/,
        use: [
          "to-string-loader",
          {
            loader: "css-loader",
            options: {
              modules: auto,
            },
          },
          "postcss-loader",
          "sass-loader",
        ],
      }
```

**Comment by evilebottnawi** [comment]
Please open an issue in `to-string-loader`, do not ignore the issue template (respect time of other developers), please use search before post the issue https://github.com/webpack-contrib/css-loader/issues/1151
