### ISSUE TITLE
exportOnlyLocals: true option exports styles with additional 'locals' property

### ISSUE THREAD

**Issue by Allgoll** [webpack-contrib/css-loader#1155]
- Operating System: macOS Catalina
- Node Version: "v10.20.1"
- NPM Version: "6.14.4"
- webpack Version: "4.44.1"
- css-loader Version: "4.2.0"

### Expected Behavior
css modules exports  like { styleName: 'hash' } 
Transpiled code example:
```
module.exports = {
	"styleName": "T06QLNyGDOjmGhMcsI8Tp"
};
```

### Actual Behavior
css modules exports  like { locals: { styleName: 'hash' } } 

Transpiled code example:
```
___CSS_LOADER_EXPORT___.locals = {
	"styleName": "_24XqfIEo49S8lwZsHfF_Wd"
};
```

### Code

```js
module.exports = {
  target: "node",
  entry: "./index.js",
  optimization: { minimize: false },
  module: {
    rules: [
      {
        test: /\.css$/i,
        loader: 'css-loader',
        options: {
          modules: {
            mode: 'local',
            exportOnlyLocals: true,
          },
        },
      },
    ],
  },
};

```

```js
import styles from './index.css';

console.log(styles) // -> { locals: { styleName: '_24XqfIEo49S8lwZsHfF_Wd' } }
```

### How Do We Reproduce?

Just run webpack with configuration from section above on any css file.

P.S.
In version 3.6.0 css-loader with onlyLocals: true option exports css modules without additional locals key. If 4.0 brake this behaviour, maybe we need to update the docs or smth?

**Comment by ElvisWang27** [comment]
I have the same problem. When I use css-modules in server side and use `babel` transform to commonJs, my component cannot correctly get styles property ， because the all the property in the `styles.locals`.

**Comment by Allgoll** [comment]
I made some investigation and also made a PR so i hope it will help us to discus this behavior or fix it.
So thats first time when i trying to contribute something so i hope i did everything fine.

**Comment by evilebottnawi** [comment]
It is expected and it is breaking change, missing in changelog

**Comment by ElvisWang27** [comment]
> It is expected and it is breaking change, missing in changelog, but maybe you are right and we need to change it

How can use it in server side render, where I just want to get the css module's classname ?

**Comment by Allgoll** [comment]
Honestly It's a very important question for me, because i have a lot of projects where css-loader configured like in my issue. So now i can't just change settings to get my css classes back durning the SSR.
So if it is expected change then i need to make another loader (or use smth?) to fix my SSR rendering, and ofc we need to write it in the documentation because it's really important thing for projects with SSR.

**Comment by evilebottnawi** [comment]
I think we should change it, I will look at this in near future, I am afraid it can potential do breaking change for some developers, who uses `css-loader` for SSR already, but we don't write about it in changelog, we can mark it bug and write about potential breaking change in CHANGELOG.

Using `styles.locals` is very unconventional for SSR, it is require rewrite a lot of code
