### ISSUE TITLE
[v3.4.2] Modules can generate invalid CSS rulesets from filenames/parent folder names with square brackets

### ISSUE THREAD

**Issue by jamsch** [webpack-contrib/css-loader#1160]
- Operating System:
- Node Version: v12.16.1
- NPM Version: 6.14.7
- webpack Version: 4.42.0
- css-loader Version: 3.4.2

### Expected Behavior

Given the folder structure:

```
src/pages/user/[id].module.css
src/pages/user/[id]/index.module.css
```

When using `[id].module.css`, the CSS loader seems to use the file name (or parent folder name if it's named index.module.css) as the basis for writing the scoped ruleset. Problem is that the square bracket notation is also CSS syntax

### Actual Behavior

![image](https://user-images.githubusercontent.com/12927717/89726132-237d6e00-da6b-11ea-947f-33c8b4d8043b.png)

### Code

Using `react-scripts@v3.4.1` (create-react-app) with no modifications to the webpack config.

### How Do We Reproduce?

1. Create a css module file with square bracket notation e.g. "[userId].module.css" or create an "index.module.css" file inside a folder that uses square bracket notation.
2. Import it in to your project
3. Run webpack and see the CSS produced.

**Comment by evilebottnawi** [comment]
Please update loader to latest version, it was fixed a long time
