### ISSUE TITLE
(1:1) Unknown word

### ISSUE THREAD

**Issue by Abdelmajeedm** [webpack-contrib/css-loader#1166]
- Operating System: Windows 10 Enterprise. 1909
- Node Version: 12.14.1
- NPM Version: 6.13.4
- webpack Version: 4.44.1
- css-loader Version: 4.2.1

### Code
webpack.config.js: 

module: {
      rules: [
        {test: /\.css$/i,use: ["style-loader","css-loader"]},
        {test: /\.(png|jpe?g|gif|svg)$/i,use: [{loader: "file-loader",}]},
        {test: /\.(js|jsx)$/,exclude: [path.resolve(__dirname, "node_modules")],loader: "babel-loader",}],
 },

console: 

ERROR in ./src/style/validation.css ((webpack)-config-single-spa/node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./src/style/validation.css)
Module build failed (from (webpack)-config-single-spa/node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) Unknown word

var api = require("!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
^       
      var content = require("!!../../node_modules/css-loader/dist/cjs.js!./validation.css");

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Loader applied twice, please check your configuration
