### ISSUE TITLE
css loader fails 

### ISSUE THREAD

**Issue by Abdelmajeedm** [webpack-contrib/css-loader#1167]
- Operating System: Windows 10 Enterprise. 1909
- Node Version: 12.14.1
- NPM Version: 6.13.4
- webpack Version: 4.44.1
- css-loader Version:  4.2.1

### Expected Behavior

Load css files successfully

### Actual Behavior

ERROR in ./src/style/validation.css ((webpack)-config-single-spa/node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader/dist/cjs.js!./src/style/validation.css)
Module build failed (from (webpack)-config-single-spa/node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) Unknown word

> 1 | var api = require("!../../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js");
    | ^
  2 |             var content = require("!!../../node_modules/css-loader/dist/cjs.js!./validation.css");

### Code

```js
https://gist.github.com/Abdelmajeedm/c96f0da8c96d1be05dc0e09f0bc64bcb
```

```js

```

**Comment by evilebottnawi** [comment]
Please do not ignore `How Do We Reproduce?`

**Comment by Abdelmajeedm** [comment]
@evilebottnawi, I updated the details above but I couldn't reopen the issue. 
can you please take a look? 
Thanks for your help!

**Comment by evilebottnawi** [comment]
Because your configuration already has `css-loader` from `webpack-config-single-spa-react` https://github.com/single-spa/create-single-spa/blob/master/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L50, just remove 
```
 {
          test: /\.css$/i,use: ["style-loader","css-loader"]
        },
```

**Comment by Abdelmajeedm** [comment]
Thanks @evilebottnawi, that helps.
