### ISSUE TITLE
PostCSS no plugins warning

### ISSUE THREAD

**Issue by ArgonAlex** [webpack-contrib/css-loader#1168]
- Operating System: Windows
- Node Version: 13.12.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- css-loader Version: 4.2.1

### Expected Behavior

No warnings.

### Actual Behavior

After upgrading to css-loader v4 I am seeing this message in the console hundreds of times:
`You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.`

### Code

```js
// webpack.config.js
module: {
  rules: [
    {
      test: /\.css$/,
      use: [
        'style-loader',
        {
          loader: 'css-loader',
          options: {
            import: false,
            modules: false,
            sourceMap: false,
            url: false
          }
        }
      ]
    }
  ]
}
```

**Comment by ArgonAlex** [comment]
Ah because of all of the config items being set to false, the plugins array is empty here:
https://github.com/webpack-contrib/css-loader/blob/835335361cd012f7db114d0c648e4f364050181c/src/index.js#L157

**Comment by evilebottnawi** [comment]
It is expected, and can be solved only for postcss@8
