### ISSUE TITLE
@import rules in css doesn't look in node_modules folder

### ISSUE THREAD

**Issue by ryanseddon** [webpack-contrib/css-loader#12]
I have a file called `base.css` that has an import statement 

``` css
@import "normalize.css/normalize.css"
body {
  background: red;
}
```

This is my `app.js`:

``` js
var css  = require('./styles/base.css');

module.exports = function Foo() {
    return {
        foo: 'bar',
        baz: 'gah'
    };
};
```

I've npm installed normalize but running the `webpack` command throws:

``` bash
$ webpack
Hash: 2a64a4ac64b2026975fb
Version: webpack 1.1.8
Time: 82ms
    Asset  Size  Chunks             Chunk Names
bundle.js  2019       0  [emitted]  main
   [0] ./src/app.js 137 {0} [built]
   [1] ./src/styles/base.css 177 {0} [built] [1 error]

ERROR in ./src/styles/base.css
Module not found: Error: Cannot resolve file or directory ./normalize.css/normalize.css in /Users/Ryan/Git/webpack-demo/src/styles
 @ ./src/styles/base.css 2:1-116
```

What am I doing wrong? I understand that it's looking in styles dir but I thought it would scan node_modules first?

**Comment by gsklee** [comment]
+1, is this documented anywhere?

**Comment by nickdima** [comment]
@ryanseddon could you please explain how you set up the alias? thanks!

**Comment by nickdima** [comment]
@sokra there's no way to avoid the `~` in the require? I was thinking about a fallback configuration or something similar.

**Comment by alexrogers** [comment]
`@import "~normalize.css/normalize.css"` worked for me, thanks for the tip.

**Comment by johnnyoshika** [comment]
For anyone else having trouble importing css like I did, make sure you don't forget the semi-colon at the end:

`@import "~normalize.css/normalize.css";`

**Comment by ericdfields** [comment]
aaaaand simply `@import "~normalize.css"` is what did it for me

**Comment by langri-sha** [comment]
If you want what @ericdfields is doing, you need to override the defaults for [`resolve.packageMains`](https://webpack.github.io/docs/configuration.html#resolve-packagemains) and make sure to include `style`.

**Comment by JamesTheHacker** [comment]
Non of the above works for me. I get the following error:

```
ERROR in ./~/css-loader!./~/postcss-loader!./src/css/base.css
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/jamesjeffery/Projects/StudentApp/src/css/~normalize.css'
        at Error (native)
```

I tried both `@import "~normalize.css/normalize.css";` and @import "~normalize.css";`. I have normalize.css installed via npm.

**Comment by langri-sha** [comment]
@JamesTheHacker do you have `postcss-import` configured and are you on Webpack 1?

**Comment by QuantumInformation** [comment]
I also have the same issue with postcss-smart-loader. Using webpack 2 beta 27

**Comment by QuantumInformation** [comment]
you need to use @import "normalize.css";

@JamesTheHacker

**Comment by thefron** [comment]
@QuantumInformation Removing tilde worked for me. Thanks!

**Comment by rhysburnie** [comment]
Hi,

Is there anyway around this issue?

If I have a css file with `@import '~normalize.css';` without css modules it's fine.
Then If I enable css modules I get an error unless I use `@import 'normalize.css';

So if you use the the same css file for two projects one with without modules one with you have to add / remove tilde `~` respectively.

I've read in other places you "may" remove tilde when using css modules, but it seems like you have to

**Comment by liuliangsir** [comment]
[<span class="ghh-user-x tooltipstered" title="" style="box-shadow: transparent 0px 0px;">@QuantumInformation</span>](https://github.com/quantuminformation) Removing tilde worked for me. Thanks!

**Comment by yyman001** [comment]
for js 
```
let reset_css = require('normalize-css/normalize.css')
```

**Comment by rhysburnie** [comment]
@liuliangsir yes, thats the same as what I said, you've just phrased it differently
