### ISSUE TITLE
Resolve extensions and compositions

### ISSUE THREAD

**Issue by midnightcoder-pro** [webpack-contrib/css-loader#1210]
- Operating System: Windows 10 2004
- Node Version: 14.11.0
- NPM Version: 6.14.8
- webpack Version: 5.1.0
- css-loader Version: 5.0.0

### src/components/Row.styl
```stylus
.row
  composes: flex from 'comp/Flex/style'
```

### webpack.config.js
```js
...
resolve: {
  extensions: ['.js', '.styl'],
  alias: {
    comp: absolute('src/components')
  }
}
...
```

### Actual Behavior
`css-loader` ignores extensions from the webpack config and I get an error

**Comment by evilebottnawi** [comment]
Described in readme

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/css-loader#importing

**Comment by midnightcoder-pro** [comment]
I saw it, it doesn't say anything about ignoring resolve.extensions

**Comment by evilebottnawi** [comment]
It say to use extensions

**Comment by midnightcoder-pro** [comment]
Are you afraid to make changes or is it difficult to implement?)

**Comment by evilebottnawi** [comment]
It is impossible

**Comment by midnightcoder-pro** [comment]
Why is it impossible? webpack does this easily. Files are resolving in order

**Comment by evilebottnawi** [comment]
@midnightcoder-pro Please use stackoverflow for questions, because CSS modules require only CSS like modules (`css`/`less`/`sass`/`stylus`/etc)

**Comment by midnightcoder-pro** [comment]
These are questions about how a particular library works.
> CSS modules require only CSS like modules (css/less/sass/stylus/etc)

So? I use a stylus (`styl`)

**Comment by evilebottnawi** [comment]
> These are questions about how a particular library works.

It was answered.
