### ISSUE TITLE
Plugin control for `url` option

### ISSUE THREAD

**Issue by kelunik** [webpack-contrib/css-loader#1213]
- webpack Version: 5.x
- css-loader Version: 5.x

### Feature Proposal

Allow other plugins to control the `url` option.

### Feature Use Case

I've upgraded `webfonts-loader` to webpack 5 and upgraded `css-loader` while doing that. The generated files now need an exception in the `url` option to work, because they're generated files and there aren't any source files for the import to resolve.

I guess one option would be to customize `resolve.alias` in `webfonts-loader` to register the generated files as an alias of themselves, but I'm not sure how exactly would work.

**Comment by evilebottnawi** [comment]
Please read docs https://github.com/webpack-contrib/css-loader#function

**Comment by kelunik** [comment]
@evilebottnawi I'm aware of the option, sorry for not being clear enough. 

Currently the users of `webfonts-loader` manually have to add such an exclusion in their `css-loader` config. It'd be great if `webfonts-loader` could programmatically tell `css-loader` to ignore certain files instead of the end user having to configure things. Is there already a way to do this? 

See also https://github.com/jeerbl/webfonts-loader/pull/122/files#diff-2fccbabe35892fcbc7ee3062f9de1503897fdd23f3a80c1847c457daa249c004R23

**Comment by evilebottnawi** [comment]
No way, `webfonts-loader` can write files to temp directory

**Comment by kelunik** [comment]
@evilebottnawi I've finally found a way to handle it automatically: [`25a0bbe` (#122)](https://github.com/jeerbl/webfonts-loader/pull/122/commits/25a0bbe33a0a242fc581c2da18ffe008aef61959)

**Comment by evilebottnawi** [comment]
@kelunik very bad idea, it will not work in the next css-loader release
