### ISSUE TITLE
(Potential) Bug with getLocalIdent function refactor

### ISSUE THREAD

**Issue by benmvp** [webpack-contrib/css-loader#1214]
- Operating System: macOS 10.15.5
- Node Version: 12.18.3
- NPM Version: 6.14.6
- webpack Version: 4.44.2
- css-loader Version: 4.3.0

### Expected Behavior

[This PR](https://github.com/webpack-contrib/css-loader/pull/1121/files#diff-3274f1a37032fb0ae4e2823def0007c634e869ae0dfc304ff6a12c36513c3a52R64) by @evilebottnawi changed the `content` being passed to `interpolateName` (in `loader-utils`) from including a plus `+` to including `\x00`.

The PR doesn't give an explanation for why this part of the change was made, but as a result upgrading to `css-loader` v4 or higher breaks my integration with `babel-plugin-react-css-modules` which is still using `+` (through the [`generic-names`](https://github.com/css-modules/generic-names/blob/d57cb1c4dbf391fb68be9e5f38e68ad1d5a0f2d9/index.js#L34-L38) package).

If this is not a bug I can try to get things changed in `generic-names`, but it would be good to at least get an understanding of why the change from `+` to `\x00`.

My expected behavior was that the class name hashes would be identical, for the same `localIdentName` (`[folder]___[name]__[local]___[md4:contenthash:base64:5]`).

### Actual Behavior

The hashes are not the same because the passed in content is different.

- For `css-loader` the content is: `app/javascript/components/QuickAction/styles.module.scss\u0000mobile-only`
- For `babel-plugin-react-css-modules` the content is: `app/javascript/components/QuickAction/styles.module.scss+mobile-only`

`css-loader` is generating the classes for the CSS code whereas `babel-plugin-react-css-modules` is generating the classes to be used in the React markup. The actual result is that nothing on the page is styled. 😄 

### Code

n/a

### How Do We Reproduce?

There's quite a bit of setup needed to reproduce the error, but hopefully by pinpointing the change above, this isn't necessary.

**Comment by evilebottnawi** [comment]
Sorry, it is not bug, we change our logic, please open an issue in `babel-plugin-react-css-modules`

> If this is not a bug I can try to get things changed in generic-names, but it would be good to at least get an understanding of why the change from + to \x00.

Because you can use `+` character in filename, so you can have same hash for different classes in some cases
