### ISSUE TITLE
Replace "@" in `[path]` of modules.localIdentName when path contains a scoped node module

### ISSUE THREAD

**Issue by weareoutman** [webpack-contrib/css-loader#1223]
- Operating System: MacOS 10.15.7
- Node Version: 12.19.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- css-loader Version: 3.6.0

### Feature Proposal

When generating local ident name for css modules, replace `@` with `-` (or any normal chars for a css class name) in `[path]` when the path contains a scoped node module such as "@abc/xyz".

### Feature Use Case

Even though currently it works in most scenarios, but it could break when some libraries don't do `CSS.escape()` when doing `querySelector` with the generated name.

E.g.:

```js
import styles from "@abc/xyz/my.module.css";
// Assuming the `styles.myClass` is `"node_modules-@abc-xyz-myClass"`
// while setting `localIdentName: '[path]-[local]'`.
document.querySelector(styles.myClass);
```

This would result in an error of `... is not a valid selector`.

**Comment by evilebottnawi** [comment]
It is unsafe, because you can have `-abc-xyz` and `@abc-xyz` packages in theory, if we replace `@` on `-` it will can create collisions

**Comment by evilebottnawi** [comment]
Please update css-loader to latest verison, we automatically escape https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L60

**Comment by evilebottnawi** [comment]
Here interesting problem, we don't know where you will selectors, but the most common use is HTML, so it is valid for HTML, but not valid in JS in some cases (https://mothereff.in/css-escapes), it is valid for `document.getElementById` and `getElementsByClassName`, but invalid for `querySelector`.

Ideally library should run `CSS.escape` before `querySelector`, i.e. `document.querySelector(CSS.escape(customSelector))`.

**Comment by evilebottnawi** [comment]
I can fix it for `@`, but it not solve problem for other edge cases (emoji, numbers, try `111` to use as class name and most of other)

**Comment by weareoutman** [comment]
@evilebottnawi Thanks for your response.

> Please update css-loader to latest verison, we automatically escape

I have not tried the latest version, since I am using a framework which takes control of these loaders and I can't. But I checked the source code of v3.6.0 which also has the `cssesc(..., { isIdentifier: true }`.

> Ideally library should run CSS.escape before querySelector, i.e. document.querySelector(CSS.escape(customSelector)).

Yes, it does, but some libraries don't do the escape (especially these old libraries not familiar with css modules, they just accept regular class names). Indeed, I did submitted a PR on one of these libraries: algolia/autocomplete.js#358. But It will be more convenient if css-loader just generate a regular name (if no new bugs introduced).

> It is unsafe, because you can have -abc-xyz and @abc-xyz packages in theory (edge case), if we replace @ on - it will can create collisions

Em, the collisions are possible, but it's really rare, and the npm scope prefix of `@` in path is quite common (but only few people). And I think css-loader has already contained some replacements which probably will create collisions too, doesn't it?

**Comment by evilebottnawi** [comment]
> I have not tried the latest version, since I am using a framework which takes control of these loaders and I can't. But I checked the source code of v3.6.0 which also has the cssesc(..., { isIdentifier: true }.

Ask, you boilerplate developers update it, because it will not work with webpack@5 in future

> And I think css-loader has already contained some replacements which probably will create collisions too, doesn't it?

That's why we recommend using hashes. 

Unfortunately, I really can't do it, we try to remove collisions, your request creates them. As I said before, this will not fix many other cases.

> Yes, it does, but some libraries don't do the escape (especially these old libraries not familiar with css modules, they just accept regular class names)

You can do it in own code, before passing selector for a library.

**Comment by weareoutman** [comment]
> You can do it in own code, before passing selector for a library.

Unfortunately for my scenario, it won't work, because the selector passed to the library will be used both generating html (which accept classNames without escaped) and js querySelector (which accept escaped selectors).

```js
function demoLibrary(className) {
  const html = `<div class="${className}"></div>`;
  const div = document.querySelector("." + className);
}
```

**Comment by evilebottnawi** [comment]
Please open an issue in your library or escape it before passing to library, I repeat myself there are thousands more other cases where it was failed

**Comment by alexander-akait** [comment]
Let's close, answered, anyway feel free to feedback
