### ISSUE TITLE
Upgrade dependency postcss

### ISSUE THREAD

**Issue by altro3** [webpack-contrib/css-loader#1226]
https://github.com/postcss/postcss/issues/1455

This is not a error!!!

operating system: Windows 10,
node: 15.1.0,
npm: 6.14.8,
webpack: 5.4.0,
postcss: 8.1.4

This is only a warning issued by "nodejs". It is recommended to make corrections according to the warning, because some writing methods are not recommended.

```
[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution
of the package at node_modules\css-loader\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
```

Postcss already fixed this potential problem in yesterday's release: 8.1.6.

Could you upgrade postcss?

**Comment by evilebottnawi** [comment]
Update your deps, we use `^` https://github.com/webpack-contrib/css-loader/blob/master/package.json#L50
