### ISSUE TITLE
~ (tilde) notation doesn't work in imports when the module is scoped

### ISSUE THREAD

**Issue by kaiyoma** [webpack-contrib/css-loader#1227]
- Operating System: Windows 10
- Node Version: 14.15.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- css-loader Version: 4.3.0

### Expected Behavior

Imports of scoped modules using tilde notation should work.

### Actual Behavior

The import doesn't work and errors are thrown.

### Code

```less
@import '~@foo/bar/styles.less';
```

### How Do We Reproduce?

Try to import a scoped module with tilde notation.

**Comment by evilebottnawi** [comment]
Sorry can't reproduce, please provide steps, and I will reopen this

**Comment by kaiyoma** [comment]
I'm not sure what you want beyond what I've already posted?

This doesn't work:

```
@import '~@foo/bar/styles.less';
```

This does:

```
@import '../../node_modules/@foo/bar/dist/styles.less';
```

**Comment by evilebottnawi** [comment]
Please create reportorial test repo

**Comment by kaiyoma** [comment]
Okay, I'll see what I can put together. It might take me a few days.

**Comment by evilebottnawi** [comment]
Don't forget you need `less-loader` to `@import` less files
