### ISSUE TITLE
DeprecationWarning node v15.2.1

### ISSUE THREAD

**Issue by borodadada** [webpack-contrib/css-loader#1235]
Hello. After install node v15.2.1
(node:16456) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at *************\node_modules\css-loader\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".

**Comment by evilebottnawi** [comment]
No related to `css-loader`, please update postcss in your projects (don't forget about lock files)
