### ISSUE TITLE
CSS Modules get generated without `import`ing them in code.

### ISSUE THREAD

**Issue by carljohnesan** [webpack-contrib/css-loader#1239]
- Operating System: osx 10.13.6 high sierra
- Node Version: 14.8.0
- NPM Version: 6.14.7
- webpack Version: 5.9.0
- css-loader Version: 5.0.0

Expected that when I import css file as "side effect dependency", css will be just bundled as normally.

However, the actual css I get is with hashed class names.
### Code

CSS part of webpack config
```js
// rules: [ ...
test: /\.css$/,
use: [
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        modules: {
          localIdentName: mode === 'development' ? '[path][name]__[local]--[hash:base64:5]' : '[hash:base64]',
          exportLocalsConvention: 'camelCase'
        }
      }
    },
]
```

My code:
```js
  import '../styles.css'
```

**Comment by alexander-akait** [comment]
They will be removed in `mode: 'production'` (tree shaking)

**Comment by carljohnesan** [comment]
They won't be removed. Mine didn't

**Comment by carljohnesan** [comment]
It's just hashed class names are in there. I remember that wasn't the case not long ago. What exactly has changed? Is this `css-loader` or is this `webpack` ?

**Comment by alexander-akait** [comment]
All works as expected, I don't understand your problem, because you missing part of the issue template
