### ISSUE TITLE
Module build failed (from ./node_modules/css-loader/dist/cjs.js):

### ISSUE THREAD

**Issue by Talent30** [webpack-contrib/css-loader#1243]
- Operating System: Alpine Linux
- Node Version: 12.18
- NPM Version: 6.14.6
- webpack Version: 5.11.1
- css-loader Version: 5.0.1

### Expected Behavior
DevServer should successfully recompile.

### Actual Behavior

Start DevServer
![DevServer](https://user-images.githubusercontent.com/12595973/103457606-a0d0b480-4d65-11eb-9406-69d74fb4cff5.png)

Save any src file to trigger recompilation
![Error](https://user-images.githubusercontent.com/12595973/103457619-b3e38480-4d65-11eb-9ee2-2568b4455d5d.png)

### Code

[Webpack config](https://gist.github.com/Talent30/234e5863824c48d0f1b58db944984ffb)

### How Do We Reproduce?
You can download this project and run 
`npm i`
`npm run dev`
https://github.com/Talent30/Test

**Comment by cap-Bernardito** [comment]
The problem is in `webpack.AutomaticPrefetchPlugin`.
To prevent the error from occurring, you can remove it from the configuration.

@alexander-akait, here's(https://github.com/webpack/webpack/issues/9485) a similar problem

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack/issues/9485#issuecomment-753644283, we can't fix it on our side
