### ISSUE TITLE
css-loader modularized pseudo-elements question

### ISSUE THREAD

**Issue by andrew2558** [webpack-contrib/css-loader#1244]
After css-loader is modularized, because the class name is automatically renamed, what about pseudo-elements based on the class name?

**Comment by alexander-akait** [comment]
`pseudo-elements` can't renamed, you will have `.a2s2s3d::pseudo-element {}`

**Comment by andrew2558** [comment]
Defined as follows in the css file:
```
.title{
}

.title:after{

}
```
.title was renamed to .a2b3
Isn't the defined .title:after useless?

@alexander-akait

**Comment by alexander-akait** [comment]
No
