### ISSUE TITLE
css-loader v4.0.0 breaking emoji-mart latest package

### ISSUE THREAD

**Issue by Streeterxs** [webpack-contrib/css-loader#1245]
### Overview
Recently after our project updates css-loader to v5.0.0 a bug occured on our emoji-mart picker. After a few debbuging we found that the breaking change occured at v4.0.0 of css-loader package

### Screenshots
after:
![image](https://user-images.githubusercontent.com/41974719/104072898-2a133b80-51eb-11eb-923f-c43c81d0c000.png)
before:
![image](https://user-images.githubusercontent.com/41974719/104073114-a3129300-51eb-11eb-8483-635743fcd953.png)

**Comment by alexander-akait** [comment]
Sorry, I can't help because you ignore our issue template and I don't know context, we don't touch your CSS code (only change classes when CSS modules enabled), feel free to provide reproducible test repo and I will help your and reopen the issue
