### ISSUE TITLE
how to debugger run css-loader? 

### ISSUE THREAD

**Issue by nianxiongdi** [webpack-contrib/css-loader#1248]
I want to debug this code.

**Comment by alexander-akait** [comment]
Debug it, sorry I can't help without context

**Comment by nianxiongdi** [comment]
> Debug it, sorry I can't help without context

I want to learn this code and maintain it.

**Comment by alexander-akait** [comment]
@nianxiongdi we have tests for this code, what exactly you want to achieve?
