### ISSUE TITLE
How can I hash multiple class names with localIdentName?

### ISSUE THREAD

**Issue by zyze5bfej** [webpack-contrib/css-loader#1252]
Hello, I'm using react with craco. My config file looks like this

```js
            localIdentName: '[hash:base64:5]'


   test: /\.css$/,
                use: [
                    {
                        loader: 'style-loader'
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            importLoaders: 1,

                        }
                    }
                ]
```
I can hash CSS modules when there is only one class, but I cannot do something like this

```jsx

  <div className="max-w-sm w-full sm:w-1/2 lg:w-1/3 py-6 px-3"> </div>
```
I do something like this to do this but it's not possible to do this every time

```jsx
import style from '../mystyle.module.scss'
import classnames from 'classnames/bind'
const cx = classnames.bind(style)

const hashClassNames = (params) => cx(`${params}`.split(" "))

  <div className={ hashClassNames("max-w-sm w-full sm:w-1/2 lg:w-1/3 py-6 px-3") }> </div>

```

Is there an easier way to do this?

**Comment by alexander-akait** [comment]
**Never ignore the issue template**, I still can't understand the problem, so I can't help, each class has hashed name

**Comment by zyze5bfej** [comment]
> **Never ignore the issue template**, I still can't understand the problem, so I can't help, each class has hashed name
this tailwindcss

```jsx
 **<div className="foo bar baz"> ... </div>**
```
I want to do something like this. I have more than one class name and the input for it is as follows. How can I hash multiple class names here?

**localIdentName** can't resolve this

**Comment by alexander-akait** [comment]
@zyze5bfej Stop spamming:

**file.js**

```js
import styles from './style.css';

console.log(styles.foo);
console.log(styles.bar);
console.log(styles.baz);
```

**style.css**

```css
.foo {
  color: red;
}

.bar {
  color: blue;
}

.baz {
  color: green;
}
```

**Comment by alexander-akait** [comment]
And you can do it in jsx:
```jsx
// https://github.com/JedWatson/classnames
import classNames from 'classnames';
import styles from './style.css';

classNames('foo', 'bar'); // => 'foo bar'
export default myComponent() {
  return <div className={classNames(styles.foo, styles.bar, styles.baz)}> ... </div>
}
```

**Comment by zyze5bfej** [comment]
> And you can do it in jsx:
> 
> ```js-jsx
> // https://github.com/JedWatson/classnames
> import classNames from 'classnames';
> import styles from './style.css';
> 
> export default myComponent() {
>   return <div className={classNames(styles.foo, styles.bar, styles.baz)}> ... </div>
> }
> ```

This is not my problem. For example, I want to use a css library and apply it to class names there. It is not possible to write it manually.

**Comment by alexander-akait** [comment]
Still can't undestand
