### ISSUE TITLE
url options is Function, don't work

### ISSUE THREAD

**Issue by noshower** [webpack-contrib/css-loader#1255]
- Operating System: macOS Catalina 10.15.7
- Node Version: v14.14.0
- NPM Version: 6.14.8
- webpack Version: 5.20.2
- css-loader Version: 5.0.1

my css-loader config:

```js
 options: {
    url: (url) => {
      console.log('url', url);
      return !url.startsWith('/guide/img')
    },
    modules: {
      localIdentName: '[path][name]__[local]--[hash:base64:5]'
    }
  }
```

### Expected Behavior

 background-image: url("/guide/img/banWord/addCoinDialogTitleBg.png");
 
expected : this url dont resolve. because this is http url 。full url likes "http://domain.com/guide/img/banWord/addCoinDialogTitleBg.png"

### Actual Behavior

this url resolve. but, throw error 'Error: Can't resolve 'guide/img/banWord/addCoinDialogTitleBg.png''

### Other

I found url funciton was never called.

it sees like a bug.

**Comment by alexander-akait** [comment]
Here run https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L107, it means you check is invalid, unfortunately you don't provide how we can reproduce it, so I can't say what is wrong

**Comment by alexander-akait** [comment]
I added test(s) with your example and everything works well, something wrong with the config
