### ISSUE TITLE
Docs out of date - Options.url now resolve absolute path

### ISSUE THREAD

**Issue by joe223** [webpack-contrib/css-loader#1258]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
`css-loader` now resolve absolute path since v4.0.0. But README file still saying 
```
Enables/Disables url/image-set functions handling. Control url() resolving. Absolute URLs are not resolving.
```
CHANGELOG of v4.0.0:
https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#400-2020-07-25

Commit of resolve algorithm:
https://github.com/webpack-contrib/css-loader/commit/bc19ddd8779dafbc2a420870a3cb841041ce9c7c

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/css-loader/pull/1259, thanks
