### ISSUE TITLE
css modules import * as not work

### ISSUE THREAD

**Issue by monic-shixi** [webpack-contrib/css-loader#1276]
- Operating System:maxOs 10.14.5
- Node Version:12.13.1
- NPM Version:6.12.1
- webpack Version:5.6.0
- css-loader Version:5.0.1

### Expected Behavior
`import * as styles form './xxx.module.css'`
`styles.className` is work.

### Actual Behavior

`import * as styles form './xxx.module.css'`
`styles` is the default module.

### Code

https://github.com/monic-shixi/cssimports

### How Do We Reproduce?

https://github.com/monic-shixi/cssimports

related issue: https://github.com/webpack/webpack/issues/12904

**Comment by alexander-akait** [comment]
No bugs, we can't change it right now because it is breaking change, but you can enable it https://github.com/webpack-contrib/css-loader#namedexport (will be true by default in the next major release, already in our roadmap) (don't forget to do it for `mini-css-extract-plugin` too)

**Comment by monic-shixi** [comment]
> No bugs, we can't change it right now because it is breaking change, but you can enable it https://github.com/webpack-contrib/css-loader#namedexport (will be true by default in the next major release, already in our roadmap) (don't forget to do it for `mini-css-extract-plugin` too)

Thanks for your response. I upgrade to version 5 by version 1. But in the verison 1 works. But in changelog no info show this change.

And if use `namedExport` will export some keyword.I had change `import * as named from 'xx.css'` to `import named from 'xx.css'` by vscode regular.

**Comment by alexander-akait** [comment]
> But in changelog no info show this change.

I think we missed that. Also note before we use `commonjs` so in some cases it works, we fix it in the next major release

**Comment by farism** [comment]
This seems to be something blocking us from upgrading past v3 as well.

Use case is that we have a bunch of clients that are consuming various versions of our component library, and these older library versions are using `import * as` syntax to import styles. So without asking clients to upgrade to the latest versions of the component library (which doesn't use `import * as` syntax) we cannot ask them to upgrade to the latest version of our shared react-scripts with latest css-loader.

But I suppose there is no urgency to upgrade past 3 other than dependency managers bugging us 😄

**Comment by jdortegar** [comment]
I upgraded my Gatsby project to v3 and it works well, but i have the  `import * as` problem when I try to use storybook...
