### ISSUE TITLE
Hashes do not change if class property values change

### ISSUE THREAD

**Issue by rodoabad** [webpack-contrib/css-loader#1278]
Will the hash not change if I change for example `background` from `red` to `blue`? I was expecting that if I am using `contenthash` that the hash being generated would change since the content of the asset (the CSS file) changed.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time of other developers
