### ISSUE TITLE
What does this Loader do?

### ISSUE THREAD

**Issue by vinay-khatri** [webpack-contrib/css-loader#1279]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

Instead of going one-liner. Can somebody explain what this webpack loader do in simple terms?
Like somewhere i read it takes all the css and converts it into javascript string. Is it true and why it does so?

The official one-line explanation is not noob friendly. 
The css-loader interprets @import and url() like import/require() and will resolve them.
I didn't understand what import or url or resolve they are talking about. Does this mean dynamically linking css or js file to corrosponding html file ?

### Your Proposal for Changes

Try to be more noob friendly in explaination.

**Comment by alexander-akait** [comment]
> The css-loader interprets @import and url() like import/require() and will resolve them.

Simple - it convert CSS file to JS files with `import`/`require`/`new URL()`, and export CSS as string and locals if you use CSS Modules. There are a lot of answers on stackoverflow. You can send a PR to improve it if you want.
