### ISSUE TITLE
Hashes do not change if the contents of the CSS/SCSS/LESS file changes.

### ISSUE THREAD

**Issue by rodoabad** [webpack-contrib/css-loader#1282]
- Operating System: macOS Catalina
- Node Version: 14.15.5
- NPM Version: 6.14.11
- webpack Version: 4.5.0
- css-loader Version: 5.0.0

### Expected Behavior

Assume...

```scss
.foo {
  background: red;
}
```

Generates...

```scss
.foo_1q2w {
  background: red;
}
```

If I do...

```diff
.foo {
-  background: red;
+  background: blue
}
```

Then I expect...

```diff
-.foo_1q2w {
+.foo_6j83f {
  background: blue;
}
```

### Actual Behavior

But the actual behaviour is...

```scss
.foo_1q2w {
  background: blue;
}
```

Where the hash stays the same.

### Code

```js
        {
            test: /\.module\.scss$/,
            use: [
                styleLoader, // default setup
                {
                    loader: cssLoader,
                    options: {
                        modules: {
                            localIdentName: '[name]-[local]-[hash:base64:5]' // example shortened
                        }
                    }
                },
                postCssLoader, // default setup
                sassLoader // default setup
            ]
        }
```

### How Do We Reproduce?

Use the exact same rule on your webpack config. Edit a class name and then check if the hash changes.

**Comment by alexander-akait** [comment]
Hashes changed only when class name changed, it is not depend on content, because it doesn't have sense

**Comment by rodoabad** [comment]
Wait why does it not make sense? Don't you want to break caching when the content changes?

**Comment by alexander-akait** [comment]
Use `localIdentHashPrefix` for this case https://github.com/webpack-contrib/css-loader#object

**Comment by rodoabad** [comment]
> Use `localIdentHashPrefix` for this case https://github.com/webpack-contrib/css-loader#object

And this will change the hash for the scenario I am showing on my example?

**Comment by rodoabad** [comment]
It does not for me.

<img width="263" alt="Screen Shot 2021-03-24 at 9 55 56 AM" src="https://user-images.githubusercontent.com/1240667/112331795-3d309600-8c87-11eb-885c-75d389198e39.png">

<img width="258" alt="Screen Shot 2021-03-24 at 9 56 20 AM" src="https://user-images.githubusercontent.com/1240667/112331805-402b8680-8c87-11eb-97d5-dc34e1d36e0b.png">

```js
        modules: {
            localIdentName: '[contenthash:base64:5]',
            localIdentHashPrefix: 'hash'
        }
```

**Comment by alexander-akait** [comment]
`[contenthash]` is has of file, please read docs, you need to use `[local]`

**Comment by rodoabad** [comment]
Using `[local]` would not generate a hash at all since it contains the original class *per the documentation*.

**Comment by alexander-akait** [comment]
You can write custom `localIdentName` function, nested declarations doesn't change hash, won't fix

**Comment by alexander-akait** [comment]
CSS modules is not webpack technology, here repos https://github.com/css-modules, if you want to improve something and change you need write RFC

**Comment by alexander-akait** [comment]
Also changing class names based on declarations will be very inefficient for cache

**Comment by rodoabad** [comment]
I created an issue in CSS Modules though I don't think this has anything to do with CSS Modules but more on hash generation.

If I could simply find a way for me to generate a hash every time content changes then let me know.

Being able to not have class drift vs inefficiency in caching is probably a separate discussion.

**Comment by danantal** [comment]
Hey @rodoabad - I am in the same situation as you described - did you find a solution to your problem?
