### ISSUE TITLE
Getting this error while npm start please help anyone

### ISSUE THREAD

**Issue by nooby17-jpg** [webpack-contrib/css-loader#1293]
./src/ccct-sist.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/ccct-sist.css)
Error: Can't resolve '../node_modules/toastr/build/toastr.min.css' in 'D:\work\ccct-sist-dashboard\src'

throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\chokidar.js
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\DirectoryWatcher.js
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\watcherManager.js
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\watchpack.js
- D:\work\ccct-sist-dashboard\node_modules\webpack\lib\node\NodeWatchFileSystem.js
- D:\work\ccct-sist-dashboard\node_modules\webpack\lib\node\NodeEnvironmentPlugin.js
- D:\work\ccct-sist-dashboard\node_modules\webpack\lib\webpack.js
- D:\work\ccct-sist-dashboard\node_modules\react-scripts\scripts\start.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\chokidar.js
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\DirectoryWatcher.js
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\watcherManager.js
- D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\watchpack.js
- D:\work\ccct-sist-dashboard\node_modules\webpack\lib\node\NodeWatchFileSystem.js
- D:\work\ccct-sist-dashboard\node_modules\webpack\lib\node\NodeEnvironmentPlugin.js
- D:\work\ccct-sist-dashboard\node_modules\webpack\lib\webpack.js
- D:\work\ccct-sist-dashboard\node_modules\react-scripts\scripts\start.js

    at Object.<anonymous> (D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\chokidar.js:17:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\work\ccct-sist-dashboard\node_modules\watchpack\lib\DirectoryWatcher.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by alexander-akait** [comment]
You have invalid `@import` or `require`/`import`, please use the issue template

**Comment by alexander-akait** [comment]
Feel free to feedback, search `toastr` import and please use the issue template in the future, without additional information I can't help you, sorry
