### ISSUE TITLE
PostCss security vulnerability < 8.2.13

### ISSUE THREAD

**Issue by dasgithub76** [webpack-contrib/css-loader#1298]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- css-loader Version:

### Expected Behavior / Situation
No known security vulnerability
### Modification Proposal
Please consider upgrading to 8.2.13

**Comment by alexander-akait** [comment]
You can do it locally, run `npm update`, we use `^` https://github.com/webpack-contrib/css-loader/blob/master/package.json#L48, so you will get fresh version
