### ISSUE TITLE
The library is old so I want you to update it.

### ISSUE THREAD

**Issue by famibee** [webpack-contrib/css-loader#1320]
Due to security issues, the library is out of date and I would like you to update it.
セキュリティの問題から、ライブラリが古いので更新して欲しいです。

| Lib | Now | Latest |
|---|---|---|
| babel-jest | 26.6.3 | 27.0.2 |
| jest | 26.6.3 | 27.0.4 |
| less-loader | 7.1.0 | 9.1.0 |
| postcss-loader | 4.3.0 | 6.1.0 |
| sass-loader | 10.2.0 | 12.1.0 |
| strip-ansi | 6.0.0 | 7.0.0 |
| stylus-loader | 4.3.3 | 6.1.0 |

https://david-dm.org/imagemin/imagemin-svgo?type=dev

**Comment by alexander-akait** [comment]
Feel free to do update
