### ISSUE TITLE
cssWithMappingToString() throw exception when loading css with @import url(https://...)

### ISSUE THREAD

**Issue by ItWorksOnMyMachine** [webpack-contrib/css-loader#1322]
- Operating System: Windows 10
- Node Version: 16.4.2
- NPM Version: 7.18.1
- webpack Version: 5.43.0
- css-loader Version: 5.2.6

### Expected Behavior
I would expect CSS files with @import url(https://...) to load properly.

### Actual Behavior
CSS files with @import url(https://...) fail to load.  The method cssWithMappingToString() is throwing an exception because the @import entries don't have a cssMapping.  The previous version of this loader, for 4.X.X of webpack, included the following code block.  This doesn't exist in the current version.  I can submit a PR for this, however this seems deliberate, so I suspect there's something else going on.

### Code

```js
  if (!cssMapping) {
    return content;
  }
```
### How Do We Reproduce?
Add the following line to a css file. 

```css
@import url(https://fonts.googleapis.com/css?family=Open+Sans&display=swap);
```

**Comment by alexander-akait** [comment]
Feel free to send PR with tests

**Comment by ItWorksOnMyMachine** [comment]
@alexander-akait, do you really think this is a bug though?  It seems like someone before me would have had an issue.  I can't be the only one using @import url() in css files.  So that makes me believe I'm actually doing something wrong in a config somewhere.

**Comment by alexander-akait** [comment]
> How Do We Reproduce?

If you provide full example of the problem I will look at code and say what is wrong

**Comment by ItWorksOnMyMachine** [comment]
https://github.com/ItWorksOnMyMachine/css-loader-au-test

This repo is build using Aurelia.  Run npm run start to build and start the webpack dev server.  The page will NOT load, and you'll see an error in console of devtools.  In the src folder is a file named app.css.  The first line has the @import url() directive.  Comment this out and save the file.  The changes will be picked up and the page will refresh without error.  Move to the Sources tab in devtools find the cssWithMappingToString() method and set a breakpoint inside it.  You'll see that the item argument passed in has only two elements.  This method is dereferencing the fourth element [3] and then using it without null checking it.  The old version of this method did include a null check.

**Comment by alexander-akait** [comment]
Bug, here fix https://github.com/webpack-contrib/css-loader/pull/1324/

**Comment by ItWorksOnMyMachine** [comment]
Thanks @alexander-akait!
