### ISSUE TITLE
TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by aleBiagini** [webpack-contrib/css-loader#1325]
- Operating System: Win 10
- Node Version: v12.18.3
- NPM Version: 6.14.6
- webpack Version: "webpack-stream": "^6.1.2"
- css-loader Version: 5.2.7

### Expected Behavior

I integrated webpack-stream and css-loader inside my gulpfile, proceeded to npm install fullcalendar. I expected to have everything working.

### Response from cli

Unhandled rejection Error in plugin "webpack-stream"
Message:
```
    ./node_modules/@fullcalendar/common/main.css
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\Projects\bergamoscienza-umbraco\BergamoScienza.Web\node_modules\style-loader\dist\index.js:19:24)
 @ ./node_modules/@fullcalendar/common/main.js 6:0-20
 @ ./node_modules/@fullcalendar/core/main.js
```

### Gulpfile extract
        `.pipe(webpack(require('./webpack.config.js')))`
### webpack.config.js
```
module.exports = {
    module: {
        rules: [
            {
                test: /\.css$/i,
                use: ["style-loader", "css-loader"],
            },
        ],
    },
};

```

The code having trouble is from the latest version of fullcalendar.

### How Do We Reproduce?
- Create a repo with a gulpfile and webpack stream
- install css loader
- install style loader
- install fullcalendar
- start gulp task

**Comment by alexander-akait** [comment]
You need webpack v5 to use v5 of css-loader, `webpack-stream` uses webpack v4 (https://github.com/shama/webpack-stream/blob/master/package.json#L39), please update `webpack` and `webpack-stream`
