### ISSUE TITLE
ValidationError: Invalid options object (options.url)

### ISSUE THREAD

**Issue by Pinnokkio** [webpack-contrib/css-loader#1347]
- Operating System: Windows 10 21H1
- Node Version: 16.4.2
- NPM Version: 7.18.1
- webpack Version: 5.45.1
- css-loader Version: 6.0.0

### Actual Behavior
For almost a half year, everything worked fine running npm run prod in my Laravel application but for an unknown reason, it throws an error since today. I have absolutely no clue what I've done, but I can't get it back to work:

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.url should be one of these:
   boolean | object { filter? }
   -> Allows to enables/disables `url()`/`image-set()` functions handling (https://github.com/webpack-contrib/css-loader#url).
   Details:
    * options.url should be a boolean.
    * options.url should be an object:
      object { filter? }
    at validate (D:\...\node_modules\webpack\node_modules\schema-utils\dist\validate.js:105:11)
    at Object.getOptions (D:\...\node_modules\webpack\lib\NormalModule.js:527:19)
    at Object.loader (D:\...\node_modules\css-loader\dist\index.js:31:27)
    at processResult (D:\...\node_modules\webpack\lib\NormalModule.js:701:19)
    at D:\...\node_modules\webpack\lib\NormalModule.js:807:5
    at D:\...\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\...\node_modules\loader-runner\lib\LoaderRunner.js:251:18
```

Before I got this error, it throwed another one which I fixed by myself that. It said, it couldn't find Module 'css-loader'. So I ran npm install --save-dev css-loader (or something similar) and the new error appeared. Bbut I never used css-loader it before, so why i it required now?!

Nevermind, how do I fix the ValidationError error above?

### Code

webpack.config.js
https://gist.github.com/Pinnokkio/240d6f2f2e31df9cc48c7fe1a1496ae4

Unfortunately, this error stops me from further development right now because my .css-files are missing and I can't recreate them. I really appreciate your support, thank you very much!

**Comment by alexander-akait** [comment]
Please read changelog, nwo you should put filter inside object, i.e. `url: { filter: () => {} }`

**Comment by Pinnokkio** [comment]
@alexander-akait Yeah, but I don't use url anywhere.

**Comment by alexander-akait** [comment]
If you don't use it you will not get the error

**Comment by 0xARK** [comment]
Hello ! I have the same error and I don't use url function anymore.... @Pinnokkio Have you solved it ?

**Comment by Pinnokkio** [comment]
> Hello ! I have the same error and I don't use url function anymore.... @Pinnokkio Have you solved it ?

Well, I found a quick fix but I‘m not really happy with it yet.

I am using sass-loader which requires css-loader in it‘s dependencies. For some reason, it updated css-loader to it‘s latest version 6.0.0 (at this time) which seems to be incompatible.

I just added the latest 5.x of css-loader (to „overwrite“ the dependencies of sass-loader) and it seem to work.

I hope I‘m telling something wrong, but I could take a look later after work on it if still required. But you could give it a try to „downgrade“ css-loader to it‘s latest 5.x.

**Comment by 0xARK** [comment]
> > Hello ! I have the same error and I don't use url function anymore.... @Pinnokkio Have you solved it ?
> 
> Well, I found a quick fix but I‘m not really happy with it yet.
> 
> I am using sass-loader which requires css-loader in it‘s dependencies. For some reason, it updated css-loader to it‘s latest version 6.0.0 (at this time) which seems to be incompatible.
> 
> I just added the latest 5.x of css-loader (to „overwrite“ the dependencies of sass-loader) to my own package.json and it seem to work.
> 
> I hope I‘m not telling something wrong, but I could take a look later after work on it if still required. But you could give it a try to „downgrade“ css-loader to it‘s latest 5.x.

Thank you ! I have tried it and it works for me too. I'll use this solution temporarily to avoid blocking production, but when the time comes I'll see if other solutions have been found (apart from your post, I haven't found anything on the internet mentioning exactly the same error, it must still be recent).

**Comment by alexander-akait** [comment]
If somebody provide full reproducible test repo I will show there is the problem

**Comment by krystyna93** [comment]
I had the same issue as well going on for a couple of weeks now, until today when I found someone else on stackoverflow with the same issue. The workaround was to downgrade to 5.2.7, which worked for me too.

I am new to this npm node and packages, so trying to figure the issue out was painful. 
Hopefully this issue can be resolved soon enough without the need to downgrade versions :/

Here is the error output I got for my project:

`ERROR in ./css/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
 - options.url should be one of these:
   boolean | object { filter? }
   -> Allows to enables/disables `url()`/`image-set()` functions handling.
   -> Read more at https://github.com/webpack-contrib/css-loader#url
   Details:
    * options.url should be a boolean.
    * options.url should be an object:
      object { filter? }
    at validate (...\wp-content\themes\workshop_01\node_modules\webpack\node_modules\schema-utils\dist\validate.js:105:11)
    at Object.getOptions ...\wp-content\themes\workshop_01\node_modules\webpack\lib\NormalModule.js:539:19)
    at Object.loader (...\wp-content\themes\workshop_01\node_modules\css-loader\dist\index.js:31:27)
    at processResult (...\wp-content\themes\workshop_01\node_modules\webpack\lib\NormalModule.js:713:19)
    at ...\wp-content\themes\workshop_01\node_modules\webpack\lib\NormalModule.js:819:5
    at ...\wp-content\themes\workshop_01\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at ...\wp-content\themes\workshop_01\node_modules\loader-runner\lib\LoaderRunner.js:251:18
 @ ./js/scripts.js 1:0-27

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.50.0 compiled with 2 errors in 2017 ms
× ｢wdm｣: asset bundled.js 411 KiB [emitted] (name: scripts) 1 related asset
runtime modules 26.3 KiB 13 modules
modules by path ./node_modules/ 344 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 20.9 KiB 10 modules
  modules by path ./node_modules/style-loader/dist/runtime/*.js 5.02 KiB 6 modules
  modules by path ./node_modules/webpack/hot/ 4.46 KiB 5 modules
  modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
  modules by path ./node_modules/url/ 37.4 KiB 3 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB
    ./node_modules/querystring/index.js 127 bytes [built] [code generated]
    ./node_modules/querystring/decode.js 2.34 KiB [built] [code generated]
    ./node_modules/querystring/encode.js 2.04 KiB [built] [code generated]
modules by path ./css/*.css 2.52 KiB
  ./css/styles.css 2.49 KiB [built] [code generated]
  ./node_modules/css-loader/dist/cjs.js?url=false!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./css/styles.css 39 bytes [built] [code generated] [1 error]
./js/scripts.js 149 bytes [built] [code generated]`

**Comment by alexander-akait** [comment]
No issues here, please read the error message

**Comment by krystyna93** [comment]
Can you be more specific. The issue was having to downgrade to older version of css-loader as a workaround to rectify the issue with the validation error.

**Comment by krystyna93** [comment]
> No issues here, please read the error message

Can you be more specific. The issue was having to downgrade to older version of css-loader as a workaround to rectify the issue with the validation error.

**Comment by krystyna93** [comment]
> No issues here, please read the error message

Well, if the symptom is this
 `Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.`

it would be an issue of the url function, so hopefully it will be fixed.

**Comment by alexander-akait** [comment]
Nothing to fix here, you have invalid options for `css-loader`

**Comment by krystyna93** [comment]
Okay. I am not using the url function, so where do I disable it so I dont get the invalid error? I am new to this, so you might need to be specific.

**Comment by alexander-akait** [comment]
Please provide options for `css-loader`

**Comment by krystyna93** [comment]
I have this set in the webpack.config.js file:
`let cssConfig = {
  test: /\.css$/i,
  use: ["css-loader?url=false", { loader: "postcss-loader", options: { postcssOptions : { plugins: postCSSPlugins } }}]
}`

But do I need to add this `/* webpackIgnore: true */` instead?

**Comment by alexander-akait** [comment]
You should change "css-loader?url=false" to:
```
{
  loader: 'css-loader',
  url: false
}
```

But I don't recommend to disable `url()` resolving, if you want to keep some `url()`, please use:
```
{
  loader: 'css-loader',
  url: { filter: () => {/* Logic */ } }
}
```

or as you write above `/* webpackIgnore: false */`

**Comment by krystyna93** [comment]
Ah right, okay. thanks for the example outputs, much appreciated
