### ISSUE TITLE
Incorrect output for :global(.a, .b)

### ISSUE THREAD

**Issue by SystemParadox** [webpack-contrib/css-loader#1356]
- Operating System: Linux
- Node Version: 12.22.2
- NPM Version: 7.19.0
- webpack Version: 4.46.0
- css-loader Version: 5.2.7

### Expected Behavior

Input:

```
.root {
  :global(.a, .b) {
    background: red;
  }
}
```

Expected output:

```
.hash1234 .a, .hash1234 .b {
  background: red;
}
```

### Actual Behavior

```
.hash1234 .a .b {
  background: red;
}
```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fill out all fields and I will reopen

**Comment by SystemParadox** [comment]
Edited.

**Comment by alexander-akait** [comment]
We are not `sass` or `less` so output is expected
