### ISSUE TITLE
After update from 5.2.6 to 6.2.0 urls are getting hashed and exported incorrectly

### ISSUE THREAD

**Issue by kevinmu17** [webpack-contrib/css-loader#1360]
The following font sources are outputted with a hash and in the root of my output->publicPath
```css
@font-face {
src: url('../fonts/XXXXXXX.woff2') format('woff2'),
         url('../fonts/XXXXXXX.woff') format('woff');
}
```

- Operating System: MacOS
- Node Version: v14.15.1
- NPM Version: 7.20.1
- webpack Version: 5.38.1
- css-loader Version: 6.2.0

### Expected Behavior
Don't do anything unexpected with these URLS

### Actual Behavior
fonts are outputted as a hashed string (aknsdfklnewoi.woff) and placed in the wrong folder. Due to this i'm getting the error:
Failed to decode downloaded font: <URL>
8OTS parsing error: invalid sfntVersion: 1702391919

I've debugged this back to CSS-loader, so everything else works fine. When going back to css-loader: 5.2.6 everything works like I configured. Something in the new version is hijacking stuff.

### Code
```js
module: {
        rules: [{
            test: /.s?css$/,
            use: [
                MiniCssExtractPlugin.loader,
                "css-loader",
                "postcss-loader",
                "sass-loader",
            ]
        }
        ]
    },
```

### How Do We Reproduce?
Use a font with @font-face and check the output of your CSS files

**Comment by alexander-akait** [comment]
file-loader and url-loader are deprecated

**Comment by alexander-akait** [comment]
Please read this https://github.com/webpack-contrib/css-loader/releases/tag/v6.0.0 and migrate on assets modules https://webpack.js.org/guides/asset-modules/
