### ISSUE TITLE
docs: incompatible extract-loader is suggested

### ISSUE THREAD

**Issue by 4eb0da** [webpack-contrib/css-loader#1363]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
https://github.com/webpack-contrib/css-loader#tostring

> If, for one reason or another, you need to extract CSS as a plain string resource ...

`extract-loader` doesn't work with current version of `css-loader`, if css contains `url(..)`
This happens because `css-loader` produces `new URL(...., import.meta.url)`, which cannot be parsed by outdated `babel-core` from `extract-loader`

Also, looks like `extract-loader` is deprecated with webpack v5 and should not be used

### Your Proposal for Changes
Add a reminder about `extract-loader` current state or completely remove it from docs

**Comment by alexander-akait** [comment]
You can use workaround - `esModule: false`, if you need `extrac-loader`, but I recommend to migrate on `mini-css-extract-plugin`
