### ISSUE TITLE
PNG files mangled

### ISSUE THREAD

**Issue by willworkforhugs** [webpack-contrib/css-loader#1364]
I just migrated from css-loader@5.2.7 to css-loader@6.2.0. This broke all the background images I used on buttons. The image was reprocessed and output with a new path in the root of dist (not in the same relative folder as the source). Upon inspecting the CSS, I see that the CSS properly points to a new set of assets.

However these generated assets are invalid. Comparing one of them, the original PNG file was 37k and was replaced with a 49k output. The contents look like they'd be useful, starting with things like "data:image/png;base64,iVBORw0KGgoAAAANSUhEU_". However, they fail to render in any browser or several image editors I tried. FireFox warns it "contains errors". Chrome shows a grey square.

Furthermore, the file size is much larger than the original.

options.url = false stops processing and I'm able to get the builds I need, but I don't understand where this would be useful if the PNG output is not readable in a web browser?

- Operating System: MacOS 10.14.6
- Node Version: v14.17.4
- NPM Version: 7.21.0
- webpack Version: 5.51.1
- css-loader Version: 6.2.0

### Expected Behavior

output contains valid images, ideally with the same relative folder structure. The file renaming is ideal from an obfuscation perspective, but I don't see the point in regenerating the assets unless explicitly for some purpose such as compression.

### Actual Behavior

New PNG files are generated which are invalid with standard web browsers and image editors.

### Code

webpack config:

```mode: 'production',
devtool: false,
module: {
		rules: [
			{
				test: /\.(css|scss)$/,
				use: [
					{
						loader: 'style-loader',
						options: {
							insert: 'html', //instead of default in <head>
							attributes: { id: 'style-loader' },
						},
					},
					{
						loader: 'css-loader',
						options: {
							sourceMap: false,
						},
					},
					{
						loader: 'sass-loader',
						options: {
							sourceMap: false,
							sassOptions: {
							},
						},
					},
				],
			},
		],
	},
```

CSS class referenced in SCSS file as:
```
.clipButton {
	background-image: url('./other/buttons/clip.png');
}
```

### How Do We Reproduce?

client's project code, I don't have something tidy to share

**Comment by alexander-akait** [comment]
Because `file-loader` and `url-loader` depreacted, please migrate on asset modules https://webpack.js.org/guides/asset-modules/#:~:text=Asset%20Modules%20is%20a%20type,bundle%20as%20a%20data%20URI
