### ISSUE TITLE
Version 6.2 generates incorrect paths to images in css files

### ISSUE THREAD

**Issue by Alecto** [webpack-contrib/css-loader#1369]
### Bug report

I am using the latest webpack and plugins.
css-loader 6.2 generates incorrect paths to images in css files (5.2.7 latest works correctly).
I did not find solutions by searching in google, and the discussions that I found, did not contain solutions.

### Actual Behavior

rule in css file
![image](https://user-images.githubusercontent.com/8464662/132317075-de26d1f1-1dde-43bc-b42e-1bccd7b03ca1.png)

rule for css files ib webpack.config.js
![image](https://user-images.githubusercontent.com/8464662/132317703-87d2b04d-cef3-4449-a70a-64e0f2b3d9f6.png)

I trye plugin version `"css-loader": "^ 5.2.7"` - it works correctly, the background image is correctly copied to the dist folder and the final css file contains the correct link to the image.

but when the plugin is updated to the latest version 6.2, the build is not performed correctly:
an empty, broken image is present...
![image](https://user-images.githubusercontent.com/8464662/132318131-db452dd2-7b93-4d20-a8f9-3945d75c4686.png)
![image](https://user-images.githubusercontent.com/8464662/132318326-af539602-2952-41f9-ae51-560d4b70319a.png)

css file also contain the path to the wrong file.
![image](https://user-images.githubusercontent.com/8464662/132318463-da1b0cbe-9587-4d8f-a27f-6d3de4b3dc48.png)

### Expected Behavior

with the same code and config as described above, but when installing version 5.2.7, everything is created correctly, the wrong file is missing ...
![image](https://user-images.githubusercontent.com/8464662/132318947-67d928e3-c02f-4555-9abb-633e89821fc3.png)
![image](https://user-images.githubusercontent.com/8464662/132319163-c9e75708-d0a0-48fc-aa97-e816dbc915da.png)

### How Do We Reproduce?

if you like, I can provide a project folder, with working code and config.
by updating the plugin to version 6.2 the problem appears.
please let me know if it is required so i do.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
λ npx webpack-cli info

  System:
    OS: Windows 10 10.0.19042
    CPU: (24) x64 AMD Ryzen 9 3900XT 12-Core Processor
    Memory: 18.48 GB / 31.92 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.38)
    Internet Explorer: 11.0.19041.906
  Packages:
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    copy-webpack-plugin: ^9.0.1 => 9.0.1
    html-webpack-plugin: ^5.3.2 => 5.3.2
    optimize-css-assets-webpack-plugin: ^6.0.1 => 6.0.1
    terser-webpack-plugin: ^5.2.3 => 5.2.3
    webpack: ^5.52.0 => 5.52.0
    webpack-bundle-analyzer: ^4.4.2 => 4.4.2
    webpack-cli: ^4.8.0 => 4.8.0
    webpack-dev-server: ^3.11.2 => 3.11.2

```

the latest versions of plugins are used
package.json
```
{
  "name": "webpack-training",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack --mode development",
    "build": "cross-env NODE_ENV=production webpack --mode production",
    "watch": "cross-env NODE_ENV=development webpack --mode development --watch",
    "start": "cross-env NODE_ENV=development webpack serve --mode development --open chrome",
    "test": "npx webpack --profile --json > stats.json && webpack-bundle-analyzer stats.json dist/"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.15.5",
    "@babel/preset-env": "^7.15.4",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.15.0",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^4.0.0",
    "copy-webpack-plugin": "^9.0.1",
    "cross-env": "^7.0.3",
    "css-loader": "^5.2.7",
    "csv-loader": "^3.0.3",
    "eslint": "^7.32.0",
    "eslint-loader": "^4.0.2",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.3.2",
    "less": "^4.1.1",
    "less-loader": "^10.0.1",
    "mini-css-extract-plugin": "^2.2.2",
    "node-sass": "^6.0.1",
    "optimize-css-assets-webpack-plugin": "^6.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sass-loader": "^12.1.0",
    "style-loader": "^3.2.1",
    "terser-webpack-plugin": "^5.2.3",
    "webpack": "^5.52.0",
    "webpack-bundle-analyzer": "^4.4.2",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^3.11.2",
    "xml-loader": "^1.2.1"
  },
  "dependencies": {
    "@babel/polyfill": "^7.12.1",
    "jquery": "^3.6.0",
    "normalize.css": "^8.0.1"
  }
}
```

**Comment by alexander-akait** [comment]
`file-loader` is deprecated, please read changelog for v6
