### ISSUE TITLE
Use of deprecated folder mapping

### ISSUE THREAD

**Issue by richardbiros** [webpack-contrib/css-loader#1370]
### Bug report
When building my Angular app I get this error.

```
DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at .../node_modules/css-loader/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
```

### Actual Behavior
Throwing deprecated error

### Expected Behavior
Not throwing deprecated error

### How Do We Reproduce?
Using css-loader 5.0.1 which is using postcss version 8.1.4.. This error is fixed with using version 8.1.5
 of postcss

**Comment by alexander-akait** [comment]
Not related to webpack, please update postcss locally https://github.com/postcss/postcss/issues/1455, can't be fixed here
