### ISSUE TITLE
Wrong URL for background images

### ISSUE THREAD

**Issue by amlbar** [webpack-contrib/css-loader#1380]
### Bug report

The css-loader does not give me the correct url for my css build like when using `background: url(***);`. The url is being hashed automatically even setting it in file-loader option to not use a hash for the filename. I also set the file-loader option `emitFile: false;` and then the finished build has still emitted a file for that url. This bug exists since css-loader@6.0.0. 

### Actual Behavior

The url in my Sass file is in this form:
```css
background: url(../../assets/img/shapes.svg);
```
The output url is converted to something like:
```css
background: url(../86b5f32909e54c79331e.svg);
```
And the build emitted a new file `86b5f32909e54c79331e.svg` with the content inside it like `export default "../img/shapes.svg";`

### Expected Behavior

The url in my Sass file is in this form:
```css
background: url(../../assets/img/shapes.svg);
```
The output url should be converted to this:
```css
background: url(../img/shapes.svg);
```

And there should be no additional images created or emitted after build.

### How Do We Reproduce?

You can clone my sample project with minimal code in it here in https://github.com/amlbar/webpack-build-css-with-bug and run on your local machine. For this project, you need to manually change the js and css source in the index.html. (It is handled automatically by django webpack loader in my real project)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
System:
    OS: Linux 4.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 1.67 GB / 11.90 GB
Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v12.16.3/bin/npm
Packages:
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    webpack: ^5.53.0 => 5.53.0
    webpack-bundle-tracker: ^1.3.0 => 1.3.0
    webpack-cli: ^4.8.0 => 4.8.0
```

**Comment by alexander-akait** [comment]
`file-loader` is deprecated for v6, please migrate on asset modules https://webpack.js.org/guides/asset-modules/

**Comment by alexander-akait** [comment]
Or use `type: 'javascript/auto'`

**Comment by AdamHess** [comment]
@amlbar in the latest version they (I don't know why) made images automatically be substituted with a hash value for the file name. 

You can turn this off by setting `url: false` I really want to know the design decision behind this.  it should be one of those things that are explicitly configured, as this is a major deviation from older versions of css-loader.

**Comment by alexander-akait** [comment]
Do you have `file-loader`?

**Comment by AdamHess** [comment]
@alexander-akait its got nothing to do with file loader (though it is a possibility) css-loader need to be explicitly told to not use hashing for the file names.

**Comment by alexander-akait** [comment]
css-loader doesn't use hashes, file-loader is deprecated and you can have problems with hashes if you use it

**Comment by AdamHess** [comment]
I see the error of my ways (I reread the docs) seems as though I solved my
problem accidentally by preventing it from touching urls.

(I was working on a bulk migration from webpack 4 to 5. Way too many deps
to figure out what needed to removed/changed due to deprecation)

**Comment by Chinmay2709** [comment]
I am using asset module, and still have the same issue, how would I resolve this, I have latest Css-loader, web-pack and I am also using asset/modules still facing the same issue.
![Screenshot 2024-05-15 142932](https://github.com/webpack-contrib/css-loader/assets/107140611/ab561fe6-3cfa-42a1-bd3e-3a10454ab790)
![Screenshot 2024-05-20 204241](https://github.com/webpack-contrib/css-loader/assets/107140611/b7f697b0-8f89-4a9f-87f8-f795422f7798)
