### ISSUE TITLE
SSR: generated class names are not consistent for client and server bundles since v5.1.3

### ISSUE THREAD

**Issue by OliverJAsh** [webpack-contrib/css-loader#1384]
### Bug report

We are using `css-loader` with server-side rendering (SSR), so we run webpack twice: once for the client and once for the server.

For the client, we need to generate CSS files, so we use `mini-css-extract-plugin` in combination with `css-loader`.

For the server, we don't need to generate CSS files, so we use `exportOnlyLocals: true`. We just need the CSS modules to export the same class names as the ones used in the CSS files we generated for the client (above).

### Actual Behavior

Generated class names are not consistent for client and server bundles.

### Expected Behavior

Generated class names are consistent for client and server bundles.

### How Do We Reproduce?

Full reduced test case: https://github.com/OliverJAsh/webpack-css-loader-ident-hash-bug

`package.json`:
```json
{
  "dependencies": {
    "css-loader": "^6.3.0",
    "mini-css-extract-plugin": "^2.4.2",
    "webpack": "^5.58.1",
    "webpack-cli": "^4.9.0"
  }
}
```

`webpack.config.js`:
```js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const { MODE } = process.env;

module.exports = {
    plugins: [new MiniCssExtractPlugin()],
    mode: "production",
    entry: "./src/main.js",
    module: {
        rules: [
            {
                test: /\.css$/,
                exclude: /node_modules/,
                use: [
                    ...(MODE === "client" ? [MiniCssExtractPlugin.loader] : []),
                    {
                        loader: "css-loader",
                        options: {
                            modules: {
                                exportOnlyLocals: MODE === "server",
                            },
                        },
                    },
                ],
            },
        ],
    },
};
```

`src/main.js`:
```js
import styles from './main.css'
console.log(styles.container);
```

`src/main.css`:
```css
.container {
    display: block;
}
```

Since [this change which first appeared in v5.1.3][change], `css-loader` generates different class names for the client/server:

```sh-session
$ rm -rf dist && MODE=client webpack && node dist/main.js
UgjPTt4sSFtvFL9kN_LV

$ rm -rf dist && MODE=server webpack && node dist/main.js
BZjOBwj614XLb60af45_
```

It seems this is because `css-loader` now uses `relativeMatchResource` as part of the hash, and in this case, `relativeMatchResource` will be different depending on whether or not we're using `mini-css-extract-plugin`:

- `MODE=server` (`mini-css-extract-plugin` is used): `relativeMatchResource` is `''`
- `MODE=client` (`mini-css-extract-plugin` is not used): `relativeMatchResource` is `'src/main.css\x00'`

We are able to workaround the issue by downgrading to v5.1.2 which does not include [this change][change].

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.09 GB / 16.00 GB
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Chrome Canary: 96.0.4664.2
    Firefox: 90.0.2
    Firefox Nightly: 77.0a1
    Safari: 15.0
    Safari Technology Preview: 15.4
  Packages:
    css-loader: ^6.3.0 => 6.3.0
    webpack: ^5.58.1 => 5.58.1
    webpack-cli: ^4.9.0 => 4.9.0
```

[change]: https://github.com/webpack-contrib/css-loader/commit/1db2f4df3ff9ae8f0667a2304853c8e7cdd0afc1#diff-3274f1a37032fb0ae4e2823def0007c634e869ae0dfc304ff6a12c36513c3a52R86

**Comment by alexander-akait** [comment]
Yes, try to avoid uses very small value for hashes, we have ideas how to improve this for webpack v6, but now we have some limitations with very small value of `contenthash`

**Comment by alexander-akait** [comment]
@jsg2021 hm, can you try to revert these changes locally https://github.com/webpack-contrib/css-loader/commit/c7db752fe6a9c7ff28d165fd24a37be08ef83af5?

**Comment by jsg2021** [comment]
I'll test that.

Here is an example of collision:

```js
import { styled } from 'astroturf/react';
import { User } from '../commons';

export const Container = styled.div`
	cursor: pointer;
	width: 70px;
	height: 70px;
	display: flex;
	align-items: center;
	justify-content: center;

	img,
	svg {
		width: 100%;
	}

	&:global(.flyout-open) {
		background-color: white;
		box-shadow: -1px 0 0 0 #dcdcdc;
		transition: background-color 0.3s, box-shadow 0.3s;
	}
`;

export const Box = styled.div`
	position: relative;
	width: 42px;
	height: 42px;
`;

export const Dot = styled(User.Presence)`
	position: absolute;
	right: 2px;
	bottom: 2px;
`;
```

on 6.4.0, each of these has the same class generated. Astrotruf extracts each template string into a virtual `ComponentName.module.css` with a classname based on the component's name in code. They should all get a unique class name each... except they're not. My localIdentName config is the recommended one:

```
localIdentName: PROD
	? '[hash:base64]' //'[hash:base64]'
	: '[path][name]__[local]--[hash:base64]',
```

**Comment by jsg2021** [comment]
Reverting https://github.com/webpack-contrib/css-loader/commit/c7db752fe6a9c7ff28d165fd24a37be08ef83af5 didn't fix it, but reverting https://github.com/webpack-contrib/css-loader/commit/303a3a171793cf1044c131e291f5c29f9ab86c77 did. 

Would restoring the `relativeMatchResource`  bits break the consistency SSR part?

**Comment by alexander-akait** [comment]
@jsg2021 Because we can't rely on `matchResource`, for example when we extract something it can change module or other loader above can change context (`astroturf` do it, i.e. we don't know `resourcePath`), also we can't change something on context above, loader above should provide context for us, ideally `astroturf` should calculate `hash` for each `js` file (from the place where `astroturf` do extract), based on `resourcePath` and provide it to `css-loader`.

As you can see the original post in this issue about this. `mini-css-extract-plugin` create pseudo module for extracting and previously we rely `matchResource`, so we got different locales.

**Comment by jquense** [comment]
i'm up to do whatever but what is the suggestion here? How would astroturf provide css-loader a hash? I'd love to not use matchResource at all, but that was the path we were led down for doing virtual modules.

**Comment by alexander-akait** [comment]
The main problem what `virtual module` doesn't have `resourcePath`, which used for locals generation and there are two possible fixed:
1. Allow to pass `hash` for `css-loader` (i.e. you can emulate different files)
2. Added API to `loaderContent` for add/renaming current `resourcePath`, so you can create virtual paths, like `src/foo/bar/index.js.css` for extracted content and `css-loader` will use it for generation locals

**Comment by alexander-akait** [comment]
@jquense we discussed with @sokra, we will implement this in near future

**Comment by evnp** [comment]
Wondering if any progress is in sight here? We're currently stuck pinning css-loader 6.3.0 within another dependency due to [^6.4.0 incompatibility with astroturf](https://github.com/4Catalyzer/astroturf/issues/728) (which is very annoying with our current version of npm – need to upgrade).

**Comment by jquense** [comment]
I would also love to not pin css-loader anymore, is there anything i can do here to move this along? I don't think this is just an astroturf issue, anything that uses matchResources (which is now documented on the doc site even) will have a problem here

**Comment by jquense** [comment]
For quick refresh:

when css-loader hashes classnames, it only looks are resourcePath. which is "wrong" for resources imported with `!=!` match resource, resulting in duplicate classNames for:

```
'style1.css!=!button.js'
'style2.css!=!button.js'
```

**Comment by alexander-akait** [comment]
@jquense Yeah, I see, looking at both side will be wrong too, because somtimes you want revers behaviour, why don't use `?modules=true` in this case? I can improve logic and we will accept this

**Comment by alexander-akait** [comment]
i.e. is it acceptable solution? Another problem is hash, because if we will use both sides it can be problem between server and client (often solution)

**Comment by alexander-akait** [comment]
@jquense I think I found the main problem, can you try https://github.com/webpack-contrib/css-loader/pull/1480, looks like I should not concatenate them, instead I should replace :confused:

**Comment by jquense** [comment]
@alexander-akait that PR seems to work! do you think that's sufficient? something like `?hash` would also work but really only if it was on the resourceQuery, not inline loader config, Otherwise we need to rewrite the whole loader chain which i've had trouble with in the past and the benefit of the inline match syntax is that i don't have to know what loaders match it

**Comment by alexander-akait** [comment]
@jquense 

> do you think that's sufficient?

I think yes, it was my fault, we should not concat such things, I will do release, because no problems with SSR and allow to solve your problem
