### ISSUE TITLE
css-loader Does not honor/inherit postcss-loader syntax

### ISSUE THREAD

**Issue by jazzyclimber** [webpack-contrib/css-loader#1396]
### Actual Behavior

I built a postcss syntax (parser, tokenizer, stringifier, the whole works) so that I can get postcss to recognize hubl syntax (hubspot) in css.

Hubl is basically Jinja and on hubspot is allowed to be used in CSS files.

If I use my postcss syntax with pure postCSS (no webpack) everything works as expected. However, when I wrap it all in webpack and use the postcss loader it appears to run postcss twice.

The first pass is the postcss-loader(which works as expected) the second pass is the css-laoder(which doesnt inherit the postcss-syntax specified) and fails.

### Expected Behavior

styles.css (pre-run)
```
{% if x %}
.test{
  text-align: center;
}
{% endif %}
```

styles.css (post-run)
```
{% if x %}
.test{
  text-align: center;
}
{% endif %}
```

### Actual Result
```
/*{% if hubl statement %}*/.test{
  text-align: center;
}
/*{% endif %}*/
```

Console Log of flow:
```
----------- Post CSS Loader Running -------------
Running new parser ==========================+
HUBL FIRE -------------------
HUBL FIRE -------------------
Hubl Stringify Running (from @spingroup/postcss-hubl/lib/stringifier.js)
Hubl Stringify Running
HUBL FIRE STRING start _-_---------------
HUBL FIRE STRING END _-_---------------
Hubl Stringify Running
Hubl Stringify Running
Hubl Stringify Running
HUBL FIRE STRING start _-_---------------
HUBL FIRE STRING END _-_---------------
----------- CSS Loader Running -------------
OG STRINGIFY (from node/postcss/stringifier.js)
OG STRINGIFY (from node/postcss/stringifier.js)
og-comment (from node/postcss/stringifier.js)
OG STRINGIFY (from node/postcss/stringifier.js)
OG STRINGIFY (from node/postcss/stringifier.js)
OG STRINGIFY (from node/postcss/stringifier.js)
og-comment (from node/postcss/stringifier.js)
```

### How Do We Reproduce?

postcss.config.js 
```
const HublSyntax = require('@spingroup/postcss-hubl/lib/hubl-syntax');

module.exports = {
  syntax: HublSyntax,
  mode: "production",
  to: "./dist/main.css",
  plugins: []
};
```

webpack.config.js
```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const path = require('path');

module.exports = {
  plugins: [
    new MiniCssExtractPlugin({
      filename: "[name].css",
    }),
  ],
  entry: {
    'index': './src/index.js',
  },
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'dist'),
  },
  mode: 'production',
  module: {
    rules: [
      // Relevant config for MiniCssExtractPlugin:
      // (the order of `use` is important)
      {
        test: /\.css$/i,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'postcss-loader',
        ],
      },
    ],
  },
};
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
 System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 196.41 MB / 16.00 GB
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.22.1/bin/yarn
    npm: 7.16.0 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 88.0.1
    Safari: 14.1.2
    Safari Technology Preview: 15.0
  Packages:
    css-loader: ^6.5.0 => 6.5.0 
    postcss-loader: ^6.2.0 => 6.2.0 
    style-loader: ^3.3.1 => 3.3.1 
    webpack: ^5.61.0 => 5.61.0 
    webpack-cli: ^4.9.1 => 4.9.1 
```

**Comment by jazzyclimber** [comment]
I made this PR #1397 which solves this issue.

**Comment by alexander-akait** [comment]
Please use `postcss-loader` for these purposes, and we will reuse AST from postcss-loader here, it is expected, current postcss parser is internal and will be replaced on faster alternative in future so we don't expose options for postcss here

**Comment by jazzyclimber** [comment]
Perhaps my big report was a bit too broad - my apologies. I am using postcss-loader. The real issue is that css-loader does not honor the stringifier mentioned in postcss loader when it runs postcss again. 

Postcss is looking for a config option called syntax which I made in my PR above or it’s looking for a stringifier option, which I can also make instead of you’d wish. Either way if you write a custom syntax for post css it does not get used by css-loader. 

You’re correct to say the AST does but if you declare a new node type it will fail because the original post css stringifier doesn’t register it. 

Does that make sense?

**Comment by alexander-akait** [comment]
css-loader should accept CSS in input and output CSS too, postcss-loader should generate valid CSS (input can be any), otherwise it will be broken and will not work

**Comment by jazzyclimber** [comment]
I’m not trying to replace the parser either. I’m really just concerned with the stringifier.

**Comment by alexander-akait** [comment]
I think you missed something when implementing strngifier

**Comment by alexander-akait** [comment]
If you provide example I will show you

**Comment by jazzyclimber** [comment]
What would you like an example of? I’d be happy to get it to you

**Comment by alexander-akait** [comment]
Provide small example of you `webpack.config.js` and source code, so that I can see the problematic

**Comment by jazzyclimber** [comment]
Here is the post css syntax https://github.com/spingroup/postcss-hubl

webpack and postcss config are both pasted in the bug report above

**Comment by alexander-akait** [comment]
Thanks I will look at this in near future :+1:

**Comment by jazzyclimber** [comment]
The syntax works fine when postcss is run on its own without webpack. 

Then I spent a lot of time digging through the post css code ssd and css loader and postcss loader to try to figure this out and it seems like postcss looks for an option configuration that just doesn’t get set at all in cssloader likely because nobody was expecting to need to edit the stringifier because css is consistent, usually. 

But I need to be able to write hubl in my css and the only way to do that is to write a syntax, according to @ai. I did that - and it kind of led me down this path. 

Open to other suggestions if you have any solutions!

**Comment by jazzyclimber** [comment]
@alexander-akait appreciate it! Thanks!

**Comment by alexander-akait** [comment]
Oh, so you keep invalid syntax in CSS? It is bad, because not only `css-loader` will be broken, minimizer and other too

**Comment by alexander-akait** [comment]
As I understand do you want to keep
```
{% if x %}
.test{
  text-align: center;
}
{% endif %}
```

in source code, but it is bad idea, because it is no valid CSS and can lead the problems.

Ideally `hubspot` should support directive via comments, like
```
/** {% if x %} **/
.test{
  text-align: center;
}
/** {% endif %} **/
```

Props:
- valid CSS
- minimizer/minificator will work
- no problems with linters
- no problems with build tools

**Comment by jazzyclimber** [comment]
Yes this also makes sense. So youre recommending to go to hubspot and see if they will support templating directives via comments. Is that correct?

**Comment by jazzyclimber** [comment]
For sure - you know It looks like - they support this in an undocumented fashion. Those expressions still fire inside of a css comment block. They just arent removed server side. 

I can change up my syntax a bit to accommodate for it in the mean time. 

Appreciate your thoughts and help on this one!

**Comment by alexander-akait** [comment]
Feel free to feedback

**Comment by jazzyclimber** [comment]
I think I am in a bit of uncharted waters here with Hubspot. I think they will be quite responsive to this. As I think it will be easy to implement on their end.

As far as I know nobody that builds on the HubSpot platform is really using webpack for their projects because of how the platform is kind of built. But they are really pushing to get devs into their own ecosystem and I think that your solution here is likely the best. 

I really wasnt thinking about how having invalid css would affect other tools such as linters and what not. So I think youre pointing me in the right direction.

Ill change my postcss syntax to auto format hubl expressions into comments. And then we should be good to go!
