### ISSUE TITLE
Using webpack specific properties decreased loader's compatibility.

### ISSUE THREAD

**Issue by malash** [webpack-contrib/css-loader#1401]
### Bug report

In the latest version of css-loader ( 6.5.1 ), there are several lines of code that used [webpack specific properties](https://webpack.js.org/api/loaders/#webpack-specific-properties) in loader context, like,

https://github.com/webpack-contrib/css-loader/blob/0df1ae95e16e925e5214719786184a36363cefea/src/utils.js#L946

and

https://github.com/webpack-contrib/css-loader/blob/0df1ae95e16e925e5214719786184a36363cefea/src/utils.js#L373

and

https://github.com/webpack-contrib/css-loader/blob/0df1ae95e16e925e5214719786184a36363cefea/src/utils.js#L412

These usage cause `css-loader` became less compatible. For example, when using `css-loader` with [`thread-loader`](https://github.com/webpack-contrib/thread-loader), the loader fails to run because of missing properties.

### Actual Behavior

When using `css-loader` with `thread-loader`, this error occurred.

![image](https://user-images.githubusercontent.com/1812118/146138289-bd2a511f-454c-4b0e-ab1a-0e3a8696ec35.png)

### Expected Behavior

`css-loader` should not depends on any webpack specific properties.

### How Do We Reproduce?

```tsx
{
  use: [
    MiniCssExtractPlugin.loader
    'thread-loader',
    'css-loader',
  ]
}
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

N/A

### Refs

Same issue in `thread-loader`: https://github.com/webpack-contrib/thread-loader/issues/66

Similar issue in previous: https://github.com/webpack-contrib/css-loader/pull/1281

**Comment by alexander-akait** [comment]
Sorry, bug in `thread-loader`, we can't fix it here, already tracked in `thread-loader` repo, anyway I recommend do not use `thread-loader`, it is slow down your build in most of case, prefer to use `cache`
