### ISSUE TITLE
Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema. mode=

### ISSUE THREAD

**Issue by cangSDARM** [webpack-contrib/css-loader#1408]
### Bug report

![image](https://user-images.githubusercontent.com/20441896/150070916-bb21f463-d910-408d-95f2-04914522e1d6.png)

**Comment by alexander-akait** [comment]
Please fill out all files, and I will reopen, thanks

**Comment by cangSDARM** [comment]
Oh sorry. It is automatically opened by github. After I found the problem, I didn't continue editing, and then github opened the issue automatically.
