### ISSUE TITLE
css-loader source code returned as result of work

### ISSUE THREAD

**Issue by gituser3000** [webpack-contrib/css-loader#1409]
### Actual Behavior
My config
`

        {
          test: /\.scss$/,
          exclude: [root('src/styles')],
          use: [
            'to-string-loader',
            'css-loader',
            'sass-loader'
          ],
        },
`

After build i have html file with <style> </style> .
A few of these style selectors have css-loader source code inside
![image](https://user-images.githubusercontent.com/15774676/150179285-63f01bcf-1429-4e55-8baa-95132763af26.png)

### Expected Behavior

Styles inlined.

### How Do We Reproduce?
Reproduced at "css-loader": "^6.5.1"
Fixed by downgrading to 5.2.7

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 11.57 GB / 31.30 GB
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 88.0.1
  Packages:
    angular2-template-loader: ^0.6.2 => 0.6.2 
    babel-loader: 8.0.2 => 8.0.2 
    copy-webpack-plugin: ^10.2.0 => 10.2.0 
    css-loader: ^6.5.1 => 6.5.1 
    html-loader: ^3.1.0 => 3.1.0 
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    postcss-loader: ^6.2.1 => 6.2.1 
    resolve-url-loader: ^5.0.0 => 5.0.0 
    sass-loader: ^12.4.0 => 12.4.0 
    stylelint-webpack-plugin: ^3.1.0 => 3.1.0 
    terser-webpack-plugin: ^5.3.0 => 5.3.0 
    to-string-loader: ^1.2.0 => 1.2.0 
    ts-loader: ^9.2.6 => 9.2.6 
    webpack: ^5.66.0 => 5.66.0 
    webpack-cli: ^4.9.1 => 4.9.1 
    webpack-dev-server: ^4.7.3 => 4.7.3

**Comment by alexander-akait** [comment]
Sorry, but in `to-string-loader`, css-loader returns JS with CSS, you should execute JS to inject it in style tag, or use `style-loader`/`mini-css-extract-plugin`

**Comment by gituser3000** [comment]
my bad. 
Still there are at least 2 ways to fix this:
css-loader 5.2.7
or
solution straight from angular cli (exports-loader)
```
    exclude: globalStylePaths, test, use: [
      'exports-loader?module.exports.toString()',
      ...commonLoaders,
      ...(use as webpack.Loader[])
    ]
```
https://github.com/angular/angular-cli/blob/67646796d977bd476c3f618dd64a6c2b6c4ddcae/packages/%40angular/cli/models/webpack-configs/styles.ts#L174

**Comment by alexander-akait** [comment]
We have https://github.com/webpack-contrib/css-loader#exporttype `string`, try it (we still export js, so you need to run it)
