### ISSUE TITLE
Invalid "+" symbol used in generated CSS Module class name "Window_container__se0+Y"

### ISSUE THREAD

**Issue by mikeaustin** [webpack-contrib/css-loader#1414]
### Actual Behavior

An invalid "+" symbol is used in generated CSS Module class names, such as "Window_container__se0+Y". Using document.querySelector('Window_container__se0+Y') returns null, when other class names without "+" are found.

### Expected Behavior

All classes referenced by JS such as 'styles.container' should be accessible via document.querySelector(). document.querySelector('Window_container__se0+Y') returns null because it parses it as an adjacent-sibling operator.

### How Do We Reproduce?

It may be difficult to reproduce because the class-names are auto-generated. I'm using "react-scripts": "5.0.0", which seems to be using css-loader "version": "6.5.1" when looking at the node_modules/css-loader/package.json.

<div class="View_container__1gVev borderRadius_small__cG+YY Window_container__**se0+Y**">...</div>

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 184.51 MB / 16.00 GB
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Chrome Canary: 100.0.4859.0
    Firefox: 95.0.2
    Safari: 15.2
    Safari Technology Preview: 15.4

**Comment by mikeaustin** [comment]
"CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_)"

https://www.w3.org/TR/CSS2/syndata.html

**Comment by alexander-akait** [comment]
You should escape selectors before passing to `document.querySelector`, js and css identifiers are different

**Comment by mikeaustin** [comment]
Can you explain how to *escape* a selector? Using CSS.escape() doesn't help.

`> document.querySelector('.' + CSS.escape('Window_container__se0+Y1'))`
`null`

`> CSS.escape('Window_container__se0+Y1')`
`'Window_container__se0\\+Y'`

**Comment by alexander-akait** [comment]
Yes, it should works, can you provide example - class in CSS and js code?

**Comment by yangjocy** [comment]
However, you couldn't escape `@keyframes` used in `animation`. That is generated by css-loader as well.

**Comment by alexander-akait** [comment]
@yangjocy Can you provide example of the problem?

**Comment by yangjocy** [comment]
![image](https://user-images.githubusercontent.com/11807272/153387613-11e49278-07ba-4482-8567-ee2176a18361.png)
Not easy to reproduce, but I have this screenshot - I have a keyframe named `slideIn`, you could see the hash contains a `+` and it invalidates the animation for both `show` and `hide` class.

**Comment by alexander-akait** [comment]
oh, it is bug, we should not generate `+`, what is version of `css-loader`? And can you reproduce it locally, so we will try to debug it

**Comment by yangjocy** [comment]
Yes I can try to reproduce it locally, just reset the code and libraries to the corresponding version.
Our configuration is a bit more nested. We use [getCSSModuleLocalIdent()](https://github.com/facebook/create-react-app/blob/react-dev-utils%4012.0.0/packages/react-dev-utils/getCSSModuleLocalIdent.js)(v12.0.0) to implement `getLocalIdent()`, which depends on `loader-utils` to generate hash, the same dep as yours to generate hash.

**Comment by yangjocy** [comment]
Any possible quick fix for keyframes?

**Comment by alexander-akait** [comment]
Oh, I am afraid bug in CRA, can you locally try to remove it and check?

**Comment by yangjocy** [comment]
Get it, sorry for misunderstanding. If I replace `react-dev-utils` with `localIdentName`, the issue is gone, but we don't know whether it's because the code is correct, or because the input parameter for hash is different - that function uses different parameters for hash from yours.
I saw below code in your repo, and I'm thinking maybe add one more `replace()` to deal with `+`?
```javascript
    localIdentHash = (localIdentHash + hash.digest(hashDigest))
      // Remove all leading digits
      .replace(/^\d+/, "")
      // Replace all slashes with underscores (same as in base64url)
      .replace(/\//g, "_")
      // Remove everything that is not an alphanumeric or underscore
      .replace(/[^A-Za-z0-9_]+/g, "")
      .slice(0, hashDigestLength);
```

**Comment by alexander-akait** [comment]
We don't generate `+` inside, so we don't need to replace it, I am afraid if we add this, it will be internally, so any external functions should do the same

**Comment by yangjocy** [comment]
`+` is an valid character in general hash strings, it's just specifically invalid for CSS names. So it makes sense to replace it in a CSS name generator.

**Comment by alexander-akait** [comment]
I understand it, but we don't generate hash with `+`

**Comment by yangjocy** [comment]
No you do not, but a CSS name generator should ensure the output is correct as a CSS class name, and its way to consume hash is correct, right? Just like the rest of the `replace()`s, they are all removing digits from a (generally valid) hash string.

**Comment by yangjocy** [comment]
I'm a bit confused, so you don't generate hash with `+`, Hence you don't do the `+` replacement but `loader-utils` or whoever actually generates hash should. Is my understanding correct? But how about the rest of the `replace()`s...

**Comment by alexander-akait** [comment]
Why you think loader utils generate them? CRA use old version (i.e. `v2`), in version 3 we fixed many cases

**Comment by yangjocy** [comment]
So the solution should be upgrading to the latest? But CRA (specifically react-dev-utils v12.0.0) uses the latest v3.2.0 actually.
The issue reporter said s/he uses css-loader "version": "6.5.1", which is quite new giving the latest version is 6.6.0.

**Comment by alexander-akait** [comment]
In this case we should investigate where we generate `+` if you can debug locally will be great

**Comment by yangjocy** [comment]
I am not able to reproduce `+` again, but I managed to mock one. Based on the test result, @alexander-akait  you are right, it's  fixed already in previous versions (css-loader@**v5.2.2**), `+` in `localIdent` will be escaped to `\+` which is valid.
code: https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L317
My test result:
![image](https://user-images.githubusercontent.com/11807272/153579497-554b3d94-10ad-4cc3-ad0a-8fc20efb9cdd.png)

**Comment by alexander-akait** [comment]
Yep, maybe we should improve hash logic here and don't generate `+`, because `\+` is 2 bytes, but we can generate only one character and it is 1byte

**Comment by yangjocy** [comment]
Agree, that would be better. Meanwhile, this issue could be closed right?

**Comment by alexander-akait** [comment]
@yangjocy I think yes, but original reporter doesn't respond me

**Comment by mikeaustin** [comment]
> Yes, it should works, can you provide example - class in CSS and js code?

I thought the example code would be sufficient. It creates a class named “Window_container__se0+Y”, which cannot be looked up by document.querySelector(). The function of the class seems to work, meaning the CSS is applied correctly.

**Comment by mikeaustin** [comment]
> @yangjocy I think yes, but original reporter doesn't respond me

If this is a CRA issue, then yes, I would say this one could be closed. Thank you for finding the source.

**Comment by neil-m** [comment]
Was this fixed? I'm using the most recent version of nextjs and css modules and am still getting classes that start with `+`

![Screenshot 2023-04-10 at 12 03 21 PM](https://user-images.githubusercontent.com/14062013/230941866-f8c05700-9d02-45ee-83a5-b3e384195f45.png)

**Comment by denisx** [comment]
we have such case with "+" when migrating from 2 to 3 version. we need change hash type at webpack css settings... i will write solving, when it will ready and tested

**Comment by denisx** [comment]
fixed at loader-utils https://github.com/webpack/loader-utils/releases/tag/v3.3.1

**Comment by adam-nielsen** [comment]
I wasn't able to upgrade right now (as it involves upgrading React along with Material UI and a bunch of other things) so as a temporary workaround, I made this script:

```
#!/bin/sh

# This fixes a bug where the compiled CSS code contains plus signs in class
# names, which is not permitted and causes errors.

# The script is safe to run multiple times without causing errors.

sed -i "s/'base64'/'base64url'/" node_modules/react-dev-utils/getCSSModuleLocalIdent.js
```

I just have to run it after I have run `npm ci` to populate `node_modules` and then everything works fine again.

It's not ideal, but it does allow me to get some bug fixes out for some older code without spending a large amount of time updating so many packages right now.

**Comment by denisx** [comment]
@adam-nielsen quick fix: use `base62` at old version

**Comment by adam-nielsen** [comment]
@denisx Sorry I'm not sure what that means!  My script does switch the old version to base62.

**Comment by denisx** [comment]
@adam-nielsen Have you resolve the problem?
