### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by mzabuawala** [webpack-contrib/css-loader#1415]
`yarn audit` complaints about 
<img width="801" alt="Screenshot 2022-01-31 at 6 22 47 PM" src="https://user-images.githubusercontent.com/19573369/151797186-f08c8ac6-f694-4b06-aa4c-83cf9c001a2d.png">

**Comment by alexander-akait** [comment]
Update your deps locally, problem in postcss, we can't fix it here

**Comment by mzabuawala** [comment]
I tried that but it is not working as you can clearly see the `Path` field, it is coming from `css-loader` module

**Comment by alexander-akait** [comment]
Update `css-loader`, we can't fix this here

**Comment by mzabuawala** [comment]
Then for which module we need to report here?

**Comment by alexander-akait** [comment]
Please run `npm ls css-loader` and `npm ls postcss`
