### ISSUE TITLE
Exposure of Sensitive Information to an Unauthorized Actor in nanoid

### ISSUE THREAD

**Issue by dlabrecq** [webpack-contrib/css-loader#1420]
### Bug report

Our project inherits a security vulnerability due to css-loader v6.6.0 having a dependency on nanoid v3.2.0.

### Actual Behavior

N/A

### Expected Behavior

It is suggested to upgrade nanoid to version 3.1.31 or later. For example:

```
nanoid@^3.1.31:
  version "3.1.31"
```

### How Do We Reproduce?

> yarn why nanoid
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "nanoid"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "nanoid@3.1.29"
info Reasons this module exists
   - "postcss" depends on it
   - Hoisted from "postcss#nanoid"
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "120KB"
info Disk size with transitive dependencies: "120KB"
info Number of shared dependencies: 0
=> Found "css-loader#nanoid@3.2.0" <<< 
info Reasons this module exists
   - "css-loader#postcss" depends on it
   - Hoisted from "css-loader#postcss#nanoid"
✨  Done in 0.60s.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 101.91 MB / 16.00 GB
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.1
  Packages:
    copy-webpack-plugin: 9.0.1 => 9.0.1 
    css-loader: 6.6.0 => 6.6.0 
    git-revision-webpack-plugin: 3.0.6 => 3.0.6 
    html-loader: 2.0.0 => 2.0.0 
    html-replace-webpack-plugin: 2.6.0 => 2.6.0 
    html-webpack-plugin: 5.3.2 => 5.3.2 
    null-loader: 4.0.1 => 4.0.1 
    sass-loader: ^11.0.1 => 11.1.1 
    ts-loader: 8.0.17 => 8.0.17 
    tsconfig-paths-webpack-plugin: 3.5.1 => 3.5.1 
    webpack: ^5.57.1 => 5.58.1 
    webpack-cli: ^4.8.0 => 4.9.0 
    webpack-dev-server: 4.7.4 => 4.7.4 
  Global Packages:
    webpack: 1.13.3

**Comment by alexander-akait** [comment]
Sorry, we can't fix it here, please update deps locally (update postcss), we don't pin `postcss` version in `package.json`, yep, it is transitive dep, please read https://dev.to/malykhinvi/fix-a-transitive-npm-dependency-vulnerability-4775
