### ISSUE TITLE
latest version 6.7.1 not work with thread-loader

### ISSUE THREAD

**Issue by BUPTlhuanyu** [webpack-contrib/css-loader#1434]
### Bug report
Cannot destructure property 'outputOptions' of 'loaderContext._compilation' as it is undefined.

https://github.com/webpack-contrib/css-loader/blob/71d317e8797972d135e616470e3d9d89abd0d829/src/utils.js#L564

### Actual Behavior

failed

### Expected Behavior

success

### How Do We Reproduce?
use thread-loader with css-loader

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
webpack-cli@3.3.12
webpack@5.64.4

**Comment by alexander-akait** [comment]
Yes, known issue, we can't fix it here, sorry, it should be fixed on thread-loader side
