### ISSUE TITLE
The (not only) primereact's dropdown css not loaded correctly

### ISSUE THREAD

**Issue by domino2** [webpack-contrib/css-loader#1435]
### Actual Behavior

The trigger icon of the dropdown is rendered as a square instead of the caret (there would be more somewhere)

### Expected Behavior

The caret should be rendered as with the css-loader version 5.2.7

### How Do We Reproduce?

Use the Dropdown from "primereact/dropdown" component
with the most recent css-loader version

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 12.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.67 GB / 32.00 GB
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Edge: 99.0.1150.46
    Firefox: 98.0.2
    Firefox Developer Edition: 99.0
    Safari: 15.4
  Packages:
    babel-loader: ^8.2.4 => 8.2.4
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    css-loader: ^6.7.1 => 6.7.1
    file-loader: ^6.2.0 => 6.2.0
    sass-loader: ^12.6.0 => 12.6.0
    style-loader: ^3.3.1 => 3.3.1
    svg-inline-loader: ^0.8.2 => 0.8.2
    webpack: ^5.70.0 => 5.70.0
    webpack-bundle-analyzer: ^4.5.0 => 4.5.0
    webpack-cli: ^4.9.2 => 4.9.2
    webpack-livereload-plugin: ^3.0.2 => 3.0.2
    webpack-merge: ^5.8.0 => 5.8.0
```

**Comment by alexander-akait** [comment]
Sorry, not related to css-loader, we don't change your code, without additional information I can't help sorry

**Comment by domino2** [comment]
It seams to me related because the upgrade breaking the style.
It is not related to code I wrote, so where may be a problem?

I was digging and it looks like the @font-face is not passes through.
```
@font-face {
    font-family: 'primeicons';
    font-display: block;
    src: url('./fonts/primeicons.eot');
    src: url('./fonts/primeicons.eot?#iefix') format('embedded-opentype'), url('./fonts/primeicons.ttf') format('truetype'), url('./fonts/primeicons.woff') format('woff'), url('./fonts/primeicons.svg?#primeicons') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Where the style is imported by this `@import "primeicons/primeicons.css";`.
It doesn't matter the order of imports in the file.

Just wondering if you see anything wrong? Thank you

**Comment by alexander-akait** [comment]
If you provide small example I will show you a problem place, hard to say without exaple

**Comment by domino2** [comment]
Hello again ... so I did my homework and here is minimal project to reproduce the issue. I don't want to say it is related to css-loader, but this is what I found and I would to get rid of it somehow.
So if it is not related, I'm happy to ask on Stackoverflow .... 

I'm looking forward for an answer

https://github.com/domino2/css-loader-issue-demonstrator/tree/master

**Comment by alexander-akait** [comment]
I think problem related to https://github.com/domino2/css-loader-issue-demonstrator/blob/master/webpack.common.js#L50 or https://github.com/domino2/css-loader-issue-demonstrator/blob/master/webpack.common.js#L86 or https://github.com/domino2/css-loader-issue-demonstrator/blob/master/webpack.common.js#L89. Do you have images/svg in dropdown? Please try to migrate on https://webpack.js.org/guides/asset-modules/

**Comment by domino2** [comment]
THANK YOU! It works ... so the final state of loaders array is this:
```
module: {
  rules: [
    {
      test: /\.js$/,
      type: "javascript/auto",
      exclude: [/node_modules/],
      use: [
        {
          loader: "babel-loader",
        },
      ],
    },
    {
      test: /\.css$/,
      type: "javascript/auto",
      use: [
        {
          loader: "style-loader",
        },
        {
          loader: "css-loader",
        },
      ],
    },
    {
      test: /\.(ttf|eot|woff|svg)$/,
      type: "asset/resource",
      generator: {
        publicPath: `${process.env.projectpath}/build/`,
        filename: "assets/fonts/[name][ext]",
      }
    },
  ],
},
```
