### ISSUE TITLE
IE11 url not work

### ISSUE THREAD

**Issue by kailong321200875** [webpack-contrib/css-loader#1439]
### Bug report

css-loader^6.7.1 does not support ie11. It is downgraded to version 5.2.7 and can work normally

![1649212820(1)](https://user-images.githubusercontent.com/32283845/161885108-aed05377-84d2-4506-8b8d-05439337b7c0.png)

### Actual Behavior

not support ie11

### Expected Behavior

support ie11

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
[ReproductionCode.zip](https://github.com/webpack-contrib/css-loader/files/8423148/ReproductionCode.zip)

**Comment by alexander-akait** [comment]
Please set `target: ['web', 'es5']` https://webpack.js.org/configuration/target/#string-1m otherwise webpack generates es6 code

**Comment by kailong321200875** [comment]
@alexander-akait It still doesn't work
![1649290933(1)](https://user-images.githubusercontent.com/32283845/162096066-dfcde964-9e16-4d8f-b13c-dec3540ffd36.png)
![1649290955(1)](https://user-images.githubusercontent.com/32283845/162096099-bc77c893-1a5d-44f8-aa71-b4a997feea23.png)

**Comment by kailong321200875** [comment]
@alexander-akait It is normal in version 5.2.7
![1649291239(1)](https://user-images.githubusercontent.com/32283845/162096519-6c872a64-5dda-4344-a00b-5e79c9abfeac.png)

**Comment by alexander-akait** [comment]
Can you copy code from `1690:31`? Or place where error happens, we have e3 compatibility code and many tests

**Comment by kailong321200875** [comment]
@alexander-akait This is actually not accurate. Maybe you can download the compressed package I uploaded and have a try?
![1649296941(1)](https://user-images.githubusercontent.com/32283845/162105505-6c692583-a1d3-4844-bff9-d67d82e54e68.png)

**Comment by alexander-akait** [comment]
@kailong321200875 I tried, sorry, I can't real reproduce this problem, can you translate to English error message? So if you downgrade css-loader and keep other versions are same does all work fine? If you remove `url()` from CSS, does all work fine? Can you set `  devtool: false,` in `webpack.base.config.js` and update `index.js`?

**Comment by kailong321200875** [comment]
@alexander-akait It is normal to downgrade CSS loader，It is also normal to remove the URL ()，If you use the code I uploaded, it should be reproducible

**Comment by kailong321200875** [comment]
@alexander-akait English error message：Object does not support this operation

**Comment by alexander-akait** [comment]
Do you polyfill `new URL(...)`? Because you need it to work with IE11, maybe we missed that in docs, as workaround you can try to set https://github.com/webpack-contrib/css-loader#esmodule to `false`

**Comment by kailong321200875** [comment]
> 你 polyfill`new URL(...)`吗？因为您需要它与 IE11 一起使用，也许我们在文档中错过了这一点，作为解决方法，您可以尝试将https://github.com/webpack-contrib/css-loader#esmodule设置为`false`

thank you，It is effective
