### ISSUE TITLE
Webpack:// mini-css-extract-plugin got appended with font url(webpack:///mini-css-extract-plugin+ Actualpath) when prod mode

### ISSUE THREAD

**Issue by muthumanig** [webpack-contrib/css-loader#1441]
### Actual Behavior

Fonts are loaded inside webpack:// and  inside css file, fontfamily url webpack:/// mini-css-extract-plugin got appended when building on production mode

### Expected Behavior

Fonts has to be loaded inside build/dist/app/static/fonts & inside css file also, fontfamily url('./fonts)

### How Do We Reproduce?
webpack:5.69.1
css-loader:6.6.0
"mini-css-extract-plugin": "2.6.0",

webpackconfig:

rule:
{
                    test: /\.(woff|woff2|eot|ttf|otf|svg)$/,  
                    type: 'asset/resource',
                    generator: {
                        filename: 'static/' + SchoolName + '/fonts/[name][ext]',
                    }
                },
                {
                    test: /\.scss$/,
                    use: [
                        {loader: MiniCssExtractPlugin.loader,options: {
                            publicPath: "/schools/"
                        }},
                        { loader: "css-loader",options:{ sourceMap:true,url:true} },

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
![image](https://user-images.githubusercontent.com/90680614/165493385-97d931bc-847f-42b2-be7d-bdbfb366be02.png)

**Comment by vankop** [comment]
it looks like you did not use mini-css plugin. please take a look a guide how to setup mini-css https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by muthumanig** [comment]
@vankop  i used mini-css already. here my webpack config 
`const webpack = require('webpack');
const path = require('path');

const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");

const nodeEnv = process.env.NODE_ENV || 'development';
const isProduction = nodeEnv === 'production';

const sourcePath = path.resolve(__dirname, './src');
const buildPath = path.resolve(__dirname, './build/dist/app');
const stylesPath = path.resolve(__dirname, './node_modules');
const tocName="northern";
module.exports = {
    name: "client",
    mode: nodeEnv,
    entry: {
        app: './src/client.js',
        vendor: ['react', 'react-transition-group', 'react-dom', 'react-redux']
    },
    output: {
        path: buildPath,
        filename: isProduction ? 'static/js/[name].[contenthash].js' : 'static/js/[name].js'
    },        
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules\/(?!web-components)/,
                loader: 'babel-loader',
                options: {
                    compact: false,
                    cacheDirectory: true,
                    presets: [
                        [
                        "@babel/preset-env", { modules: false }
                    ],
                    "@babel/preset-react"]
                }
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf|svg)$/,  
                type: 'asset/resource',
                generator: {
                    filename: 'static/' + tocName + '/fonts/[name][ext]'
                }
            },
            {
                test: /\.scss$/,
                use: [
                    {loader: MiniCssExtractPlugin.loader},
                    { loader: "css-loader"},                        
                    {
                        loader: "sass-loader",
                        options: {
                            additionalData: '@import "' + tocName + '/IndexSettings";',
                            sassOptions: {
                            includePaths: [
                                path.resolve(__dirname, "node_modules", "toc-branding", "Styles")
                            ]
                        }
                        }
                    }
                ]                    
            }                
        ]
    },
    resolve: {         
        alias: {
            process: "process/browser"
        },   
        extensions: ['.js', '.jsx'],
        fallback: { 
            "zlib": false,
            "path": false,
            "buffer":false
        }
    },
    plugins:[ 
        new webpack.ProvidePlugin({
            process: 'process/browser',
        }),    
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(nodeEnv),
            },
        }),                   
        new MiniCssExtractPlugin({
            filename: isProduction ? 'static/' + tocName + '/css/app.[contenthash].css' : 'static/' + tocName + '/css/app.css'
        })]
}`

**Comment by vankop** [comment]
please create reproducible repo
