### ISSUE TITLE
`resourceQuery` no longer working with `url()` in v6.0.0 and above

### ISSUE THREAD

**Issue by catarak** [webpack-contrib/css-loader#1442]
### Actual Behavior

When resolving a resource path with `url()`, the resourceQuery (e.g. the `raw` in `image.png?raw`) is left after the resolution, leaving a broken url. 

### Expected Behavior

In `v5.2.7`, the resourceQuery works as expected, which is that it directs the resource path to the appropriate loader given the `resourceQuery`, and generates a url that works with the `resourceQuery` no longer included in the URL.  

### How Do We Reproduce?

I have the following configuration for loading `.svg` files in my webpack config:
```js
{
        test: /\.svg$/,
        oneOf: [
          {
            resourceQuery: /byContent/,
            use: 'raw-loader'
          },
          {
            resourceQuery: /byUrl/,
            use: 'file-loader'
          },
          {
            use: {
              loader: '@svgr/webpack',
              options: {
                svgoConfig: {
                  plugins: [
                    {
                      name: 'removeViewBox',
                      active: false
                    },
                  ],
                }
              }
            }
          }
        ]
      }
```

With the following in a `.scss` file:
```scss
$codefold-icon-open: url(../images/triangle-arrow-down-white.svg?byUrl),
```

Again, this works with `v5.2.7` but not `v6.0.0` and above. Forgive me if there was a breaking change that I'm not understanding, but I searched for `resourceQuery` around and I couldn't find anything.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 446.39 MB / 16.00 GB
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 95.0.2
    Safari: 14.1.1
  Packages:
    babel-loader: ^8.2.5 => 8.2.5
    copy-webpack-plugin: ^10.2.4 => 10.2.4
    css-loader: ^5.2.7 => 5.2.7
    css-minimizer-webpack-plugin: ^3.4.1 => 3.4.1
    eslint-webpack-plugin: ^3.1.1 => 3.1.1
    file-loader: ^6.2.0 => 6.2.0
    postcss-loader: ^6.2.1 => 6.2.1
    raw-loader: ^4.0.2 => 4.0.2
    react-hot-loader: ^4.13.0 => 4.13.0
    sass-loader: ^12.6.0 => 12.6.0
    style-loader: ^3.3.1 => 3.3.1
    terser-webpack-plugin: ^5.3.1 => 5.3.1
    webpack: ^5.72.0 => 5.72.0
    webpack-cli: ^4.9.2 => 4.9.2
    webpack-dev-middleware: ^5.3.1 => 5.3.1
    webpack-hot-middleware: ^2.25.1 => 2.25.1
    webpack-manifest-plugin: ^5.0.0 => 5.0.0
    webpack-node-externals: ^3.0.0 => 3.0.0

Thank you for your help!

**Comment by alexander-akait** [comment]
`file-loader` is deprecated and should not be used in webpack v5, please migrate on assets modules and use https://webpack.js.org/guides/asset-modules/#replacing-inline-loader-syntax

**Comment by alexander-akait** [comment]
From changelog:
> file-loader and url-loader are deprecated, please migrate on [asset modules](https://webpack.js.org/guides/asset-modules/), since v6 css-loader is generating new URL(...) syntax, it enables by default built-in [assets modules](https://webpack.js.org/guides/asset-modules/), i.e. type: 'asset' for all url()

But yes, not words about `resourceQuery`, but it is under the hood

**Comment by catarak** [comment]
Ahhh got it, thank you for the clarification! I had a feeling it was something like this. I'll close this issue since it is working as expected.
