### ISSUE TITLE
Generated font files are not working

### ISSUE THREAD

**Issue by everdimension** [webpack-contrib/css-loader#1445]
I have experienced a problem where the font imports done using the css `@font-face` rule aren't working.

Downgrading to `css-loader@5.1.3` solved the issue

I have created a repo which show the bug: https://github.com/everdimension/css-loader-font-bug-reproduction/

If you build project in the main branch, which uses `css-loader@6.7.1`, generated html and css files give you this:

![image](https://user-images.githubusercontent.com/5347023/166155546-29029c48-6029-4d62-b044-c49b3bab1bf9.png)

But if you use `css-loader@5.1.3` which you can see in the other branch in the repo, you'll see the expected result:

![image](https://user-images.githubusercontent.com/5347023/166155586-a3d044c7-562d-4ee1-add9-836b30286553.png)

You can also compare the `dist` folders which are slightly different

**Comment by alexander-akait** [comment]
url-loader and file-loader deprecated - https://github.com/everdimension/css-loader-font-bug-reproduction/blob/main/webpack.config.js#L40, please migrate on https://webpack.js.org/guides/asset-modules/ or set `esModules: false`
