### ISSUE TITLE
[docs] >= 4.X `modules` without `esModule: false` does not work

### ISSUE THREAD

**Issue by wang1212** [webpack-contrib/css-loader#1452]
Documentation Is:

- [x] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

**>= 4.X** `modules` without `esModule: false` does not work.

### Your Proposal for Changes

Should it be noted in the documentation that `esModule: false` should be configured when using the `modules` configuration option?

I debugged for a long time and found some clues from here #1447.

**Comment by alexander-akait** [comment]
It is worked without `esModule` (there are many tests), if you have a problem, please open a new issue and show your problem using an issue template and I will help
