### ISSUE TITLE
URIError: URI malformed

### ISSUE THREAD

**Issue by Alex7sss227** [webpack-contrib/css-loader#1457]
"Помогите, После запуска NuxtJs дев сервер выдает ошибку
HELP , ( After starting NuxtJs dev, the server throws the error ) "

 ========== ERROR=========== 
   ERROR in ./components/InfoServicesBlocD.vue?vue&type=style&index=0&id=1a5aafcf&scoped=true&lang=css& friendly-errors 01:07:12 
`
Module build failed (from ./node_modules/css-loader/dist/cjs.js): friendly-errors 01:07:12
URIError: URI malformed
 at decodeURIComponent (<anonymous>)
 at normalizeUrl (C:\Users\weldi\OneDrive\Desktop\project72\node_modules\css-loader\dist\utils.js:108:10)
at C:\Users\weldi\OneDrive\Desktop\project72\node_modules\css-loader\dist\plugins\postcss-url-parser.js:162:45
 friendly-errors 01:07:12
 @ ./node_modules/vue-style-loader??ref--3-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-o`
==============package.json======= 
    `"@nuxtjs/axios": "^5.13.6",
    "core-js": "^3.19.3",
    "nuxt": "^2.15.8",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "eslint-config-prettier": "^8.3.0",
    "prettier": "^2.5.1"
  }``
 ===========================

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/css-loader/issues/1458
