### ISSUE TITLE
Include svg as utf-8 instead of base64?

### ISSUE THREAD

**Issue by thany** [webpack-contrib/css-loader#1460]
### Feature Proposal

Since SVG is always plaintext, usually even utf-8, there is no real need to encode it to base64. It's completely possible to include an svg as-is, except for a few character escapes, such as quotes.

### Feature Use Case

Because base64 typically adds some 30% data due to the nature of how it encodes, including SVG as plaintext should result in smaller CSS bundles.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```

  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 10.57 GB / 31.76 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.44)
    Internet Explorer: 11.0.19041.1566
```

These scripts always manage to miss Firefox, version 101 in this case. Not that it matters for this feature.

**Comment by alexander-akait** [comment]
We don't convert SVG to base64, check our code

**Comment by thany** [comment]
Is that a new feature then? I'm stuck at 5.2.7 and it's definitely outputting as base64.

**Comment by alexander-akait** [comment]
Webpack handles assets, so you can setup it using https://webpack.js.org/guides/asset-modules/, you can decide that you need to keep as file/embeded/base64, css-loader just create `new URL(...)` so webpack can handle it as an asset module
