### ISSUE TITLE
当我使用npm run build进行打包时，报错

### ISSUE THREAD

**Issue by xiayongtian** [webpack-contrib/css-loader#1465]
WARNING in ./src/routes/Home/index.jsx 14:15-26
export 'home' (imported as 'styles') was not found in './style.css' (module has no exports)
 @ ./src/router.js 4:0-33 17:15-19
 @ ./src/index.js

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
