### ISSUE TITLE
extract url imports

### ISSUE THREAD

**Issue by xHyroM** [webpack-contrib/css-loader#1468]
### Feature Proposal

Extract url imports and put content into dist file.

### Feature Use Case
Faster loading

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  System:
    OS: Linux 5.18 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz
    Memory: 5.13 GB / 15.55 GB
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.16.0 - /usr/bin/npm
  Browsers:
    Firefox: 103.0.1
  Packages:
    css-loader: ^6.7.1 => 6.7.1 
    css-minimizer-webpack-plugin: ^4.0.0 => 4.0.0 
    resolve-url-loader: ^5.0.0 => 5.0.0 
    sass-loader: ^13.0.2 => 13.0.2 
    style-loader: ^3.3.1 => 3.3.1 
    uglifyjs-webpack-plugin: ^2.2.0 => 2.2.0 
    webpack: ^5.74.0 => 5.74.0 
    webpack-cli: ^4.10.0 => 4.10.0

**Comment by alexander-akait** [comment]
mini-css-extract-plugin and webpack allow it using `splitChunks` (there are examples in README in `mini-css-extract-plugin`), this loader just generate JS code for browser, so we can't solve it here.

Unfortunately you don't provide more information, so we can't help you here
