### ISSUE TITLE
Vue 3 / Webpack 5 Boilerplate Code Not Applying CSS Scoping

### ISSUE THREAD

**Issue by jwbats** [webpack-contrib/css-loader#1475]
### Bug report

I'm setting up a Vue 3 / Webpack 5 boilerplate. The CSS scoping isn't working for me. Because of the widely suggested 'esModule : false' fix, I strongly suspect it's a css-loader issue.

The details are on [this SO thread](https://stackoverflow.com/questions/74056416/vue-3-webpack-5-boilerplate-code-not-applying-css-scoping).

### Actual Behavior

CSS scoping is applied to the injected CSS, but not the HTML elements themselves.

The CSS isn't applied at all.

### Expected Behavior

CSS scoping is applied to both the injected CSS, as well as the HTML elements themselves.

The CSS is correctly applied.

### How Do We Reproduce?

[Here's my boilerplate code.](https://github.com/jwbats/Vue3Webpack5)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 17.34 GB / 31.91 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566

**Comment by alexander-akait** [comment]
Sorry, CSS loader apply scoped changes only for CSS files (hto HTML), if you use vue please use `scoped` and create HTML using vue

**Comment by alexander-akait** [comment]
Also vue-loader under the hood inject required loader for CSS modules, you don't need to do it manually (as I remember was)

**Comment by jwbats** [comment]
Hi @alexander-akait,

Thanks for getting back to me.

I am using `scoped` in the `style` attribute of my CSS in the .vue file, which contains a HTML template.

So I'm already doing what you suggest.

Did I post this issue in the wrong repo? Should I take it to the vue-loader repo, instead?

**Comment by jwbats** [comment]
This was caused by a missing external in webpack.config.js.

```
externals: {
	vue: 'Vue'
}
```

**Comment by jwbats** [comment]
@alexander-akait, it is indeed solved. I already closed the issue, myself. Although I'd still like to learn why I have to declare Vue as an external, in order for it to work.

If Vue needs to be declared as an external for Webpack to do its work, then why did Webpack do most of its Vue-to-JS transpilation work just fine, without throwing warnings or errors?

Perhaps you are not the right person to ask, but I'm giving it a shot, anyway.

**Comment by alexander-akait** [comment]
I think it is related to vue-loader (because it should work without externals)

**Comment by jwbats** [comment]
In that case it might be worth reopening this issue, so that you can investigate?

**Comment by alexander-akait** [comment]
I don't think it is related to css-loader, css-loader doesn't have the response for these things, `scoped` is a feature for/inside `vue` and have some differente things than CSS modules, but have the same idea and solutions

**Comment by jwbats** [comment]
Oh, right... I thought I was in the vue-loader repo here.

Never mind!
