### ISSUE TITLE
wrong code in README

### ISSUE THREAD

**Issue by EaVanCN** [webpack-contrib/css-loader#1496]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [ x ] Not Sure?

### Please Explain in Detail...

In the part of README.md about the 'url' parameter, the variable used in the filter url () should be wrong, and the 'path' should be 'url'

**Comment by alexander-akait** [comment]
Can you provide a place? Do you want to send a PR?
