### ISSUE TITLE
`@import` with media query produces incorrect output when the imported file is a entry point

### ISSUE THREAD

**Issue by silverwind** [webpack-contrib/css-loader#1503]
### Feature Proposal

Support [@import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) `list-of-media-queries` syntax. Currently the plugin ignores and strips the media query from the output, making runtime-conditional import impossible without additional plugins.

### Feature Use Case

```css
@import "./dark.css" (prefers-color-scheme: dark);
```

Currently the plugin outputs the content of `dark.css` file without any media query condition, so the CSS is applied unconditionally at runtime:

```css
/* content of dark.css */
```

A better output would be:

```css
@media (prefers-color-scheme: dark) {
  /* content of dark.css */
}
```

**Comment by silverwind** [comment]
Another alternative to above standard syntax may be non-standard syntax:

```css
@media (prefers-color-scheme: dark) {
  @import "./dark.css";
}
```

`css-loader` ignores this `@import` statement and outputs it unmodified, likely because it is not on top-level so it's technically invalid CSS, thought this syntax is supported by preprocessors like `sass` or `less`, so it could be considered.

**Comment by silverwind** [comment]
Seems I found a solution by adding `postcss-loader with the`postcss-import` plugin, but I still wonder if this feature would be considered for inclusion in `css-loader` as it's standard CSS syntax, and I prefer to avoice PostCSS wherever possible.

**Comment by alexander-akait** [comment]
Anyway feel free to feedback, and check `style-loader` and `mini-css-extract-plugin` version too

**Comment by silverwind** [comment]
This was the setup where I observed it:

https://github.com/go-gitea/gitea/blob/202803fc69d21763a06d8d0f5a4c46509c18f6f1/webpack.config.js#L138-L153

No `style-loader`, `mini-css-extract-plugin` very slightly out of date by one patch release. I guess I have to retry with a clean setup, after seeing your tests.

**Comment by alexander-akait** [comment]
As you can see we have another result... I can provie history when it was implemented and can provide usage in other repos

**Comment by silverwind** [comment]
Sure thanks, that's more than I expected from this issue. Now it's on me to debug further :)

**Comment by alexander-akait** [comment]
Hm, you have vue-loader, and they register own style-loader (which I think doesn't support it), where do you use this styles?

**Comment by alexander-akait** [comment]
Can yuo try to create simple CSS file and do it, like I done in tests

**Comment by alexander-akait** [comment]
I really want to help, but as you can see we don't have problem inside css-loader

**Comment by silverwind** [comment]
Just this plain CSS file, so `.vue` loader is not involved:

https://github.com/go-gitea/gitea/blob/main/web_src/css/themes/theme-auto.css

**Comment by silverwind** [comment]
Yes, I will try to make a minimal webpack repro.

**Comment by alexander-akait** [comment]
> Just this plain CSS file, so .vue loader is not involved:

> https://github.com/go-gitea/gitea/blob/main/web_src/css/themes/theme-auto.css

Vue plugin can register loader on `css` under the hood (I don't know how it is now, but before it was), so you can think that style-loader used, but no

**Comment by silverwind** [comment]
Okay, let me see what happens if I remove `vue-loader`.

**Comment by alexander-akait** [comment]
Yeah, let's try, it is the first place where we potentially can have a probem

**Comment by silverwind** [comment]
Unfortunately, no amount of plugin removal has any effect, the imported CSS is inlined without any `@media` wrapping.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/115237/225453348-0591f861-94e2-410d-93d2-b4a77d45a3cd.png">

So I think I will make a fresh repo next.

**Comment by alexander-akait** [comment]
Yeah, I will keep open, feel free to ping me

**Comment by silverwind** [comment]
Just fyi, the minimal repro so far does not reproduce it, so it's definitely something else in that config interfering.

https://github.com/silverwind/media-url

It correctly outputs

```
@media (prefers-color-scheme: dark) {
body { background: black }

}
```

Will check further what else in the full config could be a cause.

**Comment by alexander-akait** [comment]
To be honest, I don't see anything criminal in the configuration...

**Comment by silverwind** [comment]
Added the original CSS files to https://github.com/silverwind/media-url, now it reproduces and the `@media` is gone in output. It seems it has something to do with the file that is being imported already being present in another entrypoint.

```
$ git clone https://github.com/silverwind/media-url && cd media-url
$npm install
$ npx webpack
$ head -5 dist/theme-auto.css
/*!***************************************************************************************************!*\
  !*** css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!./css/chroma/base.css ***!
  \***************************************************************************************************/
.chroma {
  background-color: var(--color-code-bg);
```

**Comment by silverwind** [comment]
Yep, as soon as I remove the separate entry point for the file that is being imported, the `@media` is emitted correctly.

**Comment by alexander-akait** [comment]
I see...give me time to think how I can fix it and there is a problem (I think in MiniCssExtractPlugin.loader, but need check)

**Comment by silverwind** [comment]
https://github.com/silverwind/media-url is minimal again.

With the two entry points, it fails to emit `@media` in index:

```js
    dark: fileURLToPath(new URL('dark.css', import.meta.url)),
    index: fileURLToPath(new URL('index.css', import.meta.url)),
```

If I remove the `dark` entry point, the `@media` in index is back again.

**Comment by alexander-akait** [comment]
Yes, I was right, the problem is in the mini-css-extract-plugin, a fix is simple:
```
identifier() {
  return `css|${this._identifier}|${this._identifierIndex}|${this.media}|${this.supports}|${this.layer}`;
}
``` 

https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L168

I am very tired today because I moved to a new country and will send a PR and do release tomorrow, anyway if you want to send a PR yourself, feel free you have fix and test case, in this case I will do just release :smile:

**Comment by silverwind** [comment]
No hurry, we have a workaround via postcss until then. But I'll be very happy to rip it out again after this fix is in 😄.

**Comment by alexander-akait** [comment]
Should work :+1:

**Comment by silverwind** [comment]
Confirmed, thanks for the quick fix! 🎉
