### ISSUE TITLE
PostCSS vulnerable to line return parsing error

### ISSUE THREAD

**Issue by kells64000** [webpack-contrib/css-loader#1546]
### Actual Behavior

yarn audit showed a vulnerability message in versions of the package postcss before 8.4.31. css-loader is depending on that via css-loader > postcss

More info https://www.npmjs.com/advisories/1094304

### Expected Behavior

Update the postcss dependency to version >=8.4.31 

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.5.1/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Packages:
    file-loader: ^6.2.0 => 6.2.0 
    sass-loader: ^13.3.2 => 13.3.2 
    ts-loader: ^9.4.4 => 9.4.4 
    webpack: ^5.88.1 => 5.88.2 
    webpack-cli: ^5.1.4 => 5.1.4 
    webpack-notifier: ^1.15.0 => 1.15.0

**Comment by swirle13** [comment]
The package.json still lists the PostCSS dependency as 8.4.29 [here](https://github.com/webpack-contrib/css-loader/blob/e27ab5ead47c6bcf8b218dbce52ddd692111e833/package.json#L50). Why was this closed as completed?
