### ISSUE TITLE
Remove `webpack` from `peerDependencies`

### ISSUE THREAD

**Issue by feedm3** [webpack-contrib/css-loader#1567]
### Modification Proposal

We are using `css-loader` with `rsbuild`. This means, we don't use webpack directly anymore / don't have it installed. `css-loader` still works fine with the setup, but when doing a `yarn install`, yarn complains about not having `webpack` listed in our dependencies.

> ➤ YN0002: │ my-awesome-rsbuild-webapp doesn't provide webpack (p1ea2d), requested by css-loader.

As `css-loader` doesn't use `webpack` directly, I think it's ok to just remove it from the `peerDependencies` array.

### Expected Behavior / Situation

The loader will behave the same, but in the context of `rsbuild` won't add a warning in the install logs.

### Actual Behavior / Situation

A warning in the install logs:

> ➤ YN0002: │ my-awesome-rsbuild-webapp doesn't provide webpack (p1ea2d), requested by css-loader.

**Comment by alexander-akait** [comment]
We can't remove `webpack`, we can do this https://github.com/jantimon/html-webpack-plugin/blob/main/package.json#L58 and this https://github.com/jantimon/html-webpack-plugin/blob/main/package.json#L62

**Comment by snitin315** [comment]
Does rspack support all loaders & plugins? We'll need to update it in them too.

**Comment by feedm3** [comment]
> We can't remove `webpack`, we can do this [jantimon/html-webpack-plugin@`main`/package.json#L58](https://github.com/jantimon/html-webpack-plugin/blob/main/package.json?rgh-link-date=2024-01-26T11%3A28%3A17Z#L58) and this [jantimon/html-webpack-plugin@`main`/package.json#L62](https://github.com/jantimon/html-webpack-plugin/blob/main/package.json?rgh-link-date=2024-01-26T11%3A28%3A17Z#L62)

Hm, I guess that doesn't really help. Now not only Webpack but also Rspack is required, so all Webpack users will also get this installation warning. AFAIK there is no way to have conditional `peerDependencies`. :/

> Does rspack support all loaders & plugins? We'll need to update it in them too.

Not sure which ones are compatible, but "Rspack loader is designed to reuse the webpack loader, it is compatible with most of the webpack loader API, the rest of the API is still being implemented, so most of the webpack loader can already run in Rspack."
- https://www.rspack.dev/api/loader-api.html#loader-api
- https://github.com/orgs/web-infra-dev/projects/10

**Comment by alexander-akait** [comment]
@feedm3 Please read how `peerDependenciesMeta` works, it was designed specifically for this and we use this for old loaders/plugins/tools which have compatibility with rspack

**Comment by alexander-akait** [comment]
@feedm3 Feel free to send a PR

**Comment by feedm3** [comment]
@alexander-akait: There is now a PR for css-loader and postcss-loader:
- https://github.com/webpack-contrib/css-loader/pull/1568
- https://github.com/webpack-contrib/postcss-loader/pull/679
