### ISSUE TITLE
Pure selector mistaken as not pure

### ISSUE THREAD

**Issue by acidfernando** [webpack-contrib/css-loader#1572]
### Actual Behavior

I'm using next 14.1.0, so I'm not 100% sure if this issue is css-loader's fault, so I apologize in advance. Here's the thing:

I understand next 14.1.0 is using css-loader in pure mode, and thus you cannot use selectors such as `span` or `body` directly. But it is allowed to do `.someClassname > span`.

The problem is that I think this should be allowed, since it's an equivalent of `.someClassname > span`

```
.someClassname {
  ...someStyles

   & > span {
      ...someOtherStyles
   }
}
```

But it is throwing an error `Selector "& > span" is not pure`

### Expected Behavior

Since the "invalid" nested version and the "valid" version are equivalent, it should allow to use both

### How Do We Reproduce?

```
.test {
    color: red;

    & > span {
        color: green;
    }
}
```

**Comment by alexander-akait** [comment]
Already fixed before , please ask next-js team to update css-loader or own deps

https://github.com/css-modules/postcss-modules-local-by-default/commit/a8c3d770e18a934892108c2b1903f0cc95cad16d
https://github.com/webpack-contrib/css-loader/commit/6515be0e35ea3f15e29def7cca26b4157472ec00
