### ISSUE TITLE
The documentation should be supplemented with how old projects work properly under 7.0.0

### ISSUE THREAD

**Issue by hellohejinyu** [webpack-contrib/css-loader#1585]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

![image](https://github.com/webpack-contrib/css-loader/assets/8766034/f15c8aec-1bcd-4c78-a985-f294595ddcc9)

There are too many places in the project where the syntax `import styles from 'xxx'` is used. So for me, it would be a better solution if the project could use 7.0.0 without changing the syntax.

### Your Proposal for Changes

Adding additional clarification in the Migration guide to add the following configuration to restore 6.x behavior.

```js
options: {
  modules: {
    ...
    namedExport: false,
    exportLocalsConvention: 'as-is'
  }
}
```

**Comment by alexander-akait** [comment]
Yeah, thank you for the issue, I will fix it

**Comment by bladeSk** [comment]
What was the reasoning behind this breaking change? Old code can be thankfully fixed by using the options above, but all the existing guides and tutorials were instantly made obsolete and misleading. Especially considering the change in syntax is so subtle.
