### ISSUE TITLE
"import styles from" syntax does not work in v7.1.1

### ISSUE THREAD

**Issue by cobyme** [webpack-contrib/css-loader#1599]
### Actual Behavior

`import styles from 'stylesheet.css'` does not work in v7.1.1

Expected syntax as of v7.1.1 is now, which is a breaking change: 👎
`import * as styles from 'stylesheet.css'`

https://github.com/webpack-contrib/css-loader/commit/d6c31a17a0dde3e2bcf2b5e55f913c3645d32868#diff-cdda60f48283e996c8b1f883f90da8e742e88e36ee234cb016223a8e21b3560f

### Expected Behavior

`import styles from 'stylesheet.css'` is the previous expected behavior as of v7.1.0

https://github.com/webpack-contrib/css-loader/commit/af834b43b375f336108d74ff7bd9ed13bc79200a#diff-5a55216a623c1604989922d9bf484539f7eadd7fd665870341a9d84615165a7d

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
