### ISSUE TITLE
incomplete-sanitization in getUrl.js

### ISSUE THREAD

**Issue by ruchira-net** [webpack-contrib/css-loader#1621]
### Bug report

When scanned with CodeQL scanner, it finds a incomplete sanitization issue in the [getUrl.js](https://github.com/webpack-contrib/css-loader/blob/9cf9cd877f934af4aef91f5aaf127467d4964b8e/src/runtime/getUrl.js#L4) file. 

### Actual Behavior

Below method doesn't escape backslash characters in the input.

![image](https://github.com/user-attachments/assets/bccf0399-3840-4a2f-99e8-72cb22d9f1b0)

### Expected Behavior

Method should sanitize untrusted input for preventing injection attacks such as SQL injection or cross-site scripting (Even if the escaped string is not used in a security-critical context, incomplete escaping may still have undesirable effects, such as badly rendered or confusing output).

### How Do We Reproduce?

1. Open the [Wave analysis extension in VSCode](https://marketplace.visualstudio.com/items?itemName=devprod.vulnerability-extension). 
2. Click Add Analysis Tools and select CodeQL.

![image](https://github.com/user-attachments/assets/29b3c9eb-1e0d-4b39-9802-521f05a37370)

4. Click OK

![image](https://github.com/user-attachments/assets/f8e4b3f6-11cb-477d-9277-7ebb9ea68a8a)

5. Run the CodeQL scanner
6. You should see that it complains about the method in the getUrl.js file as below

![image](https://github.com/user-attachments/assets/8fa973a2-ca12-497a-817f-1ef58c9b4630)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 13.15 GB / 31.69 GB
  Binaries:
    Node: 21.6.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (130.0.2849.46)
    Internet Explorer: 11.0.26100.1882

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/css-loader/pull/1622#discussion_r1867595874, It looks like the utility has false positive result here
