### ISSUE TITLE
inline import duplication

### ISSUE THREAD

**Issue by undoZen** [webpack-contrib/css-loader#17]
If I `require('sub1.css')` and `require('sub2.css')` which both `@import url("./base.css")` then I'll get rules in bass.css applied twice in my page, which may cause some problem.

Any plan to solve this?

**Comment by richburdon** [comment]
I'm still seeing duplicates (both with ExtractTextPlugin generated files, and the vanilla less loader which includes multiple style tags)

Is additional configuration required other than the following?

        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!less-loader')

webpack@1.13.0
extract-text-webpack-plugin@1.0.1

**Comment by jhnns** [comment]
When you have multiple `require()` for different Less-files, it's the expected behavior to add multiple style tags.

**Comment by mattaningram** [comment]
@jhnns But I am importing the same .scss file, just in different React components. So why can't webpack identify that these are the same .scss files and only inject a <style> tag for it once?

Isn't that what it does with the JS imports? If two components import the same dropdown JS plugin, I assume that the plugin code exists only once in the final .js file. But this appears not to be the logic applied when importing styles.

I import the .css or .scss for react-selectize in each instance that react-selectize is used. This creates multiple IDENTICAL <style> injections in the head for some bizarre reason.

**Comment by phun-ky** [comment]
While the original issue here is related to sass/less/stylus, a fix/hack/patch for this is to use the `optimize-css-assets-webpack-plugin` in conjunction with `extract-text-webpack-plugin` to produce, like this: https://gist.github.com/phun-ky/766e5ec9f75eac61c945273a951f0c0b. 

If you want to use this in dev, you will have to use a plugin like `write-file-webpack-plugin` to force webpack to write the file to disk in dev.
