### ISSUE TITLE
Human-friendly unique identifiers by default

### ISSUE THREAD

**Issue by jaroslawr** [webpack-contrib/css-loader#171]
I wonder whether the way to go from the local identifier in the source code to the one actually used in the browser really has to be through a hash function, and also whether the current particular hashing scheme is really the one that should be the advocated default. Two reasons to think of this:
1. The scheme for generating the browser class names advised in the README is really hard to read.
2. In some scenarios the generated class names needs to be used for identifying elements on the page, e.g. in acceptance tests with selenium or capybara, and then this is even more awkward.

The most prominently visible way of generating identifiers that is documented is this:

```
._23_aKvs-b8bW2Vg3fwHozO
```

It is also mentioned that you can do this:

```
.class-name-_23_aKvs-
```

Why not advocate everywhere in the documentation this by default:

```
.class-name-18f737ae6
```

Which it turns out can already be achieved with:

```
localIdentName=[local]-[sha1:hash:hex:8]
```

At least to me, this makes the whole idea a bit more appealing. Furthermore, why not document/advocate/enable a scheme of generating unique identifiers that is fully symbolic? E.g. assuming a .header class in NewsList.css, and "xyz" is your project name, you can get this:

```
xyz--NewsList--header
```

by using this:

```
localIdentName=xyz--[name]--[local]
```

and if you have a convention for dividing the css files it is quite certain this will be unique, e.g. I use React components and have ComponentName.jsx and ComponentName.css everywhere. The only thing I miss here is the ability to go from the camel case basename of the file name to a dash style name e.g. to get a component-name style identifier from ComponentName.css file name. You could then get something like BEM without actually having to type out the long cumbersome names everywhere.

In any case I think those are at least appealing possibilties, and you can currently only learn about them through reading the documentation of interpolateName at:

https://github.com/webpack/loader-utils

I personally root for those to be officially embraced and advocated.

**Comment by jaroslawr** [comment]
For the same reason of potentially having tools/code depending on the *generated* class names, it would be nice to have some guarantee of the stability of the algorithm that is used to generate the data to input into the hash function, e.g. version this and never abandon completely. Imagine having a large Capybara test suite using the generated class names and then encountering something like this https://github.com/webpack/css-loader/commit/55ad466a1b3c712f404ba12439a458cf0335d224

**Comment by michael-ciniawsky** [comment]
@jaroslawr Yep the docs should be using the most human friendly modules variant available and be consistent where possible, please send PR for that 😛  and the defaults are changing please join discuss in #442
