### ISSUE TITLE
Errors loading ionicons.css 

### ISSUE THREAD

**Issue by the-reality-engineer** [webpack-contrib/css-loader#18]
ERROR in ./ionicons-1.5.2/fonts/ionicons.eot?v=1.5.2
Module parse failed: /***/ionicons-1.5.2/fonts/ionicons.eot?v=1.5.2 Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./ionicons-1.5.2/css/ionicons.css 2:300-340 2:356-396

ERROR in ./ionicons-1.5.2/fonts/ionicons.woff?v=1.5.2
Module parse failed: /***/ionicons-1.5.2/fonts/ionicons.woff?v=1.5.2 Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./ionicons-1.5.2/css/ionicons.css 2:515-556

etc...

**Comment by naomik** [comment]
The following `loaders` worked for me

```js
{ test: /\.woff$/, loader: "url-loader?limit=10000&mimetype=application/font-woff" },
{ test: /\.ttf$/,  loader: "url-loader?limit=10000&mimetype=application/octet-stream" },
{ test: /\.eot$/,  loader: "file-loader" },
{ test: /\.svg$/,  loader: "url-loader?limit=10000&mimetype=image/svg+xml" }
```

**Comment by timuric** [comment]
Following worked for me
```javascript
            {
                test   : /\.woff/,
                loader : 'url?prefix=font/&limit=10000&mimetype=application/font-woff'
            }, {
                test   : /\.ttf/,
                loader : 'file?prefix=font/'
            }, {
                test   : /\.eot/,
                loader : 'file?prefix=font/'
            }, {
                test   : /\.svg/,
                loader : 'file?prefix=font/'
            }
```

**Comment by jacobhamblin** [comment]
this works for me:
```
{
       test   : /\.woff|\.woff2|\.svg|.eot|\.ttf|\.png/,
       loader : 'url?prefix=font/&limit=10000'
}
```

**Comment by gaokun** [comment]
this works for me:
```javascript
{ test: /\.(eot|woff|woff2|svg|ttf)([\?]?.*)$/, loader: "file-loader" },
```

**Comment by showd0wn** [comment]
{
      test: /\.woff|\.woff2|\.svg|.eot|\.ttf/,
      use: 'url-loader?prefix=font/&limit=10000'
    }

for webpack2

**Comment by darincardin** [comment]
Wow! An answer that actually works! Thank you very much sokra.

**Comment by alex996** [comment]
Can someone please provide a working example of the webpack file with the loaders in place? I tried every single suggestion posted above, and none of them seemed to work. Unless I am were using them wrong... I am on the latest version of vue-loader, and still experiencing the same issue as others did 3 years ago. Webpack gurus, where are you?

**Comment by Liwoke** [comment]
**hi，this is the error i meet,someone can help me?**

WARNING in ./src/assets/logo.png
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src ^\.\/(?!main(\.js)?$)
 @ ./test/unit/index.js
27 11 2017 08:56:29.940:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
27 11 2017 08:56:29.943:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
27 11 2017 08:56:29.950:INFO [launcher]: Starting browser PhantomJS
27 11 2017 08:56:33.035:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket l4a2fk1nyYQTqU1MAAAA with id 49733607
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Unexpected token ')'
  at test/unit/index.js:826
