### ISSUE TITLE
The same class name in different css files generates the same localIdentName

### ISSUE THREAD

**Issue by re222dv** [webpack-contrib/css-loader#198]
If I have one file with
`.fill { color: red }`
and another with
`.fill { width: 100%; height: 100%; }`

I get both styles on my element even if I just use one of them for that element because the generated class name is the same.

**Comment by mtsr** [comment]
You can probably solve this by changing the localIdentName to include the path.

**Comment by vramana** [comment]
@re222dv How are you using only one of them?

**Comment by mtsr** [comment]
@vramana Probably `import styles from './styles.scss'` and `<div className={styles.fill}></div>`

**Comment by vramana** [comment]
@mtsr I remember using `styles.scss` causes problem. It kind of throws things in a global namespace(I am bit unsure but I am think I mostly correct). Can you change both your `styles.scss` files to the corresponding component name? css-modules scoping is dependent on the filename you give.

**Comment by mtsr** [comment]
Ah, sorry, by `./styles.scss` I mean a scss files local to the component. E.g. `views/Home/styles.scss` with the homeview being `views/Home/index.js`.

**Comment by vramana** [comment]
@mtsr That still puts all the css classes in global namespce of `Styles_{your-classname}`. The scss file should be names `Home.scss` instead of `styles.scss`

**Comment by mtsr** [comment]
That all depends on what naming scheme you've defined for your css-modules, I personally always use some kind of hash, as it more or less guarantees uniqueness for anything but the same css.

**Comment by vramana** [comment]
Absolutely true. But when developing seeing hashes all over kind of feels noisy to me.

**Comment by mtsr** [comment]
Alternatively you can use [path] I guess.

**Comment by themouette** [comment]
I think https://github.com/webpack/css-loader/pull/284 will fix this issue.

**Comment by Pajn** [comment]
I'm sorry for not having responded. I have different names on all style files (the component name) however multiple components share the same folder. But I think #284 will fix this, thanks!
