### ISSUE TITLE
New reproducible hashing

### ISSUE THREAD

**Issue by mattkrick** [webpack-contrib/css-loader#206]
Awesome feature for the reproducible hash!
One "gotcha" I found is that it creates the hex from the content, and content is different depending on context. That means it won't hold up if the 2 configs have different contexts. 

To fix, we could either concat context+content in loader-utils' `interpolateName` or just say the word & I can add a blurb to the wiki on how it works.

**Comment by d3viant0ne** [comment]
@mattkrick - Is there a deleted comment here I am missing? This reads like half of a conversation.

If you are trying to suggest a feature, you will need to be more verbose.

**Comment by mattkrick** [comment]
concat context+content in loader-utils' interpolateName.

Please let me know how I can make that clearer, I'm just not sure how to be more verbose than that.

**Comment by evilebottnawi** [comment]
@mattkrick can you describe use case for this enhancement?

**Comment by mattkrick** [comment]
2 configs with different contexts
closing as this is a couple years old
