### ISSUE TITLE
@import handling should use the loader defined in the webpack config

### ISSUE THREAD

**Issue by ddelbondio** [webpack-contrib/css-loader#21]
I am currently developing a sass loader which uses the original ruby sass compiler. When the css-loader processes the output and handles `@import` directives currently calls the sass loader again (which fails, since ruby sass can't seem to handle normal css files properly). 
I think it would be better to call the loader defined in the webpack config for that file pattern instead.

**Comment by geddski** [comment]
@ddelbondio is your ruby-sass loader working and do you plan to release it?

**Comment by ddelbondio** [comment]
@geddski yes it is working. I cleaned it up a bit and published it at https://github.com/ddelbondio/ruby-sass-loader / https://www.npmjs.com/package/ruby-sass-loader
Let me know if you have any issues with it
