### ISSUE TITLE
CssSyntaxError with animation property

### ISSUE THREAD

**Issue by 4ware** [webpack-contrib/css-loader#211]
When i'm running the css-loader with the following code i get an error:

@charset "UTF-8";

.animated {
    -webkit-animation-duration: 1s;
    animation-duration: 1s;
    -webkit-animation-fill-mode: both;
    animation-fill-mode: both;
    z-index: 100;
}

Module build failed: CssSyntaxError: /css-loader!/development/flot.to.web/node_modules/style-loader/index.js!/development/flot.to.web/node_modules/css-loader/index.js!/development/flot.to.web/css/animate.css:5:1: Unknown word

**Comment by psypersky** [comment]
Same here

**Comment by batwicket** [comment]
I'm also getting an error when '@charset' is parsed.

**Comment by gmaggess** [comment]
Has anyone found a fix for this?

**Comment by arufian** [comment]
got same issue

**Comment by kincaidoneil** [comment]
I've also experienced this. Animate.css invokes it in the first line, so there's definitely the possibility many others are also encountering it.

**Comment by newbieYoung** [comment]
I have solved the problem by changing " require('css!./file.css') " to " import 'file.css' ".I guess when you use babel plugin and css-loader plugin you will meet the problem.

**Comment by Sugarball** [comment]
got same issue on normalize.css using import "css-loader!normalize.css"

**Comment by newbieYoung** [comment]
You should change " import 'css-loader!normalize.css' " to " import 'normalize.css' ". The right format is " import + path ".

**Comment by yowmamasita** [comment]
Same issue. I am using animate.css too

**Comment by jkinzel-r7** [comment]
I'm getting this issue because we are compiling SASS including some vendor SASS that has the `@charset` at the top of the file. Any ideas on work arounds or fixes?

**Comment by delijah** [comment]
Any news on this?

**Comment by michael-ciniawsky** [comment]
Reopen if still any regressions with the **latest** version of plugins/loaders/webpack etc 😛
