### ISSUE TITLE
css?sourceMap makes images disappear...

### ISSUE THREAD

**Issue by eyalw** [webpack-contrib/css-loader#216]
my config:

```
       {
        test: /\.scss$/,
        loaders: ['style', 'css?sourceMap', 'postcss', 'sass?sourceMap&sourceMapContents'],
      },
      {
        test: /\.(png|jpg)$/,
        loader: 'url?limit=25000',
      },
```

and I have a scss file containing `background-image: url('./invision.png');`

**Problem**
- If I use 'css' loader, the image url comes out correctly as:
  http://localhost:8080/f035551efcaa590a1da0bf1fae114dca.png
- if I use 'css!sourceMap' (css + sourceMap), the image urls comes out as:
  chrome-devtools://devtools/bundled/f035551efcaa590a1da0bf1fae114dca.png

I found those urls when clicking "open in a new tab" in the style panel in Chrome dev tools.

obviously the image doesn't show on the DOM when I use sourcemap....

**Comment by Darkside73** [comment]
You should use absolute url in ```publicPath``` option. See discussion here https://github.com/webpack/style-loader/issues/55

**Comment by bebraw** [comment]
Yeah, you should set up `publicPath` to an absolute url as mentioned. Time to close.
