### ISSUE TITLE
Make url() compatible to other loaders

### ISSUE THREAD

**Issue by matthiasfeist** [webpack-contrib/css-loader#217]
In the readme it states to rewrite CSS to make it compatible to this loader:

```
url(image.png) => require("./image.png")
url(~module/image.png) => require("module/image.png")
```

Could it be a solution to support both syntaxes? That way most of the components we already have would work out of the box by just surrounding the css with a `:global { ... }`block.

**Comment by michael-ciniawsky** [comment]
@matthiasfeist Can you please elaborate a bit futher ? 😛

**Comment by matthiasfeist** [comment]
Haha no not really. I have no idea anymore what the problem was after a bit more than 1 year 😝

**Comment by michael-ciniawsky** [comment]
@matthiasfeist Yeah I understand, I wasn't responsible here during that time, mind if I close the issue and you reopen or make a new issue in case it's needed ? 😛

**Comment by matthiasfeist** [comment]
Yes please :) I guess we worked around that somehow back in the days :)
