### ISSUE TITLE
Is it possible to use a hash of the file contents for localIdentName?

### ISSUE THREAD

**Issue by RGBboy** [webpack-contrib/css-loader#225]
We are running into a problem where the hash in localIdentName changes in different environments. One solution would be to use the hash of the file contents instead. Is this possible? Is this a bad idea for some reason I am not thinking? Would this affect HMR etc?

**Comment by developit** [comment]
Isn't this what `[hash]` does?

**Comment by RGBboy** [comment]
Nope, `[hash]` is the hash of the path to the file.

**Comment by themouette** [comment]
I guess #284 would address this.

**Comment by michael-ciniawsky** [comment]
@RGBboy Please see discussion in #284
