### ISSUE TITLE
css-loader exports a string when modules are enabled

### ISSUE THREAD

**Issue by danpantry** [webpack-contrib/css-loader#229]
When css modules are enabled, css-loader appears to export a string with the identifiers rather than a javascript object. The javascript object can be retrieved when using `style-loader`. This appears to be counter to the documentation which mentions no reliance on `style-loader`. Is this intended behaviour?

dependencies:

```
"css-loader": "^0.23.1",
"style-loader": "^0.13.0",
"webpack": "^1.12.12",
```

   "sass-loader": "^3.1.2",

loader setup

```
{ test: /\.scss$/, loaders: ['style', 'css?modules', 'sass'] },
```

Without `style-loader`, we get the following output from `require`ing a .scss file:

```
[[19, '.JCHg8g8dl0FeQwl5x7rcM {
  display: none !important; }
', '']]
```

With it, we get the correctly exported identifier.

**Comment by michael-ciniawsky** [comment]
@danpantry Can you try again with 'css-loader/locals' please?

**Comment by michael-ciniawsky** [comment]
@danpantry If the solution posted above shouldn't address the problem feel free to reopen 😛
