### ISSUE TITLE
Can't find background: url file if it has a trailing space

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/css-loader#237]
css-loader cannot find the background url file if it has a trailing space.

For example -

```
#trailing-space
{
  background: url(css-trailing-space.png );
}
```

Produces the following error -

```
ERROR in ./~/css-loader!./css-leading-space.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./css-trailing-space.png  in /Users/junger/css-trailing-space
 @ ./~/css-loader!./css-leading-space.css 6:68-104
```

Leading space appears to be trimmed correctly.

**Comment by michael-ciniawsky** [comment]
ohh.. 😟  No worries appreciated, I thought I closed all issues related to the PR(s), but I should better double check next time 😛
