### ISSUE TITLE
Allow to apply some postcss plugins after cssmodules

### ISSUE THREAD

**Issue by Strate** [webpack-contrib/css-loader#262]
I need to apply some postcss plugins after aplpying plugins relted to cssmodules. It need to add an extra class scope to all rules in all files

**Comment by joshwnj** [comment]
@Strate there's an example of adding extra postcss plugins here: https://github.com/css-modules/webpack-demo/blob/master/webpack.config.js#L26-L29

**Comment by Strate** [comment]
@joshwnj in that example postcss plugins applies *before* applygin plugins, related to cssmodules (which applied by css-loader). In a fact, I need something like this:

```
require("style!postcss?mypack!css?modules!./file.css").
```
But the is not possible, because css-loader returns a jsvscript module, not a css file.
I have implemented this PR: #263

**Comment by joshwnj** [comment]
I see, thanks for the clarification 👍

**Comment by avanderhoorn** [comment]
I'm needing to do the exact same thing. Did you figure this out? Is it possible?

**Comment by michael-ciniawsky** [comment]
I'm working on postcss-loader v2 with the goal to *not* depend upon `css-loader` anymore in the near future, bc of usecases like that :), for now this won't fix sry
