### ISSUE TITLE
sourceMap and react in devMode

### ISSUE THREAD

**Issue by orlandodemauro** [webpack-contrib/css-loader#279]
Hi guys,

I'm getting an issue loading the css using webpack, react and hot-reloader.

Adding sourceMap in the loaders removes the style from the bundle.js and add it back after that the bundle is loaded.

I'm not concern about the fact that the page is without style for few millisecond, the problem is that when the componentDidMount method is called and I check dom elements styles I don't get the real style. (i.e. getComputedStyle(dom).position return static)

The issue is not reproducible removing sourceMap.

here my config:

`devtool: 'inline-source-map',
`

```
module: {
  loaders: [{
     test: /\.js$/,
        loaders: ['react-hot', 'babel', 'eslint'],
        include: [sourcePath]
     },
     {
        test: /\.scss$/,
        loaders: ['style', 'css?sourceMap', 'autoprefixer?browsers=last 3 versions', 'sass?sourceMap']
     }}
```

**Comment by bdo** [comment]
Hi

I am having the same problem which causes bug in my web application to fail due to some code querying an element's style in `componentWillMount`. My webpack config is similar to @orlandodemauro

Cheers

**Comment by felixexter** [comment]
Have the same problem. Any news?

**Comment by evilebottnawi** [comment]
@orlandodemauro @bdo @felixexter Problem still exists?

**Comment by evilebottnawi** [comment]
Related to `style-loader`. Maybe solution here https://github.com/webpack-contrib/style-loader/issues/287
