### ISSUE TITLE
load css with media=all attribute

### ISSUE THREAD

**Issue by tnrich** [webpack-contrib/css-loader#294]
Hey there,

I'd like to add the media=all attribute to the css files that webpack is generating:
![image](https://cloud.githubusercontent.com/assets/2730609/16501750/d720e1a4-3ebf-11e6-8e19-7497811c7d97.png)

The reason for this is because the css is not being used when I try to print my webpack-generated webpage. 

Thanks for the help!

**Comment by aaronbloom** [comment]
+1

**Comment by andreypopp** [comment]
That should probably be done in [style-loader](https://github.com/webpack/style-loader). Consider creating a pull request there.

**Comment by evilebottnawi** [comment]
Not related to `css-loader`, you can use https://github.com/webpack-contrib/style-loader#transform option for modify css before their insert in page
