### ISSUE TITLE
Unknown word error when loading plain CSS (not Sass or Less)

### ISSUE THREAD

**Issue by decoder318** [webpack-contrib/css-loader#295]
I'm trying out webpack for the first time.. Trying to use the style-loader and css-loader. 

Plain old css (not sass and not less) could not be loaded.

```
ERROR in ./~/css-loader!./~/style-loader!./~/css-loader!./src/styles/site.css
Module build failed: CssSyntaxError: C:\css-loader!C:\Users\Foo\Desktop\try-webpack\node_modules\style-loader\index.js!C:\Users\Foo\Desktop\try-webpack\node_modules\css-loader\index.js!C:\Users\Foo\Desktop\try-webpack\src\styles\site.css:5:1: Unknown word
    at Input.error (C:\Users\Foo\Desktop\try-webpack\node_modules\postcss\lib\input.js:61:22)
    at Parser.unknownWord (C:\Users\Foo\Desktop\try-webpack\node_modules\postcss\lib\parser.js:457:26)
    at Parser.word (C:\Users\Foo\Desktop\try-webpack\node_modules\postcss\lib\parser.js:174:14)
    at Parser.loop (C:\Users\Foo\Desktop\try-webpack\node_modules\postcss\lib\parser.js:60:26)
    at parse (C:\Users\Foo\Desktop\try-webpack\node_modules\postcss\lib\parse.js:26:12)
    at new LazyResult (C:\Users\Foo\Desktop\try-webpack\node_modules\postcss\lib\lazy-result.js:61:24)
    at Processor.process (C:\Users\Foo\Desktop\try-webpack\node_modules\postcss\lib\processor.js:34:16)
    at processCss (C:\Users\Foo\Desktop\try-webpack\node_modules\css-loader\lib\processCss.js:188:11)
    at Object.module.exports (C:\Users\Foo\Desktop\try-webpack\node_modules\css-loader\lib\loader.js:24:2)
 @ ./~/style-loader!./~/css-loader!./src/styles/site.css 4:14-162
```

My webpack.config.js file is just this:

```
var path = require('path');

module.exports = {

    entry: "./src/scripts/index.js",
    output: {        
        path: path.join(__dirname, "public", "build"),
        filename: "app.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style-loader!css-loader" }
        ]
    }
};
```

If I remove the module part in the above thing, the error is gone. 

I also tried `{ test: /\.css$/, loader: "style!css" }` and 
`{test: /\.css/, loader: "style!css" }`and various possible permutations with removing characters. There are no comments in the css file or the webpack.config.js file.

Specifying the loaders sequence in the import statement works (shown below):

`var css = require("style!css!../styles/site.css");` 

Am I missing something here? I really can't see it.

Regards

**Comment by decoder318** [comment]
For whatever reason, I gave myself a couple of hours to continuously uninstall style-loader, css-loader and webpack and trying the versions form Dec 2015 and failing to solve the issue, I also ran npm cache clean, a couple of times in between.

For the 5th time, I just installed webpack, css-loader and style-loader in that order (same as I did the very first time) and voila, it just worked. Absolutely no idea why it failed the first time and succeeded the nth time. (things done in the same). (Throughout this ordeal, I had no other npm packages in my project other than webpack and the two loaders.)

May be someone should close it, or look at it, or whatever..

**Comment by huwf** [comment]
I have the same issue.  I am just using `require('style!.....')` for now, but would really like to find out what is causing this issue.  I tried uninstalling a couple of times, and that didn't work (not a fresh project).  If you figure out what caused it then please let me know!

**Comment by sdhhqb** [comment]
I had the same issue too.

`bundle.js:15842 Uncaught Error: Cannot find module "!!./../../node_modules/css-loader/index.js!./../../node_modules/style-loader/index.js!./../../node_modules/css-loader/index.js!./home.css"`

`vendor.js:160 ./~/css-loader!./~/style-loader!./~/css-loader!./css/home/home.css
Module build failed: CssSyntaxError: F:\css-loader!F:\work\memberUserCenterFrontend\node_modules\style-loader\index.js!F:\work\memberUserCenterFrontend\node_modules\css-loader\index.js!F:\work\memberUserCenterFrontend\css\home\home.css:5:1: Unknown word
    at Input.error (F:\work\memberUserCenterFrontend\node_modules\css-loader\node_modules\postcss\lib\input.js:61:22)
    at Parser.unknownWord (F:\work\memberUserCenterFrontend\node_modules\css-loader\node_modules\postcss\lib\parser.js:457:26)
    at Parser.word (F:\work\memberUserCenterFrontend\node_modules\css-loader\node_modules\postcss\lib\parser.js:174:14)
    at Parser.loop (F:\work\memberUserCenterFrontend\node_modules\css-loader\node_modules\postcss\lib\parser.js:60:26)
    at parse (F:\work\memberUserCenterFrontend\node_modules\css-loader\node_modules\postcss\lib\parse.js:26:12)
    at new LazyResult (F:\work\memberUserCenterFrontend\node_modules\css-loader\node_modules\postcss\lib\lazy-result.js:61:24)
    at Processor.process (F:\work\memberUserCenterFrontend\node_modules\css-loader\node_modules\postcss\lib\processor.js:34:16)
    at processCss (F:\work\memberUserCenterFrontend\node_modules\css-loader\lib\processCss.js:188:11)
    at Object.module.exports (F:\work\memberUserCenterFrontend\node_modules\css-loader\lib\loader.js:24:2)
 @ ./~/style-loader!./~/css-loader!./css/home/home.css 4:14-162`

But the strange thing is, if I configure loader include a not exist path, It just work fine.

```
module: {
		loaders: [
			{
				test: /\.css$/,
				include: [
					path.resolve(__dirname, "not_exist_path")
				],
				loader: "style!css"
			}
```

**Comment by ealves-pt** [comment]
Running into the same issue. After `npm i -S bootstrap` and `require('style-loader!css-loader!../node_modules/bootstrap/dist/css/bootstrap.css')` I get that error.

**Comment by sdhhqb** [comment]
I seem to figure this out. According to [webpack docs](http://webpack.github.io/docs/using-loaders.html#usage) there are multiple ways to use loaders.

```
explicit in the require statement
configured via configuration
configured via CLI
```

If use `require` statement to specify the loaders, e.g.`require("style!css!../styles/site.css")`, you don't need to configure css-loader in webpack.config.js.

On the contrary, if already configured css-loader in webpack.config.js, you should use `require("../styles/site.css")` or `import "../styles/site.css"`.

These problems may caused by specify loaders both in require and webpack.config.js.

**Comment by tjwebb** [comment]
> These problems may caused by specify loaders both in require and webpack.config.js.

Holy shit, thank you. All the docs I see show both methods, but do not explain this potential pitfall.

**Comment by cnlevy** [comment]
Additionally from the [docs](http://webpack.github.io/docs/using-loaders.html#usage), 
> It’s possible to overwrite any loaders in the configuration by prefixing the entire rule with !.
> require("!style!css!less!bootstrap/less/bootstrap.less");
> ...
> **If configuration has some transforms bound to the file, they will not be applied.**

**Comment by harwinvoid** [comment]
i meet this problem too.but i fix it by move the import css to the style tag

**Comment by harwinvoid** [comment]
I fixed it by  remove  `{ test: /\.css$/, loader: 'style!css' }` from webpack.config.js

**Comment by splurtcake** [comment]
I'm so stuck with this. Can anyone help me out? Where am I going wrong?

`export var clientConfig = {
	target: 'web',
	entry: {
		'polyfills': './src/polyfills.browser',
		'vendor': './src/vendor',
		'main': './src/client',
		'styles': './src/app/assets/sass/styles.scss'
	},
	output: {
		path: root('dist/client')
	},
	plugins: [
		new ExtractTextPlugin({
			filename: 'styles.css',
			disable: false,
			allChunks: true
		})
	],
	module: {
		loaders: [
			{
				test: /\.scss/,
				loader: ExtractTextPlugin.extract({
					loader: ['style-loader', 'sass-loader', 'postcss-loader']
				})
			}
		]
	}
};
`

**Comment by winnerhp** [comment]
@splurtcake 
maybe you should config like this: {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract(
                    'style-loader', 'css-loader!postcss-loader', 'sass-loader'
                )
            }

**Comment by mondaychen** [comment]
I had the same issue. I think in generally this error happens when the file is compiled by the css loader for more than once. Check your config to see if there are duplicated css loaders.

**Comment by guywald1** [comment]
Solved this problem by adding `node-sass` as a dependancy.

**Comment by kvfi** [comment]
Don't forget to separate the loaders as following:

`{
				test: /\.js$/,
				loader: ['babel-loader'],
				exclude: /node_modules/,
			},
			{
				test: /\.css$/,
				loader: ['style-loader', 'css-loader']
			}`

**Comment by AryanJ-NYC** [comment]
I switched from `use: [ 'css-loader', 'style-loader' ]` to `use: ['style-loader', 'css-loader']`(note the order) and all is well in the world. Weird.

**Comment by ccalvarez** [comment]
When using the vue-cli `webpack `template, the solution proposed by @harwinvoid solves the issue.

**Comment by swxy** [comment]
Spent hours, I just fixed it..shit...when using the vue-cli `webpack`template， the dev webpack config file (`build/webpack.dev.conf.js`) line 16-18 ：
```
module: {
  rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap })
}
```
replace with config like:
```
[
  {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'postcss-loader'
        ]
   }
]
```

the whole `build/webpack.dev.conf.js` is:
```
var utils = require('./utils')
var webpack = require('webpack')
var config = require('../config')
var merge = require('webpack-merge')
var baseWebpackConfig = require('./webpack.base.conf')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')

// add hot-reload related code to entry chunks
Object.keys(baseWebpackConfig.entry).forEach(function (name) {
  baseWebpackConfig.entry[name] = ['./build/dev-client'].concat(baseWebpackConfig.entry[name])
})

module.exports = merge(baseWebpackConfig, {
  // module: {
  //   rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap })
  // },
  // cheap-module-eval-source-map is faster for development
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'postcss-loader'
        ]
      }
    ]
  },
  devtool: '#cheap-module-eval-source-map',
  plugins: [
    new webpack.DefinePlugin({
      'process.env': config.dev.env
    }),
    // https://github.com/glenjamin/webpack-hot-middleware#installation--usage
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    // https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
      inject: true
    }),
    new FriendlyErrorsPlugin()
  ]
})

```

**Comment by pkout** [comment]
For me, the solution was to add the post-css loader into the `/\.css$/` loader like so:

`
{
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                modules: true,
                localIndentName: '[name]_[local]__[hash:base64:5]'
              }
            },
	   {
			  loader: 'postcss-loader',
			  options: {
				plugins: () => [require('autoprefixer')]
			  }
			}
          ]
        })
      },
`

**Comment by trusktr** [comment]
In my case, I accidentally had the same loader twice. For example:

```js

		// CSS
		{
			test: /\.css$/,
			loaders: [
				'style-loader',
				'css-loader',
			]
		},

                // ....

		// CSS
		{
			test: /\.css$/,
			loaders: [
				'style-loader',
				'css-loader',
			]
		},
```

Removing one worked, so it isn't applied twice.

**Comment by Giannidluca** [comment]
Hey guys, I actually found that if you change the order of your loaders that fix the problem. I used to have css-loader first and style-loader second inside the array but when i switch them it worked. 

            test: /\.css$/,
            use: [
                'style-loader',
                'css-loader',
                'sass-loader'    
            ]

**Comment by kumorig** [comment]
I ran into the same error issue using vuepress, and have seen something similar with vue-cli (months earlier) and since vue-cli is mentioned several times here I'd like to believe it's the same issue - and that this is a problem with vue-cli and not css-loader. 

Speculating further, I also believe this is a path problem in windows. If you get this error, try changing your work-directory to `c:\some-project` instead of `C:\some-project` (you have to use `cd` from outside the directory for windows cmd to get the hint.)

**Comment by davidrenne** [comment]
> > These problems may caused by specify loaders both in require and webpack.config.js.
> 
> Holy shit, thank you. All the docs I see show both methods, but do not explain this potential pitfall.

LOVE THAT COMMENT.  Sorry made me laugh.  Good sense of humor.

**Comment by anuragmy** [comment]
> Additionally from the [docs](http://webpack.github.io/docs/using-loaders.html#usage),
> 
> > It’s possible to overwrite any loaders in the configuration by prefixing the entire rule with !.
> > require("!style!css!less!bootstrap/less/bootstrap.less");
> > ...
> > **If configuration has some transforms bound to the file, they will not be applied.**

Thanks !!

**Comment by tomspeak** [comment]
Please avoid my mistake and take serious note of you potentially having two loaders for the same thing.

I was loading CSS myself, and had a 3rd party plugin that also loaded CSS, so I didn't immediately think about it.

Removing my loader made this work.

**Comment by yairEO** [comment]
OMG, after many hours of combing the web, I've stumbled upon a solution!

I was doing this:

```
module.exports = async ({ config, mode }) => ({
    ...config,

    module: {
        ...config.module,                      // <-- BAD!
        rules: [
            ...config.module.rules,            // <-- BAD!
            {
```

After removing these lines, my Storybook Webpack config suddenly works. Big WTF moment.

**Comment by tno2007** [comment]
The 'unknown word' problem also occurs if you css file is encoded in something else other than utf-8.
If your css looks correct, be sure to check the encoding.

**Comment by jmarceli** [comment]
As of Storybook v5 there is no need to add custom .css loader as it is already defined. If you are getting an error after upgrade from v4 you should most probably review your `.storybook/webpack.config.js` and remove custom .css loader.

**Comment by mech** [comment]
But what if I want to have "style.module.css" and is not using SASS?

I have to add custom .css loader for Storybook v5 right? Like so (but it is not working):

```js
module.exports = async ({ config, mode }) => {
  // SASS and CSS Module support
  config.module.rules.push({
    test: /\.css$/,
    use: [
      'style-loader',
      {
        loader: 'css-loader',
        options: {
          sourceMap: true,
          modules: true,
          importLoaders: 2,
          localIdentName: '[name]__[local]___[hash:base64:5]'
        }
      },
      'postcss-loader',
      'sass-loader'
    ],
    include: path.resolve(__dirname, '../')
  })

  return config
}
```

**Comment by jmarceli** [comment]
In order to make it work just add `exclude: /\.css$/,` to the existing rule and then add your own code. You may write something like this (this exact code may not work, but it should be easy to fix if required):

```
const rule = config.modules.rules.filter(rule => rule.test.indexOf('css') > -1);
rule.exclude = /\.css$/;
```

**Comment by dishagarg** [comment]
> In order to make it work just add `exclude: /\.css$/,` to the existing rule and then add your own code. You may write something like this (this exact code may not work, but it should be easy to fix if required):
> 
> ```
> const rule = config.modules.rules.filter(rule => rule.test.indexOf('css') > -1);
> rule.exclude = /\.css$/;
> ```

Thanks so much @jmarceli 
It finally worked. You're amazing!

**Comment by GeraldJM** [comment]
According to the most recent docs on GitHub, the preferred syntax is:
`
{
  test: /\.css$/,
  use: [
    { loader: 'style-loader' }, 
    { loader: 'css-loader' }
  ],
  exclude: /node_modules/
}
`

**Comment by MrJadaml** [comment]
This is how I ended up getting css modules to work

```js
// .storybook/webpack.config.js

const setCssModulesRule = rule => {
  const nextRule = rule;
  const nextOptions = { ...rule.use[1].options, modules: true }

  nextRule.use[1].options = nextOptions;  // admittedly lazy, but the array was mixed types 🤷‍♀️
  return nextRule;
}

module.exports = async ({ config, mode }) => {
  const rules = config.module.rules.map(rule => {
    const isCssRule = rule.test.toString().indexOf('css') !== -1;
    let nextRule = rule;

    if (isCssRule) {
      nextRule = setCssModulesRule(rule);
    }

    return nextRule;
  });

  config.module.rules = rules;
  return config;
};
```

**Comment by robcochranff** [comment]
If it might help someone sometime, I was playing with types in and using react-scripts.  I didnt need that, but the addition to it caused this error for me.  Removal, and voila, it worked.  Now to tell my PM why it's taken me so long haha

**Comment by AndreyDodonov-EH** [comment]
This issue is the very high in google, so posting here, maybe helps somebody.

Got the same even now by using 'css-loader' before 'style-loader'.
E.g.
```
 use: [
          'style-loader',
          'css-loader',
        ],

```
works, but not
```
 use: [
          'css-loader',
          'style-loader',
        ],

```

**Comment by jialihan** [comment]
> This issue is the very high in google, so posting here, maybe helps somebody.
> 
> Got the same even now by using 'css-loader' before 'style-loader'.
> E.g.
> 
> ```
>  use: [
>           'style-loader',
>           'css-loader',
>         ],
> ```
>
> works, but not
> 
> ```
>  use: [
>           'css-loader',
>           'style-loader',
>         ],
> ```

do you know why this order happens? in my understanding, style-loader will take all the 
css it finds generated by css-loader and inject to html. So that meas css-loader will work for us first. It's a little bit wierd to put it in reverse oreder in our config. But it really works. just don't know why.

**Comment by havja** [comment]
In our application using Storybook webpack I have fixed this issue by using this code:

`config.module.rules = config.module.rules.filter(rule => rule.test.toString().indexOf('css') == -1);`

**Comment by barbala4o** [comment]
In my case the problem appeared only when adding --watch to ng build in development. In that case I had to disable optimization. ng build --watch --no-delete-output-path --optimization=false --build-optimizer=false solved my problem.

**Comment by noobAAK** [comment]
> > This issue is the very high in google, so posting here, maybe helps somebody.
> > Got the same even now by using 'css-loader' before 'style-loader'.
> > E.g.
> > ```
> >  use: [
> >           'style-loader',
> >           'css-loader',
> >         ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > works, but not
> > ```
> >  use: [
> >           'css-loader',
> >           'style-loader',
> >         ],
> > ```
> 
> do you know why this order happens? in my understanding, style-loader will take all the
> css it finds generated by css-loader and inject to html. So that meas css-loader will work for us first. It's a little bit wierd to put it in reverse oreder in our config. But it really works. just don't know why.

Vow after hours of struggling with this issue finally writing style-loader above css-loader worked 
thanks a lot

**Comment by ambujkhanna** [comment]
I simply removed below snippet and worked for me
```

            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            },
```

**Comment by imki123** [comment]
@decoder318  In my case, '.css' rules applied twice. (One is storybook-webpack, other is react-webpack)
After I exclude one rule, it works fine.

**Comment by barzilaysapir** [comment]
Using `storybook-css-modules` addon solved it for me
 
https://storybook.js.org/addons/storybook-css-modules
