### ISSUE TITLE
Global style is hashed when using Sass ampersand

### ISSUE THREAD

**Issue by ukupat** [webpack-contrib/css-loader#306]
We started using Sass + CSS Modules with Local scoped CSS by default. We still had a lot of global styles that we wrapped with `:global` selector:

``` css
:global {
  @import "notifications";
  ...
}
```

In global styles we had selectors that reference parents using the Sass ampersand character:

``` css
.children {
  .parent & {
    ...
  }
  ...
}
```

Because these selectors are inside of `:global` selector then they should have produced:

``` css
.parent .children {...}
```

What actually happened was that parent class selector was made local

``` css
.example-file__parent___qXKr2 .child {...}
```

When using ampersand as the first selector then no hash is added:

``` css
.parent {
  & .children {
    ...
  }
  ...
}
```

**Comment by AllainPL** [comment]
I'm not sure if there is any development on this (looks like no) but a workaround for now is to
wrap `.parent` selector in an additional `:global` but that requires modification to the imported sass.
```scss
.children {
  :global(.parent) & {
    ...
  }
  ...
}
```
A bit more explanation:
the sass starts with compiling your original case to this:
```css
.parent :global .children { ... }
```
so the behavior of css-loader is technically correct.

On the other hand the workaround I provided is being compiled to:
```css
:global(.parent) :global .children { ... }
```
Which works as expected by you.

However the problem remains but probably on the side of sass - not allowing to change the trailing ampersand scope. I was experimenting with `@at-root` but without success.

**Comment by aczekajski** [comment]
I suggested a missing feature in SASS which will resolve the case:
https://github.com/sass/sass/issues/2401

You can comment there to get their attention to the use-case.

**Comment by evilebottnawi** [comment]
Thanks for issue, but not related to `css-loader`. We can not do anything here :disappointed:

**Comment by M3kH** [comment]
An year later, and we're experiencing the same with no solutions.
Where to go to solve this?
