### ISSUE TITLE
Harmony import of a CSS module should be namespace imports

### ISSUE THREAD

**Issue by Kovensky** [webpack-contrib/css-loader#320]
That is, the really appropriate way of importing all styles from a file should be `import * as styles from './styles.css'`, instead of `import styles from './styles.css'` -- that, semantically, imports the default style, whatever the default style is. Maybe you have a `.default` class.

Right now, this happens to work fine with ES6, but it is forbidden by TypeScript unless the exports are flagged with `__esModule` (https://github.com/nodejs/node-eps/issues/26#issuecomment-230572661, [TypeScript Loading Behavior for CommonJS and ES Modules](https://github.com/DanielRosenwasser/es-commonjs-interop/blob/master/Loading%20Behavior.md#summary)). It is possible node moves in a similar direction as TypeScript.

Correctly supporting namespace imports would also allow for future tree-shaking of unused styles.

The problem with fixing it either way is that it would be an API break, but I'm not sure how much weight should be put behind avoiding breaking the API of an underspecified feature.

**Comment by sokra** [comment]
I want to move the loader to use ES6 exports after the webpack 2 release.

**Comment by Kovensky** [comment]
It could help to at least set __esModule for now, in the current exported object, to make sure a default import doesn't incorrectly import the namespace.

But that, in itself, would warrant a major version bump... :(

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/css-loader/issues/320
