### ISSUE TITLE
css-loader failed when include added in webpack.config.js

### ISSUE THREAD

**Issue by BD-Joy** [webpack-contrib/css-loader#335]
I have a `webpack.config.js` file as blow:
`
    let webpack = require('webpack');

```
module.exports = {
    entry: './src/test.css',
    output: {
        path: "dist",
        filename: "app.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, include: ["E:\demo\src"], loaders: ["style", "css"] }
        ]
    }
}
```

`

It failed. The error message is:

> ERROR in ./src/test.css
>     Module parse failed: e:\demo\webpack-demo\src\test.css Unexpected token (1:4)
>     You may need an appropriate loader to handle this file type.
>     SyntaxError: Unexpected token (1:4)
>         at Parser.pp$4.raise (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:2221:15)
>         at Parser.pp.unexpected (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:603:10)
>         at Parser.pp.semicolon (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:581:61)
>         at Parser.pp$1.parseExpressionStatement (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:966:10)
>         at Parser.pp$1.parseStatement (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:730:24)
>         at Parser.pp$1.parseTopLevel (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:638:25)
>         at Parser.parse (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:516:17)
>         at Object.parse (E:\demo\webpack-demo\node_modules\acorn\dist\acorn.js:3098:39)
>         at Parser.parse (E:\demo\webpack-demo\node_modules\webpack\lib\Parser.js:902:15)
>         at DependenciesBlock.<anonymous> (E:\demo\webpack-demo\node_modules\webpack\lib\NormalModule.js:104:16)
>         at DependenciesBlock.onModuleBuild (E:\demo\webpack-demo\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
>         at nextLoader (E:\demo\webpack-demo\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
>         at E:\demo\webpack-demo\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
>         at Storage.finished (E:\demo\webpack-demo\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
>         at E:\demo\webpack-demo\node_modules\graceful-fs\graceful-fs.js:78:16
>         at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3)

But it's successfully when **include** is deleted.

**Comment by killercentury** [comment]
I am getting the same issue as well

**Comment by TheLarkInn** [comment]
This one looks to also be related to .23+ 

Thank you for the research on this. Will add this to regression of fixes for css-loader.

**Comment by michael-ciniawsky** [comment]
Thats an issue with `include` in `webpack.module.rules[i].include`, if you check the stacktrace you see that acorn (JS Parser) used by webpack tries to parse your `.css` which fails of course. `css-loader` isn't even called at this point. Closing as unrelated for now, feel free to reopen if any problems with `css-loader` occur after include works :)
