### ISSUE TITLE
path must be string

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack-contrib/css-loader#337]
After upgrading to `2.1.0-beta.23` I got:

```
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:1228:5)
    at Object.<anonymous> (/Users/foo/node_modules/css-loader/lib/loader.js:101:19)
```

Because `query.context || this.options.context` in `var p = path.relative(query.context || this.options.context, source).replace(/\\/g, "/");` was `undefined`.

I fixed it by changing my `'css-loader?sourceMap'` config to `'css-loader?sourceMap&context=/'`. Is this the _right_ way to fix this or is this a bug?

**Comment by wellyshen** [comment]
Hi have the same issue +1

**Comment by phairoh** [comment]
My solution for jtangelder/sass-loader#285 also seems to fix this.

**Comment by andreiglingeanu** [comment]
Yep, that is confirmed.

**Comment by evilebottnawi** [comment]
@donaldpipowitch @wellyshen @phairoh @andreiglingeanu   this problem is actual?

**Comment by evilebottnawi** [comment]
Inactive issue. Feel free to reopen if you still have problem. Thanks!
