### ISSUE TITLE
Module build failed: Unknown word

### ISSUE THREAD

**Issue by cuiyue** [webpack-contrib/css-loader#343]
Trying to use the style-loader and css-loader.

ERROR in ./app/main.css
Module build failed: Unknown word

My webpack.config.js file:

> module.exports={
>     devtool:'eval-source-map',
>     entry:__dirname+'/app/main.js',
>     output:{
>         path:__dirname+'/public',
>         filename:'bundle.js'
>     },
>     module:{
>         loaders:[
>             {
>                 test:/.json$/,
>                 loader:'json-loader'
>             },
>             {
>                 test:/.js$/,
>                 exclude:/node_modules/,
>                 loader:'babel',
>                 query:{
>                     presets:['es2015']
>                 }
>             },
>             {
>                 test:/.css$/,
>                 loader:'css-loader!style-loader!sass-loader'
>             }
>         ]
>     },
>     devServer:{
>         contentBase: './public',
>         colors:true,
>         historyApiFallback:true,
>         inline:true
>     }
> };

Where is the problem?
Regards

**Comment by yinshipeng** [comment]
Same here

**Comment by michael-ciniawsky** [comment]
@cuiyue 

```diff
{
   test:/.css$/,
-   loader:'css-loader!style-loader!sass-loader'
+   loader: 'style-loader'!'css-loader?importLoaders=1!sass-loader'
}
```

**Comment by jonathanphz** [comment]
@cuiyue Thank you thank you!
