### ISSUE TITLE
Make css-loader dependency graph smaller.

### ISSUE THREAD

**Issue by just-boris** [webpack-contrib/css-loader#344]
Hello!

I am using css-loader for a long time and it does the job very well.
But recently I have figured out, that I am using only a little part of features that it has.

Basically, I mean, that I don't use features provided by the bunch of plugins from css-modules organization, like `postcss-modules-values` or `postcss-modules-local-by-default`. But they are still being installed for my project because they are mentioned in `dependencies` section.

What do you think about the idea to split `css-loader` with css-modules enabled by default and other `css-loader-lite` with does only basic stuff, like inline resources as data-uri, and resolve css-imports?

**Comment by andreypopp** [comment]
I believe splitting CSS modules support from CSS loader was proposed and
discussed multiple times.

It would be no be to have a pull request made for that to start the more
comprehensive discussion.

**Comment by michael-ciniawsky** [comment]
@just-boris @andreypopp I'm working on `postcss-loader` v20.0 to **not** depend upon `css-loader` anymore and being able to use CSS Modules `postcss-modules`  based on `result.messages`. Removing CSS Modules in `css-loader` can be considered if a proper replacement is available. Anyhow I don't think the size of a loader used in a dev env really matters tbh 😛
