### ISSUE TITLE
[css-modules] Is it possible to preserve the local class name?

### ISSUE THREAD

**Issue by kcjonson** [webpack-contrib/css-loader#353]
This is best demonstrated with an example.

1) Generated CSS files are only the hash or unique identifier (prevent style bleed)
2) Class name is preserved in the html structure to inherit from global styles

component.css (source)

```
.element {
  background-color: blue;
}
```

component.jsx (source) 

```
import styles from './component.css';
...
return (<div className={styles.element}>
```

component.css (output)

```
.1vZzB {
  background-color: blue;
}
```

component.jsx (output) 

```
<div class="node 1vZzB">  
```

Note the space.  This allows global styles to target `.node` but the components styles to never bleed outside their intended scope.

**Comment by longlho** [comment]
u can use `:global node { }`

**Comment by michael-ciniawsky** [comment]
see @longlho comment

**Comment by fzembow** [comment]
One neat thing is you can use local scope inside of global scope.

For example:

```

**Comment by Zydnar** [comment]
@fzembow Thank you. Your solution led me to even nicer solution in my case:
```scss
:global {
    @import "@material/textfield/mdc-text-field"; // all styles have unchanged names
}
```
In case someone did't know you can do this.
