### ISSUE TITLE
Remove postcss or any minification operations

### ISSUE THREAD

**Issue by airtonix** [webpack-contrib/css-loader#354]
It's confusing, not properly documented and not fully configurable. Wastes time tracking problems down and requires me to load the postcss loader _anyway_ then use more config for css-loader to cancel out the over zealous nature of css-loader.

If people want minification, they can add postcss-loader.

Explicit is better than implicit.

**Comment by SpaceK33z** [comment]
As of version `0.26.0`, the stripping of vendor prefixes has been removed (#281).

**Comment by havenchyk** [comment]
@airtonix can this issue be closed?

**Comment by alex-shamshurin** [comment]
It took me 4 hours to find a problem. Why there is a PostCSS?

**Comment by airtonix** [comment]
@havenchyk yes if postcss has been removed.

**Comment by alex-shamshurin** [comment]
0.26.2 calls postCSS, I see this in stacktrace.  I had a similar issue like this http://stackoverflow.com/questions/42376762/webpack-production-build-browserslisterror-unknown-version-55-of-and-chr

**Comment by michael-ciniawsky** [comment]
PostCSS will not be removed in the near future, albeit the logic will change so it will not be called in `global` (no CSS Modules `module`) mode nor if no minification is requested to address various perf issues
