### ISSUE TITLE
Use same resolving tech as in scripts

### ISSUE THREAD

**Issue by NekR** [webpack-contrib/css-loader#363]
Right now, if I have `webpack.config.resolve.root` (webpack 1) setting set, I can do direct requires as they in modules folder, e.g. `require('components/a')` from `components/b/c/d/z` and it will work. If I need a true relative path, I use `./`. But this doesn't work with `css-loader`. In both such cases it uses relative path. I understand it's kind of compatible with how real CSS works, but it's a bit no practical for me. I tried to find some options about it in the README and it only says that I can disable handling of url()/@import, but no way to change such resolving method.

Any idea? Would it be good to have such option? I can PR it of course.

**Comment by NekR** [comment]
Okay, i just found `url(~module/image.png)`. Why not have an option to make this a default?

**Comment by michael-ciniawsky** [comment]
@NekR  Yep 👍 please send PR when you have time

**Comment by NekR** [comment]
@michael-ciniawsky lol, okay :D

**Comment by evilebottnawi** [comment]
@NekR friendly ping, problem still exists? Wait PR?

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/css-loader/issues/342. Feel free to feedback.
