### ISSUE TITLE
What is the difference between :global and :global()?

### ISSUE THREAD

**Issue by magikMaker** [webpack-contrib/css-loader#365]
In the readme it says:

> :global(.className) can be used to declare an explicit global selector. With :global (without brackets) global mode can be switched on for this selector.

But I don't see any difference in the results between these two

```
:global(.my-styles) { ... }
:global .my-other-styles { ... }
```

Or is it maybe intended for something like below? Because then the docs are not very clear to me.

```
/* only one class name is global */
:global(.global-name) .local-name { ... }
.local-name :global(.global-name) { ... }

/* both parts of the selector are global */
:global .global-name .another-global-name { ... }
```

**Comment by kumarharsh** [comment]
I could be wrong, but the way I've understood this concept is:

1. if the `:global` is used with a space, e.g. `.local-name :global .global-name`, then it just converts the immediately succeeding selector as global.
2. if the `:global` is used with parenthesis, e.g., `.local-name :global(.global-name > .global-child + .global-sibling)`, then it converts the all selectors within the parens as global.

**Comment by evilebottnawi** [comment]
Please see comment above. Thanks for issue and sorry for delay!

**Comment by evilebottnawi** [comment]
Also we have example with `local` https://github.com/webpack-contrib/css-loader#scope
