### ISSUE TITLE
Webpack 2 localIdentName [folder] is empty

### ISSUE THREAD

**Issue by MikeLP** [webpack-contrib/css-loader#370]
Here is part of config
```
{
    test: /\.(scss|sass|css)$/,
    use: [
      'style-loader',
      {
        loader: 'css-loader',
        options: {
          localIdentName: '[folder]_[path]__[name]_[local]__[hash:base64:16]',
          modules: 1,
          importLoaders: 1
        }
      },
      {
        loader: 'postcss-loader'
      }
    ]
  }
```

```
structure of project is 
components
 MyComponent
   index.js
   style.js
```

I need in [folder] tag to avoid same classes names in different css/sass files

P.S.
Why we can't do something like this in getLocalIdent file:
```
...
options.content = options.hashPrefix + request + "+" + loaderContext.resourcePath + '#' + localName;
...
```

**Comment by rnons** [comment]
Are you using LoaderOptionsPlugin? Try disable LoaderOptionsPlugin and see if [folder] is still empty.

I believe this is related to #340

**Comment by keske** [comment]
Hi rnons, I had the same problem, before I disabled LoaderOptionsPlugin, with the localIdentName, thanks!

**Comment by keske** [comment]
Also, @MikeLP if you are using `LoaderOptionsPlugin` ensure you have `context`.
My code with `LoaderOptionsPlugin` and correct `localIdentName`:

```Javascript
    new webpack.LoaderOptionsPlugin({
      options: {
        context: __dirname,
        postcss: [
          // bunch of plugins
        ],
      },
    }),
```

**Comment by sunderls** [comment]
I had the same problem, I think this is because [folder] is being taken as 'relative', which results in empty string since js & css are in the same folder. 

created an issue here https://github.com/webpack/loader-utils/issues/51
don't know whether is appropriate though...

**Comment by tonyhb** [comment]
@keske OMG CONTEXT IN OPTIONS!!!! THANK YOU

**Comment by MikeLP** [comment]
@keske Thanks.
