### ISSUE TITLE
Global selectors don't work with ~

### ISSUE THREAD

**Issue by marcselman** [webpack-contrib/css-loader#371]
I'm using CSS Modules but sometimes have to combine my selectors with global classnames.
For example:
`.default :global .Select-option-group-label ~ :global .Select-option`

But it looks like css-loader removes the space between `~` and `:global`

I get the following error:
`Module build failed: Missing whitespace before :global`
`at \node_modules\css-loader\lib\processCss.js:213:23`

**Comment by draganSm** [comment]
Did you try
```.default :global(.Select-option-group-label) ~ :global(.Select-option)```

**Comment by bebraw** [comment]
What @draganSm suggested is likely the way to go. Feel free to re-open if you feel this is still relevant.
