### ISSUE TITLE
root-relative URLs not working

### ISSUE THREAD

**Issue by hendrul** [webpack-contrib/css-loader#372]
webpack version: 1.13.3
css-loader version: 0.25.0

```javascript
// styles/index.css
.some {
    background-color: blueviolet;
}

//app.js
require('css?root=.!/styles/index.css')

//webpack.config.js
module.exports = {
  output: {
    filename: 'bundle.js'
  },
  entry: ["./app"]
};
```
Hash: 522c94f9f7ba11829620
Version: webpack 1.13.3
Time: 151ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.73 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
   [1] ./app.js 71 bytes {0} [built] [1 error]

ERROR in ./app.js
Module not found: Error: Cannot resolve 'file' or 'directory' /styles/index.css in /home/user/cssLoaderTest
 @ ./app.js 2:0-28

Debugging I see webpack doesn't even call css-loader when path is absolute

**Comment by michael-ciniawsky** [comment]
@hendrul Still doesn't work? Have you tried with webpack 2 ?

**Comment by d3viant0ne** [comment]
To that end, https://github.com/webpack/webpack-cli is looking for people to try out their migration utility. This may be an excellent opportunity to update as majors are coming for most loaders that will no longer support 1.x

**Comment by michael-ciniawsky** [comment]
```
- require('css?root=.!/styles/index.css')
+ require('!css-loader?root=.!/styles/index.css')
```

Or just avoid `root` for the meantime it's likely to be removed in the future or will undergo a bigger refactor
