### ISSUE TITLE
css rule bug ? when background-image = about:blank

### ISSUE THREAD

**Issue by luqingxuan** [webpack-contrib/css-loader#376]
in my css file , i write body background-image =  about:blank,
i notice css-load call method processNode in file processCss.js,
and processNode call isUrlRequest in loader-utils module,
bug about:blank is not a file , u can not read it,
so it is a bug? or can i do something to fix my problem? 3Q

**Comment by luqingxuan** [comment]
by the way, i try to rewrite isUrlRequest, 
return false if url param = about:blank,
and every it works for me, everything is ok,
so it is a loader-utils bug ?

**Comment by timse** [comment]
why would you use `about: blank` as a background image, that is no image nor a valid url.

**Comment by luqingxuan** [comment]
@timse 
there is a jquery plugin, such as layui dialog, for IE6 fixed position, u can see css file,
[https://github.com/sentsin/layer/blob/master/build/skin/default/layer.css](https://github.com/sentsin/layer/blob/master/build/skin/default/layer.css)

so i don't care IE6, but this plugin notice IE6 users
maybe u can see this for why set css rule about:blank
[http://www.cnblogs.com/slowsoul/archive/2013/05/31/3110135.html](http://www.cnblogs.com/slowsoul/archive/2013/05/31/3110135.html)

**Comment by timse** [comment]
fair enough, maybe ask the author of that plugin that its time to drop ie6 support :)?

**Comment by luqingxuan** [comment]
@timse 
maybe i don't think it's fair enough... 
i think loader-utils(css-loader uses loader-utils) does not consider this situation, 
not for IE6, even i write css rule just for fun, error occurs
div {background-image: ('about:blank')}; 
i think: u can't control developers, u can help them fix errors, 
and in this case, the loader-utils just confuses them

**Comment by luqingxuan** [comment]
@timse 
forget me for my pool english

**Comment by michael-ciniawsky** [comment]
@luqingxuan Please provide your fix as PR, so we can discuss it better 😛 , otherwise this hasn't any priority atm

**Comment by timse** [comment]
@luqingxuan no worries about your english mine is not as good as I wanted it to be either :)
