### ISSUE TITLE
Add documentation for importLoaders

### ISSUE THREAD

**Issue by AndrewRayCode** [webpack-contrib/css-loader#384]
Currently this is in the README for `importLoaders` documentation:

> The query parameter importLoaders allow to configure which loaders should be applied to @imported resources.
> 
> importLoaders (int): That many loaders after the css-loader are used to import resources.

This is confusing and hard to understand. After reading this, I have no idea what `importLoaders` does. In fact I think I walk away more confused than before reading the docs.

I would happily submit an improvement to make this comprehensible if I could figure out what this option does.

**Comment by Zhouzi** [comment]
There's an other issue opened with some interesting insights here: #228

**Comment by bebraw** [comment]
Let's close in favor of #228.
