### ISSUE TITLE
default localIdentName performs poorer than a composed one

### ISSUE THREAD

**Issue by enapupe** [webpack-contrib/css-loader#406]
I did some changes on my webpack config file in order to optimize generated css file size. The first move was removing my custom `localIdentName` and use `css-loader`'s  default. Surprisingly, `[hash:base64]` performs poorer than `[name][local][hash:base64:5]` considering gzip size.

That's probably because the default hash length is 23 (unique characters) and gzip can't do much about that kind of data (unique). Using a composed `localIdentName` with a smaller hash portion leaves more space for gzip to work.

Do you guys think it's possible to change the default option? I understand that `hash:base64` is probably the safest option but maybe we could get to another safe combination that also has better compression.

FYI this is what I'm getting at this project:
* bundled css total file size:

|  | `[hash:base64]`  | `[name][local][hash:base64:5]` |
| ------------- | ------------- | ------------- |
| raw | 137kb  | 139kb  |
| gzip | 44kb  | 27kb  |

**Comment by enapupe** [comment]
And on another project, left is `[hash:base64]` , right is `[path]-[name]--[local]`
![screen shot 2017-01-20 at 4 17 26 pm](https://cloud.githubusercontent.com/assets/291082/22160329/0a053eaa-df2c-11e6-8393-f39b82eebfaa.png)

**Comment by timse** [comment]
the point of hashes is, that they are collision safe, therefore they are "hard" to compress.
its basically a "pick one" situation, but maybe one could reduce the length of the hash, not sure mathematically how "short" one can get without risking the chance of a collision on a generally large website

**Comment by enapupe** [comment]
Maybe using full class names are safer than base64 hashes, and also compresses better?
What would be the config string for complete class names? `[path][name][local]`? It would be unique, right?

**Comment by enapupe** [comment]
I just reminded that the html size is also influenced by `localIdentName`. So the difference might be ever bigger considering all templates and stuff..

**Comment by michael-ciniawsky** [comment]
@enapupe Can you send PR and discussion moves on there then ? 😛

**Comment by michael-ciniawsky** [comment]
@enapupe Closed #442 I will come back to the PR soon

**Comment by amerllica** [comment]
@michael-ciniawsky , Why every developer used `hash:base64` used the minimum number 5, why I use 3 instead of 5 some class names made duplicated?
