### ISSUE TITLE
Loader can't use importedLoaders to load url in webpack 2.2.

### ISSUE THREAD

**Issue by artemkaint** [webpack-contrib/css-loader#411]
I've set importLoaders to use postcss at url. It works with webpack < 2.1 but now it use options param, but getImportPrefix function does not understand this param and use only query (request) property (https://github.com/webpack-contrib/css-loader/blob/master/lib/getImportPrefix.js#L12). 

Query property doesn't include some options of the imported loader

**Comment by michael-ciniawsky** [comment]
@artemkaint Do you also a fix in mind ?

**Comment by jquense** [comment]
this is a frustrating one :/ Shouldn't it use `ident` and a string placeholder like is down elsewhere for stringifying loader requests?

**Comment by michael-ciniawsky** [comment]
@jquense  Not sure tbh I need to look at it first, but if you think you have some a (rough) solution please send PR 😛

**Comment by evilebottnawi** [comment]
Use `ident`. Some `webpack` version was affected this bug
