### ISSUE TITLE
Problems with font src when building node package with webpack

### ISSUE THREAD

**Issue by Mioleris** [webpack-contrib/css-loader#418]
Going directly to the problem...

**lib.js code**

    import DemoModule from './DemoModule.jsx';
    import './styles/fonts/fonts.scss';
    import './styles/styles.scss';
    
    module.exports = {
        DemoModule: DemoModule,
    };

**Fonts.scss**

    @font-face {
        font-family: 'Demo font';
        src: url('./demo-font.otf') format('opentype');
        font-weight: 300;
    }

**Webpack code**

    module.exports = {
        entry: './src/lib.js',
        target: 'node',
        output: {
            filename: 'index.js',
            path: './lib/',
            library: "libName",
            libraryTarget: 'commonjs2',
        },
        plugins: [
            ***
        ],
        module: {
            loaders: [
                { test: /\.js$/, loader: 'babel-loader' },
                { test: /\.jsx$/, loader: 'babel-loader' },
                { test: /\.json$/, loader: 'json' },
                { test: /\.scss$/, loaders: ['style', 'css', 'sass'] },
                { test: /\.png$/, loader: 'url-loader' },
                { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&mimetype=application/font-woff" },
                { test: /\.[ot]tf?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader?limit=10000&mimetype=application/octet-stream' },
                { test: /\.(eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
            ]
        }
    };

When i run **npm run build** this command compiles everything in lib directory, creates index.js and moves demo-font.ots in that directory too.

Direcotry looks like that

    /lib
        index.js
        demo-font.ots

But when i use this package from **node_modules** in other project it looks for fonts like this www.abc.com/demo-font.ots and it's missing. Everything works, even css works, except fonts can't be loaded.

What I'm missing in this configuration? How to tell to look for css resources in correct way?
Font loads when i'm testing this app inside with **npm run debug**

**Comment by Mioleris** [comment]
@evilebottnawi no, everything works now as expected.

**Comment by evilebottnawi** [comment]
@Mioleris Thanks!

**Comment by fccoelho7** [comment]
@Mioleris how did you solved that problem? I've got the same. 😕

**Comment by awacode21** [comment]
me too, what was the solution for your problem @Mioleris

**Comment by Mioleris** [comment]
Sorry not posting for long time...
Somehow missed @fccoelho7 comment...

And currently I cant remember what I did. Now it works perfect.

When I'm building package I add this - `libraryTarget: 'commonjs2'`

```
    entry: [
        path.join(__dirname, "src/common.scss"),
        path.join(__dirname, "/src/lib.js")
    ],
```

My fonts are imported in `common.scss`
and then in plugins
```
new ExtractTextPlugin('common.scss'),
```

And lib folder now has fonts and that common.scss file. I'm not converting that file to css but leaving as scss
