### ISSUE TITLE
Sass and ':global' error

### ISSUE THREAD

**Issue by jasonmacdonald** [webpack-contrib/css-loader#419]
I'm probably just missing something here, but I've tried searching everywhere and can't find an answer or an example. How are you supposed to use the ":global" keyword in SASS files? Anytime I try to use it I get an error during Webpack build of:

```
ERROR in ./src/assets/styles/global.sass
Module build failed: ModuleBuildError: Module build failed: 
  :global(.test)
 ^
      Property "global" must be followed by a ':'
```

Are you not supposed to use this in SASS files? If so, how do I declare a certain style to be global?

**Comment by jopdeklein** [comment]
I am experiencing the same when upgrading to webpack 2 and css-loader `0.26.0` - it used to work with webpack 1 and css-loader `0.23.0`. I am not sure if it's related to this project or perhaps another loader that comes before it, I use:
* sass-loader `6.0.2` 
* node-sass `4.0.0` 
* postcss-loader `1.3.3`.

**Comment by michael-ciniawsky** [comment]
@jasonmacdonald @jopdeklein https://github.com/webpack-contrib/sass-loader/issues/393#issuecomment-284382968. Reopen please if that's not the case, closing for now 😛
