### ISSUE TITLE
prefix specific css file urls paths

### ISSUE THREAD

**Issue by newasmod** [webpack-contrib/css-loader#422]
set webpac.config to prefix url in `background-image: url(_prefix_- path)`
so if i have in css file something like:
`.limage09o {
    background-image: url('/img/image.png');
 }
`
i want webpack to add prefix to  url('/img/image.png') like:
`url('../../../../img/image.png')`

**Comment by michael-ciniawsky** [comment]
@newasmod You need to set `options.root` to get the `url()` resolved
