### ISSUE TITLE
see

### ISSUE THREAD

**Issue by mattkime** [webpack-contrib/css-loader#426]
**What is the current behavior?**
We're seeing module resolution failures due to a sub dependency change with `loader-utils`. `loader-utils` recently released 0.2.17. Everything works fine if we specify 0.2.16 in our devDependencies.

**If the current behavior is a bug, please provide the steps to reproduce.**

We have a large and complicated webpack build. I know I should isolate the problem but haven't had a chance yet.

**What is the expected behavior?**

Node v7.5. Seeing the problem on docker node along with OS X.

**Comment by mattkime** [comment]
@michael-ciniawsky why was this closed?

**Comment by d3viant0ne** [comment]
`loader-utils` is currently on `v1.0.3` as is this loader and every other loader in contrib. 

To the point, I fail to understand what a `loader-utils` issue has anything to do with css-loader and this was closed because this issue belongs in loader utils.

**Comment by mattkime** [comment]
@d3viant0ne thanks, just wanted an explanation

**Comment by d3viant0ne** [comment]
No worries. My suggestion would be to get your devDep up to date. The major release was mostly about enforcing NodeJS 4.x.

The other changes are reasonably simple to update.
