### ISSUE TITLE
Classnames are not unique

### ISSUE THREAD

**Issue by jeffijoe** [webpack-contrib/css-loader#431]
**Do you want to request a *feature* or report a *bug*?** 

Bug

**What is the current behavior?** 

Classnames are not unique

**What is the expected behavior?** 

Classnames should be unique

**If this is a feature request, what is motivation or use case for changing the behavior?**

Have 2 modules with the same name in 2 different folders. E.g.

```
components
- Form
  - Form.css
  - index.jsx -> import styles from './Form.css'
screens
- Account
  - Form
    - Form.css
    - index.jsx -> import styles from './Form.css'
```

I believe the ident hash is generated base on a relative import path `./Form.css`, which would be the same in both cases. If you used an absolute path (or at least relative to the source root) that would help.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

- Webpack 2.2.1
- Node 6.9.5
- maxOS Sierra

![image](https://cloud.githubusercontent.com/assets/2505474/23341260/2e8ddb12-fc44-11e6-9760-2b54f476a03d.png)

**Comment by jeffijoe** [comment]
This is actually a dupe of #413.

**Comment by bebraw** [comment]
Yeah, let's close in favor of that.

**Comment by tvrcgo** [comment]
Also facing the same problem.

**Comment by bebraw** [comment]
@tvrcgo Can you check https://github.com/webpack-contrib/css-loader/issues/413 ? They are discussing some solutions there.
