### ISSUE TITLE
Cannot find module "!!../../../node_modules/css-loader/index.js?modules&localIdentName=[name]__[local]--[hash:base64:10]!../../../node_modules/postcss-loader/index.js!./EraAccessGroupFilter.css"

### ISSUE THREAD

**Issue by Ziker22** [webpack-contrib/css-loader#439]
`Cannot find module "!!../../../node_modules/css-loader/index.js?modules&localIdentName=[name]__[local]--[hash:base64:10]!../../../node_modules/postcss-loader/index.js!./EraAccessGroupFilter.css"`

Hi guys,
Recently i started to get this error.
Strange thing is that it happens only in production when built with jenkins(on linux).
Locally on windows it works just fine
Any ideas ?

Webpack setup
```
 {
                test: /\.css$/,
                loader: "style!css-loader?modules&localIdentName=[name]__[local]--[hash:base64:10]!postcss"
            },
```

Node version : 6.9.2
npm version: 3.10.9
webpack version:  1.14.0

**Comment by michael-ciniawsky** [comment]
@Ziker22 If it still happens please feel free to reopen 😛 , but this seems to be an issue with your setup, since all loaders fail to load according to the error

**Comment by vnallamhawk** [comment]
Hi Team,

Could you please let us know on how to fix this.I am facing this in a Paas environment. Cannot find module "!!../../node_modules/css-loader/index.js?modules=true&localIdentName=[name]__[local]___[hash:base64:5]!../../node_modules/sass-loader/lib/loader.js!./style.scss". However its not coming up in my local system.
