### ISSUE TITLE
use "const" in css-base.js cause the ie10 cann't work

### ISSUE THREAD

**Issue by ImHype** [webpack-contrib/css-loader#450]

**Comment by michael-ciniawsky** [comment]
@ImHype Fixed by #452

**Comment by ImHype** [comment]
Maybe most of users use the 「ExtractTextPlugin」 to extract the stylesheet, so they haven't fount this problem. Anyway, thanks.

**Comment by ImHype** [comment]
Happy Monday !

**Comment by michael-ciniawsky** [comment]
np, also Happy Monday!
