### ISSUE TITLE
Fails on commented import

### ISSUE THREAD

**Issue by danielverejan** [webpack-contrib/css-loader#456]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When you comment an import
`// @import 'base.css'`
it fails with **Unknown word** error

**If the current behavior is a bug, please provide the steps to reproduce.**
Comment an import with **//** and run config.

**What is the expected behavior?**
Bundled css to contain **// @import 'base.css'**

Webpack: 2
css-loader: 0.27.3

**Comment by bebraw** [comment]
Only `/**/` is valid in vanilla CSS. Maybe that's it?

**Comment by michael-ciniawsky** [comment]
@danielverejan Please try with `/**/` and report back 😛 likely to be the source of failure

**Comment by danielverejan** [comment]
Yes it works with `/**/`. Wasn't aware that this is a limitation of the current version.

**Comment by bebraw** [comment]
It's a specification thing. I'm not sold on the idea that we should support non-standard syntax here. That's why postcss et al. exist.

Time to close. 👍
