### ISSUE TITLE
Because in ./css-loader/lib/css-base.js require Buffer causes the file to be too large

### ISSUE THREAD

**Issue by NightCatSama** [webpack-contrib/css-loader#461]
version: css-loader@0.27.3

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
After upgrading from webpack1 to webpack2, there is a large file package situation.
```
./~/buffer/index.js 48.6 kb {0} [depth 5] [built]
require Buffer [5] ./css-loader/lib/css-base.js 1:0-34
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I was using vue-loader to load the css code, the file size becomes larger because the package after the require of the Buffer module.

**What is the expected behavior?**
In the `@0.23.1` is normal. After the package did not require Buffer module.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Webpack version: 2.2.1
vue-loader version: 11.1.4
Node: 7.2.1

**Comment by michael-ciniawsky** [comment]
Duplicate of #454 we are aware of this 😛

**Comment by NightCatSama** [comment]
Thank you for your quick reply. 

But I think that is not a good solution, is it possible to solve this problem in the future, I am considering whether to roll back to the old version.

**Comment by michael-ciniawsky** [comment]
Solution is would be using this but I haven't had time to test by now https://developer.mozilla.org/en/docs/Web/API/WindowBase64/Base64_encoding_and_decoding

**Comment by NightCatSama** [comment]
thank you.
