### ISSUE TITLE
url('') is rewritten as require('./')

### ISSUE THREAD

**Issue by darrenscerri** [webpack-contrib/css-loader#463]
**What is the current behavior?**
`url('')` is rewritten as `require('./')`

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply specify a `url('')` rule in CSS.

**What is the expected behavior?**
`url('')` should not be allowed. Show a warning similar to https://github.com/webpack/webpack/issues/2006

**Comment by michael-ciniawsky** [comment]
Yep, also`@ìmport/url()` with protocol schema `https://`, but we need to clearify if that breaks current useage somehow (don't think so, but how knows for sure 😛)

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/css-loader/pull/513
