### ISSUE TITLE
image in code

### ISSUE THREAD

**Issue by felek000** [webpack-contrib/css-loader#468]
webpack 2
"css-loader": "^0.26.2",
How can i set output path to be set in css ?
scss code
body{
   background: url("../img/x.jpg") no-repeat;
}

Output to css 
background: url(dist/assets/x.jpg) no-repeat; }

**Comment by TrySound** [comment]
@felek000 There's a url option. Just disable it.
https://github.com/webpack-contrib/css-loader#options-1

**Comment by felek000** [comment]
ah ok thx for info :)
