### ISSUE TITLE
Unknown word exception

### ISSUE THREAD

**Issue by anandrikka** [webpack-contrib/css-loader#470]
I'm getting unknown word exception with less. My Project doesn't use ExtractTextPlugin.

**webpack config loaders**
`javascript
{
        test: /\.js$/,
        loaders: ['babel?presets[]=es2015&presets[]=react'],
        exclude: /node_modules/,
      },
      { test: /\.md$/, loader: 'html!markdown' },
      { test: /\.less$/, loader: 'style!css!autoprefixer!less' },
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.woff2{0,1}$/, loader: 'url-loader?limit=10000&mimetype=application/font-woff' },
      { test: /\.(otf|eot|svg|ttf|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file-loader' },
      { test: /\.(png|jpg|gif)$/, loader: 'url-loader?limit=8192'}
`
**version of loaders:**

"autoprefixer": "6.4.0",
"css-loader": "0.23.1",
"less": "2.7.1",
"less-loader": "2.2.3",
"style-loader": "0.13.1"

![untitled](https://cloud.githubusercontent.com/assets/8003265/24439643/7931cfde-141d-11e7-9544-844f19df71ff.jpg)

**Comment by gztchan** [comment]
I got the same issue today

**Comment by michael-ciniawsky** [comment]
Could yu try with latest `css-loader && postcss-loader`?

***webpack.config.js**
```js
[
 'style-loader',
  {
    loader: 'css-loader', options: { importLoaders: 2 }
  },
  {
    loader: 'postcss-loader', options: { plugins: [ require('autoprefixer')(...options) ] }
  },
  'less-loader'
]
```

**Comment by anandrikka** [comment]
@michael-ciniawsky Is this the right way to use it ?

`
{test: /\.less$/, loaders: [
        'style-loader',
          { loader: 'css-loader', options: { importLoaders: 2 } },
          { loader: 'postcss-loader', options: { plugins: [ require('autoprefixer')() ] } },
          'less-loader'
        ]
      }
`

I'm getting errors and what are the options that I need to pass for autoprefixer

**Comment by michael-ciniawsky** [comment]
@anandrikka What webpack version are you currently using ? 😛  My latest comment is webpack v2+ only

```diff
{ 
-  plugins: [ require('autoprefixer') ] 
+  plugins: [ require('autoprefixer')({ browsers: 'last 2 versions' }) ] // *1)
}
```

*1) [Autoprefixer Options API](https://github.com/postcss/autoprefixer#options)
      [Autoprefixer Browsers](https://github.com/postcss/autoprefixer#browsers)

**Comment by anandrikka** [comment]
@michael-ciniawsky Unfortunately webpack version is 1.13.1 and I'm not supposed to change it. Can you tell me the reason behind the error ?

**Comment by michael-ciniawsky** [comment]
@anandrikka The syntay above is simply uncompatible with webpack v1 😛 

**webpack.config.js**
```js
module {
  loaders: [
    {
       test: /\.less$/,
       loaders: [
          'style-loader',
          'css-loader?importLoaders=1',
          'postcss-loader',
          'less-loader'
       ]
    }
  ]
},
postcss: () => {
    return [
      require('autoprefixer')({..options})
    ]
}
```

On a side note :), an update is highly recommended since webpack 2 is the first release since the core team introduction and open collective initiative and therefore most `loaders` will drop webpack v1 with the next semver major

**Comment by michael-ciniawsky** [comment]
@anandrikka Reopen if you still have any regressions 😛

**Comment by yairEO** [comment]
I have the exact same problem..

`unknown word var`

## Setup:

```
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.1.2",
    "babel-loader": "^7.1.5",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-plugin-transform-es2015-computed-properties": "^6.24.1",
    "babel-plugin-transform-es2015-destructuring": "^6.23.0",
    "babel-plugin-transform-es2015-duplicate-keys": "^6.24.1",
    "babel-plugin-transform-es2015-object-super": "^6.24.1",
    "babel-plugin-transform-es2015-parameters": "^6.24.1",
    "babel-plugin-transform-es2015-shorthand-properties": "^6.24.1",
    "babel-plugin-transform-es2015-spread": "^6.22.0",
    "babel-plugin-transform-es2015-template-literals": "^6.22.0",
    "babel-plugin-transform-es2017-object-entries": "0.0.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "css-loader": "^2.1.1",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
```
