### ISSUE TITLE
Styles strangely sometimes missing from output stylesheet sometimes not

### ISSUE THREAD

**Issue by stewartmegaw** [webpack-contrib/css-loader#474]
Simple problem to describe:

1. When I compile my project with webpack the .css stylesheet output looks great.

2. Now I restart webpack compile and the stylesheet is missing many classes.

Each time I compile it gives a different result - even though NOTHING has changed. Scratching my head. I can't find any errors in the CSS which may be causing css-loader problems. 

Anyone else having this problem and discovered why?

My relevant webpack config:

    plugins: [
        new ExtractTextPlugin({
            filename: 'css/styles.css',
            disable: false,
            allChunks: true
        })
    ],
    module: {
        loaders: [
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader'
                })
            }
        ]
    },

**Comment by stewartmegaw** [comment]
Apologies I was using an old version of postcss-loader

**Comment by michael-ciniawsky** [comment]
@stewartmegaw close ?

**Comment by michael-ciniawsky** [comment]
reopen if still any regression(s) 😛
