### ISSUE TITLE
webpack-defaults upgrade

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/css-loader#479]
Addition of `webpack-defaults` & associated refactoring as a part of the next `Major` release

Issue exists for status tracking across the organization. 

>Please do not close

This is being handled as a part of a rewrite here https://github.com/webpack-contrib/css-loader/tree/new-loader

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/css-loader/pull/847
