### ISSUE TITLE
How to resolve the assetsPublicPath to the url in css?

### ISSUE THREAD

**Issue by rubyisapm** [webpack-contrib/css-loader#480]
By default, the url can be tansfered according to the direction of dist. But I didn't find the way to set it according to the assetsPublicPath. Is there  any way to deal with that?

**Comment by michael-ciniawsky** [comment]
@rubyisapm Please provide more info on your setup (file tree, `webpack.config.js`) I'm not 💯 sure what you mean and if possible

**Comment by rubyisapm** [comment]
I'm sorry It's my fault, now it works!😁
