### ISSUE TITLE
@import in css

### ISSUE THREAD

**Issue by dmytro-lymarenko** [webpack-contrib/css-loader#481]
Hey Guys! I'm not sure if this module does it but... Is it possible to change the behavior of @import in css?

I mean I want to use a loader before the content from the file is inserted into css.

Please correct me if I'm wrong but I know that if a loader (or something else) sees @import './path/to/file.css' then the content is inserted into the file where import is used.

But this behavior is not good for me. Let me explain: I want to create a json file:
`{ width: 100, height: 200, ... }`
and then import it from css file:
`@import './variables.json';`
but it doesn't work as json is not correct format for css. So I'd like to transform it to correct css and insert it into css file using loaders from webpack.

P.S. I use sass so I want to transform json into set of variables:
from { width: 100, height: 200, ... } to $width: 100px; $height: 200px;;

Having a json file which contains variables is good as I can then import it from js file and use it.

Because now I have to have two files one for css (sass) and another for js (json) which contain the same variables. (but I like single source of truth).

**Comment by michael-ciniawsky** [comment]
@dmytro-lymarenko I reply @postcss-loader :D if any questions please post them there instead, closing in favour of [#191](https://github.com/postcss/postcss-loader/issues/197)
