### ISSUE TITLE
package.json engines field value is not working as intended

### ISSUE THREAD

**Issue by mgol** [webpack-contrib/css-loader#482]
**Do you want to request a *feature* or report a *bug*?**

A small issue.

**What is the current behavior?**
`package.json`'s engines `node` field is currently defined as `">=0.12.0 || >=4.3.0 <5.0.0 || >=5.10"`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Try to install the package under io.js. It won't complain about an unsupported Node version being used.

**What is the expected behavior?**
The range seems to suggest only new enough versions of Node 0.12, 4 & >=5 are supported. Therefore, I'd expect the range to be something like `">=0.12 <0.13 || >=4.3 <5 || >=5.10"`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It's clear the intent of this version range was different to what's specified.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
N/A

**Comment by michael-ciniawsky** [comment]
👍  But maybe removing all versions`>= 4.0.0` is the sanest way, since all other node/io.js versions are EOL anyways, mind spinning up a quick PR 😛 ?

**Comment by mgol** [comment]
@michael-ciniawsky done: #483.
