### ISSUE TITLE
importLoaders option descriptions contradictory?

### ISSUE THREAD

**Issue by ndresx** [webpack-contrib/css-loader#510]
**Do you want to request a *feature* or report a *bug*?**
*documentation*

**What is the current behavior?**
Under Options (https://github.com/webpack-contrib/css-loader#options), the description for `importLoaders` mentions **before** ...

> Number of loaders applied before CSS loader

... while under the `importLoaders` section (https://github.com/webpack-contrib/css-loader#importloaders) it says used **after**

> That many loaders after the css-loader are used to import resources.

**What is the expected behavior?**
It should be either **before**, or **after**, or not? Maybe it needs some commas too, but honestly, it sounds a bit confusing to me.

As far as I am understanding this, if for example `sass-loader` and `postcss-loader` are used **before** the `css-loader`, `importLoaders` could be set to 2 to make use of both loaders when using `@import`, but also to 1 if it should only use the `sass-loader`?

**Comment by michael-ciniawsky** [comment]
Yep the spelling could be improved, PR welcome 😛 

> As far as I am understanding this, if for example sass-loader and postcss-loader are used before the css-loader, importLoaders could be set to 2 to make use of both loaders when using @import, but also to 1 if it should only use the sass-loader?

👍

**Comment by michael-ciniawsky** [comment]
Fixed by #512 @ndresx Thx again 😛
