### ISSUE TITLE
css modules :external support

### ISSUE THREAD

**Issue by pavel06081991** [webpack-contrib/css-loader#520]
There is new feature in css modules, you can read about this here https://github.com/tivac/modular-css/blob/master/docs/features.md#overriding-styles
It is necessary for using some css selector from another css file.
Are you planning to add this feature in css-loader?

**Comment by evilebottnawi** [comment]
@pavel06081991 future `css-loader` don't have buildin `css-modules`, for this purpose we create new css-modules-loader/postcss-plugin-pack, but we will leave this issue here until it starts, then we will move this to related repo

**Comment by pavel06081991** [comment]
@evilebottnawi, thank you for your answer. Maybe you know when new css-loader and css-modules-loader/postcss-plugin-pack will be released?

**Comment by evilebottnawi** [comment]
@pavel06081991 near future :smile: sorry, we have a lot of works now, but in near days repo with loader/plugins will be created and you can help :+1: i ping you

**Comment by pavel06081991** [comment]
@evilebottnawi, maybe there are any updated? I've seen there is already new branch for new version of the loader, but the last commit was made long time ago.

**Comment by amireldor** [comment]
Is anyone working on this? How can I help? I'd really like this functionality.

**Comment by evilebottnawi** [comment]
@amireldor yes, see https://github.com/postcss/postcss-loader/issues/227

**Comment by evilebottnawi** [comment]
Thanks for issue, it is RFC for modules and should resolve in spec https://github.com/css-modules/css-modules. Please recreate issue there :+1:
