### ISSUE TITLE
not success when I use global include some method with '@'

### ISSUE THREAD

**Issue by yinglau** [webpack-contrib/css-loader#530]
HI, here it's some question when i use global with '@', for example
```css
:global{
  @keyframes keyframes_name {
    //some css code
  }
}
```
then still become a local scope style, like that
```css
@-webkit-keyframes fade-in__sk-fade-in___3BoOy {
  //some css code
}
```
What can I do will success that use the global with the keyword '@keyframes', '@media' ..... 
thx...!

**Comment by Tenkir** [comment]
I am having this same issue. Specifically, trying to globally scope a package stylesheet.

```
:global {
  @import 'react-select/dist/react-select.css';
}
```

**Comment by evilebottnawi** [comment]
@yinglau @Tenkir it is related to `css-modules`, not to `css-loader`, we just using https://github.com/webpack-contrib/css-loader/blob/master/lib/processCss.js#L12 this plugins for `css-modules`

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/css-loader/issues/264
