### ISSUE TITLE
Use PostCSS 6.0

### ISSUE THREAD

**Issue by ai** [webpack-contrib/css-loader#535]
We released major update for PostCSS. It uses less memory and less dependencies, so it will be good to update dependency here.

**Comment by michael-ciniawsky** [comment]
Upgraded to PostCSS 6 ?

- [x] [ppstcss-modules-scope](https://github.com/css-modules/postcss-modules-scope/commit/45adcfb557a81ab9f5012bbfd93f5ef1d74a37a3)
- [x] [postcss-modules-values](https://github.com/css-modules/postcss-modules-values/commit/3d96fcb8bb0dd4bd9407ca4241a019034281570a)
- [x] [postcss-modules-extract-imports](https://github.com/css-modules/postcss-modules-extract-imports/commit/c2c40a2a4bccaad0545014ae312d48730b922a18)
- [x] [postcss-modules-local-by-default](https://github.com/css-modules/postcss-modules-local-by-default/commit/8c7f208f12d32d65a4233ffaf10253f538d85e9e)

I do it as soon as possible, the relevant `postcss-modules-*` got their PostCSS 6 upate a few hours ago 😛

**Comment by ai** [comment]
Maybe we also need to wait cssnano release

**Comment by michael-ciniawsky** [comment]
Yep 😄

**Comment by ben-eb** [comment]
Can you try with v4.0.0-rc.0 and let me know how you get on? Going to allow a short period (2 weeks tops) before actually releasing to see if there's anything critical that needs fixing, but it's pretty much how I'd like it to be. I just need your feedback. 😄 

https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0

**Comment by evilebottnawi** [comment]
@ben-eb I tried, everything works fine :+1:  just wait stable release and update all to `postcss` v6

**Comment by EsrefDurna** [comment]
whats the situation ?

**Comment by michael-ciniawsky** [comment]
@EsrefDurna Still waiting for cssnano@latest

**Comment by wtgtybhertgeghgtwtg** [comment]
This would necessitate bumping the minimum supported `node` version to `>=4.0.0`, so the `object-assign` dependency can be dropped here, too.

**Comment by martinkadlec0** [comment]
It seems lots of popular libraries are doing just that lately anyway. Honestly, anyone still using <4 node version probably resigned on updating module dependencies long ago.

**Comment by d3viant0ne** [comment]
@wtgtybhertgeghgtwtg - For reference, the minimum supported NodeJS version is `4.3` which comes from Webpack v2, as v1 is no longer officially supported.

The above is usually done via `webpack-defaults` but in the case of css-loader, @sokra has re-written it completely as a part of his master plan regarding the stylesheets loader chain.

**Comment by JabbyPanda** [comment]
`post-css` in 6.0.8 had fixed reinstalled the support for `Node.js 4.2.2` 

https://github.com/postcss/postcss/issues/1052, 

while as of today `post-css` v5 does not work with 4.2.2 Node.js version as of today due to the change in  `js-base-64` library

https://github.com/dankogai/js-base64/issues/56

**Comment by seitensei** [comment]
Looks like `cssnano`'s `post-css` dependency has been updated to 6.0. Is anyone working on this?

**Comment by evilebottnawi** [comment]
@seitensei wait when https://www.npmjs.com/package/cssnano release `4.0.0` stable version

**Comment by sachetsharma1** [comment]
Is there a timeline for this?
we are using css-loader@0.28.7 and postcss-loader@0.28.7 with webpack. On windows machine we run into the following issue :
Module build failed: ModuleBuildError: Module build failed: TypeError: WeakMap: incorrect 
 at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (..\node_modules\postcss-font-family-system-ui\src\index.js:2:11)

**Comment by evilebottnawi** [comment]
@sachetsharma1 which nodejs version you use?

**Comment by sachetsharma1** [comment]
Node@6.3.0
NPM@4.6.1

Note: post-css-loader version is 2.0.6. I mentioned the css-loader version in both in above comment.

**Comment by michael-ciniawsky** [comment]
#642
