### ISSUE TITLE
Unexpected character '�'

### ISSUE THREAD

**Issue by gibbok** [webpack-contrib/css-loader#536]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using CSS loader with the following CSS creates error:

> Unexpected character '�' (1:0)
> You may need an appropriate loader to handle this file type.

`@font-face {
  font-family: 'owfont';
  src: url('../fonts/owfont-regular.eot?v=1.0.0');
  src: url('../fonts/owfont-regular.eot?#iefix&v=1.0.0') format('embedded-opentype'),
	   url('../fonts/owfont-regular.woff') format('woff'),
	   url('../fonts/owfont-regular.ttf') format('truetype'),
	   url('../fonts/owfont-regular.svg#owf-regular') format('svg');
  font-weight: normal;
  font-style: normal;
}`

**If the current behavior is a bug, please provide the steps to reproduce.**
- In your React or JS component include CSS reference as `import styles from '../../bower_components/owfont/css/owfont-regular.css'`
- Run webpack.

**What is the expected behavior?**
CSS should be included in the header dynamically.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Wnidow 10.1 - Node v7.5.0 - webpack v2.3.2

**Comment by michael-ciniawsky** [comment]
Did you setup `url-loader/file-loader` for font loading (`url`) ?

**Comment by gibbok** [comment]
@michael-ciniawsky  Thanks for your feedback.
Yes `url-loader/file-loader for font loading (url) ` works and solved my issue.
