### ISSUE TITLE
Leading _ in exported classname

### ISSUE THREAD

**Issue by Diokuz** [webpack-contrib/css-loader#541]
*bug*

**What is the current behavior?**
```css
:export {
  ._x { color: red }
}
```
transformed to object
```js
exports.locals = {
	"x": "src⁄x___x"
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**
just use [`css-loader`, `postcss-loader`] with this `postcss.config.js`:

```
const plugins = [
  require('postcss-modules-local-by-default'),
  require('postcss-modules-scope')(),
];

exports.plugins = plugins;
```

**What is the expected behavior?**
should be
```js
exports.locals = {
	"_x": "src⁄x___x"
};
```

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

`node@7` `webpack@2` `css-loader@0.28.2`

**Comment by Diokuz** [comment]
Looks like you cannot take just `prop` [here](https://github.com/webpack-contrib/css-loader/blob/master/lib/processCss.js#L71), because of [this](https://github.com/postcss/postcss/blob/d06be7280469a79865ef9f6ed8bdb337db8523db/lib/parser.es6#L209-L212)

**Comment by evilebottnawi** [comment]
@Diokuz interesting, `_x` is valid ident for css-modules, maybe we need question about this here https://github.com/css-modules/postcss-modules-values

**Comment by michael-ciniawsky** [comment]
You use `postcss-modules-*` plugins in `postcss-config.js` + `postcss-loader` ?

**Comment by michael-ciniawsky** [comment]
That could be a problem then,  since `css-loader` implements CSSM via these plugins and if the source CSS is already transformed this might not work

**Comment by TrySound** [comment]
@michael-ciniawsky We can fix that :)

**Comment by michael-ciniawsky** [comment]
@TrySound We should fix that 😛 once and for all, always problems 🐛 atm... :D

**Comment by michael-ciniawsky** [comment]
@Diokuz Does it work without the plugin in `postcss.config.js` ?

**Comment by evilebottnawi** [comment]
@TrySound Am i right what we should fix this in `postcss-modules-values`?

**Comment by Diokuz** [comment]
> You use postcss-modules-* plugins in postcss-config.js + postcss-loader ?

Yes, `postcss-loader` then `css-loader`

> @Diokuz Does it work without the plugin in postcss.config.js ?

Without plugins it creates not what I need
```
/***/ "./src/x.css":
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__("./node_modules/css-loader/lib/css-base.js")(undefined);
// imports


// module
exports.push([module.i, "._x {\n  color: red;\n}\n", ""]);
```

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/css-loader/pull/543
