### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by LeopoldLerch** [webpack-contrib/css-loader#545]
Hy, 

I am webpack 2.6 and css-loader 0.28.4.  With the simple configuration as in the docs 

`                test: /\.css?$/,
                use: [{
                        loader: "style-loader"
                    },
                    {
                        loader: "css-loader"
                    }
                ]`

i am getting only the error message "cannog find module './test.css'. I am importing it as stated in the docs

`import style from './test.css';`

can anyone help?

**Comment by fjanon** [comment]
I don't understand why there is a reference to 'style-loader' in the config, I deleted it and now webpack runs.
use: [ 'style-loader', 'css-loader' ]
>>>>
use: [ 'css-loader' ]

**Comment by michael-ciniawsky** [comment]
@LeopoldLerch Please post the relevan parts of your file tree and the logs
@fjanon Without `style-loader` or `extract-text-webpack-plugin` the CSS would be just included but not used at all :)

**Comment by michael-ciniawsky** [comment]
It's a different loader you will need to install it 😛 

Post your current `webpack.config.js` please, 'then' is ambiguous here

**Comment by LeopoldLerch** [comment]
Is it possible that css-loader simply does not work with typescript files? I got it running using the "typings-for-css-modules-loader".

**Comment by michael-ciniawsky** [comment]
@What do you exactly mean by not working 😛 ?  It doesn't included any Typescript Definitions by default, but this should only be necessary for development not to consume the lib ?
