### ISSUE TITLE
Improve readme file

### ISSUE THREAD

**Issue by warpdesign** [webpack-contrib/css-loader#547]
The readme file shows how to quickly use the css-loader:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
    ]
  }
}
``` 

but it fails to mention this: 'url() URLs in block scoped (:local .abc) rules behave like requests in modules`

So if you simply try this block of code with a random css file, it's very likely the css is referencing an image file using `url()` and unless you add a loader for .png|.gif|.jpg you'll end up with an error you don't really understand.

Adding this early in the readme file would help: 

*Note* that url() URLs in block scoped (:local .abc) rules behave like requests in modules so you should add a loader for your image (and fonts) files as well otherwise you'll end up with an error. See below.`

**Comment by michael-ciniawsky** [comment]
CSS Modules will be removed from `css-loader` soon and get a redesign in terms of request resolving.
For the current README feel free to send a PR
