### ISSUE TITLE
Multiple extract

### ISSUE THREAD

**Issue by sshmyg** [webpack-contrib/css-loader#560]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I try to Extract a couple different css files with such loader option.
I paste this loader twice, into webpack config rules.
And got an error from sass, because css loader modify data source. And on the second circle, sass loader get not sass data, but modified data by css loader.
When I paste this code once - everything is ok.
Any advice, how to extract two or more different css files without errors?
```javascript
{
        test: /\.(sass|scss)$/,
        use: [
            {
                loader: 'css-loader',
                options: {
                    sourceMap: global.isDev
                }
            },
            {
                loader: 'postcss-loader',
                options: {
                    config: {
                        path: './conf/postcss.config.js'
                    }
                }
            },
            {
                loader: 'sass-loader',
                options: sassLoaderOptions
            },
            {
                loader: 'sass-resources-loader',
                options: {
                    resources
                }
            }]
    }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to extract two or more css files, with sass loader (even if this files will get same content)

**What is the expected behavior?**
Can extract more than one css file.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Mac OS - 10.12.4
webpack 2.6.1
node 7.4.0

**Comment by serheyShmyg** [comment]
[Test repo link](https://github.com/serheyShmyg/css-loader-test)

**Comment by michael-ciniawsky** [comment]
Where do you extract CSS in the example you posted above (Where is `extract-text-webpack-plugin`)?  You will need multiple instances of ETWP to extract multiple CSS files

**Comment by serheyShmyg** [comment]
@michael-ciniawsky Did you see https://github.com/serheyShmyg/css-loader-test this example?
I've multiple inst of extract-text-webpack-plugin.

**Comment by michael-ciniawsky** [comment]
How does `file1.css` `file2.css` look like, what error logs do you get? Normally you use `inlcude/exclude` in `module.rules` to extract to different files containing enterily separated CSS

**Comment by serheyShmyg** [comment]
@michael-ciniawsky I've created sandbox to reproduce this bug.
https://github.com/serheyShmyg/css-loader-test just clone and run.

**Comment by Cokser** [comment]
+1 same problem

**Comment by evilebottnawi** [comment]
Thanks for issue. Related to https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/159
