### ISSUE TITLE
 Unexpected character '�' (1:0) You may need an appropriate loader to handle this file type. SyntaxError: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by sami718** [webpack-contrib/css-loader#566]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

**Comment by evilebottnawi** [comment]
@sami718 please use issue template

**Comment by waihiga** [comment]
i am also having the trouble of debugging this. pleeeeeease somebody help
