### ISSUE TITLE
Unicode matching

### ISSUE THREAD

**Issue by PookMook** [webpack-contrib/css-loader#569]
hi

**Do you want to request a feature or report a bug?**
bug

I encounter a problem with how css-loader handle unicode in my CSS file
**What is the current behavior?**

When i feed the unicode for "é" : \0000E9, the compiled css ends up being mimified but transformed so
```
div#download:before{
  display:block;
  content:"T\E9l\0000E9charger";
}
```
becomes : 
`div#download:before{display:block;content:"T\E9l\E9  charger le fichier YAML";text-align:center}`
with two spaces after the unicode declaration which will display in the final page as "télé charger" instead of "télécharger"

I tried variations of it to see if I was missing something: 
  content:"T\E9l\E9charger"; => content:"T\E9l\E9Charger" =>" tél(accentued greek omega)harger"
  content:"T\E9l\E9 charger"; => content:"T\E9l\E9   charger"  with three spaces=> "télé charger"
  content:"T\E9l\E9\000063harger"; =>  content:"T\E9l\E9  charger"; with two spaces => "télé charger"
  content:"T\E9l\0000E9\000063harger"; => content:"T\E9l\E9  charger";  with two spaces => "télé charger"

**What is the expected behavior?**
the expected behavior would be to transform   
`content:"T\E9l\0000E9charger"; `
in 
`content:"T\E9l\E9 charger";` 
with only one space (to escape the unicode recognition, but not 2 as it is now that add an extra space in the final HTML render.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
I use 

```
    "webpack": {
      "version": "2.6.1",
```

```
"css-loader": {
      "version": "0.28.4",
```

```
"font-awesome-webpack": {
      "dependencies": {
        "css-loader": {
          "version": "0.26.4",
```

and my rule for match css is 
```
                test: /\.css$/,
                use: extractPlugin.extract({
                    use: ['css-loader']
                })
```
thanks

**Comment by evilebottnawi** [comment]
@PookMook maybe related to https://github.com/css-modules/css-selector-tokenizer/pull/4

**Comment by PookMook** [comment]
yes and no I think, this fail as well on the full unicode \0000E9, so unless this gets executed twice (from "\0000E9" to "\E9 " (with one space) then to "\E9  " (with two spaces), that shouldn't happen.

**Comment by evilebottnawi** [comment]
@PookMook seems i already found bug somewhere in the past https://github.com/webpack-contrib/css-loader/blob/master/test/simpleTest.js#L29
@TrySound what do your think about this? In past i rewrote `css-loader` from `css-selector-tokenizer` to `postcss-value-parser` (your repo :smile: ) and it is solve this problem (and some other), but for some reason, we rejected PR.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/css-loader/issues/578 . Thanks!

**Comment by Yaowenjie** [comment]
@PookMook are you still having this issue? I met this as well, could you tell me what you did for it? Thanks!
