### ISSUE TITLE
Erro when install on mac

### ISSUE THREAD

**Issue by theinvensi** [webpack-contrib/css-loader#572]
Hello,

I have this error when try to do this command on my MacBook Air
`npm i css-loader`

Here's my environment versions:
![image](https://user-images.githubusercontent.com/4583856/27985303-999a6310-63b6-11e7-882f-f15c10c05c51.png)
![image](https://user-images.githubusercontent.com/4583856/27985318-c91b356a-63b6-11e7-9417-30461c257362.png)

And here is the erro which I've said:
![image](https://user-images.githubusercontent.com/4583856/27985309-ae3c5a4e-63b6-11e7-8af5-033b342ca427.png)

Just for complement, I already tried to install this same package on my linux server, and works fine. This error just occurs on MacOS...

Thanks!

**Comment by theinvensi** [comment]
Here is the content of the log file...

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'css-loader' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose npm-session f1225122bf36a480
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/css-loader 1100ms (from cache)
8 silly pacote tag manifest for css-loader@latest fetched in 1141ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule css-loader@0.28.4 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/cssnano 258ms (from cache)
15 silly pacote range manifest for cssnano@>=2.6.1 <4 fetched in 265ms
16 silly resolveWithNewModule cssnano@3.10.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/postcss-modules-local-by-default 609ms (from cache)
18 silly pacote range manifest for postcss-modules-local-by-default@^1.0.1 fetched in 612ms
19 silly resolveWithNewModule postcss-modules-local-by-default@1.2.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/postcss-value-parser 650ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/css-selector-tokenizer 653ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/postcss-modules-values 652ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/postcss-modules-extract-imports 654ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/lodash.camelcase 657ms (from cache)
25 silly pacote range manifest for postcss-value-parser@^3.3.0 fetched in 658ms
26 silly resolveWithNewModule postcss-value-parser@3.3.0 checking installable status
27 silly pacote range manifest for css-selector-tokenizer@^0.7.0 fetched in 663ms
28 silly resolveWithNewModule css-selector-tokenizer@0.7.0 checking installable status
29 silly pacote range manifest for postcss-modules-values@^1.1.0 fetched in 661ms
30 silly resolveWithNewModule postcss-modules-values@1.3.0 checking installable status
31 silly pacote range manifest for postcss-modules-extract-imports@^1.0.0 fetched in 665ms
32 silly resolveWithNewModule postcss-modules-extract-imports@1.1.0 checking installable status
33 silly pacote range manifest for lodash.camelcase@^4.3.0 fetched in 667ms
34 silly resolveWithNewModule lodash.camelcase@4.3.0 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/postcss-modules-scope 669ms (from cache)
36 silly pacote range manifest for postcss-modules-scope@^1.0.0 fetched in 671ms
37 silly resolveWithNewModule postcss-modules-scope@1.1.0 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/icss-utils 815ms (from cache)
39 silly pacote range manifest for icss-utils@^2.1.0 fetched in 817ms
40 silly resolveWithNewModule icss-utils@2.1.0 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/fastparse 213ms (from cache)
42 silly pacote range manifest for fastparse@^1.1.1 fetched in 216ms
43 silly resolveWithNewModule fastparse@1.1.1 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/cssesc 218ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/regexpu-core 222ms (from cache)
46 silly pacote range manifest for cssesc@^0.1.0 fetched in 225ms
47 silly resolveWithNewModule cssesc@0.1.0 checking installable status
48 silly pacote range manifest for regexpu-core@^1.0.0 fetched in 227ms
49 silly resolveWithNewModule regexpu-core@1.0.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/postcss-calc 255ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/has 257ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/postcss-convert-values 257ms (from cache)
53 silly pacote range manifest for postcss-calc@^5.2.0 fetched in 261ms
54 silly resolveWithNewModule postcss-calc@5.3.1 checking installable status
55 http fetch GET 304 https://registry.npmjs.org/postcss-colormin 261ms (from cache)
56 http fetch GET 304 https://registry.npmjs.org/postcss-discard-duplicates 261ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/defined 262ms (from cache)
58 http fetch GET 304 https://registry.npmjs.org/autoprefixer 265ms (from cache)
59 silly pacote range manifest for has@^1.0.1 fetched in 277ms
60 silly resolveWithNewModule has@1.0.1 checking installable status
61 silly pacote range manifest for postcss-convert-values@^2.3.4 fetched in 279ms
62 silly resolveWithNewModule postcss-convert-values@2.6.1 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/postcss-discard-empty 280ms (from cache)
64 silly pacote range manifest for postcss-colormin@^2.1.8 fetched in 282ms
65 silly resolveWithNewModule postcss-colormin@2.2.2 checking installable status
66 silly pacote range manifest for postcss-discard-duplicates@^2.0.1 fetched in 282ms
67 silly resolveWithNewModule postcss-discard-duplicates@2.1.0 checking installable status
68 silly pacote range manifest for defined@^1.0.0 fetched in 286ms
69 silly resolveWithNewModule defined@1.0.0 checking installable status
70 http fetch GET 304 https://registry.npmjs.org/postcss-discard-comments 290ms (from cache)
71 silly pacote range manifest for autoprefixer@^6.3.1 fetched in 293ms
72 silly resolveWithNewModule autoprefixer@6.7.7 checking installable status
73 silly pacote range manifest for postcss-discard-empty@^2.0.1 fetched in 295ms
74 silly resolveWithNewModule postcss-discard-empty@2.1.0 checking installable status
75 silly pacote range manifest for postcss-discard-comments@^2.0.4 fetched in 305ms
76 silly resolveWithNewModule postcss-discard-comments@2.0.4 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/postcss-discard-unused 215ms (from cache)
78 silly pacote range manifest for postcss-discard-unused@^2.2.1 fetched in 218ms
79 silly resolveWithNewModule postcss-discard-unused@2.2.3 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/postcss-filter-plugins 247ms (from cache)
81 http fetch GET 304 https://registry.npmjs.org/postcss-merge-longhand 239ms (from cache)
82 http fetch GET 304 https://registry.npmjs.org/postcss-minify-font-values 239ms (from cache)
83 http fetch GET 304 https://registry.npmjs.org/postcss-merge-rules 239ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/postcss-merge-idents 242ms (from cache)
85 silly pacote range manifest for postcss-filter-plugins@^2.0.0 fetched in 253ms
86 silly resolveWithNewModule postcss-filter-plugins@2.0.2 checking installable status
87 http fetch GET 304 https://registry.npmjs.org/postcss-minify-gradients 246ms (from cache)
88 silly pacote range manifest for postcss-merge-longhand@^2.0.1 fetched in 252ms
89 silly resolveWithNewModule postcss-merge-longhand@2.0.2 checking installable status
90 silly pacote range manifest for postcss-minify-font-values@^1.0.2 fetched in 252ms
91 silly resolveWithNewModule postcss-minify-font-values@1.0.5 checking installable status
92 silly pacote range manifest for postcss-merge-rules@^2.0.3 fetched in 254ms
93 silly resolveWithNewModule postcss-merge-rules@2.1.2 checking installable status
94 http fetch GET 304 https://registry.npmjs.org/postcss-minify-params 246ms (from cache)
95 silly pacote range manifest for postcss-merge-idents@^2.1.5 fetched in 257ms
96 silly resolveWithNewModule postcss-merge-idents@2.1.7 checking installable status
97 http fetch GET 304 https://registry.npmjs.org/postcss-minify-selectors 240ms (from cache)
98 silly pacote range manifest for postcss-minify-gradients@^1.0.1 fetched in 255ms
99 silly resolveWithNewModule postcss-minify-gradients@1.0.5 checking installable status
100 silly pacote range manifest for postcss-minify-params@^1.0.4 fetched in 259ms
101 silly resolveWithNewModule postcss-minify-params@1.2.2 checking installable status
102 silly pacote range manifest for postcss-minify-selectors@^2.0.4 fetched in 255ms
103 silly resolveWithNewModule postcss-minify-selectors@2.1.1 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/postcss-discard-overridden 600ms (from cache)
105 silly pacote range manifest for postcss-discard-overridden@^0.1.1 fetched in 602ms
106 silly resolveWithNewModule postcss-discard-overridden@0.1.1 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/postcss-normalize-charset 213ms (from cache)
108 silly pacote range manifest for postcss-normalize-charset@^1.1.0 fetched in 217ms
109 silly resolveWithNewModule postcss-normalize-charset@1.1.1 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/postcss-normalize-url 284ms (from cache)
111 http fetch GET 304 https://registry.npmjs.org/postcss-ordered-values 280ms (from cache)
112 silly pacote range manifest for postcss-normalize-url@^3.0.7 fetched in 293ms
113 silly resolveWithNewModule postcss-normalize-url@3.0.8 checking installable status
114 silly pacote range manifest for postcss-ordered-values@^2.1.0 fetched in 290ms
115 silly resolveWithNewModule postcss-ordered-values@2.2.3 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/postcss-reduce-initial 299ms (from cache)
117 http fetch GET 304 https://registry.npmjs.org/postcss-reduce-idents 303ms (from cache)
118 http fetch GET 304 https://registry.npmjs.org/postcss-reduce-transforms 300ms (from cache)
119 silly pacote range manifest for postcss-reduce-initial@^1.0.0 fetched in 304ms
120 silly resolveWithNewModule postcss-reduce-initial@1.0.1 checking installable status
121 silly pacote range manifest for postcss-reduce-idents@^2.2.2 fetched in 307ms
122 silly resolveWithNewModule postcss-reduce-idents@2.4.0 checking installable status
123 http fetch GET 304 https://registry.npmjs.org/postcss-unique-selectors 292ms (from cache)
124 http fetch GET 304 https://registry.npmjs.org/postcss-svgo 301ms (from cache)
125 silly pacote range manifest for postcss-reduce-transforms@^1.0.3 fetched in 305ms
126 silly resolveWithNewModule postcss-reduce-transforms@1.0.4 checking installable status
127 silly pacote range manifest for postcss-unique-selectors@^2.0.2 fetched in 300ms
128 silly resolveWithNewModule postcss-unique-selectors@2.0.2 checking installable status
129 silly pacote range manifest for postcss-svgo@^2.1.1 fetched in 310ms
130 silly resolveWithNewModule postcss-svgo@2.1.6 checking installable status
131 http fetch GET 304 https://registry.npmjs.org/postcss-zindex 302ms (from cache)
132 silly pacote range manifest for postcss-zindex@^2.0.1 fetched in 304ms
133 silly resolveWithNewModule postcss-zindex@2.2.0 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/caniuse-db 207ms (from cache)
135 silly fetchPackageMetaData error for caniuse-db@^1.0.30000634 Unexpected end of input at 1:142776
135 silly fetchPackageMetaData 0000492","directories":{},"dist":{"shasum":"944fd04e80a3e3f62c9146c55
135 silly fetchPackageMetaData                                                                      ^
136 http fetch GET 304 https://registry.npmjs.org/normalize-range 273ms (from cache)
137 http fetch GET 304 https://registry.npmjs.org/browserslist 273ms (from cache)
138 http fetch GET 304 https://registry.npmjs.org/num2fraction 281ms (from cache)
139 silly pacote range manifest for normalize-range@^0.1.2 fetched in 282ms
140 silly resolveWithNewModule normalize-range@0.1.2 checking installable status
141 silly pacote range manifest for browserslist@^1.7.6 fetched in 284ms
142 silly resolveWithNewModule browserslist@1.7.7 checking installable status
143 silly pacote range manifest for num2fraction@^1.2.2 fetched in 287ms
144 silly resolveWithNewModule num2fraction@1.2.2 checking installable status
145 verbose stack SyntaxError: Unexpected end of input at 1:142776
145 verbose stack 0000492","directories":{},"dist":{"shasum":"944fd04e80a3e3f62c9146c55
145 verbose stack                                                                      ^
145 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
145 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
145 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
145 verbose stack     at <anonymous>
145 verbose stack     at process._tickCallback (internal/process/next_tick.js:169:7)
146 verbose cwd /Users/theinvensi/development/escuelaRapozo/www
147 verbose Darwin 16.6.0
148 verbose argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "i" "css-loader"
149 verbose node v8.1.3
150 verbose npm  v5.0.3
151 error Unexpected end of input at 1:142776
151 error 0000492","directories":{},"dist":{"shasum":"944fd04e80a3e3f62c9146c55
151 error                                                                      ^
152 verbose exit [ 1, true ]
`

**Comment by michael-ciniawsky** [comment]
> 6 silly install readLocalPackageData
> 7 http fetch GET 304 https://registry.npmjs.org/css-loader 1100ms (from cache)

npm <= v5.0.0  => `$ (sudo) npm cache clean && rm -rf node_modules`
npm >= v5.0.0  => `$ (sudo) npm cache clean --force  && rm -rf node_modules`

In case you recently updated to node `v8.0.0` and therefore npm `v5.0.0` your 'old' npm cache is dirty :)

**Comment by michael-ciniawsky** [comment]
Feel free to reopen if still regressions 😛
