### ISSUE TITLE
Module not found: Error: Can't resolve 'evp_bytestokey'

### ISSUE THREAD

**Issue by sharibkhan** [webpack-contrib/css-loader#574]
Hi,
I have installed the soap(npm install soap)  but when using   soap (import Soap from 'soap';)
its giving the error. Please help me i am stuck on this point.

WebConfig.js
var path = require('path');
var webpack = require('webpack');

module.exports = {
 entry: {
   app: './js/app.js',
   app1:'./js/app1.js',
 },
 output: {
  path: __dirname,
  filename: '[name].bundle.js'
 },
 watch: true,
 module: {
  loaders: [
   {
    test: /.jsx?$/,
    loader: 'babel-loader',
    exclude: /node_modules/,
    query: {
     presets: ['es2015', 'react']
    }
   }

  ]
 } ,
   node: {
  //   console: 'empty',
     fs: 'empty',
     net: 'empty',
     tls: 'empty'
   }
};﻿
package.json
{
  "name": "reactjsconnectwithapi",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "babel": "babel",
    "webpack": "webpack",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "sharib",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "es6-promise": "^4.1.1",
    "mobservable-react-devtools": "^3.0.1",
    "mobx": "^3.2.0",
    "mobx-react": "^4.2.2",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "soap": "^0.19.2",
    "superagent": "^3.5.2",
    "webpack": "^3.0.0"
  },
  "devDependencies": {},
  "description": ""
}
Thanks & Regards
sharib

**Comment by michael-ciniawsky** [comment]
@sharibkhan Please use Stackoverflow or the like for these kind of support questions, your issue doesn't even relate to this repo (**`css-loader`**) 😛
