### ISSUE TITLE
Calling wsdl API by ReactJS.

### ISSUE THREAD

**Issue by sharibkhan** [webpack-contrib/css-loader#575]
Hi, 
Thanks in advance for help :).. 
I am trying to call wsdl from ReactJS but when i am trying to use XMLHttpRequest and load my API xmlhttp.open('POST', 'localhost:50065/Adjuster.svc?wsdl', true); its giving bad error 400. 
And when trying to use SOAP,I have install soap by npm install soap but when using the soap (import Soap from 'soap';) its giving following error. 
ERROR in ./node_modules/browserify-cipher/browser.js Module not found: Error: Can't resolve 'evp_bytestokey'. 
Please help me i am stuck on this point.

**Comment by TrySound** [comment]
@sharibkhan I guess it's wrong repository.
