### ISSUE TITLE
CSSLint reporting lint error "Expected RPAREN" on all lines with class declarations

### ISSUE THREAD

**Issue by adeleke-togun** [webpack-contrib/css-loader#577]
Example code snippet:
```
:local(.card) {
  border-top: 1px solid #bdbdbd;
 }
```
will return Expected RPAREN at line 1, col 8.

**Comment by evilebottnawi** [comment]
@adeleke-togun `css-loader` and `CSSLint` difference project, it is related to `CSSLint`. Also your can use more modern linter `stylelint` (https://stylelint.io/)

**Comment by adeleke-togun** [comment]
@evilebottnawi Thank you.
