### ISSUE TITLE
css-loader is incompatible with file-loader@^1.0.0

### ISSUE THREAD

**Issue by Kovensky** [webpack-contrib/css-loader#585]
`css-loader` [is rewriting](https://github.com/webpack-contrib/css-loader/blob/v0.28.4/lib/loader.js#L94-L102) `url('./relative-path')` entries by using `require('./relative-path')`; however, `file-loader` now produces ES modules. This causes the url's contents to _actually_ become `[object Object]` at runtime.

See https://github.com/webpack-contrib/file-loader/issues/181.

**Comment by sgehrman** [comment]
Just got autoupdated to file-loader 1.1.0 and have to revert because of this incompatibility.  Please fix soon.

**Comment by sgehrman** [comment]
file-loader 1.1.4 fixed the issue.

**Comment by evilebottnawi** [comment]
@sgehrman yep, thanks
