### ISSUE TITLE
update the readme to state that style-loader needs to be installed separately

### ISSUE THREAD

**Issue by Pau1fitz** [webpack-contrib/css-loader#587]
Currently the Readme file explains how to set up the `webpack.config.js` file. 

It states that you need to add both  `[ 'style-loader', 'css-loader' ]` to the module.exports object. I believe it would be helpful to add a note explaining that it is required to install the `style-loader`  separately. Something really small but I believe it may assist people with unnecessary confusion in thinking that their code isn't working. See question [here](https://stackoverflow.com/questions/45434353/webpack-and-react-recognise-css-class-names).

I am happy to update the readme if people agree that it would be helpful.

**Comment by michael-ciniawsky** [comment]
This is more a webpack specific thing (How does the loader chain work), for e.g using `css-loader` with `extract-text-webpack-plugin` doesn't require `style-loader`. The cognitive 'overhead'  to install each loader/plugin separately is mandatory to understand in general. The README example(s) is just the most common combination for CSS (`style-loader/extract-text-webpack-plugin`) and focuses on the module itself

**Comment by Pau1fitz** [comment]
@michael-ciniawsky fair enough! 👍
