### ISSUE TITLE
Doesn't export values when NODE_ENV is set as production

### ISSUE THREAD

**Issue by VsevolodTrofimov** [webpack-contrib/css-loader#588]
BUG

**What is the current behavior?**
When NODE_ENV is set to development 
`@value pixiCanvasSize #{$pixi-canvas-size}` works
Where `$pixi-canvas-size` is Sass variable

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const cssLoader = {
    loader: 'css-loader',
    options: {
      import: false,
      modules: true,
      localIdentName: '[hash:base64:5]',
      minimize: true
    }
  }
```
//story.js
`import styles from './story.sass'`

//story.sass
`@value pixiCanvasSize #{$pixi-canvas-size}`

`styles.pixiCanvasSize` will return undefined

**What is the expected behavior?**
`styles.pixiCanvasSize` is defined regardless the  value on `process.env.NODE_ENV`

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

Windows 10 pro
Node v7.3.0
Webpack 2.6.1

**Comment by evilebottnawi** [comment]
@VsevolodTrofimov can your provide minimum reproducible test repo?

**Comment by VsevolodTrofimov** [comment]
Sure, wait a bit

**Comment by VsevolodTrofimov** [comment]
Ok, I'm sorry this is `postcss-csso` issue
