### ISSUE TITLE
Failing to inlcude any css

### ISSUE THREAD

**Issue by YellowSmiley** [webpack-contrib/css-loader#591]
Updated and install css-loader and style-loader via npm using `npm i -S` and `npm install --save-dev` but neither seem to include any of my CSS on build.

My Webpack module config looks like below:

```
module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ['es2015', 'react', 'stage-0']
        }
      },
      {
        test: /\.css$/,
        loader:'style!css!'
      }
    ]
  },
```

I've also tried adding the following rules and even added file-loader to see if that is required:

```
rules: [
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }
    ]
```

None of the above works - No errors are thrown but no CSS is present in the build directory. Any help please?

**Comment by YellowSmiley** [comment]
It is also worth noting I am expecting 3 CSS files to be included: Bootstrap from node_modules and my 2 css files which are imported:

```
import '../App.css';
import '../Hamburgers.css';
```

**Comment by evilebottnawi** [comment]
@YellowSmiley please create minimum reproducible test repo, thanks!

**Comment by YellowSmiley** [comment]
Turned out it was working the console was just throwing errors saying .css files were not included!
