### ISSUE TITLE
body style is applied, but h1, .awesome are both can't !  

### ISSUE THREAD

**Issue by anlexN** [webpack-contrib/css-loader#594]
![1](https://user-images.githubusercontent.com/8686739/29452550-54824524-8439-11e7-8b88-9b3ffe45648a.PNG)
![2](https://user-images.githubusercontent.com/8686739/29452551-54858824-8439-11e7-9200-b99358c7569b.PNG)
![3](https://user-images.githubusercontent.com/8686739/29452553-54882b06-8439-11e7-8ac0-fcea20010785.PNG)
![4](https://user-images.githubusercontent.com/8686739/29452554-548bacae-8439-11e7-94e6-214b6868a22f.PNG)
![5](https://user-images.githubusercontent.com/8686739/29452552-54878caa-8439-11e7-9a14-99f5cde6608b.PNG)
![6](https://user-images.githubusercontent.com/8686739/29452558-54f23df2-8439-11e7-9c35-ef2c3937e5bd.PNG)
![7](https://user-images.githubusercontent.com/8686739/29452556-54ac694e-8439-11e7-9f7c-c7c11e9c4694.PNG)
![8](https://user-images.githubusercontent.com/8686739/29452555-548f4256-8439-11e7-96c6-c64ca5e88b92.PNG)
![10](https://user-images.githubusercontent.com/8686739/29452557-54b7a340-8439-11e7-9333-579f8d4af463.PNG)

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

**Comment by evilebottnawi** [comment]
@anlexN please use issue template and provide minimum reproducible test repo, it is difficult to analyze your problem using screenshots, thanks!
