### ISSUE TITLE
Running into issues using webpack in node

### ISSUE THREAD

**Issue by wesmelon** [webpack-contrib/css-loader#596]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently, I am experiencing a different webpack output when using CLI compared to node.

A sample repo is here:
https://github.com/wesmelon/troubleshoot_css_loader

Using CLI works perfectly, the styles are injected into head, and the page is styled. When I use node to import webpack and run the compiler, I find that in the built output, the webpack and css-loader doesn't seem to be playing nicely.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. start up a project with loading css
2. have it buildable using cli (webpack --config webpack.config.js)
3. expect the output to be styled correctly
4. in the same project, create a node script that builds using require('webpack') using the same config, run the compiler on the project
5. expect the output to be styled correctly (and same exact bundle.js as cli)

https://github.com/wesmelon/troubleshoot_css_loader
this repo demonstrates a basic example of what i am encountering

**What is the expected behavior?**
I expect both the CLI and node webpack output to be the same.

**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
- webpack: 3.5.5
- node: 8.4.0
- os: macOS sierra (10.12.6)

**Comment by wesmelon** [comment]
Another note: if using ExtractTestPlugin with options:
            use: ExtractTextPlugin.extract({
                fallback: "style-loader",
                use: "css-loader"
            })
I do not encounter the error of not having my styles injected.

**Comment by evilebottnawi** [comment]
@wesmelon Thanks for issue, seems bug

**Comment by evilebottnawi** [comment]
@wesmelon maybe related to https://github.com/webpack-contrib/css-loader/issues/676
