### ISSUE TITLE
assertRaw called with too many arguments.

### ISSUE THREAD

**Issue by no1melman** [webpack-contrib/css-loader#598]
I know this isn't a huge issue, but just thought if it isn't intentional then probably needs to be cleaned up.

https://github.com/webpack-contrib/css-loader/blob/e16bdeb0ec404861c3799c069e56fb0147006075/test/helpers.js#L82

And actually examining that function closer, it takes `modules` as a parameter and only asks for it so it can pass it onto `assertRaw` which doesn't require it. Therefore, making `modules` completely redundant anyway.

**Comment by evilebottnawi** [comment]
@no1melman thanks, PR welcome :+1:

**Comment by no1melman** [comment]
Okay will do!
