### ISSUE TITLE
absolute paths truncate file names

### ISSUE THREAD

**Issue by davicho** [webpack-contrib/css-loader#600]
**Do you want to request a *feature* or report a *bug*?**
Not sure (this used to work, new update now did away with it I think).

**What is the current behavior?**
Latest css-loader loads "full" paths and truncates actual file name (if too long)

**What is the expected behavior?**
I just to see the file name in my inspector window: "**_bootstrap.scss**" and now it's "**/Users/x/x/x/x/x/_b...rap.scss**" (<--- need to hover that in order to see file name).

**If this is a feature request, what is motivation or use case for changing the behavior?**
This use to work in previous versions - I think you have now done away with it but I think it's useful. This will remove the extra step of the developer needing to hover over the abs path to see the actual file he/she needs to work with.

<img width="218" alt="truncated-path" src="https://user-images.githubusercontent.com/1090555/29881702-53566d6c-8d79-11e7-9174-ece10b60b6e0.png">

OR, is there an options I'm missing?

**Comment by evilebottnawi** [comment]
@davicho Sorry for delay, duplicate https://github.com/webpack-contrib/css-loader/issues/652 . Thanks!
