### ISSUE TITLE
[v0.28.6] TypeError: options.resolve is not a function

### ISSUE THREAD

**Issue by ZRogerson** [webpack-contrib/css-loader#602]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The latest update breaks at processCss.js:88:27 with the titled error.

**If the current behavior is a bug, please provide the steps to reproduce.**
options.resolve not being provided to parserPlugin

**Comment by michael-ciniawsky** [comment]
@ZRogerson Are you using `localsLoader` in your setup?

**Comment by ZRogerson** [comment]
No, I'm unaware of localsLoader.
