### ISSUE TITLE
import is not working properly

### ISSUE THREAD

**Issue by iiison** [webpack-contrib/css-loader#606]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I am using Webpack to create bundles for my react application. I am using `postcss` and `css-loader` to load CSS files. In my app, css import is not working properly. I am trying to import every thing in my `Main.css` file, but webpack throws error by saying:
```bash
./node_modules/css-loader?{"importLoaders":1,"modules":true,"minimize":{"calc":true,"colormin":true,"core":true,"discardDuplicates":true,"discardOverridden":true,"mergeLonghand":true,"minifyFontValues":true,"minifyParams":true,"normalizeCharset":true,"orderedValues":true,"reduceDisplayValues":true,"styleCache":true,"uniqueSelectors":true,"convertValues":true,"discardComments":true,"discardEmpty":true,"discardUnused":true,"filterPlugins":true,"mergeIdents":true,"mergeRules":true,"minifySelectors":true,"normalizeString":true,"normalizeUrl":true,"reduceBackgroundRepeat":true,"reduceTransforms":true},"sourceMap":true,"camelCase":true,"localIdentName":"[path][name]---[local]---[hash : base64 : 5]"}!./node_modules/postcss-loader/lib!./app/styles/main.css
        Module build failed: Error: Failed to find 'vendor/reset'
            in [ 
                /Users/bharat/Documents/redmart-repo/Partner-Portal-V2/app/styles
            ]
            at /Users/bharat/Documents/redmart-repo/Partner-Portal-V2/node_modules/postcss-import/lib/resolve-id.js:48:11
         @ ./app/styles/main.css 4:14-133 18:2-22:4 19:20-139
         @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./app/styles/main.css
```
<br/>
<br/>

Here is the webpack configs to load CSS([full config link](https://gist.github.com/iiison/184edf00ff01da15b9f3905b2790d555#file-webpack-config-babel-js)):
```js
{  
  test:/\.css$/,
  exclude:/node_modules/,
  include:`${PATHS.styles}/`,
  use:[  
    {  
      'loader':'style-loader'
    },
    {  
      'loader':'css-loader',
      options:{  
        importLoaders:1,
        modules:true,
        minimize:cssNanoConfigs,
        sourceMap:!isProd,
        camelCase:true,
        localIdentName:'[path][name]---[local]---[hash : base64 : 5]'
      }
    },
    {  
      loader:'postcss-loader'
    }
  ]
}
```

<br/>
<br/>

Here is the [link to postcss config file](https://gist.github.com/iiison/184edf00ff01da15b9f3905b2790d555#file-postcss-config-css)

Directory structure of my app is:

- app/
    - js/
    - styles/
      - base/
          - _base.css
          - _reset.css
          - _variables.css
        - vendor/
            - _reset.css
        - main.css

<br/>
<br/>

**What is the expected behavior?**
CSS file should be resolved and webpack shouldn't throw error.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
[Link to package.json](https://gist.github.com/iiison/184edf00ff01da15b9f3905b2790d555#file-package-json)

**Comment by michael-ciniawsky** [comment]
`precss` ships with `postcss-partial-import`, any `postcss-import` plugin should be avoided in webpack context, since only `css-loader` handles `@import`'s in a 'correct' way `@import "file.css";` => `require("css-loader!postcss-loader!/* <= importLoaders */./file.css")`. Personally I recommend to selectively pick plugins you need from `precss` (`package.json`)  and install them separately. It's just a plugin wrapper (package). Be careful with stuff like `postcss-assets` aswell since assets resolving is normally handled by `css-loader` aswell. Use a simple `postcss.config.js` (`autoprefixer`, `postcss-nested`) at the beginning and enhance, when the initial strcuture works
