### ISSUE TITLE
Is it possible to wrap class names?

### ISSUE THREAD

**Issue by IvanKalinin** [webpack-contrib/css-loader#608]
Hi there.
There is a situation. I need to integrate react app in existed WP website. But react's style override WP's style.
To avoid overriding styles I want add specific classname to react root element (isolate react app), but in that case css modules class names has less specificity than default, normalized and/or bootstrap styles.
e.g. 
`.specificClassname label` has more specificity than `.Label__label_hash64`.

So I need option to add wrapper classname before each compiled classname like
`.specificClassname .Label__label_hash64`

How could I do that?

**Comment by TrySound** [comment]
https://github.com/MadLittleMods/postcss-increase-specificity

**Comment by IvanKalinin** [comment]
Yeah. That plugin seems helpful, but if I add it in **postcss.config.js** it adds `.my-root` only to global rules.

```
module.exports = {
  plugins: {
    autoprefixer: {
      browsers: ['last 2 versions', 'not ie < 11'],
    },
    'postcss-increase-specificity': {
      stackableRoot: '.my-root',
    },
  },
};

```

in **webpack.config.js** case in transform `.my-root` to `Component__my-root_hash64`
```
use: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: [
    {
      loader: 'css-loader',
      options: {
        importLoaders: 2,
        modules: true,
        localIdentName: '[name]__[local]_[hash:base64:5]',
      },
    },
    {
      loader: 'sass-loader',
      options: {
        includePaths: [
          path.join(__dirname, './components-lib/src/assets/styles'),
        ],
      },
    },
    {
      loader: 'sass-resources-loader',
      options: {
        resources: [
          './components-lib/src/assets/styles/_variables.scss',
          './components-lib/src/assets/styles/_mixins.scss',
        ],
      },
    },
    {
      loader: 'postcss-loader',
      options: {
        plugins: () => [
          increaseSpecificity({ stackableRoot: '.my-root' }),
        ],
      },
    },
  ],
}),
```

**Comment by evilebottnawi** [comment]
@IvanKalinin Use `postcss-loader` above `sass-loader`. First compile `sass/scsc`, then increase specificity when `css-loader` with `css` modules
