### ISSUE TITLE
Possible to have absolute imports for `@import`?

### ISSUE THREAD

**Issue by aronwoost** [webpack-contrib/css-loader#611]
Instead of having
```
@import '../../components/css/settings.css';
```

I'd like to import with

```
@import 'components/css/settings.css';
``` 
I understand that this is currently not possible with css-loader as it does not allow custom resolver paths. Behavior could be "hacked" by using [alias](https://github.com/webpack-contrib/css-loader#alias) but it only supports `url()` not `@import`.

Are there any other ways of implementing it?

**Comment by aronwoost** [comment]
(happy to PR something, if I get pointed in the right direction)

**Comment by frenzzy** [comment]
You just need to use [resolve.modules](https://webpack.js.org/configuration/resolve/#resolve-modules) option in your webpack config.

**Comment by aronwoost** [comment]
Are you sure that works for `@imports` in css files? Tried that, but didn't work (maybe error on my side).

**Comment by frenzzy** [comment]
Are you sure your imports in css files handled by css-loader and not by postcss plugins such as postcss-import? See [css-loader url option](https://github.com/webpack-contrib/css-loader#options).

**Comment by aronwoost** [comment]
@frenzzy Thanks for the response.

Yes, they are handles by css-loader.

I created a [tiny little demo repo](https://github.com/aronwoost/webpack-css-loader-import-test). Bottom line: I think that absolute css imports to work for `require('test.css')` in JS, but they do not for `@import 'test.css'` in css files.

**Comment by aronwoost** [comment]
@frenzzy I changed the issue title to be more explicit re `@import`.

Can you confirm the behavior? Or is there an error on my side?

**Comment by aronwoost** [comment]
Just to wrap this up. I made it work in [this commit](https://github.com/aronwoost/webpack-css-loader-import-test/commit/bc1d76b1b47e88311eafdfa1c10e0b3935618561) using `postcss-import`.

**Comment by andrewMuntyan** [comment]
so, as i understand `css-loader` is not able to `@import` using absolute paths and i should use `postcss-import` for this purpose? i have ` resolve.modules ` in my webpack config but can't use `@import 'shared/styles/_colors.css';` in css file :(

**Comment by kalpeshsingh** [comment]
> Just to wrap this up. I made it work in [this commit](https://github.com/aronwoost/webpack-css-loader-import-test/commit/bc1d76b1b47e88311eafdfa1c10e0b3935618561) using `postcss-import`.

This. Is. What. I was Looking for.
