### ISSUE TITLE
CleanCSS instead CSSNano

### ISSUE THREAD

**Issue by radeno** [webpack-contrib/css-loader#614]
**Do you want to request a *feature* or report a *bug*?**
Feature

css-loader using css-nano 3 as minifier. But css-nano has so many dependencies.
clean-css looks like solid alternative https://github.com/jakubpawlowicz/clean-css

Do you expect switch to version 4 in the future?

**Comment by TrySound** [comment]
@radeno Dependencies means it's modular and every piece per one feature.  It doesn't mean cssnano is not solid. And still css-loader 1.0 won't have minifier out of the box, so you can prefer anything.

**Comment by radeno** [comment]
You are right, css-loader can not minify css file. But it does now.
CSS nano is dependency hell. It uses many dependencies with different versions which not anyone want to use.

CSS-nano should be used within only with postcss settings (postcss.config.js file).
There could be an option to choose minifier. By my tests css-nano and clean-css are both solid. But i dont like css-nano tons of dependencies.

There webpack module https://github.com/NMFR/optimize-css-assets-webpack-plugin has nice idea to choose own css minifier. But is also dependent on css-nano by default.

**Comment by TrySound** [comment]
@radeno You may say the same about any nodejs project. cssnano is a plugin pack, you should not care what it use under the hood. Same with babel, you can use presets which are just plugin packs with atomic plugins as dependencies.
