### ISSUE TITLE
Error: Module build failed: Unknown word (5:1)

### ISSUE THREAD

**Issue by Pawlarius** [webpack-contrib/css-loader#621]
This only happens when i tried to run unit test..
I'm using "css-loader": "^0.28.7"

ERROR in ./node_modules/css-loader!./node_modules/vue-style-loader!./node_modules/css-loader?{"minimize":false}!./src/assets/css/main.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../node_modules/css-loader/index.js?{\"minimize\":false}!./main.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../../node_modules/vue-style-loader/lib/addStylesClient.js")("649d00aa", content, false);

My webpack configuration
`
{
       test: /\.css$/,
        loader: ['style-loader', 'css-loader']
      }
`

 Inside my main.css file, only this 
`
.margin-auto{
  margin: auto;
}
`
I import this css file inside style tags,
`
<style>
  @import '../assets/css/main.css'
</style>
`

It is working fine when running in dev env, but when running default unit test generated from webpack, this happened. What went wrong :(

**Comment by evilebottnawi** [comment]
@Pawlarius can you create minimum reproducible test repo?

**Comment by mkMoSs** [comment]
I have the same issue, although it's not during unit testing, is while I try to build it.  #617

**Comment by evilebottnawi** [comment]
@Pawlarius what tests do you mean?

**Comment by dm-bishnoi** [comment]
same issue here
