### ISSUE TITLE
HMR with css modules reloads page, unless dummy function in accepts

### ISSUE THREAD

**Issue by fend25** [webpack-contrib/css-loader#624]
I want to report a bug.

#### Current behaviour
When the loader is configured with `{modules: true}`, any change of css file causes page reload, not css hot replacement. The app is running on webpack-dev-server.

#### Steps to reproduce
I made a repo: https://github.com/fend25/css-modules-hot-reload-test
steps:
1. git clone
2. yarn
3. npm start
4. change `src/styles.css` file (for example, change color of `.test` class)
5. look in browser console and ensure that the page didn't reload
6. comment out the line with `module.hot.accepts` in the `src/index.js` file
7. repeat step 4 (change css)
8. repeat step 5 (look in console) and ensure that page reloads

Initial config and file structure is taken from official webpack docs: https://webpack.js.org/guides/hot-module-replacement/#hmr-with-stylesheets

#### Strange workaround
If I add some dummy function to 'module.hot.accepts', it starts work properly as it should.
Example:
```js
if (module.hot) module.hot.accept(['./styles.css'], () => {})
```

#### Expected behavior
I think it should perform HMR without affecting module.hot.accepts manually.

#### Software versions
node@8.7.0
webpack@3.8.1
webpack-dev-server@2.9.3
css-loader@0.28.7
style-loader@0.19.0

**Comment by evilebottnawi** [comment]
@fend25 problem still exists?

**Comment by fend25** [comment]
@evilebottnawi I will check again and provide more info a bit later

**Comment by fend25** [comment]
@evilebottnawi yes, it does. When I comment out the HMR line in the `src/index.js`, changing of the `src/styles.css` causes page reload, not HMR.

**Comment by evilebottnawi** [comment]
@fend25 can you create minimum reproducible test repo?

**Comment by fend25** [comment]
@it's in the first message here: https://github.com/fend25/css-modules-hot-reload-test

**Comment by evilebottnawi** [comment]
@fend25 expected because `style-loader` already do this logic, if you want use own hmr logic don't use `style-loader` for this module.
