### ISSUE TITLE
Way to skip localIdentName on files from node_modules

### ISSUE THREAD

**Issue by PedroEsperanca** [webpack-contrib/css-loader#628]
I'm looking for a way to not `localIdentName` files `@imported` from **node_modules** with **css-loader**.

**Comment by max-mykhailenko** [comment]
I have the same problem. How to resolve it in the smart way without duplicating loaders for different scopes?

**Comment by jeezlee** [comment]
same problem

**Comment by michael-ciniawsky** [comment]
Please reopen this in `css-modules/postcss-icss-selectors`  instead, I will triage it there since CSS Modules will be removed from `css-loader` soon. Maybe I can add a filter option for file paths within the plugin...

**Comment by lynndylanhurley** [comment]
same problem

**Comment by lynndylanhurley** [comment]
same problem. this is the first google result for this issue - if it's been resolved can someone pls point to a fix?
