### ISSUE TITLE
Flexible url resolving behavior

### ISSUE THREAD

**Issue by SerikDM** [webpack-contrib/css-loader#630]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
urls are resolved or not. one global flag via config.

**What is the expected behavior?**
allow some urls to pass unresolved:
url(media/image.jpg')
url(./media/image.jpg')
url(/media/image.jpg')

some prefix would be great:
url(!/media/image.jpg')

**If this is a feature request, what is motivation or use case for changing the behavior?**
can't make specific urls that will respect header 'base' meta. root urls do not respect 'base' meta at all.
in case if app hosted in subdirectory like domain.com/forum

**Comment by DostalTomas** [comment]
Hello, i've same problem. Adding this feature would be great.
BTW, could you recommend me some workaround for this case?

**Comment by michael-ciniawsky** [comment]
This will happen in `v1.0.0` (#655)

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/css-loader/pull/655
