### ISSUE TITLE
Unhelpful Error Message for Invalid Class Name

### ISSUE THREAD

**Issue by colin-c** [webpack-contrib/css-loader#633]
## Summary

Error message emitted for invalid class name is very unhelpful.

The error appears to be emitted from a [different module](https://github.com/css-modules/postcss-icss-composes/blob/45adcfb557a81ab9f5012bbfd93f5ef1d74a37a3/src/index.js#L19), but css-loader should probably check the validity of rules first and spit out a more helpful error message for debugging.

### Reproduction

* Write rule for a class that begins with a number (invalid CSS) that includes composition, example:
```css
.3test {
  color: #333;
  composes: other-class from 'some-file.css'
}
```

* Run a webpack build with CSS Modules enabled in css-loader

### Current Behavior

In the output from the webpack build, the unhelpful error appears
```
Composition is only allowed when selector is single :local class name not in ".3test"
```

### Expected Behavior

An error message that would be helpful for debugging should appear in the output. Something like:
```
Class names must not begin with a number; selector ".3test" is invalid
```

**Comment by evilebottnawi** [comment]
@colin-c Thanks for issue, we use [postcss-icss-composes](https://github.com/css-modules/postcss-icss-composes) for `composes` https://github.com/css-modules/postcss-icss-composes/blob/master/src/index.js#L43, please recreate issue there.
