### ISSUE TITLE
Who can help me,“localIdentName” does not work in my code,I do not know why

### ISSUE THREAD

**Issue by wanliyunyan** [webpack-contrib/css-loader#634]
in my .tsx file,
 `import "./BasicLayout.less";`
```
<div className="logo">
   <Link to={"/"}>
       <h1>Ant Design Pro</h1>
    </Link>
</div>
```
in my webpack,  
` 

        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          use: [{
            loader: 'css-loader',
          }, {
            loader: 'less-loader',
          }],
          fallback: 'style-loader',
        }),
      }

`
in my .less file 

```
.logo {
  height: 64px;
}
```

now ,**these code can work normally,but if i want to use "localIdentName"**
 ```
 
        test: /\.less$/,
        use: ExtractTextPlugin.extract({
          use: [{
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[path][name]__[local]--[hash:base64:5]',
            },
          }, {
            loader: 'less-loader',
          }],
          fallback: 'style-loader',
        }),

```

The style
 ```
.logo {
  height: 64px;
}
```  
**does not appear on the page，when  i delete** 
```
options: {
              modules: true,
              localIdentName: '[path][name]__[local]--[hash:base64:5]',
            },
```
**The style appears on the page again.......**
Not only .less file has this problem, but also .css file 
I really have no ideal, who can help me？？？？？？

**Comment by d3viant0ne** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support though you may also inquire in [Webpack Gitter](https://gitter.im/webpack/webpack). The issue tracker is for bug reports and feature discussions. See also our CONTRIBUTING guidelines.

**Comment by michael-ciniawsky** [comment]
```diff
- import "./BasicLayout.less";
+ import styles from "./BasicLayout.less"

const component = (props) => (
+   <div className={styles.container}></div>
)
```

**Comment by wanliyunyan** [comment]
@d3viant0ne thanks！I am a noob, did not really understand the issue......

**Comment by wanliyunyan** [comment]
@michael-ciniawsky thanks！

**Comment by badaljain** [comment]
I have a question, if we use localIndentname, this breaks the css/classes defined and used by some library for example antd. How can we use both:

import './style.css'
import style from './style.css'

Thanks

**Comment by wanliyunyan** [comment]
@badaljain if you use antd,ni could code like this 

`
{
  "plugins": [
    ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }] 
  ]
}
`

but,i do not kown how to use both

**Comment by badaljain** [comment]
Hi @wanliyunyan,

Even without this, I am able to use antd properly but I want to support both the import formats.

Thanks for your time :)

**Comment by elisechant** [comment]
@badaljain for the case 

`import './style.css'`

there's a helper you can use like this: 

style.css

```
:global #app {
  border: blue;
}
```

https://github.com/css-modules/css-modules#exceptions

**Comment by badaljain** [comment]
Hi @elisechant,

This approach will work with just **import './style.css'** format right?
Actually, I want to use something like this:

1. (possible when I use localIndentName)
import style from './style.css'

className= {style.someClass}

2. and also support(possible when I remove localIndentName):
import './style.css'

className={someClass}

Thanks,
Badal

**Comment by jbbpatel94** [comment]
i am also facing same issue
