### ISSUE TITLE
Min length of localIdentName hash name

### ISSUE THREAD

**Issue by amerllica** [webpack-contrib/css-loader#637]
I use `localIdentName` in my webpack config file. I set the value as `[hash:base64:3]` but I saw all of developers configs. all of them used `[hash:base64:5]` or a number for length greater than 5.

Why anybody didn't use 3 or 2, and actually when I use 3 some class names after build has same name that this situation is not good at all. because all of my styles made very bad.

some kind developer tell why a number less than 5 cause to generate some duplicated class names?

Does `hash:base64:3`  not make different class names?

and how can I do it?

Is `getLocalIdent` my solution?

**Comment by michael-ciniawsky** [comment]
https://en.wikipedia.org/wiki/MD5
https://github.com/webpack/loader-utils/blob/master/lib/getHashDigest.js#L47 

You basically answered your question yourself already => `hash` collisions due to a lack of combinations possible with e.g `length =< 3`

> Is getLocalIdent my solution?

Yes, you can pass a `{Function}` to generate your own `localIdentName` (I would avoid it)  or simply increase the `length` to be safer

```js
{
   loader: 'css-loader',
   options: {
      modules: true,
      localIdenName: env === 'development' 
        ? '[path][local]–[hash:base64:5]' // better for debugging
        : '[hash:base64]' // maxLength: 9999 no hash collisions possible
   }
}
```

**Comment by amerllica** [comment]
Thanks @michael-ciniawsky  , I calculate the possibility of conditions, it is so simple, `base64` can has 64 characters:
[a-z][A-z][0-9][-,_] so with 3 we can has `64 x 64 x 64` conditions, it means `262144` class names!!

So why it can not generate unique names? with 3 there are many collision class names conflicts.

It make me confused, I studied applied mathematics in university so this situation is not compatible with my mathematical behavior. I expect with `262144` conditions it able to make for me `262144` class names.

But just like you said it is nature of `MD5` hash system.

> I would avoid it

Undoubtedly you are right, but I insist on having 3 length because of my code compression, for this project surely I act like you but in feature I'll write a function to generate unique class names without any collision. and I believe this is lack of `localIdentName`. thanks a lot my dude @michael-ciniawsky
