### ISSUE TITLE
CSS modules being imported globally

### ISSUE THREAD

**Issue by joshanderson99** [webpack-contrib/css-loader#643]
Hi,
I'm using this syntax to import styles:

`import myStyles from 'file.css'`

but it seems the loader is processing the css file as a normal non-modularised css file and making the style definitions global.  Any style in `file.css` is applied globally.  My understanding of css modules is that isn't supposed to happen, or else how is there a means to localise styles.  Any ideas as to why this is happening?

(I'm using the latest versions of style-loader and css loader, and the relevant fragment of webpack.config is listed below:

```
      {
        test: /\.css$/,
        use: [
          "style-loader",
          {
            loader: "css-loader",
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: "[name]--[local]--[hash:base64:8]"
            }
          },
          "postcss-loader" // has separate config, see postcss.config.js nearby
        ]
      },


```
)

**Comment by michael-ciniawsky** [comment]
Could you aswell post the CSS (Result) please? Does this also happen without setting a custom `localIdentName` (`options.localIdentName`) and just `options.modules =  true` ?

**Comment by joshanderson99** [comment]
I've created a simple example below, in a button's text is coloured green.  The button style is imported but not applied explicitly to the button.  The button however is green, which implies the import has been applied globally.


**styles.css**
```
button {
  color: green; 
}
```

**app.js**
```
import styles from './styles.css'; 
...
  <button>Test</button>
```

**result**
![screenshot from 2017-12-11 14-09-41](https://user-images.githubusercontent.com/32922283/33815440-18914f58-de7d-11e7-8706-8e25c62d30e0.png)

**generated css**

This is the css as it appears in Dev Tool:

![screenshot from 2017-12-11 14-20-37](https://user-images.githubusercontent.com/32922283/33815699-28088170-de7f-11e7-8e02-0a08e17b9fa3.png)
If a style is applied explicitly to the button, the local identifiers appear:

styles.css
```
.buttonStyle {
  color: green; 
}
```

app.js
`<button className={styles.buttonStyle}>Test</button>`

result

![screenshot from 2017-12-11 14-23-44](https://user-images.githubusercontent.com/32922283/33815727-624b79fa-de7f-11e7-978a-9fe07c6c08f5.png)


**Removing localIdentName: "[name]--[local]--[hash:base64:8]**

This makes no difference in the first example with `button` selector.  But when the style (with `.buttonStyle` class) is explicitly applied to the button element, this is the result:

![screenshot from 2017-12-11 14-35-12](https://user-images.githubusercontent.com/32922283/33815919-197bb51c-de81-11e7-85d4-fa58b0b0a5b1.png)

**Comment by michael-ciniawsky** [comment]
CSS Modules don't work for/with 'native' selectors like 

```css
button { // <= HTML <button>
  color: green; 
}
```

you need to use a `.class`  selector

```diff
+ .button { // <button class="button">
  color: green; 
}
```

**Comment by joshanderson99** [comment]
Okay, thanks for your speedy response and for clarifying that matter.
