### ISSUE TITLE
Camel case for characters after numbers inconsistent with that emitted by typed-css-modules

### ISSUE THREAD

**Issue by shirakaba** [webpack-contrib/css-loader#644]
## Current behaviour

My CSS class `.border_radius_4px` is becoming exposed in webpack in camelCase as `borderRadius4Px`. However, the `typed-css-modules` project that adds typings to my CSS files so that I can auto-complete their import names produces a subtly different camel-case name `borderRadius4px` (with a lower-case 'p' at the end). As a result, the TypeScript compiler throws no errors, yet at run-time, `require()` is unable to find the right style within the webpack bundle.

## Typescript source module

```Typescript
import {borderRadius4px, borderRadiusFourPx} from "../scss/css_prebuild/generic.css";

console.log(borderRadius4px);
```

## CSS-loader options (and webpack loader rule)

```Javascript
var webpackLoaderRule = 
{
    test: /\.css$/,
    use: ExtractTextPlugin.extract({
        use: [
            {
                loader: 'css-loader',
                options: {
                    url: false,
                    namedexport: true,
                    camelcase: true,
                    modules: modules,
                    localIdentName: '[local]', // turns off mangling
                    minimize: cssNanoOptions,
                    importLoaders: 0
                }
            }
        ],
        fallback: 'style-loader'
    })
};
```

## Typescript typings generated by `typed-css-modules`

CSS:

```CSS
.border_radius_4px {
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  -ms-border-radius: 4px;
  border-radius: 4px;
}
```

Invocation:

```bash
./node_modules/.bin/tcm src/scss/css_prebuild -o src/scss/css_prebuild --camelCase
```

```Typescript
export const borderRadius4px: string;
```

## Webpack module that exports style
```Javascript
/* 11 */
/***/ (function(module, exports) {

// removed by extract-text-webpack-plugin
module.exports = {"border_radius_4px":"border_radius_4px","borderRadius4Px":"border_radius_4px"};

/***/ })
```

## Webpack module that imports style

```Javascript
/* 36 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });

var generic_css_1 = __webpack_require__(11);

console.log(generic_css_1.borderRadius4px);
/***/ })
```

## Desired behaviour

`.border_radius_4px` should be camel-cased to `borderRadius4px` rather than `borderRadius4Px` when exported, in order to match the behaviour of `typed-css-modules`, which often is used in tandem with this project.

If someone knows of a camelcase ISO-style standard for dealing with letters following numbers, then we can determine which out of `typed-css-modules` and `css-loader` is more 'right', but otherwise it would be nice for these two projects to be compatible.

**Comment by michael-ciniawsky** [comment]
That's actually an issue between `camelcase` (`typed-css-modules`) && `lodash.camelcase` (`css-loader`). No clue what's the 'correct' way here, please reopen this is in `css-modules/postcss-icss-selectors` since CSS Modules will be removed from the `css-loader` soon and the current loader won't get a change like that as it is in 'maintenance' mode
