### ISSUE TITLE
Option to only hash first class selectors

### ISSUE THREAD

**Issue by fgarcia** [webpack-contrib/css-loader#647]
**Do you want to request a *feature* or report a *bug*?**

FEATURE

**What is the current behavior?**

All nested class selectors are hashed

**If this is a feature request, what is motivation or use case for changing the behavior?**

While prototyping I use this pattern a lot. My CSS files export a single root class selector like this

```
.root {
  :global {
    .meta { ... }
    .detail { ... }
  }
```

Then my JS component looks like this
```
import Style from './Component.scss'

      <div className={Style.root}>
        <div className="meta inline bold">
        </div>
```

Without the ".global" declaration the nested class selectors will be hashed too. For me it is enough having the hash-namespacing protection in my root selector and avoid hunting the hash in my Style along using classNames()

With the `.root { global: { ... } }` trick I set things up the way I want, but an option to make this working style the default would be great.

**Comment by michael-ciniawsky** [comment]
Please reopen this issue in `css-modules/postcss-icss-selectors`  instead, I will triage it there. CSS Modules will be removed from `css-loader` soon (`v1.0.0`)
