### ISSUE TITLE
Readme on `minimize` option should inform about actual dynamic default value

### ISSUE THREAD

**Issue by jrencz** [webpack-contrib/css-loader#650]
**Do you want to request a *feature* or report a *bug*?**

Bug (documentation)

**What is the current behavior?**
In a table there's an entry saying that `minimize` is `false` by default:
https://github.com/webpack-contrib/css-loader/blob/d999f4a599b13e19d53fdd9fbd9a323fed7a101c/README.md#L102

**If the current behavior is a bug, please provide the steps to reproduce.**

The default value depends on production setting of webpack (`this.minimize` is set to true when `-p` flag is used):

https://github.com/webpack-contrib/css-loader/blob/d999f4a599b13e19d53fdd9fbd9a323fed7a101c/lib/loader.js#L46

It can be undone only by passing actual setting in a loader query:

https://github.com/webpack-contrib/css-loader/blob/d999f4a599b13e19d53fdd9fbd9a323fed7a101c/lib/processCss.js#L148

**What is the expected behavior?**

Docs should say that `minimize` has default value depending on webpack production setting.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Rationale:
I'm trying to adopt browserslist configuration using shared browserslist config (introduced in v2)
css-loader depends on older version of cssnano, which has browserslist@1 as one of dependencies. I'm aware of why is that (https://github.com/webpack-contrib/css-loader/issues/535#issuecomment-303039974) and I didn't want to use baked-in cssnano anyway (I deliberately use cssnano@4.0.0-rc.2 in my project)
It turned out that css-loader does use cssnano (in particular: the postcss-merge-rules, which depends on caniuse-db@1 which, in turn depends on browserslist@1) even though I don't ask it to. Or at least I thought I'm not asking it to. In fact I did by using `-p` flag when calling `webpack`.

I spent a fair amount of time figuring that out. I feel like the docs should give better insight into that cssnano transforms are used depending on webpack config.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webapck 3.10.0
node 8.9.1
macOS 10.13.2

Related issues:
https://github.com/webpack-contrib/css-loader/issues/289

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/css-loader/issues/265 . Fell free to PR
