### ISSUE TITLE
Fonts relative path is incorrect when using file-loader outputPath option

### ISSUE THREAD

**Issue by kaluznyt** [webpack-contrib/css-loader#665]
Hello, 

I have an issue. I'm quite new to webpack, so possibly I just don't understand it yet fully. However, I'm trying to set up a project of asp+vue. Frontend using webpack. I'm using following configuration for css files and fonts:

```
   {
            test: /\.css$/,
            use: isDevBuild
              ? ["style-loader", "css-loader"]
              : ExtractTextPlugin.extract({
                  use: { loader: "css-loader", options: { minimize: true } }
                })
          },
          {
            test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
            use: {
              loader: "file-loader",
              options: {
                name: "[name].[ext]",
                outputPath: "fonts/"
              }
            }
          }
```

And it get 404 errors for fonts:
![image](https://user-images.githubusercontent.com/572605/35183727-d3e8ada8-fde2-11e7-940b-97d4613321ee.png)

As it seems it's trying to load the fonts from 'dist' folder, instead of 'dist/fonts' folder as directed in outputPath of file-loader for the fonts. 
![image](https://user-images.githubusercontent.com/572605/35183731-dedcdce8-fde2-11e7-88ea-89096c5b40d4.png)

However, when I skip the outputPath and place 'fonts/' in the name option like this:
```          {
            test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
            use: {
              loader: "file-loader",
              options: {
                name: "fonts/[name].[ext]"
              }
            }
          }
```

Then it works as expected (fonts are loaded from the dist/fonts relative path). 

![image](https://user-images.githubusercontent.com/572605/35183772-4692b2a4-fde3-11e7-9548-ec4c7f1d3111.png)

Is this a bug, or am I doing something wrong ?

I was also not quite sure if this is css-loader or style-loader responsible for the url's but I believe it's css-loader as style loader just emits the style inside style tag (that's my current understanding at least). 

Initially outputPath didn't work at all, but I found that it was a bug in version (0.9.0) of file-loader, but it was fixed in 0.10.0: 
https://github.com/webpack-contrib/file-loader/issues/108

In case you want to take a look at the code its under https://github.com/kaluznyt/vuebnb

Thanks for any hints, 
Tomasz

**Comment by theNotoriousHxc** [comment]
You can look at the `useRelativePath` option in file-loader, it may help.
https://github.com/webpack-contrib/file-loader#userelativepath

**Comment by evilebottnawi** [comment]
@kaluznyt Expected,  we have `name` (=== `publicPath`, url in browser) and `outputPath` (place where `file-loader` should be place files). Maybe releated https://github.com/webpack-contrib/file-loader/issues/160. But you are right not related to `css-loader`. Thanks!
