### ISSUE TITLE
Css-Loader / Less-Loader not working

### ISSUE THREAD

**Issue by sakthig** [webpack-contrib/css-loader#667]
This is my config: https://gist.github.com/sakthig/d8f99c4a31ca511caa8067537bededcb

It keeps throwing this error 

ERROR in ./components/layout/main.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "../vars.less";
|
| .layout {
 @ ./components/layout/sider.js 12:35-57
 @ ./routes/app.js
 @ ./routes/index.js
 @ ./index.js

I believe i have configured it properly. Please help in resolving this.

**Comment by evilebottnawi** [comment]
@sakthig Invalid configuration. Use `style-loader` -> `css-loader` -> `postcss-loader` -> `less-loader/sass-loader` (https://gist.github.com/sakthig/d8f99c4a31ca511caa8067537bededcb#file-webpack-config-js-L31 `postcss-loader` should be above `less-loader/sass-loader`). Thanks!

**Comment by leai-jiang** [comment]
I got a issue, the less-loader I had added in my project, but the code `require('style.less')` in node_modules,It reports an error like this. Could anyone help me to resolve this issue?
