### ISSUE TITLE
Font URL containing hashtag is not processed correctly

### ISSUE THREAD

**Issue by attrox** [webpack-contrib/css-loader#668]
url('./assets/fonts/ProximaNova/Mark Simonson - Proxima Nova Alt Regular-webfont.eot?#iefix') 

is processed to

url("Mark Simonson - Proxima Nova Alt Regular-webfont.e802340fb269d9d36021.eot”?#iefix).

The quotation mark is misplaced and the font is not downloaded properly by the browser.

It's working correctly once I revert back to "css-loader": "0.28.7"

**Comment by igorroch** [comment]
+

**Comment by evilebottnawi** [comment]
@attrox @igorroch problem still exists? Don't reproducible locally. Can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Close in favor, seems you have other invalid loader and/or plugin.

**Comment by igorroch** [comment]
Hey, @evilebottnawi 
Check this out https://github.com/igorroch/css-loader-issue-668

npm i
npm run build
Open index.html in chrome

I can still reproduce the problem with spaces in folder or file name. I used file loader to store font files with exact path.

p.s.: In this repo I used ttf with hash just for demo.

**Comment by alicoding** [comment]
I'm seeing similar issue here when upgraded to version 0.28.10.

In my case I'm seeing this once I upgraded:
```
  src: url(/react/FrutigerLTforBNS-Light.eot?#iefix) format("embedded-opentype"), url(/react/FrutigerLTforBNS-Light.woff2) format("woff2"), url(/react/FrutigerLTforBNS-Light.woff) format("woff"), url(/react/FrutigerLTforBNS-Light.ttf) format("truetype"), url(/react/FrutigerLTforBNS-Light.svg#Frutiger LT Light) format("svg"); }
```


and in an older version (which is working fine)
```
  src: url(/react/FrutigerLTforBNS-Light.eot?#iefix) format("embedded-opentype"), url(/react/FrutigerLTforBNS-Light.woff2) format("woff2"), url(/react/FrutigerLTforBNS-Light.woff) format("woff"), url(/react/FrutigerLTforBNS-Light.ttf) format("truetype"), url("/react/FrutigerLTforBNS-Light.svg#Frutiger LT Light") format("svg"); }
```

Notice no quote on the path there...

**Comment by bezin** [comment]
Hi there, I am experiencing the same issue with #iefix, but also with `/path/to/mask.svg#path`, when using an SVG path in clip-path. I am running version 2.1.1 (as dependency of symfony/webpack-encore).

**Comment by evilebottnawi** [comment]
update to latest version
