### ISSUE TITLE
sourceMap: true and minimize discardComments

### ISSUE THREAD

**Issue by wxlworkhard** [webpack-contrib/css-loader#671]
In loader.js file
```
if(query.sourceMap && result.map) {
	//....	
	moduleJs = "exports.push([module.id, " + cssAsString + ", \"\", " + map + "]);";
} else {
	moduleJs = "exports.push([module.id, " + cssAsString + ", \"\"]);";
}
```
 to
```
if(query.sourceMap && result.map && !query.minimize) 

```

is better

**Comment by evilebottnawi** [comment]
@wxlworkhard `discardComments` don't remove source map

**Comment by wxlworkhard** [comment]
@evilebottnawi 

![image](https://user-images.githubusercontent.com/8287140/35662531-923d5b68-0753-11e8-9995-d679da92baf2.png)

```
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJza */
```
should remove

**Comment by evilebottnawi** [comment]
@wxlworkhard cssnano should not remove source map URL

**Comment by evilebottnawi** [comment]
@wxlworkhard `sourceMappingURL` generated by `style-loader`, and `cssnano` don't remove source map
