### ISSUE TITLE
cssWithMappingToString fails when used in WebSphere Portal

### ISSUE THREAD

**Issue by Arvnox** [webpack-contrib/css-loader#674]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*.

**What is the current behavior?**
The script breaks when used inside an script portlet from WebSphere Portal.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a project in Angular 4 and use the script provided by IBM to upload it to WebSphere Portal.
The function cssWithMappingToString(item, useSourceMap) contains a variable named "content" which, in the line 63 and 66 of the file "lib/css-base.js" is called using "[content]". WebSphere Portal replaces the string "[content]" with a blank space.

**What is the expected behavior?**
To not raise an exception when used. It seems to be less impactful to change the variable name of a local variable of a javascript function.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
I'm using the lastest version of the library as of 6 of February of 2018. I'm also using the lastest version of WebSphere Portal (9).

**Comment by Arvnox** [comment]
I would suggest changing the function from this:

`function cssWithMappingToString(item, useSourceMap) {
	var content = item[1] || '';
	var cssMapping = item[3];
	if (!cssMapping) {
		return content;
	}

	if (useSourceMap && typeof btoa === 'function') {
		var sourceMapping = toComment(cssMapping);
		var sourceURLs = cssMapping.sources.map(function (source) {
			return '/*# sourceURL=' + cssMapping.sourceRoot + source + ' */'
		});

		return [content].concat(sourceURLs).concat([sourceMapping]).join('\n');
	}

	return [content].join('\n');
}`

to this:

`function cssWithMappingToString(item, useSourceMap) {
	var content_ = item[1] || '';
	var cssMapping = item[3];
	if (!cssMapping) {
		return content_;
	}

	if (useSourceMap && typeof btoa === 'function') {
		var sourceMapping = toComment(cssMapping);
		var sourceURLs = cssMapping.sources.map(function (source) {
			return '/*# sourceURL=' + cssMapping.sourceRoot + source + ' */'
		});

		return [content_].concat(sourceURLs).concat([sourceMapping]).join('\n');
	}

	return [content_].join('\n');
}`

I have briefly tested that change in my local installation.

**Comment by evilebottnawi** [comment]
Look https://github.com/webpack-contrib/css-loader/pull/675#issuecomment-365643840
