### ISSUE TITLE
Chore dependencies

### ISSUE THREAD

**Issue by the-spyke** [webpack-contrib/css-loader#679]
**Do you want to request a *feature* or report a *bug*?**

Bug. 

**What is the current behavior?**

`css-loader` depends on `postcss@5` while some other its dependencies depend on `postcss@6`. That creates a mess inside `node_modules`.

**What is the expected behavior?**

I have 2 options on my mind:

1. Lower some dependencies like `icss-utils`, so all depends on `postcss@5`.
2. Extract `postcss` into a `peer dependency` and post same issues in other dependent packages.

**Comment by evilebottnawi** [comment]
@the-spyke Thans for issue, should be solve in next major version, just wait :+1:
