### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by EhsanFahami** [webpack-contrib/css-loader#686]
Hi.
I put my problem inside the  [stackoverflow](https://stackoverflow.com/questions/49069032/reactjs-server-side-you-may-need-an-appropriate-loader-to-handle-this-file-typ) .

#### and in summary : 
I received the following error : 
```
ERROR in ./public/testStyle.css
Module parse failed: /media/ehsan/news-ssr/public/testStyle.css Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
| body {
|     background-color: red;
| }
 @ ./src/client/pages/HomeContainer.js 31:0-40
 @ ./src/client/Routes.js
 @ ./src/client/client.js

```
and css-loader config : 
```
            {
                test: /\.css$/,
                include: /node_modules/,
                use: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {modules: true, sourceMap: true}
                    }
                ]
            }
```
package versions : 
`  "webpack": "^2.7.0" ` , ` "style-loader": "^0.18.2" ` , `"css-loader": "^0.28.9"`

Note that I have researched so much and I have not reached the result, so I thought I would ask here to answer it

Thank you for your advice.

**Comment by michael-ciniawsky** [comment]
Remove the `include` as `webpack` will only apply the rule to CSS files within `node_modules` atm. `node_modules` will be included by default unless excluded explicitly via `exclude`

**Comment by EhsanFahami** [comment]
that I removed the include: /node_modules/ and I did not leave anything. Or I gave it exclude: /node-modules/ instead. but I encountered an.  ** ReferenceError: window is not defined.**

Is not this error related to css-loader?
Is this error related to nodeJS?
Where do I ask my question to be solved?

**Comment by michael-ciniawsky** [comment]
> Is not this error related to css-loader?

Seem unrelated

>Is this error related to nodeJS?

Nope, it's a `BuildError` somewhere, since you intend to run the code in the browsers

> Where do I ask my question to be solved?

StackOverflow {:label: webpack}
Gitter `webpack/webpack`

**Comment by EhsanFahami** [comment]
@michael-ciniawsky I thank you very much for your guidance
