### ISSUE TITLE
Importing of class names from style

### ISSUE THREAD

**Issue by dkfiresky** [webpack-contrib/css-loader#692]
The importing of class names from a CSS file doesn't seem to work.

```
// styles.css
.body {
  background: red;
}

// index.js
import styles from './styles.css';

console.log(styles.body); // => undefined

// webpack.config.js
{
  test: /\.(css)?$/,
  loader: 'css-loader',
  options: {
    camelCase: true,
  },
}
```

**Comment by dkfiresky** [comment]
```
// .babelrc
{
  "presets": [
    "react",
    ["env", {
      "targets": {
        "node": "8.9.4"
      }
    }]
  ],
  "plugins": ["transform-react-jsx"]
}
```

**Comment by michael-ciniawsky** [comment]
```diff
{
  test: /\.(css)?$/,
  loader: 'css-loader',
  options: {
+   modules: true,
    camelCase: true,
  },
}
```

This only works when using CSS Modules

**Comment by dkfiresky** [comment]
@michael-ciniawsky even with `modules: true`, I'm not able to import the class name directly.

Only this method works:
```diff
// styles.css
- .body {
+ :local .body {
  background: red;
}

// index.js
import styles from './styles.css';

- console.log(styles.body); // => undefined
+ console.log(styles.locals.body); // => _36bk0V_VtKXgUDBRmEUzlK
```

**Comment by michael-ciniawsky** [comment]
I need more info about your setup please

**Comment by r00dY** [comment]
Encountered same issue.

If you use *only* `css-loader` (without `style-loader`) you get all the local class names in `locals` property.  So with CSS like this:

```css
.className {
    color: red;
}
```

you get following results:

```javascript
import styles from "./styles.css"

console.log(styles.className); // undefined!
console.log(styles.locals.className); // this works
```

Only after adding `style-loader` you get this working as described in spec (https://github.com/css-modules/css-modules) and you can use `styles.className`.

I think it's really confusing. If we have spec in `css-modules` and `css-loader` claims it turns it on via `modules: true` flag, then it should allow for `styles.className` syntax without any extra loaders (`style-loader` in this case).

**Comment by nyngwang** [comment]
@r00dY Holy cow, you're my hero! 

background: I have spent 3-day straight reading the entire docs of `css-loader` and thought I might misunderstand something to cause everything stuck in that `locals`!

Man! it's 2024 and this is still confusing! I need to send a PR to help those people in 2028.

**Comment by nyngwang** [comment]
@r00dY Holy cow, you're my hero! 

background: I have spent 1-day straight reading the entire docs of `css-loader` and thought I might misunderstand something to cause everything stuck in that `locals`!

Man! it's 2024 and this is still confusing! I need to send a PR to help those people in 2028.

**Comment by alexander-akait** [comment]
@r00dY You can enable named export (will be true by default in the next major release)
