### ISSUE TITLE
names in Module mode

### ISSUE THREAD

**Issue by haustraliaer** [webpack-contrib/css-loader#70]
The module mode local scope is _amazing_, but is there any way to name the classes other than picking up the file name of the import?

eg, given:

```
MyComponent /
   index.css
   index.js
```

``` css
/* index.css */
.root {
  /* styles */
}
```

``` js
// index.js
var styles = require('./index.css')

// react stuff etc..
return <div className={styles.root} />
```

will output to:

``` html
<div className="index__root__eofhi28o2"></div>
```

... And so will every other module I have (sans the hash appened) becase I like to keep my component folders named and my filenames generic.

So the desired result given the folder/files above would be:

``` html
<div className="MyComponent__root__eofhi28o2"></div>
```

**Edited**: for clarity

**Comment by haustraliaer** [comment]
Found the place it seemed logical to do this and made a PR ^^

Feel free to suggest an alternative - my problem is specific to css-loader, so perhaps updatign the loader-utils module isn't necessarily the right thing? Although I'm sure this would be useful for other things too.

**Comment by d3viant0ne** [comment]
@haustraliaer - It looks like you fixed your own issue? If that is the case and this is no longer a problem, could you please close the issue?

Thanks for the PR btw :)

**Comment by michael-ciniawsky** [comment]
@haustraliaer if there should be any regressions please reopen, closing for now as it seems to be fixed 😛

**Comment by haustraliaer** [comment]
Yep was sorted in https://github.com/webpack/loader-utils/pull/27 - thanks, works a treat!
