### ISSUE TITLE
Issue when using CSS modules' compose from a node_modules file

### ISSUE THREAD

**Issue by thibautRe** [webpack-contrib/css-loader#703]
**Do you want to request a *feature* or report a *bug*?**
A *bug*

The bug was introduced by [this PR](https://github.com/webpack-contrib/css-loader/pull/698).

**What is the current behavior?**
When trying to use `compose` from CSS modules from a `node_modules` dependency, it breaks with an `Can't resolve` error.

The bug has been introduced by [this commit](https://github.com/webpack-contrib/css-loader/pull/698/commits/585b58b4af9b56ca9e771c4bb6ebdf1845bfcd8a) in `css-loader` but is actually only reproducible with `postcss-loader` as well (at least that's how I uncovered it)

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's a [reproduction of the bug](https://github.com/thibautRe/css-loader-bug). The idea is the following:

- The application uses webpack, extract-text-plugin, css-loader, postcss-loader with postcss-import.
- It tries to `composes` with a class from a UI-kit (in my case, [fyndiq-component-dropdown](https://github.com/fyndiq/fyndiq-ui/tree/master/packages/fyndiq-component-dropdown)).
- The error happens when `fyndiq-component-dropdown` tries to import the colors from the same UI kit [`fyndiq-styles-colors`](https://github.com/fyndiq/fyndiq-ui/tree/master/packages/fyndiq-styles-colors)

**What is the expected behavior?**
It shouldn't break, just like it used to work prior to `v0.28.11`

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Webpack 3 (also breaks with Webpack 4)
Node 8.9.1
NPM 5.7.1 (also breaks with NPM 5.8.0)

**Comment by evilebottnawi** [comment]
Fixed in master, in next version you should use `~fyndiq-component-dropdown/styles.css`
