### ISSUE TITLE
semantic ui error in webpack

### ISSUE THREAD

**Issue by HamzaAhmad932** [webpack-contrib/css-loader#706]
ERROR in ./node_modules/css-loader?{"localIdentName":"[name]__[local]__[hash:base64:5]","importLoaders":1,"modules":true}!./node_modules/postcss-loader/lib?{"ident":"postcss","plugins":[null]}!./node_modules/semantic-ui-css/semantic.min.css
    Module not found: Error: Can't resolve 'themes/default/assets/fonts/outline-icons.woff2' in 'C:\webpack--03-finished\node_modules\semantic-ui-css'
....
This is the error log

**Comment by evilebottnawi** [comment]
@HamzaAhmad932 you don't have loader for woff2, you can use `file-loader` for this type of assets
