### ISSUE TITLE
Using options throws error: parseQuery should get a string as first argument

### ISSUE THREAD

**Issue by mrdanimal** [webpack-contrib/css-loader#707]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Using `options` throws the error: 
```
   Module build failed: Error: parseQuery should get a string as first argument
        at Object.parseQuery (/path/to/app/node_modules/loader-utils/index.js:68:9)
        at Object.module.exports (/path/to/app/node_modules/css-loader/lib/loader.js:1
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/mrdanimal/a49acbb6fcdcb4b44171db4675b769ba

**What is the expected behavior?**
It should allow you to configure the loader using `options`

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

* webpack version: 4.6.0
* node version: 9.11.1
* OS: MacOS 10.12.6

**Comment by evilebottnawi** [comment]
@mrdanimal Looks like a bug, feel free to fix and send PR
