### ISSUE TITLE
[Help] webpack -p results in TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sacredMonster** [webpack-contrib/css-loader#710]
I am using webpack 3 and along with that css-loader@0.28.11. When running webpack -d, it compiles just fine. However on doing webpack -p I get the following error:

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./stylesheets/main.scss
Module build failed: TypeError: Cannot read property 'length' of undefined
    at module.exports (..\node_modules\postcss-value-parser\lib\unit.js:7:23)
    at ..\node_modules\css-loader\node_modules\postcss-minify-gradients\dist\index.js:65:65
    at Array.forEach (native)

 @ ./stylesheets/main.scss 2:14-116
 @ ./index.jsx

This is my webpack.config
{
        test: /\.scss$/,
        include: APP_DIR,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
 },

Any help is appreciated. Thanks...

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template]. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Also look on stack trace 
`at ..\node_modules\css-loader\node_modules\postcss-minify-gradients\dist\index.js:65:65`
Problem in `postcss-minify-gradients`

**Comment by evilebottnawi** [comment]
Will be create if you find css what throw this error and create issue in cssnano
