### ISSUE TITLE
The option "minimize: true" breaks the assembly of the project

### ISSUE THREAD

**Issue by pushkarskiy** [webpack-contrib/css-loader#712]
Hello guys!
I have a problem when i do webpack build, problem depend on option minimize=true and when i trying inline svg files in css. 
I tried to change packages versions, but i don't to found working variant

```
webpack: 4.7.0
css-loader: 0.28.11
cssnano: 4.0.0-rc.2
postcss-svgo: 2.1.6
```
<img width="1300" alt="2018-05-06 16 03 47" src="https://user-images.githubusercontent.com/5006584/39673676-431f0a46-5149-11e8-8d9a-93a1498abf12.png">

**Comment by evilebottnawi** [comment]
@pushkarskiy don't use `ETWP` for extract css for webpack@4. Please use https://github.com/webpack-contrib/mini-css-extract-plugin. Also css-loader use `cssnano@3`. In next major version `minimize` option will be remove. I recomandate switch on plugin https://github.com/NMFR/optimize-css-assets-webpack-plugin. Thanks!
