### ISSUE TITLE
Couldn't use compose in Webpack 4

### ISSUE THREAD

**Issue by tony1Centre** [webpack-contrib/css-loader#714]
Hi,

Webpack.config.js:
use: [
          {
            loader: "style-loader"
          },
          {
            loader: "css-loader",
            options: {
              modules: true,
              importLoaders: 1,
              localIdentName: "[name]_[local]_[hash:base64]",
              sourceMap: true,
              minimize: true
            }
          }
        ]
home.css:
.layout{
    composes: container from "css/grid/grid.css";
}

Error: Can't reslove css/grid/grid.css

Many thanks,
Tony

**Comment by evilebottnawi** [comment]
@tony1Centre Please use issue template. Feel free to recreate/reopen when you fixed it.
