### ISSUE TITLE
Can't Live Edit CSS/SCSS Sources in Chrome Workspaces without file://

### ISSUE THREAD

**Issue by niedfelj** [webpack-contrib/css-loader#717]
**Do you want to request a *feature* or report a *bug*?**

FEATURE

**What is the current behavior?**
Sourcemap from sub module css (from sass-loader) is stringified with absolute paths

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Would be great to be able to use Chrome 66 workspaces to live edit files, but Chrome requires that sourceMap has file:// at the beginning

**If this is a feature request, what is motivation or use case for changing the behavior?**
To use Chrome workspaces to live edit scss/css

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack 4.8.3
node 8.10.0
MacOS 10.13.4

I was able to get the correct behaviour by doing the following on lines 117..132 in loader.js

```
		var moduleJs;
		if(sourceMap && result.map) {
			// add a SourceMap
			map = result.map;
			if(map.sources) {
				map.sources = map.sources.map(function(source) {
					return "file://"+source.split("!").pop().replace(/\\/g, '/');
				}, this);
				map.sourceRoot = "";
			}
			map.file = map.file.split("!").pop().replace(/\\/g, '/');
			map = JSON.stringify(map);
			moduleJs = "exports.push([module.id, " + cssAsString + ", \"\", " + map + "]);";
		} else {
			moduleJs = "exports.push([module.id, " + cssAsString + ", \"\"]);";
		}
```

Does it make sense to set this as an option or use another webpack default, for example in the output I'm also using

```
    output: {
      devtoolModuleFilenameTemplate(info) {
        const newPath =  'file://' + path.resolve(info.absoluteResourcePath).replace(/\\/g, '/')
        return newPath
      },
    },
```

**Comment by evilebottnawi** [comment]
@niedfelj looks you ahve invalid configuration webpack out of box work with workspaces

**Comment by niedfelj** [comment]
@evilebottnawi What should it be? I'm working with the new Shopify slate/slate-tools project. Opened this ticket with them also

https://github.com/Shopify/slate/issues/447

**Comment by niedfelj** [comment]
Also reference this issue https://github.com/webpack/webpack/issues/6400

**Comment by evilebottnawi** [comment]
Looks like we can close this issue in favor https://github.com/webpack/webpack/issues/6400

**Comment by niedfelj** [comment]
@evilebottnawi While they are related, they are not the same issue. css-loader is responsible for munging these sourceMaps, there is nothing webpack or that issue can do to resolve it by itself.

**Comment by niedfelj** [comment]
I guess with an option like sourceMapUrlPrefix or a similar callback function as mentioned above with devtoolModuleFilenameTemplate(info) (or maybe look for that output setting and use the same so they output the same file formats?

**Comment by evilebottnawi** [comment]
@niedfelj we should first solve this in webpack, maybe add new api, which allow to us using this, no new option

**Comment by niedfelj** [comment]
Sounds good, can we leave this open as a tracking ticket?

**Comment by evilebottnawi** [comment]
@niedfelj :+1:

**Comment by HairyRabbit** [comment]
:)

Anything update here?

![image](https://user-images.githubusercontent.com/5752902/42418484-3d205ae8-82d4-11e8-858d-8ea3d7278a1a.png)

**Comment by evilebottnawi** [comment]
@HairyRabbit your problem already solved in last release and not related to top issue

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/css-loader/issues/622#issuecomment-471575481

Anyway you can setup editing in dev tools:
1. Open dev tools.
2. Click `Filesystem` in on left panel.
3. Click `Add folder to workspace` in left panel.
4. Add `src`/`lib` directory.
5. Change content of file.

Anyway we should respect `devtoolModuleFilenameTemplate` and other `devtool` options, close in favor https://github.com/webpack-contrib/css-loader/issues/622#issuecomment-471575481. Thanks for issue
