### ISSUE TITLE
Not able to load image url from css file + webpack 4

### ISSUE THREAD

**Issue by nguyenhuutinh** [webpack-contrib/css-loader#723]
Hello,
I tried to render image in scss file but cannot. Using require() in js is ok. But cannot load image url in css file

Here is my config
{
        // Preprocess our own .scss files
        test: /\.scss$/,
        exclude: /node_modules/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
      },
my sccs script:

background: url("images/header/book.png") no-repeat;

**Comment by evilebottnawi** [comment]
Please use issue template, also you need `url-loader` or `file-loader` for assets.

**Comment by Albosonic** [comment]
I struggled with this for some time with my upgrade to webpack v4. Until I finally found the newer webpack-image-loader so I wrote up a quick post here with a code example:
https://medium.com/@albertomadueno/webpack-v4-config-d6cee480a071
also README here: https://github.com/tcoopman/image-webpack-loader
