### ISSUE TITLE
Why i import .less file from node_modules, css-loader still compile css of class

### ISSUE THREAD

**Issue by TongDaDa** [webpack-contrib/css-loader#724]
```javascript
import 'antd/dist/style.less' // from node_modules. It should not be compiled

import style from '../style.less';  //from local file, i want to it is compiled
```

I have found no effect to do so. because it is compiled into a hash.
We can not introduce any file from a node_modules is processed by a CSS - modules

**Comment by evilebottnawi** [comment]
@TongDaDa not related to `css-loader`, looks problem in `less-loader`. Also please use issue template. We don't have enough data to help you.

**Comment by TongDaDa** [comment]
@evilebottnawi You can see the webpack config loaders, please.
