### ISSUE TITLE
Outdated cssnano, autoprefixer, browserslist

### ISSUE THREAD

**Issue by tornography** [webpack-contrib/css-loader#725]
Hi, I found out the outdated dependency of `cssnano@3.10.0` uses an outdated version of `autoprefixer@6.7.7` that uses an outdated version `browserslist@^1.7.6`.

As browserlist currently is at version 3.2.8, there are error when setting the browserlist options in package.json:

```
{
  "browserslist": [
    "last 2 versions",
    "not <1%"
  ]
}
```

causes an error `BrowserslistError: Unknown browser query '<1%'`.

As this is definately fixed in in that version, I suggest an update of these dependencies.

**Comment by evilebottnawi** [comment]
@tornography we are working on `cssnano@4`, also i recomadate to move from `minimize`, because this option will be remove in next major version. Thanks!
