### ISSUE TITLE
No resolution and/or transformation applied to `url()` using `options.alias`.

### ISSUE THREAD

**Issue by zyrolasting** [webpack-contrib/css-loader#727]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
I am adding to the conversation re: aliases similar to #557. `url()` does not seem to resolve correctly according to an alias configuration `css-loader` shares with `enhanced-resolve`. I have been using latest, but have rolled back to 0.28.0 after seeing whispers about a breaking change. Nothing improved, so I am back on latest.

**If the current behavior is a bug, please provide the steps to reproduce.**
[Here's a repo](https://github.com/zyrolasting/css-loader-alias-issue) that reproduces the issue. In this case I set up a situation where a CSS `url()` and a JS `require()` make the exact same module request, same alias and all. Read the README.

As for the actual resolution bug I would not be surprised if I just made a stupid mistake. But if I did, I'm not seeing it right now.

**What is the expected behavior?**
I expect `css-loader` to use `enhanced-resolve`'s rules and behave the exact same way when resolving modules.

In the example repo, my expectation is that `url("packages/b/img.png")` and  `require('packages/b/img.png')` would have the same effect. That is, the PNG is found, copied to the `dist` directory, and any output CSS that would go along with that shows awareness of the PNG files new location and name.

The actual behavior in the non-working case is that the PNG is not found, and `css-loader` appears to have tried to resolve the module relative to the resolver's context. In some cases `css-loader` won't even print an error to this effect and will just pass the unresolved request, as written, directly into the output bundle (hence the issue title).

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

`webpack@4.12.0`, `Node v10.3.0`, `Ubuntu 18.04 LTS`

**Comment by evilebottnawi** [comment]
Don't use `alias` option, it is removed in `1.0.0` version, please use https://webpack.js.org/configuration/resolve/ or https://github.com/postcss/postcss-url with `postcss-loader`
