### ISSUE TITLE
Hash classNames only with CSS modules

### ISSUE THREAD

**Issue by mlnor27** [webpack-contrib/css-loader#733]
Hi everyone,

Sorry if my topic is duplicated, it seems that no issues relate to my problem.
I'm on an ejected create-react-app config, where i enabled scss files and css modules.

I would like to keep the classNames as they are if i import my css file like this : 
`import './style.scss'`
with a regular className written the regular way : 
`<div className="homeContainer">...</div>`

And i only want the classNames to be hashed when i import any css files this way : 
`import styles from './style.scss'`
using it like an object : 
`<div className={styles.homeContainer}>...</div>`

We currently have a pretty big codebase without using css modules and we would like to introduce them without having to change every classNames.
Would it be possible to mix both css modules and regular css imports ?

Any help would be greatly appreciated.

**Comment by TongDaDa** [comment]
I encountered same problem with you !! i want to find a good idea for resolve it.

**Comment by TongDaDa** [comment]
I using less file to build a project and use css-modules of css-loader, but when import less file from 'node_modules' and local less, but from the 'node_modules' file is HASH classname, I hope except css-modules when from 'node_modules' import the less file.

**Comment by TongDaDa** [comment]
@mlnor27 Do you resolve this problem ?

**Comment by TongDaDa** [comment]
Ok, coincidentally, I used to have this idea too, it may not a good way though haven't others ways yet.

**Comment by evilebottnawi** [comment]
@TongDaDa using `:global` on selectors, or use `.modules.css` extensions for modules and `.css` for vanilla css, example here https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/config/webpack.config.dev.js#L302

**Comment by TongDaDa** [comment]
@valscion Thanks!
