### ISSUE TITLE
sass compile with css: require is not defined

### ISSUE THREAD

**Issue by willin** [webpack-contrib/css-loader#743]
**Do you want to request a *feature* or report a *bug*?**

perhaps bug

**What is the current behavior?**

ref: https://github.com/peerigon/extract-loader/issues/41

**If the current behavior is a bug, please provide the steps to reproduce.**

![1](https://user-images.githubusercontent.com/1890238/42299265-d5a60492-803c-11e8-8e94-dd63d8f0f0d9.jpeg)

![2](https://user-images.githubusercontent.com/1890238/42299513-25ecfa86-803e-11e8-9569-fa94f8c96bad.jpeg)

**What is the expected behavior?**

compile css

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

source: https://github.com/wshow/sass-demo

**Comment by evilebottnawi** [comment]
@willin thanks for issue, looks in `extract-loader`
