### ISSUE TITLE
npm i css-loader has return error

### ISSUE THREAD

**Issue by fabinhofz** [webpack-contrib/css-loader#744]
Hello,

I tried to start a new webpack project, when I put this css loader on my package.json like that "css-loader": "^0.28.9". Something went wrong, an ERR returned: "npm ERR! Unexpected end of JSON input while parsing near '...evDependencies":{"bab'".

![image](https://user-images.githubusercontent.com/14041042/42327904-519e662e-8043-11e8-898d-009a2e210fbb.png)

**Comment by evilebottnawi** [comment]
@fabinhofz maybe npm bug, try `rm -r node_modules && rm -r package-json.lock && npm cache clear --force && npm`, if problem still exists please create issue in npm repo, thanks!

**Comment by fabinhofz** [comment]
It works, right now! thanks, @evilebottnawi.
