### ISSUE TITLE
minimize option not working after upgrade.

### ISSUE THREAD

**Issue by MSTWNTD1** [webpack-contrib/css-loader#745]
After upgrading to version 1.0.0 the minimize option stopped working.

This is the configutation I have:

![capture](https://user-images.githubusercontent.com/5055390/42423429-00cc945a-82c8-11e8-910d-984aa7231ce4.png)

I am using ubuntu 18.04 with nodejs 8.10.0. When I downgrade css-loader to version 0.28.11, the minimize option works as expected. Is there something I'm missing?

**Comment by polco** [comment]
it's in the breaking changes of the last release: https://github.com/webpack-contrib/css-loader/releases

**Comment by evilebottnawi** [comment]
Yes, it is breaking chage, please use `cssnano` using `postcss-loader` or use plugin for this

**Comment by brunolemos** [comment]
@alexander-akait any help on how to do that using inline loaders?

for example, before the upgrade the import was like this:

`require('!!to-string-loader!css-loader?minimize!sass-loader!../index.scss'),`

but now that we need to use `post-loader`, how to configure it? tried many this like this but didn't work:
`require('!!to-string-loader!css-loader?esModule=false!postcss-loader?postcssOptions={plugins: ["cssnano"]}!sass-loader!../index.scss')`

**Comment by kissu** [comment]
Posting the release note here: https://github.com/webpack-contrib/css-loader/releases/tag/v1.0.0
