### ISSUE TITLE
css-modules changes context to it's directory when using background image: url( ... ) with relative path to node_modules package

### ISSUE THREAD

**Issue by jussikinnula** [webpack-contrib/css-loader#746]
Note! This is a copy from https://github.com/css-modules/css-modules/issues/296 to track this issue on `css-loader` side as well.

We're using bunch of loaders (e.g. stylus-loader, postcss-loader, css-loader & style-loader) on top of Webpack to bundle the CSS. After switching to CSS modules, we've had bunch of strange things occurring like this one. I'm happy to provide more input if needed.

Example CSS code (e.g. `styles.css`):
```
.foo {
  background-image: url('~foo/bar.png');
}
```

There's package `foo` installed with npm, and the physical path to `bar.png` is `node_modules/foo/bar.png`. Instead of background-image loading from the correct path, css-modules changes the context to it's directly.

Changing the `url( ... )` to `url('~/../foo/bar.png')` fixes the problem, or adding a Webpack alias helps:

```
const webpackConfig = {
  ...
  resolve: {
   ...
    alias: {
      'foo': path.resolve(__dirname, '../node_modules/foo/')
    }
  },
  ...
};
```

**Comment by evilebottnawi** [comment]
@jussikinnula looks better solve this problem in `css` modules, because we remove their support in `2.0` version in favor `postcss-loader` + `postcss-modules`

**Comment by jussikinnula** [comment]
Re @evilebottnawi, I did added this issue just for keeping track of the actual problem. There's already issue on css-modules side to work for a proper fix :-)

**Comment by evilebottnawi** [comment]
We drop built-in support `css` modules in `2.0.0` version (https://github.com/webpack-contrib/css-loader/pull/748). Now you should use `postcss-loader` for their. But looks many `css` modules plugins is abandoned. I would recommend that you switch to another technology (example `css-in-js`) or you can use old `css-loader` version.

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/css-loader/issues/746#issuecomment-411494027
