### ISSUE TITLE
Upgrade to PostCSS v7

### ISSUE THREAD

**Issue by milesj** [webpack-contrib/css-loader#754]
**Do you want to request a *feature* or report a *bug*?**

New feature.

**What is the current behavior?**

Uses PostCSS v6.

**What is the expected behavior?**

Use PostCSS v7.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Most loaders and tools have been updated to v7. Looks like this loader is the current outlier.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

N/A

**Comment by radeno** [comment]
Look at branch 2.0

**Comment by evilebottnawi** [comment]
Done in master, will be shipped in near future
