### ISSUE TITLE
Enable modules for import...from and disable modules for bare import at the same time

### ISSUE THREAD

**Issue by johannhuang** [webpack-contrib/css-loader#766]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

When `modules: true` is enabled, the raw methods like `import 'bootstrap/dist/css/bootstrap.min.css';` don't work anymore; When `modules: true` is not set, the methods like `import styles from 'bootstrap/dist/css/bootstrap.min.css';` don't work.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

When I use `import styles from '...'`, enable css module; when I use `import '...'`, work as the normal way.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Progressive enhancement for the existing code base. 

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

OS: WSL
Node: v8.11.3
"webpack": "^4.2.0",
"webpack-cli": "^2.0.12",
"webpack-dev-server": "^3.1.1"

**Comment by evilebottnawi** [comment]
Sorry it is impossible, we always load `css` (if you use `import styles from '...'` and `import '...'`) and provide `locals` (place where we store classes). You should can configure two loaders (`test: /\.css$/` and `test: /\.modules\.css/`) for css modules files and vanilla css
