### ISSUE TITLE
add version of ?sourceMap with locals already transformed

### ISSUE THREAD

**Issue by pstoica** [webpack-contrib/css-loader#77]
It would be useful to see the file at its original path, but with the final hashes available.

**Comment by pstoica** [comment]
relevant lines:

https://github.com/webpack/css-loader/blob/master/lib/loader.js#L134
https://github.com/webpack/css-loader/blob/master/lib/loader.js#L65

**Comment by michael-ciniawsky** [comment]
@pstoica Cpuld you send a PR for this ? 😛

**Comment by evilebottnawi** [comment]
@pstoica can you provide more information about feature?

**Comment by pstoica** [comment]
When I tried to debug CSS, I would go to the file and only see the `:local` syntax without the real ID.

I don't use this module anymore and don't know if this is still the case. Feel free to close this!
