### ISSUE TITLE
[feature request] add css-loader-@import-handled hooks

### ISSUE THREAD

**Issue by Aqours** [webpack-contrib/css-loader#773]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
See [cssnano-issues-604](https://github.com/cssnano/cssnano/issues/604) 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The comment in test.css should be discarded. (test.css file should be handled by postcss-loader)

**If this is a feature request, what is motivation or use case for changing the behavior?**
We want raw css file which mix with less or scss file, can be handled by postcss-loader.

loader workflow
```text
less-loader/scss-loader 
-> [postcss-loader] 
-> css-loader-@import-handled 
-> [postcss-loader] (using hooks or plugins that we can handle raw css mixed with less/scss by postcss-loader)
-> css-loader-other-tasks
-> style-loader/other-loader
```

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
webpack 4, node 10, windows 10

**Comment by evilebottnawi** [comment]
@Aqours not related to `css-loader`, we don't `minimize` code (include remove comments)

**Comment by Aqours** [comment]
In this case, postcss-loader cannot handle css file which I want to use autoprefixer, cssnano or other postcss-plugins. It's not only related to minimize code.

**Comment by evilebottnawi** [comment]
@Aqours i can't understand what you mean, please provide more information, maybe you need this https://github.com/webpack-contrib/css-loader#importloaders?
