### ISSUE TITLE
Update babel-code-frame? (License issue)

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [webpack-contrib/css-loader#774]
Hello,

Could the `babel-code-frame` dependency please be updated to `@babel/code-frame`?

The issue that we're running into is that `@babel/code-frame` contains licensing information, but `babel-code-frame` doesn't.

Thanks,
Eli

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack-contrib/css-loader/pull/799, will be shipped in near future
