### ISSUE TITLE
When passing string in url with multiline escaped as bell code it is being unescaped

### ISSUE THREAD

**Issue by Toxyxer** [webpack-contrib/css-loader#775]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If bell codes (`\a`) are used in url strings they are replaced with newlines (`\n`).

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/Toxyxer/4c8b727956d00c06b625d03f7b9c786c

**What is the expected behavior?**
Preserve bell codes (`\a`)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Operating System: Windows 10
webpack: 4.20.2
sass-loader: 7.1.0
css-loader: 1.0.0
node: 8.11.3

**Comment by evilebottnawi** [comment]
@Toxyxer it is invalid `css`
