### ISSUE TITLE
Respect exclude option when handling url

### ISSUE THREAD

**Issue by rodfersou** [webpack-contrib/css-loader#779]
Is it possible to respect exclude option when handling url?

I have a specific use case, in our CMS an url that has '++resource++' inside should be considered external image. This is my current configuration:

```javascript
     {
        // Handle SCSS files
        test: /\.scss$/,
        exclude: /\+\+resource\+\+/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            'css-loader',
            'postcss-loader',
            'sass-loader'
          ]
        }),
      },
```

But the url handling is not respecting this configuration, and throw this traceback:
```javascript
    ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./app/cover.scss
    Module not found: Error: Can't resolve './++resource++plone.app.jquerytools.pb_close.png' in '/home/rodfersou/.projects/collective.cover/webpack/app'
     @ ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./app/cover.scss 7:6933-6992
```

**Comment by evilebottnawi** [comment]
@rodfersou please use `exclude` on `file-loader/url-loader`. Can you create minimum reproducible test repo?

**Comment by rodfersou** [comment]
@evilebottnawi here you are https://github.com/rodfersou/exclude-in-url

just run:
```bash
$ npm install
$ npm run debug
```
and the error will happen

**Comment by rodfersou** [comment]
I tried to use ``file-loader/url-loader`` without success, any help would be appreciated.

**Comment by evilebottnawi** [comment]
@rodfersou yep, it is impossible right now, we prepare `css-loader@2` https://github.com/webpack-contrib/css-loader/pull/760 and can implement this after release

**Comment by rodfersou** [comment]
@evilebottnawi great, I look forward to it

**Comment by rodfersou** [comment]
Thank you very much!

**Comment by rodfersou** [comment]
@evilebottnawi could you please provide an example on how to make this feature work? I just updated the version (in the same PR mentionated) and still get a traceback.

**Comment by rodfersou** [comment]
Okay, I could figure out what was missing, but still for me looks like the result of the function should be inverted to keep in mind the same behavior when it is a boolean..
I mean when the function return false should not look the ``url``.
This is my configuration in the end:
```javascript
    {
      test: /\.scss$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          {
            loader: 'css-loader',
            options: {
              url: (url, resourcePath) => /\+\+resource\+\+/.test(url)
            }
          },
          'postcss-loader',
          'sass-loader'
        ]
      }),
    },
```

**Comment by rodfersou** [comment]
thank you very much

**Comment by evilebottnawi** [comment]
@rodfersou can you open issue?

**Comment by rodfersou** [comment]
@evilebottnawi https://github.com/webpack-contrib/css-loader/issues/891
