### ISSUE TITLE
@media query default support

### ISSUE THREAD

**Issue by YuriScarbaci** [webpack-contrib/css-loader#780]
**Do you want to request a *feature* or report a *bug*?**
I want a *feature*

**What is the current behavior?**
there is no support for `@media` queries when using `:local()`
```
:local(.className){
    width:800px;
}
@media (max-width: 800px){
    :local(.className) {
    width: 550px;
  }
}
```
results into local media never applying. currently there is no default support for @media queries, for what i have seen (only external packages).

**What is the expected behavior?**
to be able to use @media queries in a sort of default way, like one would do with normal css.
An example would be adding a keyword like `composes:` but instead be like `mediaQueryFor:` that allows us to reference a previously defined `:local` class.

**If this is a feature request, what is motivation or use case for changing the behavior?**
to be able to use media queries without adding other packages or tampering with default configuration

**Comment by evilebottnawi** [comment]
@YuriScarbaci out of scope this package, please create issue in https://github.com/css-modules/postcss-modules or related plugin to css modules
