### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by patricksmms** [webpack-contrib/css-loader#786]
Most of the dependencies are outdated. 

Some of them don't include license files, therefore can't be used legally, but in their latest versions that has been cleared out.

Also some have been renamed and have modified APIs:
babel-code-frame -> @babel/code-frame
postcss-modules-scope -> postcss-icss-composes
postcss-modules-values -> postcss-icss-values

**Comment by evilebottnawi** [comment]
Impossible solve now, we use old css modules specification, you point on ICSS spec what is not stable

**Comment by evilebottnawi** [comment]
Only babel-code-frame can be updated

**Comment by patricksmms** [comment]
Oh. Then unfortunately we won't be able to use `css-loader`, as not all of its dependencies have license files in their packages (a legal requirement).

**Comment by evilebottnawi** [comment]
@patricksmms this packages have `license` field (with `MIT`) and it is require for legal reasons

**Comment by patricksmms** [comment]
It's not. MIT license requires the inclusion of the full license in all the copies of the software, as clearly stated

_The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software._
https://opensource.org/licenses/MIT

**Comment by evilebottnawi** [comment]
@patricksmms feel free to send a PR to old version plugins and we update their here

**Comment by evilebottnawi** [comment]
License problem with `css-selector-tokenizer` already solved, you can send a PR with updated version here

**Comment by patricksmms** [comment]
Once we have `postcss-modules-scope@1.3.1` and `postcss-modules-values@1.1.1` published, with the license files, we can update the dependencies as follows:

```

  "dependencies": {
    "@babel/code-frame": "^7.0.0",
    "css-selector-tokenizer": "^0.7.1",
    "icss-utils": "^3.0.1",
    "loader-utils": "^1.1.0",
    "lodash": "^4.17.11",
    "postcss": "^6.0.23",
    "postcss-modules-extract-imports": "^2.0.0",
    "postcss-modules-local-by-default": "^1.2.0",
    "postcss-modules-scope": "^1.1.1",
    "postcss-modules-values": "^1.3.1",
    "postcss-value-parser": "^3.3.1",
    "source-list-map": "^2.0.1"
  },
  "devDependencies": {
    "codecov": "^3.1.0",
    "eslint": "5.8.0",
    "istanbul": "^0.4.5",
    "mocha": "^5.2.0",
    "should": "^13.2.3",
    "standard-version": "^4.4.0"
  },
```

and change the line 229 of lib/processCss.js to:
```
'\n\n' + formatCodeFrame.codeFrameColumns(source, { start: { line: loc.line, column: loc.column } }) + '\n';
```

**Comment by evilebottnawi** [comment]
Yep

**Comment by evilebottnawi** [comment]
Done in master, will be release in near future

**Comment by sepikas** [comment]
Shouldn't loader-utils dependency be updated in the master branch? 
I think it should be 1.1.0 but it's 1.0.2

**Comment by evilebottnawi** [comment]
@sepikas We use ` "loader-utils": "^1.0.2",` so updating or installation always fetch latest version, please read about semver and how dependencies work in `package.json`
