### ISSUE TITLE
ERROR in ./node_modules/bindings/bindings.js Module not found: Error: Can't resolve 'fs' in 'j\node_modules\bindings'

### ISSUE THREAD

**Issue by Arshad0309** [webpack-contrib/css-loader#836]
* Windows7 x64:
* 10.13.0:
* 6.4.1:

###  constructor(){
    console.log("Service Works Fine !!!");
    var RetInt = types.int;
    var callInt = types.int;   
    //callInt=7;
    var intPtr = refType(types.int);

    var libm = Library('XYZ.dll', {
    'FUNC_ABC': [ 'int', [ 'int' ] ]
    });
    var alm = libm.FUNC_ABC(7); 
    console.log("Returned:"+a);

**Comment by evilebottnawi** [comment]
Not related to `css-loader` use `node: { fs: false }`
