### ISSUE TITLE
NODE_PATH no longer respected in version 2.0.0+

### ISSUE THREAD

**Issue by rishitank** [webpack-contrib/css-loader#882]
* Operating System: Mac OS X 10.14.2
* Node Version: 10.10.0
* NPM Version: 6.5.0
* webpack Version: 4.26.1
* css-loader Version: 2.1.0

### Expected Behavior

if the NODE_PATH environment variable is set to my project's ./src folder either inline or via .env file, then I would usually be able to access the directories under this when using a URL:

```
.addon-baggage {
    background-image: url("assets/images/baggage-info.png");
    background-repeat: no-repeat;
}
```

### Actual Behavior

However with the new version of CSS-loader the above code returns the following error, showing that it is indeed not respecting the NODE_PATH variable, and is instead parsing it as a relative path:

`ModuleNotFoundError: Module not found: Error: Can't resolve './assets/images/baggage-info.png' in '/Users/dev/project/src/containers/modules/ConfirmationAddons/assets/react'`

Each of my modules has their own local css file, but also may need to access images or other media shared across the whole project.

Also note that I have always had the project's src folder setup in the webpack config as shown here: https://webpack.js.org/configuration/resolve/#resolve-module but always see this error now. Thanks.

**Comment by evilebottnawi** [comment]
@rishitank default value `node_modules` https://webpack.js.org/configuration/resolve/#resolve-modules for modules directory, we don't setup `NODE_PATH` in `css-loader`, you should add `NODE_PATH` env variable to your resolve options in `webpack` config or create issue about default support this NODE_PATH

**Comment by evilebottnawi** [comment]
And it is expected behavior you should use `./` for relative images and `~` for resolve images as module

**Comment by rishitank** [comment]
@evilebottnawi as mentioned, NODE_PATH was always setup in https://webpack.js.org/configuration/resolve/#resolve-modules but still does not work

**Comment by evilebottnawi** [comment]
@rishitank as i said above, it is breaking change for `css-loader@2`, you should use `~` for resolve asset as module
