### ISSUE TITLE
Prepend publicPath to urls referenced in *.css

### ISSUE THREAD

**Issue by d-dizhevsky** [webpack-contrib/css-loader#884]
Hi, my angular app ends up being deployed to web server with different virtual paths such as:

- http://website.com/app1/
- http://website.com/app2/

To get them both work properly, at the build stage I change angular's `<base href=>` and webpack's `publicPath` options to match specific virtual path app1 or app2.

The urls in my index.html are properly changed from  `<img src='hello.png'/>` to `<img src='app1/hello.png'/>` but the urls inside the css and sass are not changed at all.

I use style-loader, css-loader and sass-loader plugins like that:

        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
          include: [helpers.root('src', 'styles')],
        },
        {
          test: /\.scss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
          include: [helpers.root('src', 'styles')]
        }
And lets say my css is:
```
body {
  background-image: url(bg.png);
}
```

Can I force webpack to add publicPath to bg.png and load it from `url(app1/bg.png)`?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue. 

You can use difference file-loader option for difference files (using `test`, `exclude` and `include` options) or you can exclude `url`.

**Comment by johnryan** [comment]
@d-dizhevsky Did you figure out a solution to this issue? I asked the question [here](https://stackoverflow.com/questions/55930482/configuring-css-loader-with-publicpath/55932372#55932372) but I was hoping you found a more elegant solution.

**Comment by d-dizhevsky** [comment]
@johnryan no, unfortunately, I gave up on this
