### ISSUE TITLE
Remove/Shrink Lodash Dependency

### ISSUE THREAD

**Issue by kurisubrooks** [webpack-contrib/css-loader#887]
* css-loader Version: 2.1.0

### Modification Proposal
Lodash adds a significant size to the total bundle size coming in at around 530kb when including the whole library, so i'd like to propose removing it in favour of native ES6 code (see: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore), otherwise you can import each function you need as a separate module which will also help to reduce file size significantly.

Example below

```js
// require the entire lodash library including all of it's unused modules
const _ = require("lodash");
_.first([1, 2, 3, 4, 5]);

// require only the function you need by importing just that individual module
const first = require("lodash/first");
first([1, 2, 3, 4, 5]);
```

Note that destructuring still uses the original file, so prefer the above method instead of doing;

```js
const { first } = require("lodash");
```

Thanks for reading and I hope you listen to my advice 🙏

**Comment by evilebottnawi** [comment]
PR welcome
