### ISSUE TITLE
Fix url filter behavior

### ISSUE THREAD

**Issue by rodfersou** [webpack-contrib/css-loader#891]
Related to: https://github.com/webpack-contrib/css-loader/issues/779

The result of the function should be inverted to keep in mind the same behavior when it is a boolean..
I mean when the function return false should not look the ``url``.
This is my configuration in the end:
```javascript
    {
      test: /\.scss$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          {
            loader: 'css-loader',
            options: {
              url: (url, resourcePath) => /\+\+resource\+\+/.test(url)
            }
          },
          'postcss-loader',
          'sass-loader'
        ]
      }),
    },
```

**Comment by evilebottnawi** [comment]
@rodfersou thanks for issue, we can fix it only in next major release, i am afraid break loader for other developers

**Comment by rodfersou** [comment]
@evilebottnawi for me looks great!

**Comment by rodfersou** [comment]
:tada:
