### ISSUE TITLE
Module aliases and `~` prefix

### ISSUE THREAD

**Issue by OliverJAsh** [webpack-contrib/css-loader#892]
I am upgrading css-loader from 0.28.3 to 2.1.0 and it seems at some point css-loader started to require a `~` prefix in module IDs that uses webpack aliases.

I would like to ask why this is necessary? I can import using aliases in normal JS modules just fine without the `~` prefix. Is it really needed?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Issue https://github.com/webpack-contrib/css-loader/issues/861. It is current limitation before `webpack` can't solve some issues with `doResolve` function in api
