### ISSUE TITLE
Cannot find module 'css-loader/locals'，typescript+webpack+react

### ISSUE THREAD

**Issue by wenJonSnow** [webpack-contrib/css-loader#897]
"devDependencies": {
    "css-loader": "^2.1.0",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.5.0",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0",
    "ts-loader": "^5.3.3",
    "typescript": "^3.3.3333",
    "typings-for-css-modules-loader": "^1.7.0",
    "webpack": "^4.29.5",
    "webpack-cli": "^3.2.3",
    "webpack-dev-server": "^3.2.0"
  },
  "dependencies": {
    "@types/react": "^16.8.4",
    "@types/react-dom": "^16.8.2",
    "@types/react-loadable": "^5.5.0",
    "@types/react-router-dom": "^4.3.1",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "react-loadable": "^5.5.0",
    "react-router-dom": "^4.3.1"
  }

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/css-loader/releases/tag/v2.0.0 use `exportOnlyLocals`

**Comment by joacub** [comment]
same error
