### ISSUE TITLE
Tilde in composes breaks DX

### ISSUE THREAD

**Issue by klimashkin** [webpack-contrib/css-loader#898]
* Operating System: macOs
* Node Version: 10.15.0
* NPM Version: 6.4.1
* webpack Version: 4.29.5
* css-loader Version: 2.1.0

### Expected Behavior / Situation
`composes: classname from 'path/to/file'` should resolve path taking `resolve.modules` and `resolve.alias` into account

### Actual Behavior / Situation
Since 2.0.0 tilde needs to be added: `composes: classname from '~path/to/file'`

### Modification Proposal
In our project we have hundreds of css files with hundreds of `composes` usages, which rely on webpack aliases that look like that:
```js
  ...
  resolve: {
    unsafeCache: true,
    cacheWithContext: true,
    enforceExtension: false,
    enforceModuleExtension: false,
    extensions: ['.js', '.jsx', '.json', '.css'],
    modules: [path.resolve(__dirname, 'app', 'styles'), 'node_modules'],
    alias: {
      'components': path.resolve(__dirname, 'app', 'components'),
      ...
    },
  },
  module: {
    rules: {
        {
          test: /\.css/,
          exclude: [/node_modules/],
          use: [
            {
              loader: 'style-loader',
              options: {
                hmr,
                sourceMap: false,
              },
            },
            {
              loader: 'css-loader',
              options: {
                modules: true,
                sourceMap: false,
                importLoaders: 1,
                localIdentName: '[name]_[local]',
              },
            },
            {
              loader: 'postcss-loader',
              options: {
                sourceMap: false,
                config: {
                  ctx: {browserslist},
                },
              },
            },
          ],
        }
    },
  }
```

And for this example we have `utils.css` file in `app/styles` and many modules with their own css files under `app/components` folder.
And typical css files use composes like that:
```css
.someClass {
  composes: insensitive from 'utils.css';
  composes: item from 'components/Header/Header.css';
  ...
}
```
and js files imports look like that:
```js
import utilsStyles from 'utils.css';
...
```
And that used to work perfectly
1. Path to css file from js and css modules would looke the same
2. IDE would recognize paths in both cases correctly and provided the same experience like cmd/ctrl+click to navigate to the corresponding composed/imported css-module.

But after updating to css-loader 2.0.0 all those `composes` have become broken, and now adding `~` is required there to specify path to another css-module.
1. Now css import in js and composition in css look differently.
2. Now IDE can't recognize such paths with tilde, complain about them and don't provide convenient navigation on click:

<img width="344" alt="screen shot 2019-02-26 at 10 48 44 pm" src="https://user-images.githubusercontent.com/576077/53471201-b7df4680-3a18-11e9-8e0d-483b07cdf3bc.png">

I'm not sure why tilde is required now for resolving paths with aliases, it makes working with paths harder and less convenient.
Btw, on screenshot above `@import 'variables.css';` still works even though `variables.css` also sits inside `app/style`, but it's handled by postcss loader which still normally handles aliases.

I think tilde should not be required for aliases, and should be handled automatically like other loaders do, previous version of css-loader used to do and like webpack does itself.

**Comment by klimashkin** [comment]
Or at least maybe some option can be introduce to handle path `composes` in classic way.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/css-loader/issues/861, yep it is bug, feel free to send a PR, i will look on this in near future
