### ISSUE TITLE
Wrong output when deal with css modules

### ISSUE THREAD

**Issue by honghui-qiao** [webpack-contrib/css-loader#902]
* Operating System:  Mojave
* Node Version:  v10.15.1
* NPM Version: 6.4.1
* webpack Version: 4.x
* css-loader Version: 2.x

### Expected Behavior

`a[href=''] { xxx }` should compiled to `a[href=''] { xxx  }`

### Actual Behavior

`a[href=''] { xxx }` compiled to `a[href] { xxx }`

**We don't have this issue with css-loader 1.x**

**Comment by evilebottnawi** [comment]
@honghui-qiao please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
No need, reproduce

**Comment by evilebottnawi** [comment]
WIP

**Comment by evilebottnawi** [comment]
Upstream issue https://github.com/postcss/postcss-selector-parser/issues/185

**Comment by evilebottnawi** [comment]
Wait merge https://github.com/postcss/postcss-selector-parser/pull/186

**Comment by evilebottnawi** [comment]
last version of `postcss-value-parser` fixes this problem. I added test to ensure we don't do regressions in future. Unfortunately we don't have directly `postcss-selector-parser` deps, so i can't bump this on our side. I recommend update your deps and lock file. Thanks!

**Comment by honghui-qiao** [comment]
Thanks all! :D
