### ISSUE TITLE
File extension optional on imports, required on composes

### ISSUE THREAD

**Issue by dmeehan1968** [webpack-contrib/css-loader#907]
* Operating System: macOS Mojave 10.14.3
* Node Version: 11.9.0
* NPM Version: 6.8.0
* webpack Version: 4.29.4
* css-loader Version: 2.1.0

### Expected Behavior

Consistency of module name specification between `@import` and `composes`.

### Actual Behavior

Module extension can be omitted in `@import` but must be specified in `composes`.  If the extension is omitted then the module cannot be resolved. The following error is seen:

```text
Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '{url from composes statement}' in '{folder containing less module being processed}'
```

### Code

I am using Less for my source files, so `less-loader` is processed below the `css-loader` in my webpack config.  

```css
@import "filename";

.klass {
  composes: otherklass from "filename.less";
}
```

```js
const cssLoader = {
  loader: 'css-loader',
  options: {
    modules: true,
    importLoaders: 1,
    sourceMap: true,
    localIdentName: '[name]_[local]_[contenthash:base64:5]',
    camelCase: true,
  },
}

// webpack 'rule' for 'less' files
{
  test: /\.less$/,
  include: config.includes,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      cssLoader,
      'less-loader',
    ],
  }),
},
```

**Comment by evilebottnawi** [comment]
@dmeehan1968 why do you use `composes otherklass from "filename.less";` instead `composes: otherklass from "filename.less";`

Also we can't omit extension because it is part of spec https://github.com/css-modules/css-modules#dependencies

**Comment by dmeehan1968** [comment]
> @dmeehan1968 why do you use `composes otherklass from "filename.less";` instead `composes: otherklass from "filename.less";`

Apologies, that's a typo, I do of course have the colon. I've edited the original issue.

> Also we can't omit extension because it is part of spec https://github.com/css-modules/css-modules#dependencies

I don't see that spec mention that the extension is required, just that it is present by example.  There is a still an inconsistency between `composes` and `@import`, as in the latter I can omit the extension and its resolved correctly.  I guess that the `less-loader` is dealing with the `@import` however, so its not the same resolver at work.

**Comment by evilebottnawi** [comment]
Anyway feel free to send a PR with implementation, it is not high priority and most likely no one will ever do that, so PR welcome

**Comment by cap-Bernardito** [comment]
`@import" filename ";` is processed by `less-loader`. Since it handles a limited number of file extensions (.less and .css), it may try to add these extensions to the file name.

`composes: otherklass from" filename.less ";` is processed by `css-loader`. And in this case, we don’t know which extensions to add, because there may be files with the same names and different extensions (.css, .less, .sass, .scss, ...).

Therefore, we strongly recommend specifying the file extension in `composes`.
