### ISSUE TITLE
css-loader 0.15.1 breaks & + & inside :local

### ISSUE THREAD

**Issue by beckiechoi** [webpack-contrib/css-loader#92]
``` less
:local {
  .something {
    & + & {
      /* some rule */
    }
  }
}
```

which gets translated to:

``` css
:local .something + :local .something {
  /* some rule */
}
```

throws an error after upgrading to 0.15.1. 

In contrast, 
`& &-name` which becomes `:local .something :local .something-name` still works.

**Comment by michael-ciniawsky** [comment]
@beckiechoi Still relevant with `css-loader`@latest

**Comment by michael-ciniawsky** [comment]
@beckiechoi If there are still regressions with latest `css-loader` feel free to reopen 😛
