### ISSUE TITLE
Superfluous exportOnlyLocals property is crashing css-loader

### ISSUE THREAD

**Issue by arackaf** [webpack-contrib/css-loader#922]
* Operating System: Mac OS
* Node Version: 8.14.1
* NPM Version: 6.4.1
* webpack Version: 4.25.1
* css-loader Version: 2.1.1

### Expected Behavior

css modules work with mini-css-extract

### Actual Behavior

> TypeError: Cannot read property 'split' of undefined

### Code

```js
      {
        test: /\.css$/,
        oneOf: [
          {
            test: /\.module\.css$/,
            use: [MiniCssExtractPlugin.loader, { loader: "css-loader", options: { modules: true, exportOnlyLocals: true } }]
          },
          {
            use: [MiniCssExtractPlugin.loader, "css-loader"]
          }
        ]
      },
```

### How Do We Reproduce?

See above.

The error is actually eliminated by removing `exportOnlyLocals: true`, which seems to be the default behavior now anyway.  In fact, setting `exportOnlyLocals: false` causes no change in behavior (meaning, even with `exportOnlyLocals: false`, only locals are exported).  

So it seems the docs may be out of date?  It also seems this property has no effect, except to crash the build when needlessly set to true?

**Comment by evilebottnawi** [comment]
hm, can't reproducible, maybe you can create minimum reproducible test repo?

**Comment by arackaf** [comment]
Weird - glad to see you can’t repro it (ie is a rarer bug than I thought). I don’t really have a min repro, so I’ll just close.

Even without the error, is this property supposed to do anything at this point? From my usage locals are always only exported - so it seems this config property can just be removed from the docs.

**Comment by evilebottnawi** [comment]
@arackaf it is required for SSR

**Comment by HeyParkerJ** [comment]
For what it's worth, I'm reproing with the following setup (css-loader@2.0.0 and mini-css-extract-css-plugin@0.8.2)

`{
                test: /\.module.css$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            localIdentName: '[hash:base64:5]',
                            sourceMap: NODE_ENV == 'development' ? true : false,
                            getLocalIdent: (loaderContext, localIdentName, localName, options) => {
                                const fileName = path.basename(loaderContext.resourcePath);
                                const name = fileName.substr(0, fileName.indexOf('.'));
                                options.content = path.relative('', loaderContext.resourcePath) + '+' + localName;
                                const nameTemplate = includeHash
                                    ? `${localName}_${name}_${localIdentName}`
                                    : `${localName}_${name}`;
                                return loaderUtils.interpolateName(loaderContext, nameTemplate, options);
                            },
                            exportOnlyLocals: true,
                        },
                    },
                ],
            },`


Removing the exportOnlyLocals removes the error, but I'm unsure of side effects.
