### ISSUE TITLE
using contentHash to generate css classes hash

### ISSUE THREAD

**Issue by pOoOf** [webpack-contrib/css-loader#926]
I need to update the CSS class hashes on every build based on the content of css/sass file.

**Use Case**
I have a modal component that works fine and whenever I build it, it generates its CSS and JS files which I can use anywhere by importing it.

Now I have an address component that uses this modal component and whenever I build this address component, It includes Modals CSS in its CSS and modals js in its js and builds fine.
still no issue.

Now while building the entire app which uses both of these components, it includes Modals CSS as well as Address components CSS in the chunk. Now if I want to change anything in the modal styles, those styles gets overridden by the Modal styles present inside the address component.

Now if i can generate css classes has on every build, then Address component can keep using the older modal component while Modal used separately anywhere on the app will be having different class hashes so it won't get affected by the Address component modal styles.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

It is bad practice you always will be invalidate css. but you can use.
