### ISSUE TITLE
using contentHash to generate css classes hash

### ISSUE THREAD

**Issue by pOoOf** [webpack-contrib/css-loader#927]
* Operating System:
Mac Mojave: 10.14.4

* Node Version:
v10.11.0

* NPM Version:
6.4.1
* webpack Version:
4.29.5
* css-loader Version:
0.28.11

### Feature Proposal
CSS class name hashes should be calculated based on the content of CSS/SCSS file or content or the specific CSS class block, very much like the way content hash is calculated in MiniCssExtractPlugin or ExtractTextWebpackPlugin

### Feature Use Case
I have a modal component that works fine and whenever I build it, it generates its CSS and JS files which I can use anywhere by importing it.

Now I have an address component that uses this modal component and whenever I build this address component, It includes Modals CSS in its CSS and modals js in its js and builds fine.
still no issue.

Now while building the entire app which uses both of these components, it includes Modals CSS as well as Address components CSS in the chunk. Now if I want to change anything in the modal styles, those styles get overridden by the Modal styles present inside the address component.

Now if I can generate CSS classes has on every build, then Address component can keep using the older modal component while Modal used separately anywhere on the app will be having different class hashes so it won't get affected by the Address component modal styles.

**Comment by evilebottnawi** [comment]
It is impossible as i say before, we don't have contenthash when we handle css, you need use milticompiler for this component and then include this in bundle.
