### ISSUE TITLE
Integration postcss-loader and css-loader in one loader

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/css-loader#929]
* Operating System: no matter
* Node Version: no matter
* NPM Version: no matter
* webpack Version: 4.30.0
* css-loader Version: latest

### Feature Proposal

Integrate `postcss-loader` and `css-loader`

### Feature Use Case

Avoid using two loaders, cons:
- Better DX
- Increase perf
- Easy setup

**Comment by Airkro** [comment]
Why close?
