### ISSUE TITLE
Problem with modules

### ISSUE THREAD

**Issue by wendal2841** [webpack-contrib/css-loader#932]
Hi, I have an old project.
I need to add CSS modules.
In webpack.config.js I added 
` loader: 'css-loader',
   options: {
         importLoaders: 1,
         modules: true,
         localIdentName: '[local]--[hash:base64:5]',
},`
after this, I have problem with url() and className 
new logic with css modules works cool
but old less style don't works 

old logic includes index.less in index.jsx file and in the whole project classname use when string and I use localIdentName and it broke all styles

How need to exclude old file styles?
How need add config for correct work url()?

![image](https://user-images.githubusercontent.com/27301672/57548924-dc399680-736a-11e9-847f-a2df3280b972.png)

**Comment by wendal2841** [comment]
./src/index.less
Module not found: Can't resolve 'components/general/header/~assets/images/pages/icon.svg' in '/Users/******/src'

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use gitter or stackoverflow for questions and supporting.

> How need to exclude old file styles?

You need rewrite old code to new code

> How need add config for correct work url()?

You need rewrite code or use https://github.com/webpack-contrib/css-loader#url as `Function`
