### ISSUE TITLE
about attributes(margin,padding)

### ISSUE THREAD

**Issue by VictorWuSH** [webpack-contrib/css-loader#936]
* Operating System: 
* Node Version: v9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.32.2
* css-loader Version: 1.0.1

### Code ###
I create a .css file 
.popup  {
    height: calc(env(safe-area-inset-top) + 46px);
    height: 44px;
    height: 10rem;
    width: calc(env(safe-area-inset-top) + 46px);
    width: 44px;
    width: 10rem;
    padding: calc(env(safe-area-inset-top) + 46px); 
    padding: 10rem;
    padding: 46px;
    margin: calc(env(safe-area-inset-top) + 46px); 
    margin: 10rem;
    margin: 46px;
    top: calc(env(safe-area-inset-top) + 46px); 
    top: 10rem;
    top: 46px;
}

after css-loader ,it turns to
.popup{height:calc(env(safe-area-inset-top) + 46px);height:44px;height:10rem;width:calc(env(safe-area-inset-top) + 46px);width:44px;width:10rem;padding:46px;margin:46px;top:calc(env(safe-area-inset-top) + 46px);top:10rem;top:46px}

why the attributes(margin,padding) are megered ?

**Comment by evilebottnawi** [comment]
Irrelevant to css-loader, we don't modify your values, maybe broken or outdated minimizer version

**Comment by evilebottnawi** [comment]
Also please update css-loader to latest version

**Comment by VictorWuSH** [comment]
sorry, I made a mistake.
It was affected by optimize-css-assets-webpack-plugin who is using cssnano.

**Comment by Edge00** [comment]
@VictorWu90 Hello. Have you solved this problem? i came across to this problem too.
