### ISSUE TITLE
Exporting only used CSS

### ISSUE THREAD

**Issue by mbulfair** [webpack-contrib/css-loader#944]
Question:
I am not sure this is the correct loader, but when you have css modules enabled. Isn't it supposed to only "import" the css classes imported into a JS component? Unless it has `:global` on it? I'm asking because when doing a production build, the entire file is being extracted (mini-css-extract). While I'm using (webpack development) the style blocks only show the css I am importing. What am I missing here? Any help or guidance would be greatly appreciated.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/css-loader/issues/506, it is feature

**Comment by evilebottnawi** [comment]
And no supported right now
