### ISSUE TITLE
Reduce count of `require` for locals

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/css-loader#954]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- css-loader Version:

### Feature Proposal

Reduce count of `require` for locals

### Feature Use Case

Above

**Comment by ogonkov** [comment]
There is no way to get `utils.getLocalIdent` anymore? I used to have it for my custom ident logic, just wanted to tune it a bit, but keep whole other thing on defaults.

**Comment by evilebottnawi** [comment]
Yes `utils.getLocalIdent` is private API and can be changed/improved in any time, you can copy/paste code
