### ISSUE TITLE
Suggesting a more detailed error message for users upgrading from 2.1.1

### ISSUE THREAD

**Issue by taylortdixon** [webpack-contrib/css-loader#961]
- css-loader Version: 3.0.0

In 3.0.0 there are a lot of breaking changes in the webpack configuration. Right now, when you have additional options, you receive the error `options should NOT have additional properties`. 

This is a good step, but I suggest enumerating the options that are no longer valid, which would make the upgrade for those from 2.1.1 easier.

**Comment by evilebottnawi** [comment]
Thanks for issue, already in todo, we use `schema-utils` package for this and need solve this problem here https://github.com/webpack-contrib/schema-utils/issues/35
