### ISSUE TITLE
Cannot nest :global to switch modes in scss

### ISSUE THREAD

**Issue by DanielHeath** [webpack-contrib/css-loader#964]
- Operating System: ubuntu
- Node Version: v12.5.0
- NPM Version: 6.9.2
- Yarn version: 1.16.0 
- webpack Version: 4.32.2
- css-loader Version: 2.1.1
- sass-loader "7.1.0"

### Expected Behavior

`.foo` is exported mangled, but `.bar` is left alone.

### Actual Behavior

`.bar` gets its name mangled

### Code

```
.foo {
  :global {
    .bar {
      color: red;
    }
  }
}
```

### How Do We Reproduce?

An app produced by 'rails new' with webpacker has css modules and scss configured in a way that hits this issue.

**Comment by evilebottnawi** [comment]
Please use latest version of css-loader, also it is expected
