### ISSUE TITLE
Behaviour of the "[path]" placeholder have been changed in a refactor commit

### ISSUE THREAD

**Issue by fa93hws** [webpack-contrib/css-loader#967]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- css-loader Version: 3.0+

### Expected Behavior
`[path]` placeholder gives `path-to-file`

### Actual Behavior
`[path]` placeholder gives `path/to/file`

### How Do We Reproduce?
Should be very clear in this commit. https://github.com/webpack-contrib/css-loader/pull/920
`normalizeIdentifier` is removed.

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo

**Comment by fa93hws** [comment]
> Please create minimum reproducible test repo

It should be clear enough by seeing here https://github.com/webpack-contrib/css-loader/pull/920/files#diff-2b4ca49d4bb0a774c4d4c1672d7aa781L108.

If you are looking for the config
```
    modules: {
      mode: 'local',
      context: path.resolve(__dirname, '../src'),
      localIdentName: '[path][name]__[local]',
    },
    localsConvention: 'camelCaseOnly',
    importLoaders: 0,
sourceMap: true,
```

If you are looking for the repo
https://github.com/fa93hws/simple-typescript-react-starter

**Comment by evilebottnawi** [comment]
Still can't understand, what is output was previously and what is output actually, no need link on source code, just clarify you problem

**Comment by fa93hws** [comment]
> Still can't understand, what is output was previously and what is output actually, no need link on source code, just clarify your problem

The `[path]` in classname should was mapped to `path-to-file` and it is mapped to `path/to/file` now.

**Comment by evilebottnawi** [comment]
@fa93hws looks like regression, feel free to send a PR

**Comment by fa93hws** [comment]
> @fa93hws looks like regression, feel free to send a PR

No problem. OK to have this function back? https://github.com/webpack-contrib/css-loader/pull/920/files#diff-2b4ca49d4bb0a774c4d4c1672d7aa781L108

**Comment by evilebottnawi** [comment]
No, css classes can have non standard characters, so we can back this function

**Comment by evilebottnawi** [comment]
stop, why you think it is bug? Looks like it is expected behavior, and looks it is breaking change, i think you should use own `localIdentName` implementation if you want to have `-`

**Comment by fa93hws** [comment]
> stop, why you think it is bug? Looks like it is expected behavior, and looks it is breaking change, i think you should use own `localIdentName` implementation if you want to have `-`

Because that commit says it's a "refactor" and a "refactor" normally won't change the behavior of the code.
That make me think it's probably a mistake?

**Comment by fa93hws** [comment]
> stop, why you think it is bug? Looks like it is expected behavior, and looks it is breaking change, i think you should use own `localIdentName` implementation if you want to have `-`

Anyway, if it is expected behavior, I am happy to implement the `-` in my configuration.
Thanks

**Comment by evilebottnawi** [comment]
Sometimes refactor has breaking change. Css allow to use `/` character so we need allow to use this in code also, but `[path][name]__[local]` to `/path/to/name__hash` looks very bad and it is very uncomfortably, maybe we should change `/` to `-` only for placeholders for better DX

**Comment by evilebottnawi** [comment]
Let's think about this, because maybe it is really not good DX

**Comment by evilebottnawi** [comment]
In version@2 it was `-`, right (i am look on code)?

**Comment by fa93hws** [comment]
> In version@2 it was `-`, right (i am look on code)?

2.something is with `-` but 3.0 is not.
I'm not sure which version it start not to replace the `/` but it's after this PR: https://github.com/webpack-contrib/css-loader/pull/920

I will replace the '/' to '-' only then.

**Comment by evilebottnawi** [comment]
Let's keep open i think about this in near future, as workaround you can use custom `localIdentName` function to fix problem, feel free to feedback. Here interesting problem

**Comment by fa93hws** [comment]
> Let's keep open i think about this in near future, as workaround you can use custom `localIdentName` function to fix problem, feel free to feedback. Here interesting problem

No problem, Thanks

**Comment by evilebottnawi** [comment]
Yes, it is big regression :disappointed: thanks for catching this
