### ISSUE TITLE
Minimize (obfuscate) class names

### ISSUE THREAD

**Issue by Yegorich555** [webpack-contrib/css-loader#969]
### Feature Proposal
add options like 
```js
options: {
    modules: {
        minifyNames: true
    },
}
```

### Feature Use Case
It is helpful for changing classNames to 'a_a', 'a_b' etc. like Google does. It is a must-have improvement for production build since it can reduce bundle size up to 70%: [https://www.freecodecamp.org/news/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b/](https://www.freecodecamp.org/news/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b/ )

**Comment by evilebottnawi** [comment]
As as said i think we don't need this as part of css-loader, anyway you can send a example in docs

**Comment by evilebottnawi** [comment]
Out of scope this plugin please use custom implementation for getLoaderIdent based on https://github.com/grabantot/incstr, anyway feel free to feedback, if issue collects many :+1: i will reopen this and we implement this as option, thanks for issue
