### ISSUE TITLE
Can't reference keyframe animation name inside jsx

### ISSUE THREAD

**Issue by Kashio** [webpack-contrib/css-loader#975]
- Operating System: Windows 10
- Node Version: v10.15.3
- NPM Version: v6.4.1
- webpack Version: 4.28.3
- css-loader Version: 1.0.0

`Webpack.config.js`:
(not really relevant to the issue..)
```js
            {
              test: cssModuleRegex,
              use: getStyleLoaders({
                importLoaders: 1,
                sourceMap: isEnvProduction && shouldUseSourceMap,
                modules: true,
                localIdentName: isEnvProduction ? '[sha1:hash:hex:4]' : '[name]__[local]'
              }),
            },
```

Hey, I'm using css modules with css loader, and I've stumbled upon a problem.
I have a `LoadingOverlay` component which shows a loader for `duration` ms.
I apply a fade-in-out animation on the overlay with the following code inside the component:
```
if (show) {
            return {
                animation: `fade-out-long ${duration}ms ease-out forwards`
            };
        }
```
This style object is applied to the overlay node.
I do it this way since the duration is prop which is passed from the parent component.
My problem is that `LoadingOverlay` scss file is a scss module which @includes this animations like so:
```
@import '../../../constants/zIndexes';
@import '../../../constants/animations';

@include fade-out-long-keyframes();
@include fade-out-long2-keyframes();
```
and the animation name is getting compiled as-well  to something like `LoadingOverlay-module__fade-out-long`
How can I reference the correct animation name from my jsx then?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use gitter or stackoverflow for questions, use `:global` for animation in you case
