### ISSUE TITLE
请问nodejs 6.11.5 兼容哪个版本的css-loader 

### ISSUE THREAD

**Issue by GHUserZ** [webpack-contrib/css-loader#977]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [StackOverflow](https://stackoverflow.com/questions/tagged/webpack)
or [the Webpack Gitter](https://gitter.im/webpack/webpack) instead.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/css-loader/blob/master/package.json#L12
