### ISSUE TITLE
. is not replaced in filenames

### ISSUE THREAD

**Issue by rianbotha** [webpack-contrib/css-loader#980]
- Operating System: MacOS
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.39.1
- css-loader Version: 3.1.0

### Expected Behavior

In 2.1.0 using this pattern for localIdentName: `[name]_[local]_[hash:base64:5]` the name portion would be transformed from `file.module` to `file-module`. File name is file.module.scss.

### Actual Behavior

The `.` in `file.module` is no longer changed to a `-`.

We use babel-plugin-react-css-modules alongside css-loader. The babel plugin still transforms filenames in the same way the CSS Loader 2.* did.

### Code

```js
// CSS Loader portion of webpack config
{
  loader: 'css-loader',
  options: {
    modules: {
      localIdentName: '[name]_[local]_[hash:base64:5]',
    },
    importLoaders: 2,
    sourceMap: !production,
  },
},
```

### How Do We Reproduce?

Use a SCSS filename with one or more `.` in the filename.

**Comment by evilebottnawi** [comment]
It is expected and breaking change for `css-loader@3`, `babel-plugin-react-css-modules` should change logic generation too

**Comment by evilebottnawi** [comment]
@rianbotha anyway can you create minimum reproducible test repo?

**Comment by jquense** [comment]
The `file.module.css` or whatever css flavor (scss, less, etc) is fairly conventional at this point but I don't know that default replacing the dot is a convention...I do think that replacing invalid case characters like this is better than escaping them like we do now but that's just my preference. For my webpavk builds I do change the default getLocalIdent to replace dots with dashes

**Comment by evilebottnawi** [comment]
@jquense just for information, can you provide `getLocalIdent` source code, will be great see one of use case, maybe we can improve standard generation for better DX

**Comment by jquense** [comment]
It's pretty simple I don't escape other path characters tho since we don't use the path interpolation https://github.com/jquense/webpack-atoms/blob/master/src/index.ts#L150

**Comment by evilebottnawi** [comment]
Ok, let's fix it, as regression from 2.0.0

**Comment by rianbotha** [comment]
@evilebottnawi Do you still need a repo?
To get around it in the meantime I just added a custom getLocalIdent copied from the original, that just replaces `.` with `-`. A bit blunt, but solves the immediate issue for us:
```
const getLocalIdent = (loaderContext, localIdentName, localName, options) => {
  const filenameReservedRegex = /[<>:"/\\|?*\x00-\x1F]/g;
  const reControlChars = /[\u0000-\u001f\u0080-\u009f]/g;
  const reRelativePath = /^\.+/;

  if (!options.context) {
    options.context = loaderContext.rootContext;
  }

  const request = normalizePath(
    path.relative(options.context || '', loaderContext.resourcePath)
  );

  options.content = `${options.hashPrefix + request}+${unescape(localName)}`;

  return cssesc(
    loaderUtils
      .interpolateName(loaderContext, localIdentName, options)
      // For `[hash]` placeholder
      .replace(/^((-?[0-9])|--)/, '_$1')
      .replace(filenameReservedRegex, '-')
      .replace(reControlChars, '-')
      .replace(reRelativePath, '-')
      .replace(/\./g, '-'),
      { isIdentifier: true }
  ).replace(/\\\[local\\\]/gi, localName);
};
```

**Comment by evilebottnawi** [comment]
@rianbotha no need new option, it is bug and need fix, PR welcome

**Comment by rianbotha** [comment]
@evilebottnawi Thanks for the quick action.

**Comment by michaeltaranto** [comment]
FYI this was the same issue i [raised here](https://github.com/webpack-contrib/css-loader/issues/966#issuecomment-514874689). Can also confirm that 3.2.0 fixes the issue. Thanks for getting to this 🙌

**Comment by evilebottnawi** [comment]
@michaeltaranto behaviour for this https://github.com/webpack-contrib/css-loader/issues/966 expected when you use user function you should escape non standard characters manually, mayme we change this in next major release
