### ISSUE TITLE
:global blocks for css modules seem not working

### ISSUE THREAD

**Issue by shiatsumat** [webpack-contrib/css-loader#987]
- Operating System: Ubuntu 19.04
- Node Version: v12.9.1 
- NPM Version: 6.11.2
- webpack Version: 4.39.3
- css-loader Version: 3.2.0

### Expected Behavior

A css module with a `:global` block in `contents/main.css`
```
:global {
  .dummy {
    display: none;
  }
}
```
should be transpiled into the following (prettified for human beings).
```
.main--dummy {
  display: none;
}
```

### Actual Behavior

The following is output. Although the tag `:global` is removed, the outer curly brace `{...}` wrongly remains and also incorrectly the discriminant `main--` is prepended.
```
{
  .main--dummy {
    display: none;
  }
}
```

### Code

The settings for css-loader in `webpack.config.js` is as follows.
```js
{
  loader: 'css-loader',
  options: {
    modules: {
      localIdentName: '[path][name]--[local]',
      context: `${__dirname}/contents`
    },
    localsConvention: 'camelCaseOnly'
  }
}
```

### How Do We Reproduce?

The bug can be reproduced easily, I believe.

**Comment by evilebottnawi** [comment]
Because default `mode` is `local` and when you use `global` use mark this as `global`
