### ISSUE TITLE
webpack with "production" mode , the option "getLocalIdent" has not any effect?

### ISSUE THREAD

**Issue by DemonCloud** [webpack-contrib/css-loader#989]
<img width="578" alt="Screen Shot 2019-09-07 at 11 30 58 PM" src="https://user-images.githubusercontent.com/7436361/64476921-95986380-d1c7-11e9-876f-07a6f766a23e.png">

on process.env.NODE_ENV = "production" production mode, ths "getLocalIdent" was not work!!!,  but use it with devServer, it work fine!

**Comment by evilebottnawi** [comment]
Please use issue template, i don't know what is work or not, you don't provide example of full configuration or reproducible test repo, also i don't know what `abcJSON.css` and what is it in production

**Comment by DemonCloud** [comment]
@evilebottnawi  

you can try a simple example with this option "getLocalIdent"

it does not work when webpack build in mode "production" 

like the pic, I can't get any console.log ... 

<img width="470" alt="Screen Shot 2019-09-08 at 12 17 14 AM" src="https://user-images.githubusercontent.com/7436361/64477427-06db1500-d1ce-11e9-8be4-151c3ae1a402.png">

**Comment by evilebottnawi** [comment]
Please create minimum reproducible test repo, looks you have problem in configuration, a lot of repositories use this option and no problem (for example CRA)

**Comment by DemonCloud** [comment]
@evilebottnawi 

OK, no problem, but you can turn off the problem first. I try to locate the problem first. During this time, if I really can't find the problem, I will make an example to prove that this setting may be a problem. Thank you, I closed the question.
