### ISSUE TITLE
Module local mode assigned to CSS animation

### ISSUE THREAD

**Issue by wanaryytel** [webpack-contrib/css-loader#991]
- Operating System: node:10.16.0 docker image running on Manjaro Linux
- Node Version: 10.16.0
- NPM Version: 6.9.0
- webpack Version: 4.41.0
- css-loader Version: 3.2.0

### Expected Behavior

I expect this CSS animation `animation: 2.5s blow 0s linear infinite;` to remain unchanged.

### Actual Behavior

The output looks like this `animation: 2.5s :local(blow) 0s linear infinite;`. This only happens when the `modules` key is set in options for `css-loader`. Also when you set `modules.mode` to `"global"`, this is fixed again, but the behavior of `modules` not set and `modules: {}` isn't the same.

### Code

```js
// webpack.config.js module conf
module: {
            rules: [
                {
                test: /\.(css|scss)$/,
                include: [
                    path.resolve(project_root, 'static', 'assets'),
                ],
                use: [
                    ExtractCssChunks.loader,
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                            modules: {},
                        },
                    },
                ],
            },
            ],
        },
```

### How Do We Reproduce?

Just add the ^ animation to any CSS file and set an empty object `{}` for the value of `options.modules` in `css-loader` conf.

**Comment by evilebottnawi** [comment]
It is exampled because modules: {} === `local` mode, so you need use `global` if you need keep animation name

**Comment by wanaryytel** [comment]
@evilebottnawi Yes but why if I don't define modules at all it does not default to local?

**Comment by evilebottnawi** [comment]
When you enable css modules all possible global value (include animation name) will be converting in local

**Comment by foxbunny** [comment]
I know this is a bit old, but how do you give animation names in a CSS module without having `:local()` added to it?
