### ISSUE TITLE
_Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema_

### ISSUE THREAD

**Issue by coopeu** [webpack-contrib/css-loader#992]
Issues are so 🔥
👉🏽 SYSTEM
rails webpacker:info
Ruby: ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]
Rails: 6.0.0
Webpacker: 4.0.7
Node: v8.16.1
Yarn: 1.19.0
@rails/webpacker:
MRCOM@0.1.0 /var/www/html/MRCOM
└── @rails/webpacker@4.0.7
Is bin/webpack present?: true
Is bin/webpack-dev-server present?: true
Is bin/yarn present?: true

### Expected Behavior

$ rails/webpack NOT 2 ERRORS
$ rails assets:precompile -> Compilation failed:

### Actual Behavior

ERROR in ./app/javascript/src/application.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/src/application.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'localIdentName'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
    at validate (/var/www/html/MRCOM/node_modules/css-loader/node_modules/schema-utils/dist/validate.js:50:11)
    at Object.loader (/var/www/html/MRCOM/node_modules/css-loader/dist/index.js:34:28)
 @ ./app/javascript/src/application.css 2:14-159
 @ ./app/javascript/packs/application.js

ERROR in ./app/javascript/css/application.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/css/application.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(4:3) Unknown word

### Code
/var/www/html/WEBAPP/node_modules/css-loader/dist/options.js

```
        "type": "object",
          "additionalProperties": false,
          "properties": {
            "mode": {
              "enum": ["local", "global"]
            },
            "localIdentName": {
              "type": "string"
            },
            "localIdentRegExp": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "instanceof": "RegExp"
                }
              ]
            },
            "context": {
              "type": "string"
            },
            "hashPrefix": {
              "type": "string"
```

### How Do We Reproduce?

[https://github.com/coopeu/MilRevolts.com](MRCOM)

**Comment by evilebottnawi** [comment]
open issue in `webpacker`, you should move `localIdentName` in `modules` https://github.com/webpack-contrib/css-loader#object
